// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("../../../Color ../../../request ../../../renderers/SimpleRenderer ../../../renderers/ClassBreaksRenderer ../../../renderers/UniqueValueRenderer ../../../core/Accessor ../../../core/HandleRegistry ../../../core/Logger ../../../core/arrayUtils ../../../../esri/layers/support/ExportImageParameters ./colorRampUtils ./sizeRampUtils dojo/Deferred dojo/promise/all dojo/_base/lang".split(" "),function(u,v,s,h,t,w,x,y,z,A,n,B,q,C,k){var r=y.getLogger("esri.widgets.Legend.support.ActiveLayerInfo");
return w.createSubclass({declaredClass:"esri.widgets.Legend.support.ActiveLayerInfo",constructor:function(){this._legendResponse=null;this._handles=new x;var a=this.watch("tearingDown",function(){this.destroy()}.bind(this));this._handles.add(a,"tearingDown-watcher")},getDefaults:function(){return{legendElements:[]}},destroy:function(){this._handles.destroy();this._legendResponse=this._handles=null},properties:{layer:null,legendElements:{type:Array},ready:!1,tearingDown:!1,title:null,scale:null,updating:!1,
version:{value:0,readOnly:!0,dependsOn:["updating"],get:function(){return this._get("version")+1}},_hasSizeRamp:!1},buildLegendElementsForRenderer:function(){var a=this.layer.renderer,c=this._getVisualVariableLegendElements(a);this._getRendererSymbolTableElement(a).then(function(a){a&&a.infos.length&&this.legendElements.push(a);c&&Array.prototype.push.apply(this.legendElements,c);this.legendElements.length&&(this.ready=!0)}.bind(this)).otherwise(function(a){r.warn("error while building activeLayerInfo!",
a)}).always(function(){this.updating=!1}.bind(this))},buildLegendElementsForTools:function(){this.layer.sublayers?this._constructLegendElementsForSublayers():this._getLegendLayers().then(function(a){a.forEach(function(a){(a=this._generateSymbolTableElementForLegendLayer(a))&&a.infos.length&&this.legendElements.push(a)},this);this.legendElements.length&&(this.ready=!0)}.bind(this)).otherwise(function(a){r.warn("Request to server for legend has failed!",a)}).always(function(){this.updating=!1}.bind(this))},
_getLegendLayers:function(a){var c=a&&a.hasDynamicLayers,b=this._legendResponse;return!c&&b?(a=new q,a.resolve(b),a.promise):this._legendRequest(c?a.dynamicLayers:null).then(function(a){return this._legendResponse=a=a.data.layers}.bind(this))},_legendRequest:function(a){var c=this.layer,b=c.url;a={f:"json",dynamicLayers:a};if(10.01<=c.version){var d=b.indexOf("?"),b=-1<d?b.substring(0,d)+"/legend"+b.substring(d):b+"/legend";c.token&&(b+="?token\x3d"+c.token)}else b=b.toLowerCase().indexOf("/rest/"),
c=c.url.substring(0,b)+c.url.substring(b+5,c.url.length),b="http://utility.arcgis.com/sharing/tools/legend?soapUrl\x3d"+window.escape(c)+"\x26returnbytes\x3dtrue";return v(b,{query:a,callbackParamName:"callback"})},_constructLegendElementsForSublayers:function(){this.updating=!0;this.ready=!1;this.legendElements=[];this._handles.remove("sublayers-watcher");var a=new A({layer:this.layer});this._getLegendLayers(a).then(function(a){var b={};a.forEach(function(a){b[a.layerId]=a});this.legendElements=
this._generateLegendElementsForSublayers(this.layer.sublayers,b,this.layer.opacity);this.legendElements.length&&(this.ready=!0)}.bind(this)).otherwise(function(a){r.warn("Request to server for legend has failed!",a)}).always(function(){a.destroy();this.updating=!1}.bind(this))},_generateLegendElementsForSublayers:function(a,c,b){var d=[];this._handles.add(a.on("change",this._constructLegendElementsForSublayers.bind(this)),"sublayers-watcher");a.forEach(function(a){var f=a.watch("renderer, opacity, title, visible",
this._constructLegendElementsForSublayers.bind(this));this._handles.add(f,"sublayers-watcher");a.visible&&a.legendEnabled&&(f=a&&null!=a.opacity?a.opacity:null,(a=this._generateSymbolTableElementForSublayer(a,c,null!=f?f*b:b))&&a.infos.length&&d.unshift(a))},this);return d},_generateSymbolTableElementForSublayer:function(a,c,b){var d=c[a.id];return!d&&a.sublayers?(c=this._generateLegendElementsForSublayers(a.sublayers,c,b),{type:"symbol-table",title:a.title,infos:c}):this._generateSymbolTableElementForLegendLayer(d,
a,b)},_generateSymbolTableElementForLegendLayer:function(a,c,b){if(a){var d=a.layerName,e=c&&c.renderer;if(e&&(e=c&&c.title?c.title:this._getRendererTitle(e,this.layer,c)))d&&(e.title=d),d=e;d={type:"symbol-table",title:d,infos:[]};a.legend&&this._isLegendLayerInScale(a,c)&&(c=c?this._sanitizeLegendForSublayer(a.legend,c):a.legend,d.infos=c.map(function(d){var c=d.url;if(d.imageData&&0<d.imageData.length)c="data:image/png;base64,"+d.imageData;else if(0!==c.indexOf("http")){var c=this.layer.url+"/"+
a.layerId+"/images/"+c,e=this.layer.token;e&&(c+="?token\x3d"+e)}else return null;return{label:d.label,src:c,opacity:b,width:d.width,height:d.height}},this).filter(function(a){return!!a}));return d.infos.length?d:null}},_sanitizeLegendForSublayer:function(a,c){if(10.1>this.layer.version||0===a.length)return a;var b=c.renderer,d,e;a.some(function(a){return a.values})&&a.some(function(a,c){a.values||(d=c,e=a,e.label||(e.label="others"));return null!=e});b?"uniqueValue"===b.type?e&&(a.splice(d,1),a.push(e)):
"classBreaks"===b.type&&(e&&a.splice(d,1),a.reverse(),e&&a.push(e)):e&&(a.splice(d,1),a.push(e));return a},_isLegendLayerInScale:function(a,c){var b=c||this.layer,d=!0,e,f;!b.minScale&&0!==b.minScale||!b.maxScale&&0!==b.maxScale?(0===a.minScale&&b.tileInfo&&(e=b.tileInfo.lods[0].scale),0===a.maxScale&&b.tileInfo&&(f=b.tileInfo.lods[b.tileInfo.lods.length-1].scale)):(e=Math.min(b.minScale,a.minScale)||b.minScale||a.minScale,f=Math.max(b.maxScale,a.maxScale));if(0<e&&e<this.scale||f>this.scale)d=!1;
return d},_getVisualVariableLegendElements:function(a,c,b){var d=a.visualVariables,e=[],f=[],g=[],p=null!=b?b:this.layer.opacity,l=null;if(!d)return null;d.forEach(function(a){"color"===a.type?e.push(a):"opacity"===a.type?f.push(a):"size"===a.type&&g.push(a)});d=[];Array.prototype.push.apply(d,e);Array.prototype.push.apply(d,f);Array.prototype.push.apply(d,g);0===e.length&&(a.isInstanceOf(h)&&a.classBreakInfos&&1===a.classBreakInfos.length)&&(l=(b=a.classBreakInfos[0])&&b.symbol.color.toRgba());return d.map(function(d){var b=
c?c.title:this._getRampTitle(d,this.layer),e=n._getRampBorderColor(a),f=n._getRampOverlayColor(p),g;"color"===d.type?g={type:"color-ramp",title:b,borderColor:e,overlayColor:f,infos:n._getRampStops(a,d)}:"opacity"===d.type?g={type:"opacity-ramp",title:b,borderColor:e,overlayColor:f,infos:n._getRampStops(a,d,l)}:"size"===d.type&&(g={type:"size-ramp",title:b,infos:B._getRampStops(a,d,this._getMedianColor(a),this.scale)},this._hasSizeRamp||(this._hasSizeRamp=null!=g.infos&&g.infos.length));return g.infos&&
g},this).filter(function(a){return!!a})},_getRendererSymbolTableElement:function(a,c,b){var d=a.visualVariables,e=this._getMedianColor(a),f=null!=b?b:this.layer.opacity,g=a.isInstanceOf(s),p=a.isInstanceOf(h),l=a.isInstanceOf(t),m=g||p||l;return this._loadSymbols(a,m).then(function(a){var b={type:"symbol-table",title:c&&c.title?c.title:this._getRendererTitle(a,this.layer,c),infos:[]};if(p){var h=this._isUnclassedRenderer(a,d);if(!h||!this._hasSizeRamp){var k=a.classBreakInfos.slice().reverse();b.infos=
k.map(function(a){return{label:a.label||(h?null:a.minValue+" - "+a.maxValue),value:[a.minValue,a.maxValue],symbol:this._getAppliedCloneSymbol(a.symbol,e,f)}},this);h&&(b.title=null)}}l&&(b.infos=a.uniqueValueInfos.map(function(a){return{label:a.label||a.value,value:a.value,symbol:this._getAppliedCloneSymbol(a.symbol,e,f)}},this));m&&(k=a.label||a.defaultLabel,(a=a.symbol||a.defaultSymbol)&&!h&&b.infos.push({label:g?k:k||"others",symbol:this._getAppliedCloneSymbol(a,e,f)}));return b.infos.length?b:
null}.bind(this))},_loadSymbols:function(a,c){var b=new q,d=[];if(!c)return b.reject(),b.promise;a=a.clone();if(a.isInstanceOf(h)||a.isInstanceOf(t))(a.classBreakInfos||a.uniqueValueInfos).forEach(function(a){d.push(this._fetchSymbol(a.symbol).then(function(d){a.symbol=d}))},this);d.push(this._fetchSymbol(a.symbol||a.defaultSymbol).then(function(d){a.isInstanceOf(s)?a.symbol=d:a.defaultSymbol=d}));C(d).then(function(){b.resolve(a)}).otherwise(function(){b.reject()});return b.promise},_fetchSymbol:function(a){if(a&&
"web-style-symbol"===a.type)return a.fetchSymbol();var c=new q;c.resolve(a);return c.promise},_getMedianColor:function(a){var c,b,d;if(!a.visualVariables)return null;d=z.find(a.visualVariables,function(a){return"color"===a.type});if(!d)return null;if(d.colors)c=d.minDataValue,b=d.maxDataValue;else if(d.stops){if(1===d.stops.length)return d.stops[0].color;c=d.stops[0].value;b=d.stops[d.stops.length-1].value}if(null!=c&&null!=b)return a.getColor(c+(b-c)/2,{colorInfo:d})},_getAppliedCloneSymbol:function(a,
c,b){a=a.clone();var d=a.type,e=-1<d.indexOf("3d");c&&(c=new u(c.toRgba()),e?this._applyColorTo3dSymbol(a,c):a.color=c);if("simple-line-symbol"===d||"cartographic-line-symbol"===d||"text-symbol"===d){if(!a.color)return;c=a.color.toRgba();c[3]*=b;a.color=c}else"simple-marker-symbol"===d||"simple-fill-symbol"===d?(a.color&&(c=a.color.toRgba(),c[3]*=b,a.color=c),a.outline&&a.outline.color&&(c=a.outline.color.toRgba(),c[3]*=b,a.outline.color=c)):e&&this._applyColorTo3dSymbol(a,null,b);return a},_applyColorTo3dSymbol:function(a,
c,b){a.symbolLayers.forEach(function(a){if(a&&(c&&(a.material||(a.material={}),a.material.color=c),null!=b)){var e;a.material&&a.material.color&&(e=a.material.color.toRgba(),e[3]*=b,a.material.color=e);a.outline&&a.outline.color&&(e=a.outline.color.toRgba(),e[3]*=b,a.outline.color=e)}})},_getRampTitle:function(a,c){var b=a.field,d=a.normalizationField,e=!1,f=!1,g=!1,b=k.isFunction(b)?null:b,d=k.isFunction(d)?null:d;if(a.legendOptions&&a.legendOptions.title)b=a.legendOptions.title;else{if(c.renderer.authoringInfo&&
c.renderer.authoringInfo.visualVariables)for(var h=c.renderer.authoringInfo.visualVariables,l=0;l<h.length;l++){var m=h[l];if("colorInfo"===m.type)if("ratio"===m.style){e=!0;break}else if("percent"===m.style){f=!0;break}else if("percentTotal"===m.style){g=!0;break}}b={field:b&&this._getFieldAlias(b,c),normField:d&&this._getFieldAlias(d,c),ratio:e,ratioPercent:f,ratioPercentTotal:g}}return b},_getRendererTitle:function(a,c,b){var d=a.field,e,f,g;a instanceof h&&(e=a.normalizationField,f="percent-of-total"===
a.normalizationType);d=k.isFunction(d)?null:d;e=k.isFunction(e)?null:e;if(d||e)g={field:b?d:d&&this._getFieldAlias(d,c),normField:b?e:e&&this._getFieldAlias(e,c),normByPct:f};return g},_getFieldAlias:function(a,c){var b=c.popupTemplate,d=b&&b.fieldInfos,b=k.isFunction(a)?null:c.getField&&c.getField(a),e,f;d&&d.some(function(b){if(a===b.fieldName)return f=b,!0});(d=f||b)&&(e=f&&f.label||b&&b.alias||d.name||d.fieldName);return e},_isUnclassedRenderer:function(a,c){var b=!1;a.isInstanceOf(h)&&(a.classBreakInfos&&
1===a.classBreakInfos.length)&&c&&(b=c.some(function(b){return!(!b||!(a.field===b.field&&a.normalizationField==b.normalizationField))}));return b}})});