// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/accessorSupport/decorators ../Layer ../../core/MultiOriginJSONSupport ./ArcGISService ./OperationalLayer ./PortalLayer ../../core/Error ../../core/urlUtils ../../core/promiseUtils ../../core/requireUtils ../../request dojo/_base/lang dojo/io-query ../../geometry/Extent ../support/arcgisLayerUrl".split(" "),function(n,z,p,c,b,q,r,s,t,u,v,e,k,w,g,x,h,l,f){return function(m){function a(){m.apply(this,
arguments);this.fullExtent=this.blendMode=null;this.version={major:Number.NaN,minor:Number.NaN,versionString:""};this.copyright=null;this.sublayerTitleMode="item-title";this.layerId=this.title=null}p(a,m);a.prototype.readFullExtent=function(d,y){var a=y.store,b=a.indexCRS||a.geographicCRS,b=b&&parseInt(b.substring(b.lastIndexOf("/")+1,b.length),10);return null==a||null==a.extent?null:new l({xmin:a.extent[0],ymin:a.extent[1],xmax:a.extent[2],ymax:a.extent[3],spatialReference:b})};a.prototype.readVersion=
function(d,a){var b=a.store,c=null!=b.version?b.version.toString():"",b={major:Number.NaN,minor:Number.NaN,versionString:c},c=c.split(".");2<=c.length&&(b.major=parseInt(c[0],10),b.minor=parseInt(c[1],10));return b};a.prototype.readCopyright=function(d,a){return a.copyrightText};a.prototype.readTitlePortalItem=function(d,a){return"item-title"!==this.sublayerTitleMode?void 0:d};a.prototype.readTitleService=function(d,a){var b=this.portalItem&&this.portalItem.title;if("item-title"===this.sublayerTitleMode)return f.titleFromUrlAndName(this.url,
a.name);var c=a.name||f.parse(this.url).title;"item-title-and-service-name"===this.sublayerTitleMode&&b&&(c=b+" - "+c);return f.cleanTitle(c)};a.prototype.readLayerId=function(d,a){return a.id};Object.defineProperty(a.prototype,"url",{set:function(d){var a=e.urlToObject(d),b=f.parse(a.path);b&&null!=b.sublayer&&(this.layerId=b.sublayer,a=h.objectToQuery(a.query),d=b.url.path,a&&(d=d+"?"+a));for(;"/"===d[d.length-1];)d=d.slice(0,-1);this._set("url",d)},enumerable:!0,configurable:!0});a.prototype.writeUrl=
function(d,a){d&&(a.url=d);var b=e.urlToObject(d);null!=this.layerId&&b&&(a.url=b.path+"/layers/"+this.layerId,b.query&&Object.keys(b.query)&&(a.url+="?"+h.objectToQuery(b.query)))};Object.defineProperty(a.prototype,"parsedUrl",{get:function(){var a=this._get("url");if(!a)return null;a=e.urlToObject(a);null!=this.layerId&&f.match.test(a.path)&&(a.path=a.path+"/layers/"+this.layerId);return a},enumerable:!0,configurable:!0});a.prototype._addUrlToken=function(a){var b=x.mixin({},this.parsedUrl.query,
{token:this.token}),b=h.objectToQuery(b);a+=b?"?"+b:"";null==this._canUseXhr&&(this._canUseXhr=e.canUseXhr(a));return!this._canUseXhr?e.addProxy(a):a};a.prototype.readRootNode=function(a,b){return b.store.rootNode};a.prototype._verifyRootNodeAndUpdateExtent=function(){var a=this;return this._fetchRootNode().then(function(b){return a._updateExtentFromRootNode(b)})};a.prototype._updateExtentFromRootNode=function(a){if(!(null==this.fullExtent||this.fullExtent.hasZ)&&null!=a&&Array.isArray(a.mbs)&&4===
a.mbs.length){var b=a.mbs[2];a=a.mbs[3];this.fullExtent.zmin=b-a;this.fullExtent.zmax=b+a}};a.prototype._fetchRootNode=function(){if(!this.rootNode)return k.resolve();var a=e.join(this.parsedUrl.path,this.rootNode);return g(this._addUrlToken(a),{query:{f:"json"},responseType:"json"}).then(function(a){return a.data}).otherwise(function(b){throw new v("sceneservice:root-node-missing","Root node missing.",{error:b,url:a});})};a.prototype._fetchService=function(){var a=this;return(null==this.layerId&&
/SceneServer\/*$/i.test(this.url)?this._fetchFirstLayerId().then(function(b){null!=b&&(a.layerId=b)}):k.resolve()).then(function(){return a._fetchServiceLayer()})};a.prototype._fetchFirstLayerId=function(){return g(this._addUrlToken(this.url),{query:{f:"json"},callbackParamName:"callback",responseType:"json"}).then(function(a){if(a.data&&Array.isArray(a.data.layers)&&0<a.data.layers.length)return a.data.layers[0].id})};a.prototype._fetchServiceLayer=function(){var a=this;return g(this._addUrlToken(this.parsedUrl.path),
{query:{f:"json"},responseType:"json"}).then(function(b){b.ssl&&(a.url=a.url.replace(/^http:/i,"https:"));b=b.data;a.read(b,{origin:"service",url:a.parsedUrl});a._validateLayer(b)})};a.prototype._validateLayer=function(a){};a.prototype.createGraphicsController=function(a){var b=this;a.layer=this;a.addUrlTokenFunction=this._addUrlToken.bind(this);var c=w.when(n,"../graphics/controllers/I3SOnDemandController").then(function(b){return new b(a)});c.then(function(a){b.emit("graphics-controller-create",
{graphicsController:a})});return c};c([b.shared({id:{json:{origins:{service:{readable:!1},portalItem:{readable:!1}}}}})],a.prototype,"properties",void 0);c([b.property({type:l})],a.prototype,"fullExtent",void 0);c([b.read("fullExtent",["store.indexCRS","store.geographicCRS"])],a.prototype,"readFullExtent",null);c([b.property({readOnly:!0})],a.prototype,"version",void 0);c([b.read("version",["store.version"])],a.prototype,"readVersion",null);c([b.property({type:String})],a.prototype,"copyright",void 0);
c([b.read("copyright",["copyrightText"])],a.prototype,"readCopyright",null);c([b.property({type:String})],a.prototype,"sublayerTitleMode",void 0);c([b.property({type:String})],a.prototype,"title",void 0);c([b.read("portal-item","title")],a.prototype,"readTitlePortalItem",null);c([b.read("service","title",["name"])],a.prototype,"readTitleService",null);c([b.property({type:Number})],a.prototype,"layerId",void 0);c([b.read("service","layerId",["id"])],a.prototype,"readLayerId",null);c([b.property()],
a.prototype,"url",null);c([b.write("url")],a.prototype,"writeUrl",null);c([b.property({dependsOn:["layerId"]})],a.prototype,"parsedUrl",null);c([b.property()],a.prototype,"store",void 0);c([b.property({type:String})],a.prototype,"rootNode",void 0);c([b.read("rootNode",["store.rootNode"])],a.prototype,"readRootNode",null);return a=c([b.subclass("esri.layers.mixins.SceneService")],a)}(b.declared(q,s,r,t,u))});