var usos_homologacion = [
{ text: 'Habitacional menor o igual a 3 pisos en NPH', value: 1, consolidado: 'RESIDENCIAL' },
{ text: 'Habitacional mayor o igual a 4 pisos en NPH', value: 2, consolidado: 'RESIDENCIAL' },
{ text: 'Comercio Puntual en NPH', value: 3, consolidado: 'COMERCIAL' },
{ text: 'Corredor Comercial en NPH', value: 4, consolidado: 'COMERCIAL' },
{ text: 'Estaciones de servicio', value: 5, consolidado: 'COMERCIAL' },
{ text: 'Centro Comercial Mediano NPH', value: 6, consolidado: 'COMERCIAL' },
{ text: 'Centro Comercial Grande NPH', value: 7, consolidado: 'COMERCIAL' },
{ text: 'Bodega comercial NPH', value: 8, consolidado: 'COMERCIAL' },
{ text: 'Industria artesanal', value: 9, consolidado: 'COMERCIAL' },
{ text: 'Industria Mediana', value: 10, consolidado: 'COMERCIAL' },
{ text: 'Industria Grande', value: 11, consolidado: 'COMERCIAL' },
{ text: 'Institucional Puntual', value: 12, consolidado: 'INSTITUCIONAL' },
{ text: 'Colegios y Universidades de 1 a 3 pisos', value: 13, consolidado: 'INSTITUCIONAL' },
{ text: 'Iglesias', value: 14, consolidado: 'COMERCIAL' },
{ text: 'Oficinas y Consultorios oficiales en NPH', value: 15, consolidado: 'COMERCIAL' },
{ text: 'Colegios y Universidades de 4 pisos o mas', value: 16, consolidado: 'COMERCIAL' },
{ text: 'Clinicas Hospitales Centro Medicos', value: 17, consolidado: 'INSTITUCIONAL' },
{ text: 'Instalaciones Militares', value: 18, consolidado: 'INSTITUCIONAL' },
{ text: 'Industria artesanal en PH', value: 19, consolidado: 'COMERCIAL' },
{ text: 'Oficinas y Consultorios en NPH', value: 20, consolidado: 'COMERCIAL' },
{ text: 'Hoteles en NPH', value: 21, consolidado: 'COMERCIAL' },
{ text: 'Depositos de Almacenamiento en NPH', value: 22, consolidado: 'COMERCIAL' },
{ text: 'Teatros y Cinemas en NPH', value: 23, consolidado: 'COMERCIAL' },
{ text: 'Edificio de Parqueo en NPH', value: 24, consolidado: 'COMERCIAL' },
{ text: 'Bodega de Almacenamiento en NPH', value: 25, consolidado: 'COMERCIAL' },
{ text: 'Moteles Amoblado y Residencias en NPH', value: 26, consolidado: 'COMERCIAL' },
{ text: 'Moteles Amoblado y Residencias en PH', value: 27, consolidado: 'COMERCIAL' },
{ text: 'Industria Mediana en PH', value: 28, consolidado: 'COMERCIAL' },
{ text: 'Parques de Diversion en NPH', value: 29, consolidado: 'COMERCIAL' },
{ text: 'Clubes de Mayor Extension', value: 30, consolidado: 'COMERCIAL' },
{ text: 'Piscinas en NPH', value: 31, consolidado: 'COMERCIAL' },
{ text: 'Coliseos', value: 32, consolidado: 'COMERCIAL' },
{ text: 'Bodega Economica', value: 33, consolidado: 'COMERCIAL' },
{ text: 'Industria Grande en PH', value: 34, consolidado: 'COMERCIAL' },
{ text: 'Colegios y Universidades de 1 a 3 pisos en PH', value: 35, consolidado: 'COMERCIAL' },
{ text: 'Parques de Diversion en PH', value: 36, consolidado: 'COMERCIAL' },
{ text: 'Habitacional menor o igual a 3 pisos en PH', value: 37, consolidado: 'RESIDENCIAL' },
{ text: 'Habitacional mayor o igual a 4 pisos en PH', value: 38, consolidado: 'RESIDENCIAL' },
{ text: 'Comercio Puntual en PH', value: 39, consolidado: 'COMERCIAL' },
{ text: 'Corredor Comercial en PH', value: 40, consolidado: 'COMERCIAL' },
{ text: 'Centro Comercial Mediano en PH', value: 41, consolidado: 'COMERCIAL' },
{ text: 'Centro Comercial Grande en PH', value: 42, consolidado: 'COMERCIAL' },
{ text: 'Clinicas Hospitales Centro Medicos en PH', value: 43, consolidado: 'COMERCIAL' },
{ text: 'Institucional Puntual en PH', value: 44, consolidado: 'INSTITUCIONAL' },
{ text: 'Oficinas y Consultorios en PH', value: 45, consolidado: 'COMERCIAL' },
{ text: 'Hoteles en PH', value: 46, consolidado: 'COMERCIAL' },
{ text: 'Teatros y Cinemas en PH', value: 47, consolidado: 'COMERCIAL' },
{ text: 'Parqueo libre en PH', value: 48, consolidado: 'COMERCIAL' },
{ text: 'Parqueadero Cubierto en PH', value: 49, consolidado: 'COMERCIAL' },
{ text: 'Edificio de Parqueo en PH', value: 50, consolidado: 'COMERCIAL' },
{ text: 'Deposito Lockers en PH', value: 51, consolidado: 'COMERCIAL' },
{ text: 'Piscinas en PH', value: 52, consolidado: 'COMERCIAL' },
{ text: 'Iglesias en PH', value: 53, consolidado: 'COMERCIAL' },
{ text: 'Cementerios', value: 55, consolidado: 'INSTITUCIONAL' },
{ text: 'Restaurantes en NPH', value: 56, consolidado: 'COMERCIAL' },
{ text: 'Culto Religioso en NPH', value: 58, consolidado: 'COMERCIAL' },
{ text: 'Restaurantes en PH', value: 60, consolidado: 'COMERCIAL' },
{ text: 'Pista Aeropuerto', value: 62, consolidado: 'INSTITUCIONAL' },
{ text: 'Aulas de Clases', value: 64, consolidado: 'INSTITUCIONAL' },
{ text: 'Clubes Pequeños', value: 65, consolidado: 'COMERCIAL' },
{ text: 'Plazas de Mercado', value: 66, consolidado: 'COMERCIAL' },
{ text: 'Museos', value: 67, consolidado: 'COMERCIAL' },
{ text: 'Enrramadas Cobertizos Cayenes', value: 70, consolidado: 'COMERCIAL' },
{ text: 'Galpones Gallineros', value: 71, consolidado: 'COMERCIAL' },
{ text: 'Establos Pesebreras Caballerizas', value: 72, consolidado: 'COMERCIAL' },
{ text: 'Cocheras Marraneras Porquerizas', value: 73, consolidado: 'COMERCIAL' },
{ text: 'Beneficiadores', value: 74, consolidado: 'COMERCIAL' },
{ text: 'Secadores', value: 75, consolidado: 'COMERCIAL' },
{ text: 'Kioscos', value: 76, consolidado: 'COMERCIAL' },
{ text: 'Silos', value: 77, consolidado: 'COMERCIAL' },
{ text: 'Oficinas en Bodegas y/o Industrias en NPH', value: 80, consolidado: 'COMERCIAL' },
{ text: 'Oficinas en Bodegas y/o Industrias en PH', value: 81, consolidado: 'COMERCIAL' },
{ text: 'Oficinas operativas (estaciones de servicio)', value: 82, consolidado: 'COMERCIAL' },
{ text: 'Predios sin construir en PH', value: 90, consolidado: 'COMERCIAL' },
{ text: 'Bodega comercial en PH', value: 91, consolidado: 'COMERCIAL' },
{ text: 'Oficinas y Consultorios oficiales en PH', value: 92, consolidado: 'COMERCIAL' },
{ text: 'Bodega de Almacenamiento en PH', value: 93, consolidado: 'COMERCIAL' },
{ text: 'Centro Comercial Pequeño en NPH', value: 94, consolidado: 'COMERCIAL' },
{ text: 'Centro Comercial Pequeño en PH', value: 95, consolidado: 'COMERCIAL' },
{ text: 'Parqueadero Cubierto en NPH', value: 96, consolidado: 'COMERCIAL' },
{ text: 'Bodega Economica en PH', value: 97, consolidado: 'COMERCIAL' },
{ text: 'Deposito de Almacenamiento en PH', value: 98, consolidado: 'COMERCIAL' }
];
