// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/sniff dojo/number dojo/Deferred dstore/Csv ../../../core/Accessor ../../../core/Error ../../../core/Promise ../../../core/urlUtils ../../../core/promiseUtils ../../../geometry/Extent ../../support/Field ../../../tasks/support/FeatureSet ../../../request".split(" "),function(p,q,r,s,t,u,g,v,w,x,y,z,A,B){var C=["small-integer","integer","single","double","long"],D="lat latitude y ycenter latitude83 latdecdeg POINT-Y".split(" "),E="lon lng long longitude x xcenter longitude83 longdecdeg POINT-X".split(" "),
F=[","," ",";","|","\t"];return u.createSubclass([v],{properties:{parsedUrl:{get:function(){return this.url?w.urlToObject(this.url):null}},delimiter:null,fields:[],latitudeField:null,longitudeField:null,layerDefinition:null,outFields:null,url:null},initialize:function(){this.addResolvingPromise(this._fetchCSV())},queryFeatures:function(b){return x.resolve(A.fromJSON(this._featureSetJSON))},_updateUrl:function(b){b&&(this.url=this.url.replace(/^http:/i,"https:"))},_fetchCSV:function(){return B(this.parsedUrl.path,
{query:this.parsedUrl.query,responseType:"text"}).then(function(b){this._updateUrl(b.ssl);return this._processCSV(b.data)}.bind(this))},_isValidDate:function(b,a){if(!b||"[object Date]"!==Object.prototype.toString.call(b)||isNaN(b.getTime()))return!1;var c=!0;if(q("chrome")&&/\d+\W*$/.test(a)){var h=a.match(/[a-zA-Z]{2,}/);if(h){for(var c=!1,e=0,k=h.length,g=/^((jan(uary)?)|(feb(ruary)?)|(mar(ch)?)|(apr(il)?)|(may)|(jun(e)?)|(jul(y)?)|(aug(ust)?)|(sep(tember)?)|(oct(ober)?)|(nov(ember)?)|(dec(ember)?)|(am)|(pm)|(gmt)|(utc))$/i;!c&&
e<=k&&!(c=!g.test(h[e]));)e++;c=!c}}return c},_getCSVExtent:function(b){var a;b.forEach(function(c){c.geometry&&(a?(a.xmin=Math.min(a.xmin,c.geometry.x),a.ymin=Math.min(a.ymin,c.geometry.y),a.xmax=Math.max(a.xmax,c.geometry.x),a.ymax=Math.max(a.ymax,c.geometry.y)):a=new y(c.geometry.x,c.geometry.y,c.geometry.x,c.geometry.y))});a&&(0>=a.width&&0>=a.height)&&(a=null);return a},_readFirstLine:function(b){var a=b.indexOf("\n");return p.trim(b.substr(0,a))},_detectDelimiter:function(b){if(!this.delimiter){var a=
0,c="";F.forEach(function(h){var e=b.split(h).length;e>a&&(a=e,c=h)});this.delimiter=c}},_readFieldNames:function(b){return b.split(this.delimiter)},_createLayerDefinition:function(b){this.layerDefinition||(this.layerDefinition={name:"csv",geometryType:"esriGeometryPoint",fields:[]});this.fields&&(this.layerDefinition.fields=this.fields.map(function(a){return a.toJSON()}));var a=this.layerDefinition.fields;if(!this.layerDefinition.objectIdField){for(var c=0;c<a.length;c++)if("esriFieldTypeOID"===
a[c].type){this.layerDefinition.objectIdField=a[c].name;break}this.layerDefinition.objectIdField||(a.push({name:"__OBJECTID",alias:"__OBJECTID",type:"esriFieldTypeOID",editable:!1}),this.layerDefinition.objectIdField="__OBJECTID")}b.forEach(function(c){a.some(function(a){return c===a.name})||a.push({name:c,alias:c,type:c===this.latitudeField||c===this.longitudeField?"esriFieldTypeDouble":"esriFieldTypeString"})},this)},_getCoordinateFields:function(b){var a,c;b.forEach(function(b){var e;e=D.indexOf(b.toLowerCase());
-1!==e&&!a&&(a=b);e=E.indexOf(b.toLowerCase());-1!==e&&!c&&(c=b)});this.latitudeField=this.latitudeField||a;this.longitudeField=this.longitudeField||c},_createFeatureSet:function(b){var a=[],c=[],h=[],e=this.latitudeField,k=this.longitudeField,g=this.fields.filter(function(a){return a.name!==this.layerDefinition.objectIdField},this).map(function(a){return a.name});this.fields.forEach(function(a){"date"===a.type?c.push(a.name):-1<C.indexOf(a.type)&&h.push(a.name)});var l;-1===this.outFields.indexOf("*")&&
(l=this.outFields);var m=new t;m.delimiter=this.delimiter;m.fieldNames=g;m.newline="\n";b=m.parse(b);var n=0;b.shift();b.forEach(function(b){for(var d in b)if(d===e||d===k||!l||-1<l.indexOf(d))if(-1<c.indexOf(d)){var f=new Date(b[d]);b[d]=this._isValidDate(f,b[d])?f.getTime():null}else{if(-1<h.indexOf(d)){f=r.parse(b[d]);if((d===e||d===k)&&(isNaN(f)||181<Math.abs(f)))f=parseFloat(b[d]);isNaN(f)?b[d]=null:b[d]=f}}else delete b[d];d=b[e];f=b[k];b[this.layerDefinition.objectIdField]=n;n++;var g={attributes:b};
null!==f&&(null!==d&&!isNaN(d)&&!isNaN(f))&&(l&&-1===l.indexOf(e)&&delete b[e],l&&-1===l.indexOf(k)&&delete b[k],g.geometry={x:f,y:d});a.push(g)},this);this._featureSetJSON={features:a,geometryType:"esriGeometryPoint",spatialReference:{wkid:4326}}},_processCSV:function(b){var a=new s,c=this._readFirstLine(b);if(!c)return a.reject(g("CSVSource","CSV is empty"));this._detectDelimiter(c);if(!this.delimiter)return a.reject(g("CSVSource","Unable to detect the delimiter from CSV"));c=this._readFieldNames(c);
this._getCoordinateFields(c);if(!this.latitudeField||!this.longitudeField)return a.reject(g("CSVSource","Unable to identify latitudeField and/or longitudeField from CSV"));this._createLayerDefinition(c);this.fields=this.layerDefinition.fields.map(function(a){return z.fromJSON(a)},this);this._createFeatureSet(b);if(b=this._getCSVExtent(this._featureSetJSON.features))this.layerDefinition.extent=b.toJSON();return a.resolve()}})});