// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("../../../core/declare dojo/_base/lang dojo/Deferred ../../../core/Accessoire ../../../core/AccessoirePromise ../../../core/urlUtils ../../../core/promiseUtils ../../support/WebSocketConnector ../../../tasks/QueryTask ../../../request".split(" "),function(p,f,q,r,s,l,k,t,n,u){return p([r,s],{classMetadata:{properties:{url:{dependsOn:["layerDefinition"]},parsedUrl:{dependsOn:["url"]},connectionInfo:{dependsOn:["layerDefinition"]}}},getDefaults:function(a){var b=this.inherited(arguments),d=a.layer;
d&&(b=f.mixin(b,{url:d.url,connectionInfo:{direction:d.socketDirection,socketUrl:d.socketUrl}}));return b},initialize:function(){this.addResolvingPromise(this._fetchLayers())},_connectionInfoGetter:function(){if(this.layer.hasMemorySource||this.layer.socketUrl)return{serviceSocketUrls:[this.layer.socketUrl]};var a={},b=this.layerDefinition,d=[],e=[],c=[],g,h,f;b.streamUrls&&b.streamUrls.forEach(function(b){"ws"===b.transport&&(d=b.urls,a.token=b.token)},this);d.forEach(function(a){0===a.lastIndexOf("wss",
0)?c.push(a):e.push(a)});if((b="https"===l.appUrl.scheme||0===this.url.lastIndexOf("https:",0)?c:0===e.length?c:e)&&1<b.length)for(g=0;g<b.length-1;g++)h=g+Math.floor(Math.random()*(b.length-g)),f=b[h],b[h]=b[g],b[g]=f;a.serviceSocketUrls=b;return a},_latestUrlGetter:function(){var a=this.layerDefinition;return(a=a.keepLatestArchive&&a.keepLatestArchive.featuresUrl)?a:null},_latestQueryTaskGetter:function(){var a=this.latestUrl;return a?new n(a):null},_relatedFeaturesInfoGetter:function(){var a=(this.layerDefinition||
{}).relatedFeatures;return a=a&&a.featuresUrl?a:null},_relatedFeaturesQueryTaskGetter:function(){var a=this.relatedFeaturesInfo;return(a=a?a.featuresUrl:null)?new n(a):null},_parsedUrlGetter:function(){return this.url?l.urlToObject(this.url):null},url:null,createWebSocketConnector:function(a){var b=this,d=new q;b.then(function(){var e=b.connectionInfo,c,g=b.layer.spatialReference,h,k,m={};try{c=b.makeFilter()}catch(l){d.reject(l);return}if(e){e.socketUrl?k=[e.socketUrl]:e.serviceSocketUrls&&(k=e.serviceSocketUrls.map(function(a){return a+
"/"+b.layer.socketDirection}));m.socketUrls=k;if(c&&(c.where||c.geometry||c.outFields)||e.token)h=f.mixin(h||{},{where:c.where,geometry:c.geometry,outFields:c.outFields,token:e.token});a&&(g&&a.wkid!==g.wkid)&&(h=f.mixin(h||{},{outSR:a.wkid}));m.queryParams=h;m.layerSource=b;e=new t(m);d.resolve(e)}else d.reject(Error("No web socket urls found"))});return d.promise},getWebSocketToken:function(){return this._fetchLayer().then(function(){var a=null;this.layerDefinition.streamUrls&&this.layerDefinition.streamUrls.some(function(b){if("ws"===
b.transport)return a=b.token,!0},this);return a}.bind(this))},makeFilter:function(a){var b=this.layer,d=null,e=null,c;a?(a.hasOwnProperty("definitionExpression")&&(c=f.mixin(c||{},{where:a.definitionExpression})),a.hasOwnProperty("geometryDefinition")&&(d=a.geometryDefinition,c=f.mixin(c||{},{geometry:d}))):(b.hasOwnProperty("definitionExpression")&&b.definitionExpression&&(c=f.mixin(c||{},{where:b.definitionExpression})),b.hasOwnProperty("geometryDefinition")&&b.geometryDefinition&&(d=JSON.stringify(b.geometryDefinition.toJSON()),
c=f.mixin(c||{},{geometry:d})));if(b.hasOwnProperty("outFields")){if(b.outFields&&"*"!==b.outFields[0])var g=b.fields.map(function(a){return a.name}),e=b.outFields.filter(function(a){return-1!==g.indexOf(a)}).join(",");c=f.mixin(c||{},{outFields:e})}return c},_fetchLayers:function(){return this._fetchStreamLayer().then(function(a){a.ssl&&(this.url=this.url.replace(/^http:/i,"https:"));this.layerDefinition=a.data;return this._fetchArchiveLayer()}.bind(this)).then(function(a){this.archivedLayerDefinition=
a&&a.data;return this._fetchRelatedLayer()}.bind(this)).then(function(a){this.relatedLayerDefinition=a&&a.data}.bind(this))},_fetchStreamLayer:function(){return this._requestServiceDefinition({url:this.layer.parsedUrl.path,content:f.mixin({f:"json"},this.layer.parsedUrl.query)})},_fetchArchiveLayer:function(){var a=this.latestUrl;return!a?k.resolve():this._requestServiceDefinition({url:a})},_fetchRelatedLayer:function(){var a=this.relatedFeaturesInfo;return!a?k.resolve():this._requestServiceDefinition({url:a.featuresUrl})},
_requestServiceDefinition:function(a){return!a||!a.url?k.reject(Error("url is a required options property")):u(a.url,{query:f.mixin(a.content||{},{f:"json"}),responseType:"json",callbackParamName:"callback"})}})});