// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("dojo/_base/lang ../core/urlUtils ../core/MultiOriginJSONSupport ../geometry/SpatialReference ./support/VectorTileLayerLoader ./TiledLayer ./mixins/OperationalLayer ./mixins/PortalLayer ./mixins/ScaleRangeLayer ./support/TileInfo".split(" "),function(f,g,n,p,h,q,r,s,t,u){for(var l=[],c=0;20>c;c++){var m=78271.51696402048/Math.pow(2,c);l.push({level:c,scale:Math.floor(3779.527559055118*m),resolution:m})}var c={wkid:102100},v={spatialReference:c,tileInfo:{rows:512,cols:512,dpi:96,format:"pbf",
origin:{x:-2.0037508342787E7,y:2.0037508342787E7,spatialReference:c},spatialReference:c,lods:l},fullExtent:{xmin:-2.003750834E7,ymin:-2.003750834E7,xmax:2.003750834E7,ymax:2.003750834E7,spatialReference:c},version:null},k=q.createSubclass([n,r,s,t],{declaredClass:"esri.layers.VectorTileLayer",viewModulePaths:{"2d":"../views/2d/layers/VectorTileLayerView2D"},_mapsWithAttribution:["World_Basemap"],constructor:function(){this._serviceOverrides={}},normalizeCtorArgs:function(a,b){return"string"===typeof a||
a.version?f.mixin({url:a},b):a},getDefaults:function(a){var b=a.url,d=null;b&&"string"===typeof b&&(b=g.urlToObject(a.url),d=this._getDefaultAttribution(b.path));return f.mixin(this.inherited(arguments),{styles:[],attributionDataUrl:d})},load:function(){this.style||this.addResolvingPromise(this.loadFromPortal({supportedTypes:["Vector Tile Service"]}).always(this._loadStyle.bind(this)))},properties:{legendEnabled:{value:!0,json:{readFrom:["showLegend"],read:function(a,b){return!!b.showLegend}}},operationalLayerType:"VectorTileLayer",
popupEnabled:{value:!0,json:{readFrom:["disablePopup"],read:function(a,b){return!b.disablePopup}}},style:{readOnly:!0},spatialReference:{json:{readFrom:["fullExtent.spatialReference"],read:function(a,b){return(a=b.fullExtent.spatialReference)&&p.fromJSON(a)}}},tileInfo:{value:null,json:{read:function(a,b){if(a){var d=b.minScale?b.minScale:Infinity,e=b.maxScale?b.maxScale:-Infinity;a.lods=a.lods.filter(function(a){return a.scale<=d&&a.scale>=e});return u.fromJSON(a)}return null}}},styles:{cast:function(a){if(a){if("string"===
typeof a)return[a];if(Array.isArray(a))return a}else return[]}},url:{}},loadStyle:function(a){return this._loadStyle(a)},addStyle:function(a){var b=this.styles;-1===b.indexOf(a)&&(this.styles=b.concat([a]))},removeStyle:function(a){var b=this.styles;a=b.indexOf(a);-1!==a&&(b.splice(a,1),this.styles=b.concat())},hasStyle:function(a){return-1!==this.styles.indexOf(a)},_getDefaultAttribution:function(a){var b=a.match(/^https?:\/\/(basemaps|basemapsbeta)\.arcgis\.com(\/[^\/]+)?\/arcgis\/rest\/services\/([^\/]+(\/[^\/]+)*)\/vectortileserver/i);
if(b&&(a=b[3])){var b=b[2]||"",d;a=a.toLowerCase();for(var e=0,c=this._mapsWithAttribution.length;e<c;e++)if(d=this._mapsWithAttribution[e],-1<d.toLowerCase().indexOf(a))return this._getProtocol()+"//static.arcgis.com/attribution/Vector"+b+"/"+d}},_getProtocol:function(){var a=window.location.protocol;return"file:"===a?"http:":a},_loadStyle:function(a){if(!a){a=this.url;"string"===typeof a&&!h.isMapboxUrl(a)&&(this.url=a=g.makeAbsolute(a));var b=this.tileServers;b&&b.length&&(this._serviceOverrides.tileServers=
b.map(function(a){return h.isMapboxUrl(a)?a:g.makeAbsolute(a)},this))}var b=new h,c=h.getCredentialFromUrl(a);this._serviceOverrides.credential=c;return b.loadMetadata(a,k.ACCESS_TOKEN,this._serviceOverrides).then(function(a){a=a||{};var b=a.layerDefinition,c={style:a.style};this.layerDefinition=b||null;this.serviceUrl=a.serviceUrl||null;this.styleUrl=a.styleUrl||null;a=a.serviceUrl?g.urlToObject(a.serviceUrl):null;if(b)var d=this._getDefaultAttribution(a.path),c=f.mixin(c,{attributionDataUrl:d},
b);else c=f.mixin(c,v);this.read(c,{origin:"service",url:a})}.bind(this),function(a){this.emit("error",a)}.bind(this))}});k.ACCESS_TOKEN=null;return k});