// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define(["../../lib/IdGen","../../lib/gl-matrix","../../parts/Model","../../lib/Util","../../../../webgl/Util"],function(V,E,W,F,X){var x=E.vec3d,Y=E.mat4d,L=E.mat4,Q=F.VertexAttrConstants,g={};g.__Material_idGen=new V;g.__GLMaterial_id=0;g.IDENTITY=Y.identity();g.fill=function(a,c,b,e,f,d){if(void 0===f||3!==d)for(f=0;f<d;++f)b[e+f]=a[c+f];else{var t=a[c],n=a[c+1];a=a[c+2];b[e]=f[0]*t+f[4]*n+f[8]*a+f[12];b[e+1]=f[1]*t+f[5]*n+f[9]*a+f[13];b[e+2]=f[2]*t+f[6]*n+f[10]*a+f[14]}return d};var R=function(a,
c,b,e,f,d){for(var t=a.length,n=0;n<t;++n){for(var B=b*a[n],u=0;u<b;++u)e[f+u]=c[B+u];f+=d}};g.fillInterleaved=function(a,c,b,e,f,d,t,n){for(var B=X.getStride(f)/4,u=0;u<f.length;u++){var h=f[u],l=t+h.offset/4,h=h.name;if(!(null!=n&&null==n[h])){var k;switch(h){case "uv0":k=a.vertexAttr[h];null!=k&&R(a.faces.indices[h],k.data,k.size,d,l,B);break;case "region":k=a.vertexAttr[h];var h=a.faces.indices[h],g=k.data,m=k.size;k=d;var p=B;k=new Uint16Array(k.buffer);for(var l=2*l,p=2*p,v=h.length,r=0;r<v;++r){var w=
m*h[r],q;for(q=0;q<m;++q)k[l+q]=g[w+q];l+=p}break;case "color":k=a.vertexAttr[h];if(e&&e.color){h=a.faces.indices[h];g=k.data;m=e.color;k=k.size;p=d;v=B;p=new Uint8Array(p.buffer);l*=4;v*=4;r=h.length;for(w=0;w<r;++w){q=k*h[w];var s;for(s=0;s<k;++s)p[l+s]=g[q+s]*m[s];4>s&&(p[l+3]=255*m[3]);l+=v}}else{h=a.faces.indices[h];g=k.data;m=k.size;k=d;p=B;k=new Uint8Array(k.buffer);l*=4;p*=4;v=h.length;for(r=0;r<v;++r){w=m*h[r];for(q=0;q<m;++q)k[l+q]=g[w+q];4>q&&(k[l+3]=255);l+=p}}break;default:if(k=a.vertexAttr[h],
m=h===Q.POSITION?c:h===Q.NORMAL?b:void 0,void 0!==m&&3===k.size){h=a.faces.indices[h];g=k.data;k=d;p=B;v=h.length;for(r=0;r<v;++r)s=3*h[r],w=g[s],q=g[s+1],s=g[s+2],k[l]=m[0]*w+m[4]*q+m[8]*s+m[12],k[l+1]=m[1]*w+m[5]*q+m[9]*s+m[13],k[l+2]=m[2]*w+m[6]*q+m[10]*s+m[14],l+=p}else R(a.faces.indices[h],k.data,k.size,d,l,B)}}}};g.triangleVertexArrayToWireframeLines=function(a,c,b,e){for(b=Math.floor(b/3)-1;0<=b;b--){var f=c+3*b*e,d=c+6*b*e+5*e;this.fill(a,f,a,d,null,e);d-=e;this.fill(a,f+e,a,d,null,e);d-=
e;this.fill(a,f+e,a,d,null,e);d-=e;this.fill(a,f+2*e,a,d,null,e);d-=e;this.fill(a,f+2*e,a,d,null,e);d-=e;this.fill(a,f,a,d,null,e)}};var S=x.create(),Z=x.create(),$=x.create(),aa=x.create(),T=function(a,c,b,e,f){var d=a.getCenter();x.project(d,c,b,S);var d=x.dist2(S,d),t=a.getBSRadius();if(d<t*t){var d=a.getPrimitiveIndices(),t=a.getIndices(),n=a.getPosition(),g=d?d.length:t.length/3;if(1E4<g&&(a=a.getChildren(),void 0!==a)){for(d=0;8>d;++d)void 0!==a[d]&&T(a[d],c,b,e,f);return}a=n.size;var n=n.data,
u=c[0],h=c[1];c=c[2];var l=b[0]-u,k=b[1]-h;b=b[2]-c;for(var A=0;A<g;++A){var m=d?d[A]:A,p=a*t[3*m],v=a*t[3*m+1],r=a*t[3*m+2],w=n[p],q=n[p+1],p=n[p+2],s=n[v],D=n[v+1],v=n[v+2],E=n[r],F=n[r+1],r=n[r+2],G=s-w,H=D-q,I=v-p,J=E-w,z=F-q,C=r-p,K=k*C-z*b,M=b*J-C*l,L=l*z-J*k,y=G*K+H*M+I*L;if(!(y>-e&&y<e)){var y=1/y,N=u-w,O=h-q,P=c-p,K=y*(N*K+O*M+P*L);0>K||1<K||(M=O*I-H*P,I=P*G-I*N,G=N*H-G*O,H=y*(l*M+k*I+b*G),0>H||1<K+H||(J=y*(J*M+z*I+C*G),0<=J&&(z=Z,C=$,y=aa,x.set3(w,q,p,z),x.set3(s,D,v,C),x.set3(E,F,r,y),
x.subtract(C,z,C),x.subtract(y,z,y),x.normalize(x.cross(C,y,z)),f(J,z,m))))}}}};g.intersectTriangleGeometry=function(a,c,b,e,f,d,t,n,g,u,h){F.assert("triangle"===a.getData().getFaces()[c].type);T(a.getBoundingInfo(c),t,n,u,h)};g.basicMaterialConstructor=function(a,c){var b=!0,e=0,f=g.__Material_idGen.gen(c);a.getId=function(){return f};var d;a.getParentStage=function(){return d};a.addParentStage=function(a){F.assert(void 0===d,"Material can only be added to a single Stage");d=a};a.removeParentStage=
function(a){d=void 0};a.setVisible=function(d){b!==d&&(b=d,a.notifyDirty("matChanged"))};a.isVisible=function(){return b};a.notifyDirty=function(b){d&&d.notifyDirty(W.ContentType.MATERIAL,a,b)};a.setRenderPriority=function(a){e=a;this.notifyDirty("matChanged")};a.getRenderPriority=function(){return e}};var A=g.aquireIfNotUndefined=function(a,c,b,e){return void 0===a?void 0:b.aquire(a,c,e)},D=g.releaseIfNotUndefined=function(a,c){void 0!==a&&c.release(a)},U=L.create();g.bindView=function(a,c,b){L.translate(c,
a,U);b.setUniformMatrix4fv("view",U)};g.bindCamPos=function(a,c,b){b.setUniform3f("camPos",c[3]-a[0],c[7]-a[1],c[11]-a[2])};g.basicGLMaterialConstructor=function(a,c){var b=g.__GLMaterial_id++;a.getId=function(){return b};a.getMaterialId=function(){return c.getId()};a.isVisible=function(){return c.isVisible()};a.getRenderPriority=function(){return c.getRenderPriority()}};g.singleTextureGLMaterialConstructor=function(a,c,b,e){var f=A(b.textureId,b.initTexture,c,e);a.updateTexture=function(a){b.textureId!==
a&&(D(b.textureId,c),b.textureId=a,f=A(b.textureId,b.initTexture,c,e))};a.renderTexture=function(a){var e=c.getTexture(b.textureId);e&&e.renderGl&&e.renderGl(f.getGLTexture(),a)};a.bindTexture=function(a,b){void 0!==f&&(b.setUniform1i("tex",0),a.bindTexture(f.getGLTexture()))};a.bindTextureSize=function(a,b){if(void 0!==f){var e=f.getGLTexture();b.setUniform2f("texSize",e.descriptor.width,e.descriptor.height)}};a.dispose=function(){D(b.textureId,c)}};g.multiTextureGLMaterialConstructor=function(a,
c,b,e){for(var f=e.length,d=Array(f),g=0;g<f;g++)d[g]=A(b[e[g][0]],b[e[g][1]],c);a.updateTextures=function(a){for(var g=0;g<f;g++){var u=b[e[g][0]],h=a[e[g][0]];u!==h&&(D(u,c),b[e[g][0]]=h,d[g]=A(h,b[e[g][1]],c))}};a.bindTextures=function(a,b){for(var c=0;c<f;c++)void 0!==d[c]&&(b.setUniform1i(e[c][2],c),a.bindTexture(d[c].getGLTexture(),c));a.setActiveTexture(0)};a.bindOneTexture=function(a,b,c){b.setUniform1i(e[c][2],c);a.bindTexture(d[c].getGLTexture(),c);a.setActiveTexture(0)};a.disposeTextures=
function(){for(var a=0;a<f;a++)D(b[e[a][0]],c)}};return g});