// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define(["require","exports","dojo/i18n!../nls/basemaps"],function(a,c,b){return{streets:{id:"streets",title:b.streets,thumbnailUrl:a.toUrl("../images/basemap/streets.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer",showLegend:!1}]},satellite:{id:"satellite",title:b.satellite,thumbnailUrl:a.toUrl("../images/basemap/satellite.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer",showLegend:!1}]},hybrid:{id:"hybrid",
title:b.hybrid,thumbnailUrl:a.toUrl("../images/basemap/hybrid.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer",showLegend:!1},{url:"//services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer",isReference:!0,showLegend:!1}]},terrain:{id:"terrain",title:b.terrain,thumbnailUrl:a.toUrl("../images/basemap/terrain.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/World_Terrain_Base/MapServer",
showLegend:!1},{url:"//services.arcgisonline.com/ArcGIS/rest/services/Reference/World_Reference_Overlay/MapServer",isReference:!0,showLegend:!1}]},topo:{id:"topo",title:b.topo,thumbnailUrl:a.toUrl("../images/basemap/topo.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer",showLegend:!1}]},gray:{id:"gray",title:b.gray,thumbnailUrl:a.toUrl("../images/basemap/gray.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer",
showLegend:!1},{url:"//services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Reference/MapServer",isReference:!0,showLegend:!1}]},"dark-gray":{id:"dark-gray",title:b["dark-gray"],thumbnailUrl:a.toUrl("../images/basemap/dark-gray.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Base/MapServer",showLegend:!1},{url:"//services.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Dark_Gray_Reference/MapServer",isReference:!0,showLegend:!1}]},
oceans:{id:"oceans",title:b.oceans,thumbnailUrl:a.toUrl("../images/basemap/oceans.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/arcgis/rest/services/Ocean/World_Ocean_Base/MapServer",showLegend:!1},{url:"//services.arcgisonline.com/arcgis/rest/services/Ocean/World_Ocean_Reference/MapServer",isReference:!0,showLegend:!1}]},"national-geographic":{id:"national-geographic",title:b["national-geographic"],thumbnailUrl:a.toUrl("../images/basemap/national-geographic.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer",
showLegend:!1}]},osm:{id:"osm",title:b.osm,thumbnailUrl:a.toUrl("../images/basemap/osm.jpg"),baseMapLayers:[{layerType:"OpenStreetMap",showLegend:!1}]},"dark-gray-vector":{id:"dark-gray-vector",title:b["dark-gray"],thumbnailUrl:a.toUrl("../images/basemap/dark-gray.jpg"),baseMapLayers:[{url:"//www.arcgis.com/sharing/rest/content/items/850db44b9eb845d3bd42b19e8aa7a024/resources/styles/root.json",layerType:"VectorTileLayer"}]},"gray-vector":{id:"gray-vector",title:b.gray,thumbnailUrl:a.toUrl("../images/basemap/gray.jpg"),
baseMapLayers:[{url:"//www.arcgis.com/sharing/rest/content/items/0e02e6f86d02455091796eaae811d9b5/resources/styles/root.json",layerType:"VectorTileLayer"}]},"streets-vector":{id:"streets-vector",title:b.streets,thumbnailUrl:a.toUrl("../images/basemap/streets.jpg"),baseMapLayers:[{url:"//www.arcgis.com/sharing/rest/content/items/4e1133c28ac04cca97693cf336cd49ad/resources/styles/root.json",layerType:"VectorTileLayer"}]},"topo-vector":{id:"topo-vector",title:b.topo,thumbnailUrl:a.toUrl("../images/basemap/topo.jpg"),
baseMapLayers:[{url:"//www.arcgis.com/sharing/rest/content/items/6f65bc1351b7411588a8cb43fe23dad7/resources/styles/root.json",layerType:"VectorTileLayer"}]},"streets-night-vector":{id:"streets-night-vector",title:b["streets-night-vector"],thumbnailUrl:a.toUrl("../images/basemap/streets-night.jpg"),baseMapLayers:[{url:"//www.arcgis.com/sharing/rest/content/items/bf79e422e9454565ae0cbe9553cf6471/resources/styles/root.json",layerType:"VectorTileLayer"}]},"streets-relief-vector":{id:"streets-relief-vector",
title:b["streets-relief-vector"],thumbnailUrl:a.toUrl("../images/basemap/streets-relief.jpg"),baseMapLayers:[{url:"//services.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer",showLegend:!1},{url:"//www.arcgis.com/sharing/rest/content/items/2e063e709e3446459f8538ed6743f879/resources/styles/root.json",layerType:"VectorTileLayer",showLegend:!1}]},"streets-navigation-vector":{id:"streets-navigation-vector",title:b["streets-navigation-vector"],thumbnailUrl:a.toUrl("../images/basemap/streets-navigation.jpg"),
baseMapLayers:[{url:"//www.arcgis.com/sharing/rest/content/items/dcbbba0edf094eaa81af19298b9c6247/resources/styles/root.json",layerType:"VectorTileLayer"}]}}});