// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define(["require","exports","dojo/_base/lang","../../../../core/Logger","../../../../core/Error"],function(y,g,m,w,k){function x(b,a,d){for(var e="",f=0,h=0,c=0,g=0;f<d;)if(h=b[a+f],128>h)e+=String.fromCharCode(h),f++;else if(191<h&&224>h){if(f+1>=d)throw new k("utf8-decode-error","UTF-8 Decode failed. Two byte character was truncated.");c=b[a+f+1];e+=String.fromCharCode((h&31)<<6|c&63);f+=2}else{if(f+2>=d)throw new k("utf8-decode-error","UTF-8 Decode failed. Multi byte character was truncated.");
c=b[a+f+1];g=b[a+f+2];e+=String.fromCharCode((h&15)<<12|(c&63)<<6|g&63);f+=3}return e}function n(b,a){for(var d={byteOffset:0,byteCount:0,fields:Object.create(null)},e=0,f=0;f<a.length;f++){var h=a[f],c=h.valueType||h.type;d.fields[h.property]=(0,g.valueType2ArrayBufferReader[c])(b,e);e+=g.valueType2TypedArrayClassMap[c].BYTES_PER_ELEMENT}d.byteCount=e;return d}function s(b,a,d){var e=[],f,h=0,c;for(c=0;c<b;c+=1){f=a[c];if(0<f){if(e.push(x(d,h,f-1)),0!==d[h+f-1])throw new k("string-array-error","Invalid string array: missing null termination.");
}else e.push(null);h+=f}return e}function p(b,a){return new g.valueType2TypedArrayClassMap[a.valueType](b,a.byteOffset,a.count*a.valuesPerElement)}function t(b,a){return new Uint8Array(b,a.byteOffset,a.byteCount)}function u(b,a,d){b=null!=a.header?n(b,a.header):{byteOffset:0,byteCount:0,fields:{count:d}};d={header:b,byteOffset:b.byteCount,byteCount:0,entries:Object.create(null)};for(var e=b.byteCount,f=0;f<a.ordering.length;f++){var h=a.ordering[f],c=m.clone(a[h]);c.count=b.fields.count;if("String"===
c.valueType){if(c.byteOffset=e,c.byteCount=b.fields[h+"ByteCount"],"UTF-8"!==c.encoding)throw new k("unsupported-encoding","Unsupported String encoding.",{encoding:c.encoding});}else if(q(c.valueType)){var g=l(c.valueType),e=e+(0!==e%g?g-e%g:0);c.byteOffset=e;c.byteCount=g*c.valuesPerElement*c.count}else throw new k("unsupported-value-type","Unsupported binary valueType",{valueType:c.valueType});e+=c.byteCount;d.entries[h]=c}d.byteCount=e-d.byteOffset;return d}function v(b,a,d){a!==b&&r.error("Invalid "+
d+" buffer size\n expected: "+b+", actual: "+a+")");if(a<b)throw new k("buffer-too-small","Binary buffer is too small",{expectedSize:b,actualSize:a});}function q(b){return g.valueType2TypedArrayClassMap.hasOwnProperty(b)}function l(b){return q(b)&&g.valueType2TypedArrayClassMap[b].BYTES_PER_ELEMENT}var r=w.getLogger("esri.layers.SceneService");g.readHeader=n;g.readStringArray=s;g.createTypedView=p;g.createRawView=t;g.createAttributeDataIndex=u;g.createGeometryDataIndex=function(b,a,d){var e=n(b,a.header),
f=e.byteCount,h={header:e,byteOffset:e.byteCount,byteCount:0,vertexAttributes:m.clone(a.vertexAttributes)},c=h.vertexAttributes;!d&&null!=c.region&&delete c.region;for(d=0;d<a.ordering.length;d++){var g=a.ordering[d];null!=c[g]&&(c[g].byteOffset=f,c[g].count=e.fields.vertexCount,f+=l(c[g].valueType)*c[g].valuesPerElement*e.fields.vertexCount)}if(a.faces){h.faces=m.clone(a.faces);c=h.faces;for(d=0;d<a.ordering.length;d++)name=a.ordering[d],c[name].byteOffset=f,c[name].count=e.fields.vertexCount;f+=
l(c[name].valueType)*c[name].valuesPerElement*e.fields.vertexCount}if(a.featureAttributes&&a.featureAttributeOrder&&e.fields.featureCount){h.featureAttributes=m.clone(a.featureAttributes);c=h.featureAttributes;for(d=0;d<a.featureAttributeOrder.length;d++)name=a.featureAttributeOrder[d],c[name].byteOffset=f,c[name].count=e.fields.featureCount,g=l(c[name].valueType),"UInt64"===c[name].valueType&&(g=8),f+=g*c[name].valuesPerElement*e.fields.featureCount}v(f,b.byteLength,"geometry");h.byteCount=f-h.byteOffset;
return h};g.readBinaryAttribute=function(b,a,d){b["attributeByteCounts "]&&!b.attributeByteCounts&&(r.error("Warning: Trailing space in 'attributeByteCounts '."),b.attributeByteCounts=b["attributeByteCounts "]);"ObjectIds"===b.ordering[0]&&b.hasOwnProperty("objectIds")&&(r.error("Warning: Case error in objectIds"),b.ordering[0]="objectIds");d=u(a,b,d);v(d.byteOffset+d.byteCount,a.byteLength,"attribute");if(b=d.entries.attributeValues||d.entries.objectIds){if("String"===b.valueType){d=d.entries.attributeByteCounts;
var e=p(a,d);a=t(a,b);return s(d.count,e,a)}return p(a,b)}throw new k("bad-attribute-storage-info","Bad attributeStorageInfo specification.");};g.valueType2TypedArrayClassMap={Float32:Float32Array,Float64:Float64Array,UInt8:Uint8Array,Int8:Int8Array,UInt16:Uint16Array,Int16:Int16Array,UInt32:Uint32Array,Int32:Int32Array};g.valueType2ArrayBufferReader={Float32:function(b,a){return(new DataView(b,0)).getFloat32(a,!0)},Float64:function(b,a){return(new DataView(b,0)).getFloat64(a,!0)},UInt8:function(b,
a){return(new DataView(b,0)).getUint8(a)},Int8:function(b,a){return(new DataView(b,0)).getInt8(a)},UInt16:function(b,a){return(new DataView(b,0)).getUint16(a,!0)},Int16:function(b,a){return(new DataView(b,0)).getInt16(a,!0)},UInt32:function(b,a){return(new DataView(b,0)).getUint32(a,!0)},Int32:function(b,a){return(new DataView(b,0)).getInt32(a,!0)}};g.isValueType=q;g.getBytesPerValue=l});