// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("./support/viewModelWiring ./Widget ./Legend/LegendViewModel ./Legend/support/swatchUtils ../core/watchUtils ../core/HandleRegistry ../core/lang ../core/screenUtils dojox/gfx dojox/gfx/matrix dojo/_base/lang dojo/dom-construct dojo/dom-style dojo/dom-class dojo/i18n!./Legend/nls/Legend".split(" "),function(D,w,x,r,n,y,z,A,s,B,t,f,C,l,u){return w.createSubclass({declaredClass:"esri.widgets.Legend",baseClass:"esri-legend",constructor:function(){this._handles=new y;this._DOMByLayerId={}},postCreate:function(){this.inherited(arguments);
this._createLegend()},destroy:function(){this._handles.destroy();this._handles=null},properties:{activeLayerInfos:{aliasOf:"viewModel.activeLayerInfos"},layerInfos:{aliasOf:"viewModel.layerInfos"},basemapLegendVisible:{aliasOf:"viewModel.basemapLegendVisible"},groundLegendVisible:{aliasOf:"viewModel.groundLegendVisible"},view:{aliasOf:"viewModel.view"},viewModel:{type:x}},_createLegend:function(){var a=this._buildLegendDOM(),b=this.activeLayerInfos;b.length&&b.forEach(function(b){this._createLegendForLayer(b,
a)},this);b=b.on("change",function(b){var d,g=b.added;b.removed.forEach(function(a){(d=this._DOMByLayerId[a.layer.uid])&&this._toggleDisplay(d)},this);g.forEach(function(b){(d=this._DOMByLayerId[b.layer.uid])?this._toggleDisplay(d):this._createLegendForLayer(b,a)},this);this._sortDOMNodes(a)}.bind(this));this._handles.add(b,"activeLayerInfos-change")},_hasVisibleDOMNodes:function(){var a=this._DOMByLayerId,b=!1,c;for(c in a)if(!l.contains(a[c],"esri-hidden")){b=!0;break}return b},_isActiveLayerInfosReady:function(a){return!a.length||
1===a.length&&a.getItemAt(0).updating&&!this._hasVisibleDOMNodes()?!1:a.some(function(a){return a.ready||a.updating})},_sortDOMNodes:function(a){var b=this.activeLayerInfos,c=this.domNode,d=c.childNodes,g=[],e={},f=this.id+"_",h=this._isActiveLayerInfosReady(b),v=l.contains(a.message,"esri-hidden");(h&&!v||!h&&v)&&this._toggleDisplay(a.message);for(a=0;a<d.length;++a)h=d[a],h.id&&-1<h.id.indexOf(f)&&!l.contains(h,"esri-hidden")&&g.push(h);b.forEach(function(a,b){e[a.layer.uid]=b});b=g.sort(function(a,
b){var c=e[a.id.split(f)[1]]||0,d=e[b.id.split(f)[1]]||0;return c-d});for(a=0;a<b.length;++a)c.appendChild(b[a])},_buildLegendDOM:function(){var a=this.domNode,b=f.create("div",{id:this.id+"_msg",className:"esri-legend__message",textContent:u.noLegend},a);return{widget:a,message:b}},_createLegendForLayer:function(a,b){var c=n.init(a,"version",function(){var c=a.layer.uid,e=this._DOMByLayerId[c];e&&!a.updating&&(delete this._DOMByLayerId[c],f.destroy(e));a.ready&&(e=this._buildLegendDOMForLayer(a,
b),this._DOMByLayerId[c]=e.root,this._createLegendElements(a,e.layer).length&&-1!==this.activeLayerInfos.indexOf(a)&&this._toggleDisplay(e.root));this._sortDOMNodes(b)}.bind(this)),d=n.init(a,"tearingDown",function(b){var c=a.layer.uid;if(b&&(b=this._DOMByLayerId[c]))this._handles.remove(c),delete this._DOMByLayerId[c],f.destroy(b)}.bind(this));this._handles.add([c,d],a.layer.uid)},_buildLegendDOMForLayer:function(a,b){var c=f.create("div",{id:b.widget.id+"_"+a.layer.uid,className:"esri-legend__service esri-hidden"},
b.widget),d=f.create("p",{textContent:a.title,className:"esri-legend__service-label"},c),g=f.create("div",{className:"esri-legend__layer"},c);return t.mixin(b,{root:c,title:d,layer:g})},_createLegendElements:function(a,b){var c=a.legendElements,d=a.layer;c.forEach(function(a){this._createLegendElement(a,b,d)},this);return c},_createLegendElement:function(a,b,c,d){var g="color-ramp"===a.type,e="opacity-ramp"===a.type,f="size-ramp"===a.type,h=this._buildDOMForElement(b,a.title,g||e,d);"symbol-table"===
a.type||f?a.infos.forEach(function(a){a.type?this._createLegendElement(a,h.body,c,!0):this._buildDOMForElementInfo(a,h,c,f)},this):(g||e)&&this._buildRampDOM(a.infos,h.body,a.overlayColor,e)},_buildDOMForElement:function(a,b,c,d){"string"!==typeof b&&b&&(c=this._getTitle(b,c),b=b.title?b.title+" ("+c+")":c);d=f.create("div",{className:d?"esri-legend__layer-child-table":"esri-legend__layer-table"},a);b=b?f.create("div",{className:"esri-legend__layer-caption",textContent:b},d):null;c=f.create("div",
{className:"esri-legend__layer-body"},d);return{layer:a,table:d,caption:b,body:c}},_buildDOMForElementInfo:function(a,b,c,d){var g=f.create("div",{className:"esri-legend__layer-row"},b.body),e=a.symbol,k=r.getSymbolSize(e),h=k.width,k=k.height;d=f.create("div",{className:d?"esri-legend__layer-cell esri-legend__layer-cell--symbols esri-legend__size-ramp":"esri-legend__layer-cell esri-legend__layer-cell--symbols"},g);(e?this._drawSymbol(d,e,h,k,c):this._drawImage(d,a,c))?(l.add(d.firstChild,"esri-legend__symbol"),
f.create("div",{className:"esri-legend__layer-cell esri-legend__layer-cell--info"},g).textContent=a.label||""):f.destroy(b.table)},_drawImage:function(a,b,c){var d=b.src,g=b.opacity,e=b.width;b=b.height;return d?(a=f.create("img",{src:d,border:0},a),null!=e&&null!=b&&(a.width=e,a.height=b),a.style.opacity=null!=g?g:c.opacity,!0):!1},_drawSymbol:function(a,b,c,d,f){"picture-marker-symbol"===b.type&&(a.style.opacity=f.opacity);var e=s.createSurface(a,c,d);a=r.getSwatch(b);var k;try{if(null==a)throw"no shape descriptors!";
var h=e.createGroup();a.forEach(function(a){a.forEach(function(a){var b=a.shape,c=a.fill,d=a.stroke;if(b){var e="text"===b.type;e&&!b.text&&(b.text="Aa");"image"===b.type&&(b.src&&"data:"!==b.src.substr(0,5))&&(b.src+=(-1===b.src.indexOf("?")?"?":"\x26")+"legend\x3d1");k=h.createShape(b).setFill(c).setStroke(d?d:{width:0});e&&k.setFont(a.font)}})})}catch(l){return e.clear(),e.destroy(),!1}var m=h.getBoundingBox();a=m.width;var p=m.height,q=-(m.x+a/2),n=-(m.y+p/2),e=e.getDimensions(),q={dx:q+e.width/
2,dy:n+e.height/2};"simple-marker-symbol"===b.type&&"path"===b.style&&(b=f._getScaleMatrix(m,A.pt2px(b.size)),h.applyTransform(B.scaleAt(b.xx,b.yy,{x:e.width/2,y:e.height/2})));if(a>c||p>d)b=a/c>p/d,c=((b?c:d)-5)/(b?a:p),t.mixin(q,{xx:c,yy:c});h.applyTransform(q);return!0},_buildRampDOM:function(a,b,c,d){var g=a.length-1,e,k,h;b=f.create("div",{className:"esri-legend__layer-row"},b);e=f.create("div",{className:"esri-legend__layer-cell esri-legend__layer-cell--symbols",style:"width:24px"},b);e=f.create("div",
{className:"esri-legend__ramps"},e);e=f.create("div",{className:"esri-legend__color-ramp "+(d?"esri-legend__opacity-ramp":"")},e);d=f.create("div",{className:"esri-legend__layer-cell esri-legend__layer-cell--info"},b);g=2<g?25*g:50;C.set(e,"height",g+"px");b=s.createSurface(e,"100%",g);try{h=b.createRect({x:0,y:0,width:"100%",height:g}),h.setFill({type:"linear",x1:0,y1:0,x2:0,y2:g,colors:a}).setStroke(null),c&&0<c.a&&b.createRect({width:"100%",height:g}).setFill(c).setStroke(null)}catch(l){b.clear(),
b.destroy()}k=f.create("div",{className:"esri-legend__ramp-labels",style:{height:g+"px"}},d);a.forEach(function(a){a.label&&f.create("div",{className:"esri-legend__ramp-label",innerHTML:a.label},k)})},_getTitle:function(a,b){var c;return(c=b?a.ratioPercentTotal&&"showRatioPercentTotal"||a.ratioPercent&&"showRatioPercent"||a.ratio&&"showRatio"||a.normField&&"showNormField"||a.field&&"showField"||null:a.normField&&"showNormField"||(a.normByPct?"showNormPct":null)||a.field&&"showField"||null)?z.substitute({field:a.field,
normField:a.normField},u[c]):null},_toggleDisplay:function(a){l.contains(a,"esri-hidden")?l.remove(a,"esri-hidden"):l.add(a,"esri-hidden")}})});