// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/widgets/Print/templates/Print.html":'\x3cdiv\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"_printButtonContainerNode" class\x3d"${_css.printButtonContainer}"\x3e\r\n    \x3cdiv role\x3d"button" tabindex\x3d"0" class\x3d"${_css.button} ${_css.printButton}" data-dojo-attach-point\x3d"_printButtonNode"\x3e\r\n      ${_i18n.print}\r\n    \x3c/div\x3e\r\n\r\n    \x3cdiv role\x3d"button" tabindex\x3d"0" class\x3d"${_css.button} ${_css.arrowButton}" data-dojo-attach-point\x3d"_arrowButtonNode"\x3e\r\n      \x3cdiv class\x3d"${_css.printArrowIcon}"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n\r\n  \x3cdiv role \x3d "menu" class\x3d"${_css.menu} ${_css.hide}" data-dojo-attach-point\x3d"_dropdownMenuNode"\x3e\x3c/div\x3e\r\n\r\n  \x3ca id\x3d"printAnchor" tabindex\x3d"0" class\x3d"${_css.printAnchor} ${_css.hide}" data-dojo-attach-point\x3d"_printoutLinkNode"\x3e${_i18n.printout}\x3c/a\x3e\r\n\x3c/div\x3e'}});
define("dijit/a11yclick dijit/_TemplatedMixin ../core/watchUtils ../core/urlUtils ./support/viewModelWiring ./Print/PrintViewModel ./Widget dojo/_base/lang dojo/dom dojo/dom-class dojo/dom-construct dojo/dom-attr dojo/on dojo/i18n!./Print/nls/Print dojo/text!./Print/templates/Print.html".split(" "),function(e,g,h,r,k,l,m,s,t,c,n,p,f,d,q){var b={base:"esri-print",button:"esri-button esri-widget-button",arrowButton:"esri-print__arrow-down-button",menu:"esri-print__dropdown-menu",menuItem:"esri-print__dropdown-item",
printButtonContainer:"esri-print__container",printButton:"esri-print__print-button",printArrowIcon:"esri-icon esri-icon-down-arrow",printAnchor:"esri-print__anchor",hide:"esri-hidden",disabled:"esri-disabled"};return m.createSubclass([g],{declaredClass:"esri.widgets.Print",baseClass:b.base,templateString:q,constructor:function(){this._handlePrintAnchorClick=this._handlePrintAnchorClick.bind(this);this._handleArrowButtonClick=this._handleArrowButtonClick.bind(this);this._handleStateChange=this._handleStateChange.bind(this);
this._handlePrintMap=this._handlePrintMap.bind(this)},postCreate:function(){this.inherited(arguments);this.own(f(this._printoutLinkNode,e,this._handlePrintAnchorClick),f(this._arrowButtonNode,e,this._handleArrowButtonClick),f(this._printButtonNode,e,this._handlePrintMap),h.init(this.viewModel,"state",this._handleStateChange));this._createUI(this.templates)},properties:{printServiceUrl:{aliasOf:"viewModel.printServiceUrl"},printoutUrl:{aliasOf:"viewModel.printoutUrl"},templates:{aliasOf:"viewModel.templates"},
view:{aliasOf:"viewModel.view"},viewModel:{type:l}},_css:b,_i18n:d,_selectionTemplate:null,_handleArrowButtonClick:function(){c.toggle(this._dropdownMenuNode,b.hide)},_handlePrintMap:function(){"ready"===this.viewModel.state&&(this.print(this._selectionTemplate),this._printButtonNode.innerHTML=d.printing,this._togglePrintButtonClasses())},_handlePrintAnchorClick:function(){p.set("printAnchor",{href:this.printoutUrl,target:"_blank"});this.viewModel.openPrintout();this._togglePrintButtonClasses()},
_handleStateChange:function(a){"ready"===a&&(this._printButtonNode.innerHTML=d.print,c.remove(this._printButtonContainerNode,b.hide));c.toggle(this._printButtonContainerNode,b.hide,"printoutReady"===a);c.toggle(this._printoutLinkNode,b.hide,"printoutReady"!==a)},print:k.createMethodDelegate("print"),_createUI:function(a){!a||1===a.length?(this._selectionTemplate=a&&a[0],c.toggle(this._arrowButtonNode,b.hide)):this._createMenu(this.templates)},_createMenu:function(a){var d={};a.forEach(function(a){d[a.label]=
a;n.create("div",{className:b.menuItem,textContent:a.label,tabIndex:"0",role:"menuitem"},this._dropdownMenuNode)}.bind(this));f(this._dropdownMenuNode,e,function(a){this._selectionTemplate=d[a.target.innerHTML];this._handlePrintMap();c.toggle(this._dropdownMenuNode,b.hide,!0)}.bind(this))},_togglePrintButtonClasses:function(){c.toggle(this._printButtonNode,b.disabled);c.toggle(this._arrowButtonNode,b.disabled)}})});