// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("../core/Accessor ../core/declare ../core/accessorSupport/metadata dijit/_WidgetBase dijit/Destroyable dijit/registry dojo/_base/lang dojo/_base/window dojo/dom dojo/dom-attr dojo/dom-class dojo/on".split(" "),function(m,k,n,c,p,f,e,q,r,l,g,s){function t(a){return function(b){this._set(a,b)}}function u(a,b){return function(d){v.call(this,a,b,d);this._set(a,d)}}function v(a,b,d){(Array.isArray(b)?b:[b]).forEach(function(b){var c=this[b.node||b||"domNode"];switch(b.type||"attribute"){case "attribute":e.isFunction(d)&&
(d=d.bind(this));b=b.attribute?b.attribute:/^on[A-Z][a-zA-Z]*$/.test(a)?a.toLowerCase():a;c.tagName?l.set(c,b,d):c.set(b,d);break;case "innerText":c.innerHTML="";c.appendChild(this.ownerDocument.createTextNode(d));break;case "innerHTML":c.innerHTML=d;break;case "class":b=this._get(a),g.replace(c,d,b)}},this)}k.before(function(a,b){if(b.declaredClass===h||k.hasMixin(a,h)){var d=n.getPropertiesMetadata(b);Object.keys(d).forEach(function(a){var b=d[a];var c=b.set;a="function"===typeof c?c:null===c?t(b.name):
"string"===typeof c||"object"===typeof c?u(a,c):void 0;b.set=a})}});var h="esri.widgets._WidgetBase";return m.createSubclass([p],{declaredClass:h,postscript:function(a){var b=this.__accessor__;a=b.ctorArgs||a;var c;(c=this.getDefaults?a?this.getDefaults(a):this.getDefaults({}):null)&&Object.getOwnPropertyNames(c).forEach(function(a){b.set(a,c[a])},this);this.postMixInProperties();this.ownerDocument=this.ownerDocument||(this.srcNodeRef?this.srcNodeRef.ownerDocument:document);this.ownerDocumentBody=
q.body(this.ownerDocument);f.add(this);this.buildRendering();b.initialize();a&&(this.set(a),b.ctorArgs=null);b.initialize();this.initialize();this.postCreate();if(this.domNode){var e;if((a=this.srcNodeRef)&&a.parentNode&&this.domNode!==a)a.parentNode.replaceChild(this.domNode,a),e=!0;l.set(this.domNode,{widgetId:this.id,id:this.id});e&&delete this.srcNodeRef}this._created=!0},getDefaults:function(a){var b={};b.id=a.id?a.id:a.srcNodeRef&&a.srcNodeRef.id||f.getUniqueId(this.declaredClass.replace(/\./g,
"_"));delete a.id;a.srcNodeRef&&(b.srcNodeRef=a.srcNodeRef,delete a.srcNodeRef);return e.mixin(this.inherited(arguments),b)},normalizeCtorArgs:function(a,b){a=a||{};if(a.srcNodeRef||b)a.srcNodeRef=r.byId(b||a.srcNodeRef);return a},destroy:function(){this._customWidgetBaseDestroy()},postMixInProperties:c.prototype.postMixInProperties,buildRendering:c.prototype.buildRendering,postCreate:c.prototype.postCreate,startup:c.prototype.startup,_beingDestroyed:!1,_destroyed:!1,_created:!1,properties:{"class":{value:"",
set:{node:"domNode",type:"class"}},domNode:{value:null},focused:!1,id:{value:""},srcNodeRef:{value:null},style:{value:null,set:c.prototype._setStyleAttr},widgetId:{}},destroyDescendants:c.prototype.destroyDescendants,destroyRecursive:c.prototype.destroyRecursive,destroyRendering:c.prototype.destroyRendering,emit:c.prototype.emit,on:function(a,b){return this.own(s(this.domNode,a,b))[0]},toString:c.prototype.toString,getChildren:c.prototype.getChildren,getParent:c.prototype.getParent,isLeftToRight:c.prototype.isLeftToRight,
placeAt:c.prototype.placeAt,onFocus:function(){},onBlur:function(){},_onFocus:function(){this.onFocus()},_onBlur:function(){this.onBlur()},dojoAttachEvent:"",dojoAttachPoint:"",_customWidgetBaseDestroy:function(a){function b(b){b.destroyRecursive?b.destroyRecursive(a):b.destroy&&b.destroy(a)}this._beingDestroyed=!0;this.domNode&&f.findWidgets(this.domNode,this.containerNode).forEach(b);this.destroyRendering(a);f.remove(this.id);this._destroyed=!0}}).createSubclass({declaredClass:"esri.widgets.Widget",
getDefaults:function(){return e.mixin(this.inherited(arguments),{viewModel:{}})},buildRendering:function(){this.inherited(arguments);g.add(this.domNode,"esri-widget")},destroy:function(){this.viewModel.destroy&&this.viewModel.destroy();this.viewModel=null},properties:{viewModel:{value:null},visible:{value:!0,set:function(a){this._set("visible",a);g.toggle(this.domNode,"esri-hidden",!a)}}}})});