// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("require exports ../../layers/Layer ../../core/promiseUtils ../../core/requireUtils ./byReferenceRenderer dojo/has".split(" "),function(q,f,r,h,s,t,B){function u(e,a,b){var c,g;return s.when(q,"../../layers/"+a).then(function(a){var d={};e.itemId&&(d.portalItem={id:e.itemId,portal:b.context.portal});g=c=new a(d);return t.read(g,e,b.context)}).then(function(){g.read(e,b.context);return h.resolve(c)})}function l(e,a){var b=e.layerType||e.type;!b&&(a&&a.defaultLayerType)&&(b=a.defaultLayerType);
var c;switch(a.context.origin){case "web-scene":switch(a.context.layerContainerType){case "basemap":c=v;break;case "ground":c=w;break;default:c=x}break;default:switch(a.context.layerContainerType){case "basemap":c=y;break;default:c=z}}return u(e,c[b]||"UnknownLayer",a)}function m(e,a,b){return!a||!a.filter?b:b.then(function(c){var b=a.filter(c);return void 0===b?h.resolve(c):b instanceof r?h.resolve(b):b})}function k(e,a,b){if(!a)return[];for(var c=[],g=[],f=0;f<a.length;f++){var d=a[f],k=l(d,b);
c.push(k);g.push(null);if("GroupLayer"===d.layerType&&d.layers&&Array.isArray(d.layers)&&0<d.layers.length){d=d.layers.map(function(a){return l(a,b)});c.push.apply(c,d);for(var n=0;n<d.length;n++)g.push(k)}}var p={};return c.map(function(a,c){var d=function(a,b){p[b.id]=c;var d=a.findIndex(function(a){if(!a.id)return!1;a=p[a.id];return void 0===a?!1:c<a});0>d&&(d=void 0);a.add(b,d)},f=m(e,b,a).then(function(a){if(null===g[c])d(e,a);else return g[c].then(function(b){d(b.layers,a);return h.resolve(a)});
return h.resolve(a)});A&&(f=f.otherwise(function(a){console.error(a.toString?a.toString():a);return h.reject(a)}));return f})}var A=0,x={ArcGISFeatureLayer:"FeatureLayer",ArcGISMapServiceLayer:"MapImageLayer",ArcGISSceneServiceLayer:"SceneLayer",IntegratedMeshLayer:"IntegratedMeshLayer",ArcGISTiledElevationServiceLayer:"ElevationLayer",ArcGISTiledImageServiceLayer:"TileLayer",ArcGISTiledMapServiceLayer:"TileLayer",GroupLayer:"GroupLayer",OpenStreetMap:"OpenStreetMapLayer",WebTiledLayer:"WebTileLayer",
DefaultTileLayer:"TileLayer"},w={ArcGISTiledElevationServiceLayer:"ElevationLayer",DefaultTileLayer:"ElevationLayer"},v={ArcGISTiledMapServiceLayer:"TileLayer",ArcGISTiledImageServiceLayer:"TileLayer",OpenStreetMap:"OpenStreetMapLayer",WebTiledLayer:"WebTileLayer",DefaultTileLayer:"TileLayer"},z={ArcGISFeatureLayer:"FeatureLayer",ArcGISImageServiceLayer:"ImageryLayer",ArcGISImageServiceVectorLayer:"UnsupportedLayer",ArcGISMapServiceLayer:"MapImageLayer",ArcGISStreamLayer:"StreamLayer",ArcGISTiledElevationServiceLayer:"ElevationLayer",
ArcGISTiledImageServiceLayer:"TileLayer",ArcGISTiledMapServiceLayer:"TileLayer",GroupLayer:"GroupLayer",OpenStreetMap:"OpenStreetMapLayer",VectorTileLayer:"VectorTileLayer",WebTiledLayer:"WebTileLayer",CSV:"CSVLayer",GeoRSS:"UnsupportedLayer",KML:"UnsupportedLayer",WMS:"UnsupportedLayer",DefaultTileLayer:"TileLayer"},y={ArcGISImageServiceLayer:"ImageryLayer",ArcGISImageServiceVectorLayer:"UnsupportedLayer",ArcGISMapServiceLayer:"MapImageLayer",ArcGISTiledImageServiceLayer:"TileLayer",ArcGISTiledMapServiceLayer:"TileLayer",
OpenStreetMap:"OpenStreetMapLayer",VectorTileLayer:"VectorTileLayer",WebTiledLayer:"WebTileLayer",bingLayer:"UnsupportedLayer",WMS:"UnsupportedLayer",DefaultTileLayer:"TileLayer"};f.createLayer=l;f.processLayer=m;f.populateLayers=k;f.populateOperationalLayers=function(e,a,b){return k(e,a,b)}});