// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("require exports ./IntervalUtilities ./ModelDirtyTypesTs ./Float32ArrayList ./InstanceBufferData ./Lighting ../materials/internal/SimpleGLMaterial ../materials/internal/TexOnlyGLMaterial ./LinearDepthTextureHelper ./NormalTextureHelper ./HighlightTextureHelper ./RenderPass ./RenderSlot ./RenderContext ./ExternalRendererContainer ./StencilRenderingHelper ./BitSet ./Util ./gl-matrix ../../../webgl/Texture ../../../webgl/VertexArrayObject ../../../webgl/BufferObject ../../../webgl/Util ./FxaaRenderPass ./SmaaRenderPass ../../../webgl/enums ./DefaultVertexBufferLayouts ./DefaultVertexAttributeLocations".split(" "),
function(R,S,T,qa,U,aa,ba,V,ca,da,ea,fa,y,r,ga,ha,ia,ja,C,L,W,M,N,D,ka,la,ra,ma,O){var B=C.assert,X=C.array2object,Y=C.objectEmpty,G=C.getFirstObjectValue,P=C.setMatrixTranslation3;R=L.vec2d;S=L.vec3d;var Q=L.vec4d,A=L.mat4d,na=C.VertexAttrConstants,H=A.identity();C=S.create();var oa=1535,Z={proj:H,view:H,nearFar:[-1,1],origin:C};C=function(){function e(a,b,d,c,f){this._lighting=new ba;this._mat2dataMerged={};this._mat2dataInstanced={};this._renderOrder=[];this._externalRenderers=new ha;this._renderContext=
new ga;this._framesRendered=0;this._isRendering=!1;this._pixelRatio=1;this._threshold=oa;this._needsRender=!0;this._stats=new pa;this.ssaoEnabled=!1;this.renderOptions={antialiasing:"smaa",earlyOcclusionPixelDraw:!1};this._programRep=a;this._materialRep=b;this._textureRep=d;this._orderedRendering=f;this._rctx=c;b=c.gl;this._fxaaPass=new ka(c);this._smaaPass=new la(c);this._selectionMaterial=new V(a,Q.createFrom(0.1,0.2,0.9,0.4),b.EQUAL);this._selectionMaterialLines=new V(a,Q.createFrom(0.1,0.2,0.9,
0.4),b.EQUAL,b.LINES);this._renderContext.lightingData=this._lighting.get();c.setDepthTestEnabled(!0);c.setFaceCullingEnabled(!0);c.setBlendingEnabled(!1);c.setBlendFunctionSeparate(770,771,1,771);this._bindParameters={view:null,proj:null,viewInvTransp:null,nearFar:null,lightingData:null,viewport:null,framebufferTex:null,shadowMap:null,origin:null,pixelRatio:null,instanceParameters:null,depthFBO:null,normalFBO:null,extensions:{angleInstancedArrays:c.extensions.angleInstancedArrays}};this._linearDepthTextureHelper=
new da(c);this._normalTextureHelper=new ea(c);this._highlightTextureHelper=new fa(c);this._stencilRenderingHelper=new ia(c);this._initializeFramebufferTexture();this._initializeIeTextureFix()}e.prototype._initializeQuadVAO=function(){if(!this._quadVAO){var a=this._rctx,b=new Float32Array([-1,-1,0,0,0,1,-1,0,1,0,-1,1,0,0,1,1,1,0,1,1]);this._quadVAO=new M(a,O.Default3D,{geometry:ma.Pos3Tex},{geometry:N.createVertex(a,35044,b)})}};e.prototype._initializeFramebufferTexture=function(){var a=this._rctx.gl,
a=this._rctx.contextAttributes.alpha?a.RGBA:a.RGB,b=new W(this._rctx,{target:3553,pixelFormat:a,dataType:5121,samplingMode:9728,wrapMode:33071,width:4,height:4});this._framebuffer={format:a,texture:b,copied:!1}};e.prototype._initializeIeTextureFix=function(){if(6408===this._framebuffer.format){for(var a=new Uint8Array(64),b=0;64>b;b++)a[b]=255;this._ieFixTexture=new W(this._rctx,{target:3553,pixelFormat:6408,dataType:5121,samplingMode:9728,width:4,height:4});this._ieFixMaterial=new ca(this._programRep,
this._ieFixTexture,Q.createFrom(1,1,1,1),!0,519)}};e.prototype.dispose=function(){for(var a in this._mat2dataMerged){this._releaseMaterials(a);var b=this._mat2dataMerged[a],d;for(d in b.origin2data)b.origin2data[d].vao.dispose(!0)}this._mat2dataMerged=null;for(a in this._mat2dataInstanced)for(d in this._releaseMaterials(a),b=this._mat2dataInstanced[a],b.origin2data)b.origin2data[d].vao.dispose(!0);this._mat2dataInstanced=null;this._quadVAO&&(this._quadVAO.dispose(!0),this._quadVAO=null);this._ieFixTexture&&
(this._ieFixTexture.dispose(),this._ieFixTexture=null);this._framebuffer.texture.dispose();this._framebuffer.texture=null;this._linearDepthTextureHelper.getEnableState()&&this._linearDepthTextureHelper.disable();this._normalTextureHelper.getEnableState()&&this._normalTextureHelper.disable();this._highlightTextureHelper.getEnableState()&&this._highlightTextureHelper.setEnableState(!1);this._stencilRenderingHelper.getEnableState()&&this._stencilRenderingHelper.setEnableState(!1)};e.prototype.setLightingData=
function(a){this._lighting.set(a);this._needsRender=!0};e.prototype.getLightingData=function(){return this._lighting.get()};e.prototype.setPixelRatio=function(a){this._pixelRatio=a;this._needsRender=!0};e.prototype.getPixelRatio=function(){return this._pixelRatio};e.prototype.addExternalRenderer=function(a,b){this._externalRenderers.addRenderer(a,b);return!0};e.prototype.removeExternalRenderer=function(a){this._externalRenderers.removeRenderer(a);return!0};e.prototype.getExternalRenderers=function(){return this._externalRenderers};
e.prototype.resetNeedsRender=function(){this._needsRender=!1;this._externalRenderers.resetNeedsRender()};e.prototype.needsRender=function(){return this._needsRender||this._externalRenderers.needsRender()};e.prototype.getCombinedStats=function(){this._stats.VBOallocatedSize=0;this._stats.VBOoptimalSize=0;this._stats.VBOusedSize=0;for(var a in this._mat2dataInstanced){var b=this._mat2dataInstanced[a],d;for(d in b.origin2data){var c=b.origin2data[d];this._stats.VBOallocatedSize+=c.buffer.getArray().length;
this._stats.VBOusedSize+=c.buffer.getSize();this._stats.VBOoptimalSize+=c.optimalCount}}for(a in this._mat2dataMerged)for(d in b=this._mat2dataMerged[a],b.origin2data)c=b.origin2data[d],this._stats.VBOallocatedSize+=c.buffer.getArray().length,this._stats.VBOusedSize+=c.buffer.getSize(),this._stats.VBOoptimalSize+=c.optimalCount;this._stats.VBOallocatedSize*=0.00390625;this._stats.VBOusedSize*=0.00390625;this._stats.VBOoptimalSize*=0.00390625;return this._stats};e.prototype.setSelectionObject=function(a,
b){a?(Array.isArray(a)?this._selectionIndices=this._name2indices(X(a)):this._selectionIndices=this._name2indices(X([a])),this._selectionFaceIndexRange=void 0,null!=b&&1===b.length&&(this._selectionFaceIndexRange=[[3*b[0][0],3*b[0][1]]])):this._selectionFaceIndexRange=this._selectionIndices=void 0;this._needsRender=!0};e.prototype.renderGeometrySlots=function(a){this._externalRenderers.render(r.INTERNAL_MATERIAL,a);this._renderInternalSlot(r.STENCIL_MATERIAL,a);this._externalRenderers.render(r.OPAQUE_TERRAIN,
a);this._renderInternalSlot(r.OPAQUE_MATERIAL,a);this._externalRenderers.render(r.OPAQUE_EXTERNAL,a);this._renderInternalSlot(r.TRANSPARENT_MATERIAL,a);this.renderOptions.earlyOcclusionPixelDraw&&this._renderInternalSlot(r.OCCLUSION_PIXELS,this._renderContext);this._externalRenderers.render(r.TRANSPARENT_EXTERNAL,a);this._externalRenderers.render(r.TRANSPARENT_TERRAIN,a)};e.prototype._renderHighlights=function(a,b,d,c){var f=!!c&&c.getEnableState()&&void 0!==this._selectionIndices;this._highlightTextureHelper.setEnableState(f);
f&&(this._highlightTextureHelper.setupFBOs(a),this._highlightTextureHelper.prepareHighlightPass(),this.renderGeometryPass(y.MATERIAL_HIGHLIGHT,a,b,this._selectionIndices,this._selectionFaceIndexRange),this._rctx.clear(this._rctx.gl.DEPTH_BUFFER_BIT),this._renderInternalSlot(r.OVERLAY,this._renderContext),this._highlightTextureHelper.finish(d),b=this._highlightTextureHelper.getHighlightFBO(),c.render(a,d,b))};e.prototype._renderUnordered=function(a,b,d,c,f,k,h){var p=this._rctx;this._isRendering=!0;
this._stats.reset();this._framebuffer.copied=!1;this._updateGlobalUniforms(a.projectionMatrix);this._renderContext.pass=y.MATERIAL;this._renderContext.camera=a;this._renderContext.shadowMap=d;this._renderContext.ssaoHelper=c;this._renderContext.offscreenRenderingHelper=k;this._renderContext.stencilRenderingHelper=this._stencilRenderingHelper;this._renderContext.depth=this._linearDepthTextureHelper.getDepthFBO();this._renderContext.normals=this._normalTextureHelper.getNormalFBO();this._renderContext.highlight=
this._highlightTextureHelper.getHighlightFBO();this._renderContext.visibleContent=b;this._renderContext.filterContent=null;this._renderContext.filterFaceRange=null;this._renderContext.options=this.renderOptions;k.setEnableState(!0);k.initializeFrame(a);this._externalRenderers.render(r.BACKGROUND,this._renderContext);this.renderGeometrySlots(this._renderContext);this._externalRenderers.render(r.POSTPROCESSING_ATMOSPHERE,this._renderContext);switch(this.renderOptions.antialiasing){case "none":d=a.viewport;
d=A.ortho(d[0],d[2],d[1],d[3],-1,1);k.drawQuad(d);this._fxaaPass.disable();this._smaaPass.disable();break;case "fxaa":this._smaaPass.disable();this._fxaaPass.render({colorTexture:k.getColorTexture()},null);break;case "smaa":this._fxaaPass.disable(),this._smaaPass.render({colorTexture:k.getColorTexture()},null)}this.renderOptions.earlyOcclusionPixelDraw||(k.bindFramebuffer(),this._renderInternalSlot(r.OCCLUSION_PIXELS,this._renderContext));p.bindFramebuffer(null);this._renderContext.framebufferTex=
k.getColorTexture();this._renderInternalSlot(r.OVERLAY,this._renderContext);this._renderHighlights(a,b,f,h);this._ieFixMaterial&&!f&&(p.setBlendFunctionSeparate(0,1,1,0),this._ieFixMaterial.bind(p,Z),this._ieFixMaterial.bindView(p,Z),this._initializeQuadVAO(),p.bindVAO(this._quadVAO),p.drawArrays(5,0,D.vertexCount(this._quadVAO,"geometry")),this._ieFixMaterial.release(p),p.setBlendFunctionSeparate(770,771,1,771));this._framesRendered++;this._isRendering=!1};e.prototype._renderOrdered=function(a,b){var d=
this._rctx;this._isRendering=!0;this._stats.reset();this._framebuffer.copied=!1;this._updateGlobalUniforms(a.projectionMatrix);this._bindParameters.view=a.viewMatrix;this._bindParameters.proj=a.projectionMatrix;this._bindParameters.viewInvTransp=a.viewInverseTransposeMatrix;I[0]=a.near;I[1]=a.far;this._bindParameters.nearFar=I;this._bindParameters.lightingData=this._lighting.get();this._bindParameters.viewport=a.fullViewport;this._bindParameters.framebufferTex=this._framebuffer.texture;this._bindParameters.pixelRatio=
this._pixelRatio;this._bindParameters.instanceParameters=void 0;this._bindParameters.depthFBO=this._linearDepthTextureHelper.getDepthFBO();this._bindParameters.normalFBO=this._normalTextureHelper.getNormalFBO();for(var c=!0,f=0;f<this._renderOrder.length;f++){var k=this._renderOrder[f][1];if(k.instanced){var h=k.instanced,p=h[y.MATERIAL];if(p&&(!p.isVisible||p.isVisible()))this._renderInternalInstanced(h,p,this._bindParameters,Infinity,b,null,null,!1),c=!0}if(k.merged&&(h=k.merged,(p=h[y.MATERIAL])&&
(!p.isVisible||p.isVisible())))c&&(c=p.getProgram(),d.bindProgram(c),c.setUniformMatrix4fv("model",H),c.hasUniform("modelNormal")&&c.setUniformMatrix4fv("modelNormal",H),c=!1),this._renderInternalMerged(h,p,this._bindParameters,Infinity)}this._framesRendered++;this._isRendering=!1};e.prototype.render=function(a,b,d,c,f,k,h){this._orderedRendering?this._renderOrdered(a,b):this._renderUnordered(a,b,d,c,f,h,k)};e.prototype.renderAuxiliaryBuffers=function(a,b,d,c,f,k,h){h=this.ssaoEnabled||this._externalRenderers.needsDepthMap();
this._linearDepthTextureHelper.setEnableState(h);h&&(this._linearDepthTextureHelper.setupFBOs(a),this._linearDepthTextureHelper.prepareDepthPass(),this.renderGeometryPass(y.MATERIAL_DEPTH,a,b,void 0,void 0,d,c),this._linearDepthTextureHelper.finish(k));this._normalTextureHelper.setEnableState(this.ssaoEnabled);this.ssaoEnabled&&(this._normalTextureHelper.setupFBOs(a),this._normalTextureHelper.prepareNormalPass(),this.renderGeometryPass(y.MATERIAL_NORMAL,a,b,void 0,void 0,d,c),this._normalTextureHelper.finish(k));
this.ssaoEnabled&&c.computeSSAO(a,k,f,this._linearDepthTextureHelper.getDepthFBO(),this._normalTextureHelper.getNormalFBO());c.bindAll(this._programRep)};e.prototype.renderGeometryPass=function(a,b,d,c,f,k,h){this._isRendering=!0;this._updateGlobalUniforms(b.projectionMatrix);this._renderContext.pass=a;this._renderContext.camera=b;this._renderContext.shadowMap=k;this._renderContext.ssaoHelper=h;this._renderContext.depth=this._linearDepthTextureHelper.getDepthFBO();this._renderContext.normals=this._normalTextureHelper.getNormalFBO();
this._renderContext.visibleContent=d;this._renderContext.filterContent=c;this._renderContext.filterFaceRange=f;this._renderContext.rctx=this._rctx;this.renderGeometrySlots(this._renderContext);this._isRendering=!1};e.prototype.renderSelection=function(a){this._isRendering=!0;for(var b=0;b<r.MAX_SLOTS;++b)this._renderInternalSlot(b,a);this._isRendering=!1};e.prototype._renderInternalSlot=function(a,b){this._bindParameters.view=b.camera.viewMatrix;this._bindParameters.proj=b.camera.projectionMatrix;
this._bindParameters.viewInvTransp=b.camera.viewInverseTransposeMatrix;this._bindParameters.cameraAboveGround=b.camera.aboveGround;I[0]=b.camera.near;I[1]=b.camera.far;this._bindParameters.nearFar=I;this._bindParameters.lightingData=this._lighting.get();this._bindParameters.viewport=b.camera.fullViewport;this._bindParameters.framebufferTex=this._renderContext.offscreenRenderingHelper?this._renderContext.offscreenRenderingHelper.getColorTexture():this._framebuffer.texture;this._bindParameters.shadowMap=
b.shadowMap;this._bindParameters.pixelRatio=this._pixelRatio;this._bindParameters.instanceParameters=void 0;this._bindParameters.depthFBO=this._linearDepthTextureHelper.getDepthFBO();for(var d in this._mat2dataInstanced){var c=this._mat2dataInstanced[d],f=c[b.pass];f&&(f.beginSlot(a)&&(!f.isVisible||f.isVisible()))&&this._renderInternalInstanced(c,f,this._bindParameters,a,b.visibleContent,b.filterContent,b.filterFaceRange,!1)}if(b.filterContent)for(d in this._mat2dataMerged)c=this._mat2dataMerged[d],
(f=c[b.pass])&&(f.beginSlot(a)&&(!f.isVisible||f.isVisible()))&&this._renderInternalInstanced(c,f,this._bindParameters,a,null,b.filterContent,b.filterFaceRange,!0);else{for(var c=this._programRep.getProgramsUsingUniform("model"),f=this._programRep.getProgramsUsingUniform("modelNormal"),k=0;k<c.length;k++){var h=c[k];h.setUniformMatrix4fv("model",H);-1<f.indexOf(h)&&h.setUniformMatrix4fv("modelNormal",H)}for(d in this._mat2dataMerged)c=this._mat2dataMerged[d],(f=c[b.pass])&&(f.beginSlot(a)&&(!f.isVisible||
f.isVisible()))&&this._renderInternalMerged(c,f,this._bindParameters,a)}this._stencilRenderingHelper.getEnableState()&&a===r.STENCIL_MATERIAL&&this._stencilRenderingHelper.prepareStencilDisabledPass()};e.prototype._renderInternalInstanced=function(a,b,d,c,f,k,h,p){var l=this._rctx,g=l.gl,e=!1,x=b.getDrawMode(l),s=this._bindParameters.extensions.angleInstancedArrays,n;for(n in a.origin2data){var z=a.origin2data[n];d.origin=z.origin;c===r.STENCIL_MATERIAL&&(this._stencilRenderingHelper.setEnableState(!0),
this._stencilRenderingHelper.prepareStencilWritePass());var q=!1;if(b.instanced)for(var w in z.perGeometryDataInfo){var v=z.perGeometryDataInfo[w];e||(b.bind(l,d),e=!0);l.bindVAO(v.vao);var m=b.getProgram();D.assertCompatibleVertexAttributeLocations(v.vao,m);q||(b.bindView(l,d),q=!0);var m=v.to-v.from,t=v.refCount;x===g.TRIANGLES&&(this._stats.trianglesRendered+=t*m/3);s.drawArraysInstancedANGLE(x,v.from,m,t);this._stats.drawCallsAngleInstanced++;this._stats.instancesDrawnAngle+=t}else{var v=z.instances,
y;for(y in v){var m=v[y],t=m.idx,u=m.displayedIndexRange;h&&(u=h);if(!(u&&0===u.length)&&!(f&&!f.get(t)||k&&!k.get(t)))e||(b.bind(l,d),e=!0),q||(l.bindVAO(z.vao),b.bindView(l,d),q=!0),p||b.bindInstance(l,m),this._stats.drawCallsInstanced++,x===g.TRIANGLES&&(this._stats.trianglesRendered+=(m.to-m.from)/3),u?this._drawArraysFaceRange(u,m.from,x):l.drawArrays(x,m.from,m.to-m.from)}}}l.bindVAO(null);e&&b.release(l,d)};e.prototype._drawArraysFaceRange=function(a,b,d){for(var c=this._rctx,f=0;f<a.length;f++){var k=
a[f];c.drawArrays(d,k[0]+b,k[1]-k[0]+1)}this._stats.drawCallsFragmented+=a.length-1};e.prototype._renderInternalMerged=function(a,b,d,c){var f=this._rctx,k=f.gl,h=!1,p;for(p in a.origin2data){var l=a.origin2data[p];d.origin=l.origin;c===r.STENCIL_MATERIAL&&(this._stencilRenderingHelper.setEnableState(!0),this._stencilRenderingHelper.prepareStencilWritePass());if(!(l.displayedIndexRange&&0===l.displayedIndexRange.length)){h||(b.bind(f,d),h=!0);var g=b.getProgram();f.bindVAO(l.vao);D.assertCompatibleVertexAttributeLocations(l.vao,
g);b.bindView(f,d);this._stats.drawCallsMerged++;g=b.getDrawMode(f);g===k.TRIANGLES&&(this._stats.trianglesRendered+=l.vao.vertexBuffers.geometry.size/3);l.displayedIndexRange?this._drawArraysFaceRange(l.displayedIndexRange,0,g):f.drawArrays(g,0,D.vertexCount(l.vao,"geometry"))}}h&&b.release(f,d)};e.prototype._updateGlobalUniforms=function(a){for(var b=this._programRep.getProgramsUsingUniform("proj"),d=0;d<b.length;d++)b[d].setUniformMatrix4fv("proj",a);if(this._lighting){b=this._programRep.getProgramsUsingUniform("lightDirection");
for(d=0;d<b.length;d++)this._lighting.setUniforms(b[d])}};e.prototype.print=function(){var a=Object.keys(this._mat2dataMerged).length,b=Object.keys(this._mat2dataInstanced).length;console.log("number of materials (merged/instanced): "+a+"/"+b);var a=0,d;for(d in this._mat2dataMerged){var b=this._mat2dataMerged[d],c;for(c in b.origin2data)a+=Object.keys(b.origin2data[c].instances).length}var f=0;for(d in this._mat2dataInstanced)for(c in b=this._mat2dataInstanced[d],b.origin2data)f+=Object.keys(b.origin2data[c].instances).length;
console.log("number of instances (merged/instanced): "+a+"/"+f)};e.prototype.isEmpty=function(){for(var a in this._mat2dataInstanced){var b=this._mat2dataInstanced[a],d;for(d in b.origin2data)if(!Y(b.origin2data[d].instances))return!1}for(a in this._mat2dataMerged)for(d in b=this._mat2dataMerged[a],b.origin2data)if(!Y(b.origin2data[d].instances))return!1;return!0};e.prototype.modify=function(a,b,d,c){this._isRendering&&console.warn("Renderer.modify called while rendering");var f=[],k=[];this._mergedOrInstanced(a,
f,k);a=[];var h=[];this._mergedOrInstanced(b,a,h);b={};d&&this._performUpdates(d,b);d=[];this._modifyMerged(f,a,d,b);this._modifyInstanced(k,h,d);this._updateMergedFaceranges(b);this._releaseMaterials(d);this._modifyMaterials(c);this._needsRender=!0};e.prototype._isInstanced=function(a){var b=!1,d=G(a.data.faces.indices).length,b=(b=(b=b||!1===a.material.canBeMerged)||a.material.instanced)||a.material.isBackdrop;return a.singleUse?b:b=b||d>this._threshold};e.prototype._mergedOrInstanced=function(a,
b,d){for(var c=0;c<a.length;++c)1>G(a[c].data.faces.indices).length||(this._isInstanced(a[c])?d.push(a[c]):b.push(a[c]))};e.prototype._performUpdates=function(a,b){for(var d=0;d<a.length;d++){var c=a[d],f=c.renderGeometry,k=this._isInstanced(f),c=c.updateType;c&2&&this._updateFaceranges(f,k,b);c&4||!k&&c&16?this._updateVertexAttributes(f,k):k&&c&16?this._updateInstanceTransformation(f,k):c&8&&this._updateColorAttributes(f)}};e.prototype._updateFaceranges=function(a,b,d){var c=a.material.getId(),f=
a.origin.id,k=(b?this._mat2dataInstanced:this._mat2dataMerged)[c].origin2data[f],h=k.instances[a.uniqueName];h&&(h.displayedIndexRange=a.displayedIndexRange,b||(d[this._modifiedMergedFacerangesKey(c,f)]=k))};e.prototype._updateMergedFaceranges=function(a){for(var b in a){var d=a[b];d.displayedIndexRange=[];var c=d.instances,f=!0,k;for(k in c){var h=c[k];h.displayedIndexRange?(d.displayedIndexRange.push.apply(d.displayedIndexRange,T.offsetIntervals(h.displayedIndexRange,h.from)),f=!1):d.displayedIndexRange.push([h.from,
h.to-1])}d.displayedIndexRange=f?null:T.mergeIntervals(d.displayedIndexRange)}};e.prototype._updateVertexAttributes=function(a,b){var d=a.material,c=d.getId(),c=(b?this._mat2dataInstanced:this._mat2dataMerged)[c].origin2data[a.origin.id],f=c.instances[a.uniqueName],k,h;b||(k=a.origin.vec3,P(F,-k[0],-k[1],-k[2]),A.multiply(F,a.transformation,J),A.inverse(J,K),A.transpose(K),k=J,h=K);var p=D.getStride(d.getVertexBufferLayout()),l=p/4;B(f.from+d.getOutputAmount(G(a.data.faces.indices).length)/l===f.to,
"material VBO layout has changed");d.fillInterleaved(a.data,k,h,a.instanceParameters,c.buffer.getArray(),f.from*l);c.vao.vertexBuffers.geometry.setSubData(c.buffer.getArray(),f.from*p,f.from*p,f.to*p)};e.prototype._updateInstanceTransformation=function(a,b){var d=a.origin.vec3,c=(b?this._mat2dataInstanced:this._mat2dataMerged)[a.material.getId()].origin2data[a.origin.id],f=c.instances[a.uniqueName];P(F,-d[0],-d[1],-d[2]);A.multiply(F,a.transformation,f.transformation);A.inverse(f.transformation,f.transformationNormal);
A.transpose(f.transformationNormal,f.transformationNormal);d=c.perGeometryDataInfo[a.data.id];if(c=d.instanceBufferData){var k=c.getSlot(a.idx);c.fill(k,0,f.transformation);c.fill(k,16,f.transformationNormal);f=4*c.getOffset(k);k=D.getStride(d.vao.layout.instance);d.vao.vertexBuffers.instance.setSubData(c.getArray(),f,f,f+k)}};e.prototype._updateColorAttributes=function(a){var b=a.material,d=b.getId(),c=a.origin.id,d=(this._isInstanced(a)?this._mat2dataInstanced:this._mat2dataMerged)[d].origin2data[c],
c=d.instances[a.uniqueName],f={};f[na.COLOR]=!0;var k=D.getStride(b.getVertexBufferLayout())/4;B(c.from+b.getOutputAmount(G(a.data.faces.indices).length)/k===c.to,"material VBO layout has changed");b.fillInterleaved(a.data,void 0,void 0,a.instanceParameters,d.buffer.getArray(),c.from*k,f);d.vao.vertexBuffers.geometry.setSubData(d.buffer.getArray(),4*c.from*k,4*c.from*k,4*c.to*k)};e.prototype._modifyMerged=function(a,b,d,c){var f=this._rctx;a=this._compMat2delta(a,b,!1);for(var k in a){b=a[k];for(var h in b){var p=
b[h],l=p.optimalCount,g=p.material,e=g.getVertexBufferLayout(),x=D.getStride(e)/4,s=this._mat2dataMerged[k];if(null==s){B(0<l);var n=g.getRenderPriority(),s={origin2data:{}};s[y.MATERIAL]=this._materialRep.aquire(g);s[y.MATERIAL_DEPTH_SHADOWMAP]=this._materialRep.aquireDepthShadowMap(g);s[y.MATERIAL_NORMAL]=this._materialRep.aquireNormal(g);s[y.MATERIAL_DEPTH]=this._materialRep.aquireDepth(g);s[y.MATERIAL_HIGHLIGHT]=this._materialRep.aquireHighlight(g);this._mat2dataMerged[k]=s;this._orderedRendering&&
this._insertIntoRenderOrder(s,n,"merged")}n=s.origin2data[h];null==n&&(B(0<l),n={instances:{},vao:new M(f,O.Default3D,{geometry:e},{geometry:N.createVertex(f,35044)}),buffer:new U(l),optimalCount:0,origin:p.origin},s.origin2data[h]=n);if(0<l){var e=n.buffer.getSize(),z=n.buffer.getArray(),s=l<p.sparseCount/2,q=n.buffer.resize(s?l:p.sparseCount),w=p.toRemove;if(s||q){for(var e=0,v=n.buffer.getArray(),s=0,m=w.length;s<m;++s)q=n.instances[w[s].uniqueName],n.optimalCount-=(q.to-q.from)*x,delete n.instances[w[s].uniqueName];
var s={},t;for(t in n.instances)q=n.instances[t],B(null==s[q.from]),s[q.from]=q;for(var r in s){var q=s[r],m=q.from*x,u=q.to*x;v.set(z.subarray(m,u),e);q.from=e/x;e+=u-m;q.to=e/x}B(e===n.optimalCount)}else{s=0;for(q=w.length;s<q;++s)z=w[s].uniqueName,B(void 0!==n.instances[z]),m=n.instances[z].from*x,u=n.instances[z].to*x,n.buffer.erase(m,u),delete n.instances[z],n.optimalCount-=u-m}P(F,-p.origin[0],-p.origin[1],-p.origin[2]);w=p.toAdd;p=!1;s=0;for(z=w.length;s<z;++s)m=w[s],u=m.data,A.multiply(F,
m.transformation,J),A.inverse(J,K),A.transpose(K),q=e,g.fillInterleaved(u,J,K,m.instanceParameters,n.buffer.getArray(),e),u=g.getOutputAmount(G(u.faces.indices).length),v=q+u,B(null==n.instances[m.uniqueName]),q=new $(m.name,q/x,v/x,m.displayedIndexRange,void 0,void 0,m.idx),m.displayedIndexRange&&(p=!0),n.instances[m.uniqueName]=q,n.optimalCount+=u,e+=u;B(n.optimalCount===l);l=new Float32Array(n.buffer.getArray().buffer,0,n.buffer.getSize());n.vao.vertexBuffers.geometry.setData(l);if(p||n.displayedIndexRange)c[this._modifiedMergedFacerangesKey(k,
h)]=n}else B(0===l),n.vao.dispose(!0),n.vao=null,delete s.origin2data[h],0===Object.keys(s.origin2data).length&&(d.push(k),delete this._mat2dataMerged[k],this._orderedRendering&&this._removeFromRenderOrder(s,"merged"))}}};e.prototype._modifyInstanced=function(a,b,d){a=this._compMat2delta(a,b,!0);b=this._rctx;for(var c in a){var f=a[c],k;for(k in f){var h=f[k];if(0===h.optimalCount)h=this._mat2dataInstanced[c],h.origin2data[k].vao.dispose(!0),delete h.origin2data[k],0===Object.keys(h.origin2data).length&&
(d.push(c),delete this._mat2dataInstanced[c],this._orderedRendering&&this._removeFromRenderOrder(h,"instanced"));else{var e=h.material,l=this._mat2dataInstanced[c];if(null==l){var g=e.getRenderPriority(),l={origin2data:{}};l[y.MATERIAL]=this._materialRep.aquire(e);l[y.MATERIAL_DEPTH_SHADOWMAP]=this._materialRep.aquireDepthShadowMap(e);l[y.MATERIAL_NORMAL]=this._materialRep.aquireNormal(e);l[y.MATERIAL_DEPTH]=this._materialRep.aquireDepth(e);l[y.MATERIAL_HIGHLIGHT]=this._materialRep.aquireHighlight(e);
this._mat2dataInstanced[c]=l;this._orderedRendering&&this._insertIntoRenderOrder(l,g,"instanced")}var E=e.getVertexBufferLayout(),x=l[y.MATERIAL].instanced?e.getInstanceBufferLayout():void 0,s=x&&D.hasAttribute(x,"instanceColor"),n=D.getStride(E)/4,g=l.origin2data[k];null==g&&(g={instances:{},vao:new M(b,O.Default3D,{geometry:E},{geometry:N.createVertex(b,35044)}),buffer:new U(h.optimalCount),optimalCount:0,perGeometryDataInfo:{},origin:h.origin},l.origin2data[k]=g);var l=g.buffer.getSize(),z=g.buffer.getArray(),
q=h.optimalCount<h.sparseCount/2,w=g.buffer.resize(q?h.optimalCount:h.sparseCount),v;for(v in h.perGeometryDelta){var m=g.perGeometryDataInfo[v];if(m&&m.instanceBufferData){var t=h.perGeometryDelta[v].removeCount;0<t&&m.instanceBufferData.prepareFree(t)}}var r=h.toRemove;if(q||w){q=0;for(l=r.length;q<l;++q){w=r[q];delete g.instances[w.uniqueName];v=w.data.id;var u=m=g.perGeometryDataInfo[v];0===--u.refCount&&null==h.dataId2refCount[v]?(g.optimalCount-=(u.to-u.from)*n,delete g.perGeometryDataInfo[v]):
m.instanceBufferData&&m.instanceBufferData.free(w.idx)}var l=0,q=g.buffer.getArray(),w={},C;for(C in g.perGeometryDataInfo)u=g.perGeometryDataInfo[C],B(null==w[u.from]),w[u.from]=u;for(name in w)u=w[name],t=u.from*n,m=u.to*n,q.set(z.subarray(t,m),l),u.from=l/n,l+=m-t,u.to=l/n;for(name in g.instances)t=g.instances[name],t.from=g.perGeometryDataInfo[t.dataId].from,t.to=g.perGeometryDataInfo[t.dataId].to}else{q=0;for(z=r.length;q<z;++q)w=r[q],delete g.instances[w.uniqueName],v=w.data.id,m=g.perGeometryDataInfo[v],
0===--m.refCount&&null==h.dataId2refCount[v]?(t=m.from*n,m=m.to*n,g.buffer.erase(t,m),g.optimalCount-=m-t,delete g.perGeometryDataInfo[v]):m.instanceBufferData&&m.instanceBufferData.free(w.idx)}P(F,-h.origin[0],-h.origin[1],-h.origin[2]);for(v in h.perGeometryDelta)if((m=g.perGeometryDataInfo[v])&&m.instanceBufferData)q=h.perGeometryDelta[v].addCount,0<q&&m.instanceBufferData.prepareAllocate(q);z=h.toAdd;q=0;for(r=z.length;q<r;++q){w=z[q];t=w.data;v=t.id;m=g.perGeometryDataInfo[v];null==m?(e.fillInterleaved(t,
void 0,void 0,void 0,g.buffer.getArray(),l),u=e.getOutputAmount(G(t.faces.indices).length),t=l/n,l+=u,m=l/n,g.optimalCount+=u,m={refCount:1,from:t,to:m,vao:null,instanceBufferData:null},x&&(t=D.getStride(x)/4,m.vao=new M(b,O.Default3D,{geometry:E,instance:x},{geometry:g.vao.vertexBuffers.geometry,instance:N.createVertex(b,35044)}),m.instanceBufferData=new aa(t,h.perGeometryDelta[v].addCount)),g.perGeometryDataInfo[v]=m):++m.refCount;B(m.from*n<=g.buffer.getSize()&&m.to*n<=g.buffer.getSize());t=A.create();
A.multiply(F,w.transformation,t);t=new $(w.name,m.from,m.to,w.displayedIndexRange,t,w.instanceParameters,w.idx,v);if(m=m.instanceBufferData)u=m.allocate(w.idx),m.fill(u,0,t.transformation),m.fill(u,16,t.transformationNormal),s&&m.fill(u,32,w.instanceParameters.color);g.instances[w.uniqueName]=t}B(g.optimalCount===h.optimalCount);e=new Float32Array(g.buffer.getArray().buffer,0,g.buffer.getSize());g.vao.vertexBuffers.geometry.setData(e);for(v in g.perGeometryDataInfo)if(E=g.perGeometryDataInfo[v],E.vao&&
(e=E.vao.vertexBuffers.instance))x=h.perGeometryDelta[v],0<x.addCount+x.removeCount&&(E=E.instanceBufferData.compact(),e.setData(E))}}}};e.prototype._compMat2delta=function(a,b,d){var c={};this._updateMat2delta(a,!0,d,c);this._updateMat2delta(b,!1,d,c);return c};e.prototype._updateMat2delta=function(a,b,d,c){for(var f=0,k=a.length;f<k;++f){var h=a[f],e=h.origin,l=h.material,g=l.getId(),r=d?this._mat2dataInstanced[g]:this._mat2dataMerged[g],r=r&&r.origin2data[e.id],x=c[g];null==x&&(x={},c[g]=x);g=
x[e.id];if(null==g){g={optimalCount:null==r?0:r.optimalCount,sparseCount:null==r?0:r.buffer.getSize(),material:l,toAdd:[],toRemove:[],perGeometryDelta:null,origin:e.vec3};if(d){var s={};if(void 0!==r)for(var n in r.perGeometryDataInfo)s[n]=r.perGeometryDataInfo[n].refCount;g.dataId2refCount=s;g.perGeometryDelta={}}x[e.id]=g}e=l.getOutputAmount(G(h.data.faces.indices).length);d?(l=h.data.id,r=g.perGeometryDelta[l],r||(r={addCount:0,removeCount:0},g.perGeometryDelta[l]=r),b?(r.addCount++,null==g.dataId2refCount[l]&&
(g.dataId2refCount[l]=0),1===++g.dataId2refCount[l]&&(g.optimalCount+=e,g.sparseCount+=e),g.toAdd.push(h)):(r.removeCount++,0===--g.dataId2refCount[l]&&(delete g.dataId2refCount[l],g.optimalCount-=e),g.toRemove.push(h))):b?(g.optimalCount+=e,g.sparseCount+=e,g.toAdd.push(h)):(g.optimalCount-=e,g.toRemove.push(h))}};e.prototype._modifiedMergedFacerangesKey=function(a,b){return a+"_"+b};e.prototype._insertIntoRenderOrder=function(a,b,d){for(var c=a[y.MATERIAL].getMaterialId(),f=this._renderOrder.length,
e=0;e<f&&this._renderOrder[e][0]>=b;){var h=this._renderOrder[e][1];if(h.id===c){B(!h[d],"matData for type already exists");h[d]=a;return}e++}c={id:c,instanced:null,merged:null};c[d]=a;this._renderOrder.splice(e,0,[b,c])};e.prototype._removeFromRenderOrder=function(a,b){for(var d=a[y.MATERIAL].getMaterialId(),c=0;this._renderOrder[c][1].id!==d;)c++;d=this._renderOrder[c][1];d[b]=null;!d.instanced&&!d.merged&&this._renderOrder.splice(c,1)};e.prototype._updateRenderOrder=function(a,b){for(var d=b.length,
c=0;c<d&&b[c][1].id!==a;)c++;if(c<d){var f=b[c][1],f=(f.merged||f.instanced)[y.MATERIAL].getRenderPriority(),e=b[c][0];if(f!==b[c][0]){b[c][0]=f;e=f>e?-1:1;for(c+=e;-1<c&&c<d&&e*b[c][0]>e*f;){var h=b[c];b[c]=b[c-e];b[c-e]=h;c+=e}}}};e.prototype._modifyMaterials=function(a){for(var b in a)this._materialRep.updateMaterialParameters(b)};e.prototype.modifyRenderOrder=function(a){if(this._orderedRendering){for(var b in a)this._updateRenderOrder(b,this._renderOrder);this._needsRender=!0}};e.prototype._releaseMaterials=
function(a){if(Array.isArray(a))for(var b=0;b<a.length;b++)this._materialRep.release(a[b]),this._materialRep.releaseDepthShadowMap(a[b]),this._materialRep.releaseNormal(a[b]),this._materialRep.releaseDepth(a[b]),this._materialRep.releaseHighlight(a[b]);else this._materialRep.release(a),this._materialRep.releaseDepthShadowMap(a),this._materialRep.releaseNormal(a),this._materialRep.releaseDepth(a),this._materialRep.releaseHighlight(a)};e.prototype._name2indices=function(a){for(var b=new ja,d=0;2>d;++d){var c=
0===d?this._mat2dataMerged:this._mat2dataInstanced,e;for(e in c){var k=c[e].origin2data,h;for(h in k){var p=k[h].instances,l;for(l in p){var g=p[l];void 0!==a[g.name]&&b.set(g.idx)}}}}return b};return e}();var pa=function(){function e(){this.reset()}e.prototype.reset=function(){this.VBOusedSize=this.VBOoptimalSize=this.VBOallocatedSize=this.instancesDrawnAngle=this.drawCallsFragmented=this.drawCallsMerged=this.drawCallsAngleInstanced=this.drawCallsInstanced=this.trianglesRendered=0};return e}(),$=
function(){return function(e,a,b,d,c,f,k,h){this.name=e;this.from=a;this.to=b;this.displayedIndexRange=d;this.transformation=c;this.instanceParameters=f;this.idx=k;this.dataId=h;null!=c&&(this.transformationNormal=A.create(),A.set(c,this.transformationNormal),A.inverse(this.transformationNormal,this.transformationNormal),A.transpose(this.transformationNormal,this.transformationNormal))}}(),I=R.create(),F=A.identity(),J=A.create(),K=A.create();return C});