// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("require exports ./core/tsSupport/declareExtendsHelper ./core/tsSupport/decorateHelper ./core/accessorSupport/decorators dojo/_base/lang ./support/basemapDefinitions ./core/Collection ./core/collectionUtils ./core/Evented ./core/JSONSupport ./core/Loadable ./core/promiseUtils ./core/requireUtils ./core/urlUtils ./core/Logger ./portal/Portal ./portal/PortalItem ./layers/Layer".split(" "),function(q,D,r,d,c,l,s,k,f,t,u,v,m,w,x,y,n,z,A){var B=0,g=k.ofType(A),C=y.getLogger("esri.Basemap");return function(p){function b(a){p.call(this);
this.thumbnailUrl=this.resourceInfo=this.portalItem=this.id=null;this.title="";this.id=Date.now().toString(16)+"-basemap-"+B++;this.baseLayers=new k;this.referenceLayers=new k;var b=function(a){"esri.layers.ElevationLayer"===a.declaredClass&&C.error("Layer '"+a.title+", id:"+a.id+"' of type '"+a.declaredClass+"' cannot be added as a basemap layer.")};this.baseLayers.on("after-add",function(a){return b(a.item)});this.referenceLayers.on("after-add",function(a){return b(a.item)})}r(b,p);b.prototype.initialize=
function(){this.resourceInfo&&this.read(this.resourceInfo)};Object.defineProperty(b.prototype,"baseLayers",{set:function(a){this._set("baseLayers",f.referenceSetter(a,this._get("baseLayers"),g))},enumerable:!0,configurable:!0});b.prototype.writeBaseLayers=function(a,b,e){var c=[];if(!a)return c;e=l.mixin({},e,{layerContainerType:"basemap"});this.baseLayers.forEach(function(a){if(a.write){var b={};a.write(b,e)&&c.push(b)}});this.referenceLayers.forEach(function(a){if(a.write){var b={isReference:!0};
a.write(b,e)&&c.push(b)}});b.baseMapLayers=c};Object.defineProperty(b.prototype,"referenceLayers",{set:function(a){this._set("referenceLayers",f.referenceSetter(a,this._get("referenceLayers"),g))},enumerable:!0,configurable:!0});b.prototype.writeTitle=function(a,b){a&&(b.title=a)};b.prototype.load=function(){this.addResolvingPromise(this._loadFromSource());return this};b.prototype.clone=function(){var a={id:this.id,title:this.title};this.resourceInfo||this.portalItem?(a.portalItem=this.portalItem,
a.resourceInfo=this.resourceInfo):(a.baseLayers=this.baseLayers.slice(),a.referenceLayers=this.referenceLayers.slice());return new b(a)};b.prototype.read=function(a,b){b&&b.origin&&(this._layerOrigin=b.origin);return this.inherited(arguments)};b.prototype.write=function(a,b){a=a||{};!this.loaded&&this.resourceInfo?l.mixin(a,this.resourceInfo):this.inherited(arguments,[a,b]);return a};b.prototype.toJSON=function(){return this.write(null,{origin:"web-map"})};b.prototype._loadFromSource=function(){var a=
this.resourceInfo,b=this.portalItem;return a?this._loadFromJSON(a):b?this._loadFromItem(b):m.resolve(null)};b.prototype._loadFromJSON=function(a,b){var e=this,c=this.portalItem&&this.portalItem.portal;return w.when(q,"./portal/support/layersCreator").then(function(d){var h=[];if(a.baseMapLayers&&Array.isArray(a.baseMapLayers)){var f={context:{origin:e._layerOrigin||"web-map",layerContainerType:"basemap",url:b,portal:c},defaultLayerType:"DefaultTileLayer"},g=d.populateOperationalLayers(e.baseLayers,
a.baseMapLayers.filter(function(a){return!a.isReference}),f);h.push.apply(h,g);d=d.populateOperationalLayers(e.referenceLayers,a.baseMapLayers.filter(function(a){return a.isReference}),f);h.push.apply(h,d)}return m.eachAlways(h)}).then(function(){})};b.prototype._loadFromItem=function(a){var b=this;return a.load().then(function(a){b.read({title:a.title,thumbnailUrl:a.thumbnailUrl},{origin:"portal-item",portal:a.portal||n.getDefault()});return a}).then(function(a){return a.fetchData()}).then(function(c){b.resourceInfo=
c.baseMap;c=x.urlToObject(a.itemUrl);b.read(b.resourceInfo,{origin:"portal-item",portal:a.portal||n.getDefault(),url:c});return b._loadFromJSON(b.resourceInfo,c)})};b.fromJSON=function(a){return!a?null:new b({resourceInfo:a})};b.fromId=function(a){return(a=s[a])?b.fromJSON(a):null};d([c.property({type:g,json:{writeAlways:!0}}),c.cast(f.castForReferenceSetter)],b.prototype,"baseLayers",null);d([c.write("baseLayers")],b.prototype,"writeBaseLayers",null);d([c.property({json:{origins:{webScene:{writable:!0}}}})],
b.prototype,"id",void 0);d([c.property({type:z})],b.prototype,"portalItem",void 0);d([c.property({type:g}),c.cast(f.castForReferenceSetter)],b.prototype,"referenceLayers",null);d([c.property()],b.prototype,"resourceInfo",void 0);d([c.property()],b.prototype,"thumbnailUrl",void 0);d([c.property()],b.prototype,"title",void 0);d([c.write("title")],b.prototype,"writeTitle",null);return b=d([c.subclass("esri.Basemap")],b)}(c.declared(u,t,v))});