// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
require({cache:{"esri/portal/support/geometryServiceUtils":function(){define("require exports ../Portal ../PortalItem ../../config ../../tasks/GeometryService ../../core/promiseUtils ../../core/Error".split(" "),function(p,q,n,d,k,b,f,g){q.create=function(e){void 0===e&&(e=null);if(k.geometryServiceUrl)return f.resolve(new b({url:k.geometryServiceUrl}));if(!e)return f.reject(new g("internal:geometry-service-url-not-configured"));var l;e.isInstanceOf(d)?l=e.portal||n.getDefault():e.isInstanceOf(n)&&
(l=e);return l.load().then(function(a){if(a.helperServices&&a.helperServices.geometry&&a.helperServices.geometry.url)return f.resolve(new b({url:a.helperServices.geometry.url}));throw new g("internal:geometry-service-url-not-configured");})}})},"esri/tasks/GeometryService":function(){define("../core/kebabDictionary ../geometry/Extent ../geometry/Multipoint ../geometry/Polyline ../geometry/Polygon ../geometry/support/jsonUtils ../request ./Task dojo/_base/lang".split(" "),function(p,q,n,d,k,b,f,g,
e){var l=p({MGRS:"mgrs",USNG:"usng",UTM:"utm",GeoRef:"geo-ref",GARS:"gars",DMS:"dms",DDM:"ddm",DD:"dd"});p=g.createSubclass({declaredClass:"esri.tasks.GeometryService",areasAndLengths:function(a){a=e.mixin({},this.parsedUrl.query,{f:"json"},a.toJSON());return f(this.parsedUrl.path+"/areasAndLengths",{query:a,callbackParamName:"callback"}).then(function(a){return a.data})},autoComplete:function(a,c){var h=a[0].spatialReference,b=e.mixin({},this.parsedUrl.query,{f:"json",sr:JSON.stringify(h.toJSON()),
polygons:JSON.stringify(this._encodeGeometries(a).geometries),polylines:JSON.stringify(this._encodeGeometries(c).geometries)});return f(this.parsedUrl.path+"/autoComplete",{query:b,callbackParamName:"callback"}).then(function(a){return(a.data.geometries||[]).map(function(a){return new k({spatialReference:h,rings:a.rings})})})},buffer:function(a){var c=e.mixin({},this.parsedUrl.query,{f:"json"},a.toJSON()),h=a.outSpatialReference||a.geometries[0].spatialReference;return f(this.parsedUrl.path+"/buffer",
{query:c,callbackParamName:"callback"}).then(function(a){return(a.data.geometries||[]).map(function(a){return new k({spatialReference:h,rings:a.rings})})})},cut:function(a,c){var h=a[0].spatialReference,d=a.map(function(a){return a.toJSON()}),d=e.mixin({},this.parsedUrl.query,{f:"json",sr:JSON.stringify(h.toJSON()),target:JSON.stringify({geometryType:b.getJsonType(a[0]),geometries:d}),cutter:JSON.stringify(c.toJSON())});return f(this.parsedUrl.path+"/cut",{query:d,callbackParamName:"callback"}).then(function(a){a=
a.data;return{cutIndexes:a.cutIndexes,geometries:(a.geometries||[]).map(function(a){return b.fromJSON(a).set("spatialReference",h)})}})},convexHull:function(a){var c=a[0].spatialReference;a=e.mixin({},this.parsedUrl.query,{f:"json",sr:JSON.stringify(c.toJSON()),geometries:JSON.stringify(this._encodeGeometries(a))});return f(this.parsedUrl.path+"/convexHull",{query:a,callbackParamName:"callback"}).then(function(a){return b.fromJSON(a.data.geometry).set("spatialReference",c)})},densify:function(a){var c=
e.mixin({},this.parsedUrl.query,{f:"json"},a.toJSON()),h=a.geometries[0].spatialReference;return f(this.parsedUrl.path+"/densify",{query:c,callbackParamName:"callback"}).then(function(a){return(a.data.geometries||[]).map(function(a){return b.fromJSON(a).set("spatialReference",h)})})},difference:function(a,c){var h=a[0].spatialReference,d=e.mixin({},this.parsedUrl.query,{f:"json",sr:JSON.stringify(h.toJSON()),geometries:JSON.stringify(this._encodeGeometries(a)),geometry:JSON.stringify({geometryType:b.getJsonType(c),
geometry:c.toJSON()})});return f(this.parsedUrl.path+"/difference",{query:d,callbackParamName:"callback"}).then(function(a){return(a.data.geometries||[]).map(function(a){return b.fromJSON(a).set("spatialReference",h)})})},distance:function(a){a=e.mixin({},this.parsedUrl.query,{f:"json"},a.toJSON());return f(this.parsedUrl.path+"/distance",{query:a,callbackParamName:"callback"}).then(this._handleDistanceResponse)},fromGeoCoordinateString:function(a){var c={};e.isObject(a.sr)?c.sr=a.sr.wkid||JSON.stringify(a.sr.toJSON()):
c.sr=a.sr;c.strings=JSON.stringify(a.strings);c.conversionType=l.toJSON(a.conversionType||"mgrs");c.conversionMode=a.conversionMode;a=e.mixin({},this.parsedUrl.query,{f:"json"},c);return f(this.parsedUrl.path+"/fromGeoCoordinateString",{query:a,callbackParamName:"callback"}).then(this._handleFromGeoCoordinateResponse)},generalize:function(a){var c=e.mixin({},this.parsedUrl.query,{f:"json"},a.toJSON()),h=a.geometries[0].spatialReference;return f(this.parsedUrl.path+"/generalize",{query:c,callbackParamName:"callback"}).then(function(a){return(a.data.geometries||
[]).map(function(a){return b.fromJSON(a).set("spatialReference",h)})})},intersect:function(a,c){var h=a[0].spatialReference,d=e.mixin({},this.parsedUrl.query,{f:"json",sr:JSON.stringify(h.toJSON()),geometries:JSON.stringify(this._encodeGeometries(a)),geometry:JSON.stringify({geometryType:b.getJsonType(c),geometry:c.toJSON()})});return f(this.parsedUrl.path+"/intersect",{query:d,callbackParamName:"callback"}).then(function(a){return(a.data.geometries||[]).map(function(a){return b.fromJSON(a).set("spatialReference",
h)})})},lengths:function(a){a=e.mixin({},this.parsedUrl.query,{f:"json"},a.toJSON());return f(this.parsedUrl.path+"/lengths",{query:a,callbackParamName:"callback"}).then(function(a){return a.data})},labelPoints:function(a){var c=a.map(function(a){return a.toJSON()}),h=a[0].spatialReference;a=e.mixin({},this.parsedUrl.query,{f:"json",sr:h.wkid?h.wkid:JSON.stringify(h.toJSON()),polygons:JSON.stringify(c)});return f(this.parsedUrl.path+"/labelPoints",{query:a,callbackParamName:"callback"}).then(function(a){return(a.data.labelPoints||
[]).map(function(a){return b.fromJSON(a).set("spatialReference",h)})})},offset:function(a){var c=e.mixin({},this.parsedUrl.query,{f:"json"},a.toJSON()),h=a.geometries[0].spatialReference;return f(this.parsedUrl.path+"/offset",{query:c,callbackParamName:"callback"}).then(function(a){return(a.data.geometries||[]).map(function(a){return b.fromJSON(a).set("spatialReference",h)})})},project:function(a,c){var h=e.mixin({},this.parsedUrl.query,{f:"json"}),d;a.geometries?(c=a.outSR,d=a.geometries[0],h=e.mixin(h,
a.toJSON())):(d=a[0],h=e.mixin(h,{outSR:c.wkid||JSON.stringify(c.toJSON()),inSR:d.spatialReference.wkid||JSON.stringify(d.spatialReference.toJSON()),geometries:JSON.stringify(this._encodeGeometries(a))}));var g=b.getJsonType(d),l=this._decodeGeometries;return f(this.parsedUrl.path+"/project",{query:h,callbackParamName:"callback"}).then(function(a){return l(a.data,g,c)})},relation:function(a){a=e.mixin({},this.parsedUrl.query,{f:"json"},a.toJSON());return f(this.parsedUrl.path+"/relation",{query:a,
callbackParamName:"callback"}).then(this._handleRelationResponse)},reshape:function(a,c){var h=a.spatialReference,d=e.mixin({},this.parsedUrl.query,{f:"json",sr:JSON.stringify(h.toJSON()),target:JSON.stringify({geometryType:b.getJsonType(a),geometry:a.toJSON()}),reshaper:JSON.stringify(c.toJSON())});return f(this.parsedUrl.path+"/reshape",{query:d,callbackParamName:"callback"}).then(function(a){return b.fromJSON(a.data.geometry).set("spatialReference",h)})},simplify:function(a){var c=a[0].spatialReference,
d=e.mixin({},this.parsedUrl.query,{f:"json",sr:c.wkid?c.wkid:JSON.stringify(c.toJSON()),geometries:JSON.stringify(this._encodeGeometries(a))}),g=b.getJsonType(a[0]),l=this._decodeGeometries;return f(this.parsedUrl.path+"/simplify",{query:d,callbackParamName:"callback"}).then(function(a){return l(a.data,g,c)})},toGeoCoordinateString:function(a){var c={};e.isObject(a.sr)?c.sr=a.sr.wkid||JSON.stringify(a.sr.toJSON()):c.sr=a.sr;c.coordinates=JSON.stringify(a.coordinates);c.conversionType=l.toJSON(a.conversionType||
"mgrs");c.conversionMode=a.conversionMode;c.numOfDigits=a.numOfDigits;c.rounding=a.rounding;c.addSpaces=a.addSpaces;a=e.mixin({},this.parsedUrl.query,{f:"json"},c);return f(this.parsedUrl.path+"/toGeoCoordinateString",{query:a,callbackParamName:"callback"}).then(this._handleToGeoCoordinateResponse)},trimExtend:function(a){var c=e.mixin({},this.parsedUrl.query,{f:"json"},a.toJSON()),h=a.sr;return f(this.parsedUrl.path+"/trimExtend",{query:c,callbackParamName:"callback"}).then(function(a){return(a.data.geometries||
[]).map(function(a){return new d({spatialReference:h,paths:a.paths})})})},union:function(a){var c=a[0].spatialReference;a=e.mixin({},this.parsedUrl.query,{f:"json",sr:JSON.stringify(c.toJSON()),geometries:JSON.stringify(this._encodeGeometries(a))});return f(this.parsedUrl.path+"/union",{query:a,callbackParamName:"callback"}).then(function(a){return b.fromJSON(a.data.geometry).set("spatialReference",c)})},_handleRelationResponse:function(a){return a.data.relations},_handleDistanceResponse:function(a){return(a=
a.data)&&a.distance},_handleToGeoCoordinateResponse:function(a){return a.data.strings},_handleFromGeoCoordinateResponse:function(a){return a.data.coordinates},_encodeGeometries:function(a){var c=[],e,d=a.length;for(e=0;e<d;e++)c.push(a[e].toJSON());return{geometryType:b.getJsonType(a[0]),geometries:c}},_decodeGeometries:function(a,c,d){var f=b.getGeometryType(c);a=a.geometries;var g=[],l={spatialReference:d.toJSON()},k=e.mixin;a.forEach(function(a,c){g[c]=new f(k(a,l))});return g},_toProjectGeometry:function(a){var c=
a.spatialReference.toJSON();return a instanceof q?new k({rings:[[[a.xmin,a.ymin],[a.xmin,a.ymax],[a.xmax,a.ymax],[a.xmax,a.ymin],[a.xmin,a.ymin]]],spatialReference:c}):new d({paths:[[].concat(a.points)],spatialReference:c})},_fromProjectedGeometry:function(a,c,e){return"extent"===c?(a=a.rings[0],new q(a[0][0],a[0][1],a[2][0],a[2][1],e)):new n({points:a.paths[0],spatialReference:e.toJSON()})}});e.mixin(p,{UNIT_METER:9001,UNIT_GERMAN_METER:9031,UNIT_FOOT:9002,UNIT_SURVEY_FOOT:9003,UNIT_CLARKE_FOOT:9005,
UNIT_FATHOM:9014,UNIT_NAUTICAL_MILE:9030,UNIT_SURVEY_CHAIN:9033,UNIT_SURVEY_LINK:9034,UNIT_SURVEY_MILE:9035,UNIT_KILOMETER:9036,UNIT_CLARKE_YARD:9037,UNIT_CLARKE_CHAIN:9038,UNIT_CLARKE_LINK:9039,UNIT_SEARS_YARD:9040,UNIT_SEARS_FOOT:9041,UNIT_SEARS_CHAIN:9042,UNIT_SEARS_LINK:9043,UNIT_BENOIT_1895A_YARD:9050,UNIT_BENOIT_1895A_FOOT:9051,UNIT_BENOIT_1895A_CHAIN:9052,UNIT_BENOIT_1895A_LINK:9053,UNIT_BENOIT_1895B_YARD:9060,UNIT_BENOIT_1895B_FOOT:9061,UNIT_BENOIT_1895B_CHAIN:9062,UNIT_BENOIT_1895B_LINK:9063,
UNIT_INDIAN_FOOT:9080,UNIT_INDIAN_1937_FOOT:9081,UNIT_INDIAN_1962_FOOT:9082,UNIT_INDIAN_1975_FOOT:9083,UNIT_INDIAN_YARD:9084,UNIT_INDIAN_1937_YARD:9085,UNIT_INDIAN_1962_YARD:9086,UNIT_INDIAN_1975_YARD:9087,UNIT_FOOT_1865:9070,UNIT_RADIAN:9101,UNIT_DEGREE:9102,UNIT_ARCMINUTE:9103,UNIT_ARCSECOND:9104,UNIT_GRAD:9105,UNIT_GON:9106,UNIT_MICRORADIAN:9109,UNIT_ARCMINUTE_CENTESIMAL:9112,UNIT_ARCSECOND_CENTESIMAL:9113,UNIT_MIL6400:9114,UNIT_BRITISH_1936_FOOT:9095,UNIT_GOLDCOAST_FOOT:9094,UNIT_INTERNATIONAL_CHAIN:109003,
UNIT_INTERNATIONAL_LINK:109004,UNIT_INTERNATIONAL_YARD:109001,UNIT_STATUTE_MILE:9093,UNIT_SURVEY_YARD:109002,UNIT_50KILOMETER_LENGTH:109030,UNIT_150KILOMETER_LENGTH:109031,UNIT_DECIMETER:109005,UNIT_CENTIMETER:109006,UNIT_MILLIMETER:109007,UNIT_INTERNATIONAL_INCH:109008,UNIT_US_SURVEY_INCH:109009,UNIT_INTERNATIONAL_ROD:109010,UNIT_US_SURVEY_ROD:109011,UNIT_US_NAUTICAL_MILE:109012,UNIT_UK_NAUTICAL_MILE:109013,UNIT_SQUARE_INCHES:"esriSquareInches",UNIT_SQUARE_FEET:"esriSquareFeet",UNIT_SQUARE_YARDS:"esriSquareYards",
UNIT_ACRES:"esriAcres",UNIT_SQUARE_MILES:"esriSquareMiles",UNIT_SQUARE_MILLIMETERS:"esriSquareMillimeters",UNIT_SQUARE_CENTIMETERS:"esriSquareCentimeters",UNIT_SQUARE_DECIMETERS:"esriSquareDecimeters",UNIT_SQUARE_METERS:"esriSquareMeters",UNIT_ARES:"esriAres",UNIT_HECTARES:"esriHectares",UNIT_SQUARE_KILOMETERS:"esriSquareKilometers"});return p})},"esri/tasks/support/ProjectParameters":function(){define(["../../core/declare","dojo/_base/array","../../core/Accessoire","../../core/lang","../../geometry/support/jsonUtils"],
function(p,q,n,d,k){return p(n,{declaredClass:"esri.tasks.support.ProjectParameters",geometries:null,outSR:null,transformation:null,transformForward:null,toJSON:function(){var b=q.map(this.geometries,function(d){return d.toJSON()}),f={};f.outSR=this.outSR.wkid||JSON.stringify(this.outSR.toJSON());f.inSR=this.geometries[0].spatialReference.wkid||JSON.stringify(this.geometries[0].spatialReference.toJSON());f.geometries=JSON.stringify({geometryType:k.getJsonType(this.geometries[0]),geometries:b});this.transformation&&
(f.transformation=this.transformation.wkid||JSON.stringify(this.transformation));d.isDefined(this.transformForward)&&(f.transformForward=this.transformForward);return f}})})},"esri/webmap/InitialViewProperties":function(){define("require exports ../core/tsSupport/extendsHelper ../core/tsSupport/decorateHelper ../Viewpoint ../core/Accessoire ../geometry/SpatialReference ../core/accessoireSupport/typescript".split(" "),function(p,q,n,d,k,b,f,g){return function(e){function b(a){e.call(this,a);this.viewpoint=
this.spatialReference=null}n(b,e);b.prototype.clone=function(){return new b({spatialReference:this.spatialReference?this.spatialReference.clone():null,viewpoint:this.viewpoint?this.viewpoint.clone():null})};d([g.shared("esri.webmap.InitialViewProperties")],b.prototype,"declaredClass",void 0);d([g.property({value:null,type:f})],b.prototype,"spatialReference",void 0);d([g.property({value:null,type:k})],b.prototype,"viewpoint",void 0);return b=d([g.subclass()],b)}(b)})},"esri/core/accessoireSupport/typescript":function(){define(["../declare",
"../typescript","../JSONSupporter","dojo/_base/lang"],function(p,q,n,d){function k(d,f){if(!d)return f;if(!f)return d;for(var g in f){var e=d[g],l=f[g];Array.isArray(l)&&Array.isArray(e)?d[g]=e.concat(l):d[g]="object"===typeof l&&"object"===typeof e?k(e,l):l}return d}return{subclass:function(b,f){return function(g){g=q.declareDefinition(g,b);f&&(g.instanceMembers.classMetadata=k(f,g.instanceMembers.classMetadata));var e=g.instanceMembers.classMetadata;if(e&&e.properties)for(var l in e.properties){var a=
e.properties[l];a&&(!a.reader&&a.type)&&(a.type===Date?a.reader=function(a){return null!=a?new Date(a):null}:-1!==a.type._meta.bases.indexOf(n)&&(a.reader=function(a){return function(d){return a.fromJSON(d)}}(a.type)))}return d.mixin(p(g.bases,g.instanceMembers),g.classMembers)}},shared:q.shared,property:function(d){return function(f,g){var e=Object.getPrototypeOf(f),e=e&&e.classMetadata;if(!f.classMetadata||f.classMetadata===e)f.classMetadata={};f.classMetadata.properties=f.classMetadata.properties||
{};f.classMetadata.properties[g]=d||{}}}}})},"esri/core/typescript":function(){define(["./declare","dojo/_base/lang"],function(p,q){var n={declareDefinition:function(d,k){var b=[],f=Object.getPrototypeOf(d.prototype),g;if(f!==Object.prototype){var e=f.constructor;g=e.prototype;b.push(e)}k&&(b=b.concat(k));for(var e={},l=Object.getOwnPropertyNames(d.prototype),a=0;a<l.length;a++){var c=l[a];if("constructor"!==c){var h=c;"dojoConstructor"===c&&(h="constructor");if(!g||d.prototype[c]!==g[c])e[h]=d.prototype[c]}}l=
Object.getOwnPropertyNames(d);f=Object.getOwnPropertyNames(f.constructor);g={};for(a=0;a<l.length;a++)c=l[a],-1===f.indexOf(c)&&(g[c]=d[c]);return{bases:b,instanceMembers:e,classMembers:g}},subclass:function(d){return function(k){k=n.declareDefinition(k,d);return q.mixin(p(k.bases,k.instanceMembers),k.classMembers)}},shared:function(d){return function(k,b){k[b]=d}}};return n})},"*noref":1}});
define("require exports ./core/tsSupport/declareExtendsHelper ./core/tsSupport/decorateHelper ./Basemap ./Map ./Viewpoint ./core/Error ./core/JSONSupport ./core/Loadable ./core/promiseUtils ./core/requireUtils ./geometry/SpatialReference ./geometry/support/webMercatorUtils ./portal/Portal ./portal/PortalItem ./portal/support/geometryServiceUtils ./tasks/support/ProjectParameters ./webmap/InitialViewProperties ./core/accessorSupport/decorators".split(" "),function(p,q,n,d,k,b,f,g,e,l,a,c,h,s,t,u,v,
w,r,m){return function(e){function b(a){e.call(this);this.widgets=this.tables=this.sourceVersion=this.presentation=this.portalItem=this.initialViewProperties=this.bookmarks=this.authoringAppVersion=this.authoringApp=this.applicationProperties=null}n(b,e);b.prototype.initialize=function(){if(this.resourceInfo){var b=void 0;try{b=this._validateJSON(this.resourceInfo)}catch(c){this.addResolvingPromise(a.reject(c));return}this.read(b)}};b.prototype.readBasemap=function(a,b){return!b.baseMap||!Array.isArray(b.baseMap.baseMapLayers)||
!b.baseMap.baseMapLayers.length?null:k.fromJSON(b.baseMap)};b.prototype.readInitialViewProperties=function(a,b){var c={};b.spatialReference&&(c.spatialReference=h.fromJSON(b.spatialReference));return new r(c)};b.prototype.readSourceVersion=function(a,b){var c=b.version.split("."),d=c[1];return{major:parseInt(c[0],10),minor:parseInt(d,10)}};b.prototype.load=function(){this.addResolvingPromise(this._loadFromSource());return this};b.prototype.toJSON=function(){throw new g("internal:not-yet-implemented",
"WebMap.toJSON is not yet implemented");};b.fromJSON=function(a){if(!a)return null;if(a.declaredClass)throw Error("JSON object is already hydrated");return new b({resourceInfo:a})};b.prototype._loadFromSource=function(){return this.resourceInfo?this._loadFromJSON(this.resourceInfo):this.portalItem&&this.portalItem.id?this._loadFromItem(this.portalItem):a.resolve(null)};b.prototype._loadFromItem=function(a){var b=this;return a.load().then(function(a){return a.fetchData()}).then(function(a){b.resourceInfo=
a;return b._readAndLoadFromJSON(a)}).then(function(){return b._getInitialExtent()}).then(function(a){if(a){var c=b.initialViewProperties?b.initialViewProperties.clone():new r;c.viewpoint=new f;c.viewpoint.targetGeometry=a;b.initialViewProperties=c}})};b.prototype._readAndLoadFromJSON=function(a){a=this._validateJSON(a);this.read(a);return this._loadFromJSON(a)};b.prototype._validateJSON=function(a){a=this._sanitizeJSON(a);var b=this._validateVersion(a.version);a.version=b.major+"."+b.minor;return a};
b.prototype._sanitizeJSON=function(a){return{authoringApp:a.authoringApp||"",authoringAppVersion:a.authoringAppVersion||"",applicationProperties:a.applicationProperties,baseMap:a.baseMap,bookmarks:a.bookmarks,operationalLayers:a.operationalLayers,presentation:a.presentation,spatialReference:a.spatialReference,tables:a.tables,version:a.version||"0.0",widgets:a.widgets}};b.prototype._validateVersion=function(a){var b=a.split("."),c=b[0],b=b[1],d=/^\s*\d+\s*$/;if(!d.test(c))throw new g("webmap:invalid-version",
"Expected major version to be a number, but got '"+a+"'",{version:a});if(!d.test(b))throw new g("webmap:invalid-version","Expected minor version to be a number, but got '"+a+"'",{version:a});c=parseInt(c,10);b=parseInt(b,10);if(2!==c)throw new g("webmap:unsupported-version","Required major version is '2', but got '"+c+"'",{version:a});return{major:c,minor:b}};b.prototype._loadFromJSON=function(b){var d=this,e={context:{origin:"web-map"}};this.portalItem&&(e.context.portal=this.portalItem.portal||
t.getDefault());return c.when(p,"./portal/support/layersCreator").then(function(c){var f=[],g=b.operationalLayers;g&&g.length&&f.push.apply(f,c.populateOperationalLayers(d.layers,g,e));return a.eachAlways(f).then(function(){})})};b.prototype._getInitialExtent=function(){var b=null,c=this.initialViewProperties&&this.initialViewProperties.spatialReference,d=this.portalItem&&this.portalItem.extent;if(c&&d)if(c.isWGS84)b=d.clone();else if(c.isWebMercator)b=s.geographicToWebMercator(d);else return v.create(this.portalItem).then(function(a){var b=
new w;b.geometries=[d];b.outSR=c;return a.project(b)}).then(function(a){return a[0]}).otherwise(function(a){console.log("Error projecting item's extent:",a);return null});return a.resolve(b)};d([m.property()],b.prototype,"applicationProperties",void 0);d([m.property()],b.prototype,"authoringApp",void 0);d([m.property()],b.prototype,"authoringAppVersion",void 0);d([m.read("basemap",["baseMap"])],b.prototype,"readBasemap",null);d([m.property()],b.prototype,"bookmarks",void 0);d([m.property({type:r})],
b.prototype,"initialViewProperties",void 0);d([m.read("initialViewProperties",["spatialReference"])],b.prototype,"readInitialViewProperties",null);d([m.property({type:u})],b.prototype,"portalItem",void 0);d([m.property()],b.prototype,"presentation",void 0);d([m.property()],b.prototype,"resourceInfo",void 0);d([m.property({readOnly:!0})],b.prototype,"sourceVersion",void 0);d([m.read("sourceVersion",["version"])],b.prototype,"readSourceVersion",null);d([m.property()],b.prototype,"tables",void 0);d([m.property()],
b.prototype,"widgets",void 0);return b=d([m.subclass("esri.WebMap")],b)}(m.declared(b,l,e))});