// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("require exports dojo/_base/lang dojo/Deferred ../../../tasks/support/Query ../../../tasks/support/StatisticDefinition ./classBreaks ./support/utils".split(" "),function(z,A,m,g,n,p,q,f){function r(a){var b=new g,d=a.normalizationType,e=a.normalizationField,c=a.field;q({layer:a.layer,field:"string"===typeof c?c:null,classificationMethod:"standard-deviation",standardDeviationInterval:0.25,normalizationType:d,normalizationField:"field"===d?e:void 0,minValue:a.minValue,maxValue:a.maxValue}).then(function(a){var c,
d,e;a.classBreakInfos.some(function(a){a.hasAvg&&(c=a);return!!c});c&&(e=c.maxValue-c.minValue,d=c.minValue+e/2,e*=4);b.resolve({min:a.minValue,max:a.maxValue,avg:d,stddev:e})}).otherwise(function(a){b.reject(f.createError("attributeStatistics","unable to calculate class breaks."))});return b.promise}function s(a,b){var d=a;b&&(d=d?"("+d+") AND ("+b+")":b);return d}function t(a){var b=a.layer,d=a.field,e=new g;if(b.url&&b.advancedQueryCapabilities.supportsStatistics){var c=new n,h="string"===typeof d?
a.sqlExpression||d:a.sqlExpression||null,d=h?f.getRangeExpr(h,a.minValue,a.maxValue):null;c.sqlFormat=a.sqlExpression?"standard":null;c.where=s(a.sqlWhere,d);c.outStatistics="min max avg stddev count sum var".split(" ").map(function(a){var c=new p;c.statisticType=a;c.onStatisticField=h;c.outStatisticFieldName=("var"===a?"variance":a)+u;return c});b.queryFeatures(c).then(function(a){a=(a=a&&a.features)&&a[0]&&a[0].attributes;var c={},b;for(b in a)c[b.replace(v,"").toLowerCase()]=a[b];c.min===c.max&&
(null!=c.min&&null==c.stddev)&&(c.stddev=c.variance=0);e.resolve(c)}).otherwise(function(a){e.reject(f.createError("attributeStatistics","Statistics query operation failed."))})}else e.reject(f.createError("attributeStatistics","Statistics query requires a layer that supports statistics."));return e.promise}function w(a,b){var d,e=a.field;f.canUseSQL92Expression(a.layer)&&b&&(d=m.mixin({},a),delete d.field,d.sqlExpression=f.msSinceUnixEpochSQL(a.layer,"string"===typeof e?e:null));return t(d||a).then(function(a){b&&
("min max avg stddev sum variance".split(" ").forEach(function(b){null!=a[b]&&(a[b]=Math.ceil(a[b]))}),a.min===a.max&&null!=a.min&&(a.avg=a.min,a.stddev=a.variance=0));return a})}function x(a,b){var d=b.layer,e=b.field,c=b.normalizationType,h="function"===typeof e,g=b.valueExpression||b.sqlExpression,k=(e="string"===typeof e?d.getField(e):null)?e.type===l:!1;if(e){if(f.verifyFieldType(a,d,e,"attributeStatistics",y))return;if(k&&c){a.reject(f.createError("attributeStatistics","normalization is not supported when calculating statistics for date field."));
return}}else if(g&&c){a.reject(f.createError("attributeStatistics","normalization is not supported when valueExpression or sqlExpression is specified."));return}!f.isFeatureCollection(d)&&!b.features&&!h?!f.canUseSQL92Expression(d)&&(k||g)?a.reject(f.createError("attributeStatistics","unable to calculate statistics. Make sure the layer supports SQL expressions and standardized queries.")):(c?r(b):w(b,k)).then(function(b){a.resolve(b)}).otherwise(function(b){a.reject(f.createError("attributeStatistics",
"unable to calculate field statistics."))}):a.reject(f.createError("attributeStatistics","unable to calculate field statistics."))}var l="date",y=[].concat(["integer","small-integer","single","double"]).concat(l),u="_value",v=/_value$/i;return function(a){var b=new g;!a||!a.layer||!a.field&&!a.valueExpression&&!a.sqlExpression?b.reject(f.createError("attributeStatistics","'layer' and 'field', 'valueExpression' or 'sqlExpression' parameters are required.")):a.layer.then(function(){x(b,a)});return b.promise}});