// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("../../core/Accessor ../../core/HandleRegistry ../../core/lang ../../core/urlUtils ../../core/promiseList ../../core/promiseUtils ../../core/watchUtils ../../request ../../tasks/support/StatisticDefinition ../../tasks/support/Query ../../tasks/QueryTask dojo/_base/lang dojo/promise/all dojo/i18n!dojo/cldr/nls/number".split(" "),function(A,B,l,C,D,q,w,x,E,y,F,n,v,z){var G=/\'/g,H=/href\s*=\s*(?:\"([^\"]+)\"|\'([^\']+)\')/ig,I=/(\{([^\{\r\n]+)\})/g,k={attachments:"attachments",fields:"fields",
media:"media",text:"text"},t={"short-date":"(datePattern: 'M/d/y', selector: 'date')","short-date-le":"(datePattern: 'd/M/y', selector: 'date')","long-month-day-year":"(datePattern: 'MMMM d, y', selector: 'date')","day-short-month-year":"(datePattern: 'd MMM y', selector: 'date')","long-date":"(datePattern: 'EEEE, MMMM d, y', selector: 'date')","short-date-short-time":"(datePattern: 'M/d/y', timePattern: 'h:mm a', selector: 'date and time')","short-date-le-short-time":"(datePattern: 'd/M/y', timePattern: 'h:mm a', selector: 'date and time')",
"short-date-short-time-24":"(datePattern: 'M/d/y', timePattern: 'H:mm', selector: 'date and time')","short-date-le-short-time-24":"(datePattern: 'd/M/y', timePattern: 'H:mm', selector: 'date and time')","short-date-long-time":"(datePattern: 'M/d/y', timePattern: 'h:mm:ss a', selector: 'date and time')","short-date-le-long-time":"(datePattern: 'd/M/y', timePattern: 'h:mm:ss a', selector: 'date and time')","short-date-long-time-24":"(datePattern: 'M/d/y', timePattern: 'H:mm:ss', selector: 'date and time')",
"short-date-le-long-time-24":"(datePattern: 'd/M/y', timePattern: 'H:mm:ss', selector: 'date and time')","long-month-year":"(datePattern: 'MMMM y', selector: 'date')","short-month-year":"(datePattern: 'MMM y', selector: 'date')",year:"(datePattern: 'y', selector: 'date')"};return A.createSubclass({declaredClass:"esri.widgets.Popup.PopupRendererViewModel",properties:{content:{readOnly:!0},contentEnabled:!0,contentTypes:{readOnly:!0},formattedAttributes:{readOnly:!0},graphic:{},title:{readOnly:!0},
waitingForContent:{readOnly:!0}},constructor:function(){this._handles=new B},initialize:function(){this._handles.add([w.init(this,"graphic",function(a){this._updateGraphic(a,this.contentEnabled)}.bind(this)),w.init(this,"contentEnabled",function(a){this._updateGraphic(this.graphic,a)}.bind(this))])},destroy:function(){this._handles.destroy();this._handles=null;this._clearRelatedInfo();this._cancelPromises();this.graphic=null;this._set("title",null);this._set("content",null);this._set("waitingForContent",
null)},content:null,contentEnabled:!0,contentTypes:k,formattedAttributes:null,graphic:null,title:"",waitingForContent:!1,_handles:null,_contentPromise:null,_contentPromiseLookup:null,_relatedRecordsPromise:null,_relatedRecordsQueryPromises:[],_relatedRecordsLayerPromises:[],_relatedLayersInfo:null,_relatedInfo:null,_dateFormats:t,_addValuesToHref:function(a,b,c,d){b=this._trimString(b);return l.substitute(b&&0===b.indexOf("${")?c:d,a)},_cancelPromises:function(){this._contentPromiseLookup&&(Object.keys(this._contentPromiseLookup).forEach(function(a){this._contentPromiseLookup[a].cancel()},
this),this._contentPromiseLookup=null);this._contentPromise&&(this._contentPromise.cancel(),this._contentPromise=null);this._relatedRecordsQueryPromises.forEach(function(a){a.cancel()});this._relatedRecordsQueryPromises.length=0;this._relatedRecordsLayerPromises.length&&(this._relatedRecordsLayerPromises.forEach(function(a){a.cancel()}),this._relatedRecordsLayerPromises.length=0);this._relatedRecordsPromise&&(this._relatedRecordsPromise.cancel(),this._relatedRecordsPromise=null)},_clearRelatedInfo:function(){this._relatedInfo=
this._relatedLayersInfo=null},_compileContent:function(a,b){var c=a.content;if("function"===typeof c&&(c=c.call(null,{graphic:a.graphic}))&&c.nodeName)return c;if("string"===typeof c)return this._compileText(a,{type:k.text,text:c}).text;if(Array.isArray(c))return c.map(function(c,d){switch(c.type){case k.attachments:return this._proxyAttachments(c,b&&b[d]);case k.fields:return c;case k.media:return this._compileMedia(a,c);case k.text:return this._compileText(a,c)}},this);try{throw Error(this.declaredClass+
"::invalid content type.");}catch(d){console.warn(d.stack)}},_compileMedia:function(a,b){var c=n.clone(b),d=c.mediaInfos,f=a.attributes,e=a.layer,h=this.formattedAttributes.global,g=a.substOptions,r,m;d&&(r=[],d.forEach(function(c){m=0;var b=c.value;switch(c.type){case "image":var d=b.sourceURL,d=d&&this._trimString(l.substitute(f,this._fixTokens(d,e)));m=!!d;break;case "pie-chart":case "line-chart":case "column-chart":case "bar-chart":var s,d=b.normalizeField;b.fields=b.fields.map(function(a){return(s=
this._getLayerFieldInfo(e,a))?s.name:a},this);d&&(s=this._getLayerFieldInfo(e,d),b.normalizeField=s?s.name:d);m=b.fields.some(function(a){return l.isDefined(f[a])||-1!==a.indexOf("relationships/")&&this._relatedInfo},this);break;default:return}if(m){c=n.clone(c);var b=c.value,d=c.title?this._processFieldsInLinks(this._fixTokens(c.title,e),f):"",p=c.caption?this._processFieldsInLinks(this._fixTokens(c.caption,e),f):"";c.title=d?this._trimString(l.substitute(h,d,g)):"";c.caption=p?this._trimString(l.substitute(h,
p,g)):"";if("image"===c.type)b.sourceURL=l.substitute(f,this._fixTokens(b.sourceURL,e)),b.linkURL&&(b.linkURL=this._trimString(l.substitute(f,this._fixTokens(b.linkURL,e))));else{var u,k=(d=a.template)&&d.fieldInfos;b.fields.forEach(function(a,c){if(-1!==a.indexOf("relationships/")){var d=this._getRelatedChartInfos(e,k,a,b,f,g);Array.isArray(d)?b.fields=d:b.fields[c]=d}else{d=f[a];d=void 0===d?null:d;u=f[b.normalizeField]||0;d&&u&&(d/=u);var h=k&&this._getFieldInfo(k,a);b.fields[c]={y:d,tooltip:(h&&
h.label||a)+":"+this._formatValue(k,d,a,g,!!u)}}},this)}r.push(c)}},this));c.mediaInfos=r;return c},_compileText:function(a,b){var c=n.clone(b);if(c&&c.text){var d=a.attributes,f=this.formattedAttributes.global,e=a.substOptions,d=this._processFieldsInLinks(this._fixTokens(c.text,a.layer),d);c.text=this._trimString(l.substitute(f,d,e))}return c},_compileTitle:function(a){var b="",c=a.title,d=a.layer,f=a.attributes,e=a.substOptions,h=this.formattedAttributes.global;c&&("function"===typeof c&&(c=c.call(null,
{graphic:a.graphic})),"string"===typeof c&&-1===c.indexOf("{relationships/")&&(a=this._processFieldsInLinks(this._fixTokens(c,d),f),b=this._trimString(l.substitute(h,a,e))));return b},_createGraphicInfo:function(a,b){var c=a.getEffectivePopupTemplate(),d=c&&c.title,f=c&&c.content,e=a.layer,h=e&&e._getDateOpts&&e._getDateOpts().properties,g=n.clone(a.attributes)||{};return{graphic:a,template:c,title:d,content:f,contentEnabled:b,layer:e,attributes:g,properties:h,substOptions:{dateFormat:{properties:h,
formatter:"DateFormat"+t["short-date-short-time"]}}}},_fixTokens:function(a,b){return a.replace(I,function(a,d,f){return(a=this._getLayerFieldInfo(b,f))?"{"+a.name+"}":d}.bind(this))},_encodeAttributes:function(a){var b=n.clone(a)||{};Object.keys(b).forEach(function(a){var d=b[a];"string"===typeof d&&(d=encodeURIComponent(d).replace(G,"\x26apos;"),b[a]=d)});return b},_formatAttributesToFieldInfos:function(a,b,c,d,f){a.forEach(function(e){var h=e.fieldName,g=this._getLayerFieldInfo(b,h);g&&(h=e.fieldName=
g.name);f[h]=this._formatValue(a,f[h],h,c);d&&(e.format&&e.format.dateFormat)&&(e=d.indexOf(h),-1<e&&d.splice(e,1))},this)},_formatAttributes:function(a,b,c,d,f,e){var h=n.clone(f);this._relatedInfo&&Object.keys(this._relatedInfo).forEach(function(a){var c=this._relatedInfo[a];a=this._relatedLayersInfo[a];c&&(c.relatedFeatures.forEach(this._relatedFeaturesAttributes.bind(this,a,f,h)),c.relatedStatsFeatures.forEach(this._relatedStatsAttributes.bind(this,a,f,h)))},this);a&&this._formatAttributesToFieldInfos(a,
b,c,d,h);if(b){var g=b.typeIdField;Object.keys(f).forEach(function(a){if(-1===a.indexOf("relationships/")){var c=f[a];if(l.isDefined(c)){var d=this._getDomainName(b,e,a,c);l.isDefined(d)?h[a]=d:a===g&&(c=this._getTypeName(b,e,c),l.isDefined(c)&&(h[a]=c))}}},this)}return h},_formatValue:function(a,b,c,d,f){var e=a&&this._getFieldInfo(a,c);a=e&&e.format;c="number"===typeof b&&d.dateFormat.properties&&-1===d.dateFormat.properties.indexOf(c)&&(!a||!a.dateFormat);if(!l.isDefined(b)||!e||!l.isDefined(a))return c?
this._forceLTR(b):b;var h="",g=[],e=a.hasOwnProperty("places")||a.hasOwnProperty("digitSeparator"),r=a.hasOwnProperty("digitSeparator")?a.digitSeparator:!0;if(e)h="NumberFormat",g.push("places: "+(l.isDefined(a.places)&&(!f||0<a.places)?Number(a.places):"Infinity")),g.length&&(h+="("+g.join(",")+")");else if(a.dateFormat)h="DateFormat"+t[a.dateFormat]||t["short-date-short-time"];else return c?this._forceLTR(b):b;b=l.substitute({myKey:b},"{myKey:"+h+"}",d)||"";e&&!r&&z.group&&(b=b.replace(RegExp("\\"+
z.group,"g"),""));return c?this._forceLTR(b):b},_forceLTR:function(a){return"\x26lrm;"+a},_getDomainName:function(a,b,c,d){return(a=a.getDomain&&a.getDomain(c,{feature:b}))&&a.codedValues?a.getName(d):null},_getFieldInfo:function(a,b){for(var c=b.toLowerCase(),d,f=0;f<a.length;f++){var e=a[f];if(e.fieldName&&e.fieldName.toLowerCase()===c){d=e;break}}return d},_getLayerFieldInfo:function(a,b){return a&&a.getField?a.getField(b):null},_getTypeName:function(a,b){var c=a.getType&&a.getType(b);return c&&
c.name},_processFieldsInLinks:function(a,b){var c=this._encodeAttributes(b);a&&(a=a.replace(H,function(a,f){return this._addValuesToHref(a,f,b,c)}.bind(this)));return a},_proxyAttachments:function(a,b){var c=n.clone(a);if(b&&!(b instanceof Error)&&b.attachmentInfos&&b.attachmentInfos.length){var d=b.attachmentInfos.map(function(a){a.url=C.addProxy(a.url);return a},this);c.attachmentInfos=d}return c},_queryAttachments:function(a){var b=a.layer,c=a.attributes;a=b&&b.objectIdField;c=c&&a&&c[a];if(a&&
b.hasAttachments&&c)return this._queryAttachmentInfos(b,c)},_queryAttachmentInfos:function(a,b){var c=a.url+"/"+a.layerId+"/"+b+"/attachments",d=a.token||"";return x(c,{query:{f:"json",token:d},callbackParamName:"callback"}).then(function(a){a=a.data;a.attachmentInfos.forEach(function(a){a.url=c+"/"+a.id;d&&(a.url+="?token\x3d"+d);a.objectId=b});return a})},_queryContent:function(a){var b=a.template,b=b&&b.content;if(!b||"string"===typeof b||"function"===typeof b)return q.resolve();if(!Array.isArray(b))return q.reject(Error(this.declaredClass+
"::Invalid content type."));var c={};b.forEach(function(b,f){b.type===k.attachments&&(c[f]=this._queryAttachments(a))},this);if(0===Object.keys(c).length)return q.resolve();this._contentPromiseLookup=c;return D(c).always(function(a){this._contentPromiseLookup=null;return a}.bind(this))},_trimString:function(a){return(a||"").trim()},_updateContent:function(a){if(a.contentEnabled){var b=this._queryContent(a).then(function(c){this._set("content",this._compileContent(a,c))}.bind(this),function(a){console.log(this.declaredClass+
"::error loading template",a)}.bind(this)).always(function(){this._contentPromise=null}.bind(this));return this._contentPromise=b}return q.resolve()},_createFormattedAttributes:function(a){var b=a.graphic,c=a.attributes,d=a.layer,f=a.template,e=a.substOptions,h=a.properties,g={global:this._formatAttributes(f&&f.fieldInfos,d,e,h,c,b),content:[]};a=f&&f.content;Array.isArray(a)&&a.forEach(function(a,f){a.type===k.fields&&a.fieldInfos&&(g.content[f]=this._formatAttributes(a.fieldInfos,d,e,h,c,b))},this);
return g},_updateGraphic:function(a,b){if(this._handles&&(this._clearRelatedInfo(),this._cancelPromises(),this._set("title",""),this._set("content",null),this._set("formattedAttributes",null),this._set("waitingForContent",!1),a)){this._set("waitingForContent",!0);var c=this._createGraphicInfo(a,b);this._relatedRecordsPromise=this._checkForRelatedRecords(c).then(function(){this._set("formattedAttributes",this._createFormattedAttributes(c));this._set("title",this._compileTitle(c));return this._updateContent(c)}.bind(this)).always(function(){this._relatedRecordsPromise=
null;this._relatedRecordsLayerPromises.length=0;this._relatedRecordsQueryPromises.length=0;this._set("waitingForContent",!1)}.bind(this))}},_getAllFieldInfos:function(a){var b=[],c=a.template,d=c&&c.fieldInfos;a=a.contentEnabled;d&&(b=b.concat(d));a&&(c=c&&c.content,Array.isArray(c)&&c.forEach(function(a){b=b.concat(a&&a.fieldInfos)},this));return b},_checkForRelatedRecords:function(a){var b=this._getAllFieldInfos(a).filter(function(a){return a&&a.fieldName&&-1!==a.fieldName.indexOf("relationships/")},
this);return b&&0<b.length?this._getRelatedRecords({graphic:a.graphic,fieldsInfo:b}):q.resolve()},_relatedFeaturesAttributes:function(a,b,c,d){Object.keys(d.attributes).forEach(function(f){if("esriRelCardinalityOneToOne"===a.relation.cardinality){var e=this._toRelatedFieldName([a.relation.id,f]);b[e]=c[e]=d.attributes[f]}},this)},_relatedStatsAttributes:function(a,b,c,d){Object.keys(d.attributes).forEach(function(f){var e=this._toRelatedFieldName([a.relation.id,f]);b[e]=c[e]=d.attributes[f]},this)},
_getRelatedChartInfos:function(a,b,c,d,f,e){var h,g,l,m,k,n;h=[];n=this._fromRelatedFieldName(c);k=n[0];g=this._relatedInfo[k];k=this._relatedLayersInfo[k];g&&g.relatedFeatures.forEach(function(g){var k=g.attributes,p;Object.keys(k).forEach(function(g){if(g===n[1]){p={};m=k[g];d.normalizeField&&(l=-1!==d.normalizeField.indexOf("relationships/")?k[this._fromRelatedFieldName(d.normalizeField)[1]]:f[d.normalizeField]);m&&l&&(m/=l);if(d.tooltipField)if(-1!==d.tooltipField.indexOf("relationships/"))g=
this._fromRelatedFieldName(d.tooltipField)[1],p.tooltip=k[g]+": "+this._formatValue(b,m,k[g],e,!!l);else{if(g=this._getLayerFieldInfo(a,c))c=g.name;p.tooltip=c+": "+this._formatValue(b,m,d.tooltipField,e,!!l)}else p.tooltip=m;p.y=m;h.push(p)}},this)},this);return"esriRelCardinalityOneToMany"===k.relation.cardinality||"esriRelCardinalityManyToMany"===k.relation.cardinality?h:h[0]},_getRelatedRecords:function(a){var b=a.graphic;return this._relatedLayersInfo?this._queryRelatedLayers(b).then(function(a){this._setRelatedRecords(a);
return a}.bind(this)):this._getRelatedLayersInfo(a).then(function(a){Object.keys(a).forEach(function(b){a[b]&&(this._relatedLayersInfo[b].relatedLayerInfo=a[b].data)},this);return this._queryRelatedLayers(b).then(function(a){this._setRelatedRecords(a);return a}.bind(this))}.bind(this))},_getRelatedLayersInfo:function(a){var b=a.fieldsInfo,c,d={};c=a.graphic.layer;this._relatedLayersInfo||(this._relatedLayersInfo={});b.forEach(function(a){var b,d,g;b=this._fromRelatedFieldName(a.fieldName);d=b[0];
b=b[1];d&&(this._relatedLayersInfo[d]||(c.relationships.some(function(a){if(a.id==d)return g=a,!0}),g&&(this._relatedLayersInfo[d]={relation:g,relatedFields:[],outStatistics:[]})),this._relatedLayersInfo[d]&&(this._relatedLayersInfo[d].relatedFields.push(b),a.statisticType&&(a=new E({statisticType:a.statisticType,onStatisticField:b,outStatisticFieldName:b}),this._relatedLayersInfo[d].outStatistics.push(a))))},this);Object.keys(this._relatedLayersInfo).forEach(function(a){var b;this._relatedLayersInfo[a]&&
(b=this._relatedLayersInfo[a].relation,b=c.url+"/"+b.relatedTableId,this._relatedLayersInfo[a].relatedLayerUrl=b,d[a]=x(b,{query:{f:"json"},callbackParamName:"callback"}))},this);Object.keys(d).forEach(function(a){this._relatedRecordsLayerPromises.push(d[a])},this);return v(d)},_queryRelatedLayers:function(a){var b={};Object.keys(this._relatedLayersInfo).forEach(function(c){b[c]=this._queryRelatedLayer({graphic:a,relatedInfo:this._relatedLayersInfo[c]})},this);return v(b)},_queryRelatedLayer:function(a){var b,
c,d,f,e,h,g,k,l;b=a.graphic;c=b.layer.layerId;g=a.relatedInfo;a=g.relatedLayerInfo;k=g.relatedLayerUrl;l=g.relation;a&&a.relationships&&a.relationships.some(function(a){if(a.relatedTableId===parseInt(c,10))return d=a,!0});d&&(a.fields.some(function(a){if(a.name===d.keyField)return f=-1!==["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"].indexOf(a.type)?"number":"string",!0}),e="string"===f?d.keyField+"\x3d'"+b.attributes[l.keyField]+"'":d.keyField+"\x3d"+
b.attributes[l.keyField],e=new y({where:e,outFields:g.relatedFields}),g.outStatistics&&(0<g.outStatistics.length&&a.supportsStatistics)&&(h=new y({where:e.where,outFields:e.outFields,outStatistics:g.outStatistics})),a=new F({url:k}),e=[a.execute(e)],h&&e.push(a.execute(h)));this._relatedRecordsQueryPromises=this._relatedRecordsQueryPromises.concat(e);return v(e)},_setRelatedRecords:function(a){this._relatedInfo=[];Object.keys(a).forEach(function(b){if(a[b]){var c=a[b];this._relatedInfo[b]={relatedFeatures:c[0].features};
l.isDefined(c[1])&&(this._relatedInfo[b].relatedStatsFeatures=c[1].features)}},this)},_fromRelatedFieldName:function(a){return-1!==a.indexOf("relationships/")?a.split("/").slice(1):[]},_toRelatedFieldName:function(a){return a&&0<a.length?"relationships/"+a[0]+"/"+a[1]:""}})});