// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/widgets/Popup/templates/PopupRenderer.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"${_css.container}"\x3e\r\n    \x3cdiv class\x3d"${_css.main}"\x3e\r\n      \x3cdiv class\x3d"${_css.loadingSpinnerContainer}"\x3e\x3cspan class\x3d"${_css.iconLoading} ${_css.spinner}"\x3e\x3c/span\x3e\x3c/div\x3e\r\n      \x3cdiv data-dojo-attach-point\x3d"_contentNode"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("require ../Widget ./PopupRendererViewModel ../../core/requireUtils ../../core/watchUtils dojo/_base/lang dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/on dijit/_TemplatedMixin dijit/a11yclick dojo/i18n!./nls/PopupRenderer dojo/text!./templates/PopupRenderer.html".split(" "),function(t,u,v,w,r,q,x,k,d,p,y,s,m,z){var c={iconText:"esri-icon-font-fallback-text",iconLoading:"esri-icon-loading-indicator esri-rotating",iconDownload:"esri-icon-download",iconLeftTriangleArrow:"esri-icon-left-triangle-arrow",
iconRightTriangleArrow:"esri-icon-right-triangle-arrow",iconMedia:"esri-icon-media",iconChart:"esri-icon-chart",base:"esri-popup-renderer",container:"esri-popup-renderer__size-container",main:"esri-popup-renderer__main-container",btn:"esri-popup-renderer__button",icon:"esri-popup-renderer__icon",content:"esri-popup-renderer__content",contentElement:"esri-popup-renderer__content-element",text:"esri-popup-renderer__text",showMediaPagination:"esri-popup-renderer--media-pagination-visible",attachments:"esri-popup-renderer__attachments",
attachmentsTitle:"esri-popup-renderer__attachments-title",attachmentsItem:"esri-popup-renderer__attachments-item",attachmentsItemIcon:"esri-popup-renderer__attachments-item-icon",fields:"esri-popup-renderer__fields",media:"esri-popup-renderer__media",mediaContainer:"esri-popup-renderer__media-container",mediaItemContainer:"esri-popup-renderer__media-item-container",mediaItem:"esri-popup-renderer__media-item",mediaItemTitle:"esri-popup-renderer__media-item-title",mediaItemCaption:"esri-popup-renderer__media-item-caption",
mediaPrevious:"esri-popup-renderer__media-previous",mediaPreviousIconLTR:"esri-popup-renderer__media-previous-icon",mediaPreviousIconRTL:"esri-popup-renderer__media-previous-icon--rtl",mediaNext:"esri-popup-renderer__media-next",mediaNextIconLTR:"esri-popup-renderer__media-next-icon",mediaNextIconRTL:"esri-popup-renderer__media-next-icon--rtl",mediaSummary:"esri-popup-renderer__media-summary",mediaCount:"esri-popup-renderer__media-count",mediaImageSummary:"esri-popup-renderer__media-image-summary",
mediaImageIcon:"esri-popup-renderer__media-image-icon",mediaChart:"esri-popup-renderer__media-chart",mediaChartSummary:"esri-popup-renderer__media-chart-summary",mediaChartIcon:"esri-popup-renderer__media-chart-icon",loading:"esri-popup-renderer__loading",loadingSpinnerContainer:"esri-popup-renderer__loading-container",spinner:"esri-popup-renderer__loading-spinner"},A=/^\s*(https?:\/\/[^\s]+)\s*$/i;return u.createSubclass([y],{declaredClass:"esri.widgets.Popup.PopupRenderer",templateString:z,properties:{viewModel:{type:v}},
baseClass:c.base,constructor:function(){this._charts=[];this._chartTooltips=[]},postCreate:function(){this.inherited(arguments);var a=this,d=this.viewModel;this.own(r.init(d,"waitingForContent",this._loadingSpinner.bind(this)),r.init(d,"content",this._render.bind(this)),p(this._contentNode,p.selector("."+c.mediaNext,s),function(){a._nextMedia(this)}),p(this._contentNode,p.selector("."+c.mediaPrevious,s),function(){a._previousMedia(this)}))},destroy:function(){this._destroyCharts();this._clearResizeTimer()},
_i18n:m,_css:c,resize:function(){this._resizeCharts();this.emit("resize")},_clearResizeTimer:function(){this._mediaResizeTimer&&(clearTimeout(this._mediaResizeTimer),this._mediaResizeTimer=0)},_countMediaInfos:function(a){var c=0,b=0;a.forEach(function(a){"image"===a.type?c++:-1!==a.type.indexOf("chart")&&b++});return{total:b+c,images:c,charts:b}},_createMediaNodes:function(a){this._destroyCharts();var g=a.mediaIndex,b=a.mediaInfos[g];a=a.node;d.empty(a);var f=d.create("div",{className:c.mediaItem},
a),g=this._createMediaType(b,g);d.place(g,f,"only");b.title&&d.create("div",{className:c.mediaItemTitle,innerHTML:b.title},a);b.caption&&d.create("div",{className:c.mediaItemCaption,innerHTML:b.caption},a);this._clearResizeTimer();this._mediaResizeTimer=setTimeout(function(){this.resize();this._clearResizeTimer()}.bind(this),0)},_createMediaType:function(a,g){var b=a.value,f;if("image"===a.type){var e=d.create("img",{alt:a.title||"",src:b.sourceURL});b.linkURL?(f=d.create("a",{title:a.title||"",href:b.linkURL,
target:this._preventNewTab(b.linkURL)?"":"_blank"}),d.place(e,f)):f=e}else-1!==a.type.indexOf("chart")&&(f=d.create("div",{className:c.mediaChart},f),b=["dojox/charting/Chart2D","dojox/charting/action2d/Tooltip"],e=a.value.theme||this.chartTheme,"string"===typeof e&&(e=e.replace(/\./gi,"/"),-1===e.indexOf("/")&&(e="dojox/charting/themes/"+e)),e||(e="dojox/charting/themes/Claro"),b.push(e),this._cancelChartModules(),this._chartsPromise=w.when(t,b).then(function(b){this._showChart(f,a.type,a.value,
b[0],b[1],b[2]);this._chartsPromise=null}.bind(this)));return f},_cancelChartModules:function(){this._chartsPromise&&this._chartsPromise.cancel()},_destroyCharts:function(){this._cancelChartModules();var a;if(this._chartTooltips&&this._chartTooltips.length)for(a=0;a<this._chartTooltips.length;a++)this._chartTooltips[a].destroy();this._chartTooltips.length=0;if(this._charts&&this._charts.length)for(a=0;a<this._charts.length;a++)this._charts[a].destroy();this._charts.length=0},_loadingSpinner:function(a){k.toggle(this.domNode,
c.loading,!!a)},_nextMedia:function(a){this._pageMedia(a,"next")},_pageMedia:function(a,c){var b,d=x.get(a,"data-element-index");d&&(b=parseInt(d,10),b=this._elementInfo[b]);if(b){var d=b.mediaInfos,e=b.mediaIndex;"previous"===c?e--:e++;d&&d.length&&(e=(e+d.length)%d.length);b.mediaIndex=e;this._createMediaNodes(b)}},_preventNewTab:function(a){return(a=a&&q.trim(a).toLowerCase())&&(0===a.indexOf("mailto:")||0===a.indexOf("tel:"))},_previousMedia:function(a){this._pageMedia(a,"previous")},_render:function(a){this._elementInfo=
[];this._destroyCharts();d.empty(this._contentNode);var c=this.viewModel;a&&("string"===typeof a?(a=this._renderText({type:"text",text:a}))&&d.place(a,this._contentNode,"only"):a.nodeName?d.place(a,this._contentNode,"only"):Array.isArray(a)&&a.forEach(function(a,f){var e;switch(a.type){case c.contentTypes.attachments:e=this._renderAttachments(a,f);break;case c.contentTypes.fields:e=this._renderFields(a,f);break;case c.contentTypes.media:e=this._renderMedia(a,f);break;case c.contentTypes.text:e=this._renderText(a,
f)}e&&d.place(e,this._contentNode,0===f?"only":"last")},this));this.resize()},_renderAttachments:function(a,g){var b,f=a.attachmentInfos;if(f&&f.length){b=d.create("div");k.add(b,[c.attachments,c.contentElement]);d.create("div",{className:c.attachmentsTitle,textContent:m.attach},b);var e=d.create("ul",{},b);f.forEach(function(a){var b=d.create("li",{},e),b=d.create("a",{href:a.url,target:"_blank"},b);d.create("span",{className:c.iconDownload+" "+c.attachmentsItemIcon},b);d.create("span",{className:c.attachmentsItem,
textContent:a.name||m.noTitle},b)},this)}return b},_renderFields:function(a,g){var b=this.viewModel,f,e=b.graphic.getEffectivePopupTemplate();if(e=a.fieldInfos||e&&e.fieldInfos){var h=b.formattedAttributes.content[g]||b.formattedAttributes.global;f=d.create("div");k.add(f,[c.fields,c.contentElement]);var b=d.create("table",{summary:m.fieldsSummary},f),l=d.create("tbody",{},b);e.forEach(function(a){if(a.hasOwnProperty("visible")?a.visible:1){var b=a.fieldName;a=a.label||b;var b=h[b]||"",c;b&&"string"===
typeof b&&(c=b.replace(A,'\x3ca target\x3d"_blank" href\x3d"$1" title\x3d"'+a+'"\x3e'+m.view+"\x3c/a\x3e"));var e=d.create("tr",{},l),f=a,g=b;c&&c!==b&&(f=a,g=c);d.create("th",{innerHTML:f},e);d.create("td",{innerHTML:g},e)}},this)}return f},_renderMedia:function(a,g){var b,f=a.mediaInfos;if(f&&f.length){var e=this._countMediaInfos(f),h={tabIndex:"0",role:"button"};h["data-element-index"]=g;b=d.create("div");k.add(b,[c.media,c.contentElement]);k.toggle(b,c.showMediaPagination,1<e.total);var l=d.create("ul",
{className:c.mediaSummary},b),n=d.create("li",{className:c.mediaImageSummary},l);d.create("span",{className:c.mediaCount,"aria-label":m.numImages,textContent:"("+e.images+")"},n);d.create("span",{"aria-hidden":!0,className:c.mediaImageIcon+" "+c.iconMedia},n);l=d.create("li",{className:c.mediaImageSummary},l);d.create("span",{className:c.mediaCount,"aria-label":m.numCharts,textContent:"("+e.charts+")"},l);d.create("span",{"aria-hidden":!0,className:c.mediaChartIcon+" "+c.iconChart},l);e=d.create("div",
{className:c.mediaContainer},b);l=d.create("div",q.mixin({title:m.previous},h),e);k.add(l,[c.btn,c.mediaPrevious]);n=d.create("span",{"aria-hidden":!0},l);k.add(n,[c.icon,c.mediaPreviousIconLTR,c.iconLeftTriangleArrow]);n=d.create("span",{"aria-hidden":!0},l);k.add(n,[c.icon,c.mediaPreviousIconRTL,c.iconRightTriangleArrow]);d.create("span",{className:c.iconText,textContent:m.previous},l);f={mediaIndex:0,node:d.create("div",{className:c.mediaItemContainer},e),mediaInfos:f};this._elementInfo[g]=f;this._createMediaNodes(f);
h=d.create("div",q.mixin({title:m.next},h),e);k.add(h,[c.btn,c.mediaNext]);f=d.create("span",{"aria-hidden":!0},h);k.add(f,[c.icon,c.mediaNextIconLTR,c.iconRightTriangleArrow]);f=d.create("span",{"aria-hidden":!0},h);k.add(f,[c.icon,c.mediaNextIconRTL,c.iconLeftTriangleArrow]);d.create("span",{className:c.iconText,textContent:m.next},h)}return b},_renderText:function(a,g){var b;a&&a.text&&(b=d.create("div",{innerHTML:a.text}),k.add(b,[c.text,c.contentElement]));return b},_resizeCharts:function(){if(this._charts&&
this._charts.length)for(var a=0;a<this._charts.length;a++){var c=this._charts[a],b=c.node;b&&(b.offsetWidth&&b.offsetHeight)&&c.resize()}},_showChart:function(a,c,b,d,e,h){a=new d(a,{margins:{l:4,t:4,r:4,b:4}});h&&a.setTheme(h);switch(c){case "pie-chart":a.addPlot("default",{type:"Pie",labels:!1});a.addSeries("Series A",b.fields);break;case "line-chart":a.addPlot("default",{type:"Markers"});a.addAxis("x",{min:0,majorTicks:!1,minorTicks:!1,majorLabels:!1,minorLabels:!1});a.addAxis("y",{includeZero:!0,
vertical:!0,fixUpper:"minor"});b.fields.forEach(function(a,b){a.x=b+1});a.addSeries("Series A",b.fields);break;case "column-chart":a.addPlot("default",{type:"Columns",gap:3});a.addAxis("y",{includeZero:!0,vertical:!0,fixUpper:"minor"});a.addSeries("Series A",b.fields);break;case "bar-chart":a.addPlot("default",{type:"Bars",gap:3}),a.addAxis("x",{includeZero:!0,fixUpper:"minor",minorLabels:!1}),a.addAxis("y",{vertical:!0,majorTicks:!1,minorTicks:!1,majorLabels:!1,minorLabels:!1}),a.addSeries("Series A",
b.fields)}c=new e(a);a.render();this._charts.push(a);this._chartTooltips.push(c)}})});