// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("../../core/declare dojo/_base/lang dojox/gfx dojox/gfx/matrix ./math/common ./math/mat2d ./math/vec2 ./Projector ./viewpointUtils ../../geometry/Extent ../../geometry/Polygon ../../geometry/support/webMercatorUtils ../../symbols/SimpleMarkerSymbol ../../symbols/support/gfxUtils ../../core/screenUtils ../../core/Accessoire".split(" "),function(x,v,y,r,z,n,u,A,B,C,D,E,q,s,p,F){var G=0,w=-1!==y.renderer.toLowerCase().indexOf("svg"),H={"picture-marker-symbol":"image","picture-fill-symbol":"path",
"simple-fill-symbol":"path","simple-line-symbol":"path","cartographic-line-symbol":"path","text-symbol":"text"},I={square:1,cross:1,x:1,diamond:1,target:1};return x(F,{declaredClass:"esri.views.2d.VectorGroup",constructor:function(a){this.id="vecgp"+G++;this._transform=n.create();this._projector=new A;this.vectors=[];this.adding=[];this.removing=[];this.updating=[]},applyState:function(a){if(this.transform){var c=n.invert(this._transform,this.transform);n.multiply(c,a.transformNoRotation,c);this.surface.setTransform({xx:c[0],
yx:c[1],xy:c[2],yy:c[3],dx:c[4],dy:c[5]})}},requestVectorDraw:function(a){},addVector:function(a){return this.addVectorAt(a,this.vectors.length)},addVectorAt:function(a,c){c=Math.min(this.vectors.length,c);this.vectors.splice(c,0,a);a.set({parent:this,view:this.view});return a},removeVector:function(a){if(!this.vectors)return a;var c=this.vectors.indexOf(a);-1<c&&(a=this.vectors.splice(c,1)[0],a.set({parent:null,view:null}),this._removeShape(a));return a},draw:function(a){this.transform||this._updateTransform();
var c=this.view,b=c.state;if(0<b.width-b.worldScreenWidth){var d=b.size.concat();d[0]=Math.min(d[0],Math.round(b.worldScreenWidth));this._viewExtent=B.getExtent(new C,b.viewpoint,d)}else this._viewExtent=c.extent;this._viewGeoExtent=c.spatialReference.isWebMercator?E.webMercatorToGeographic(this._viewExtent,!0):null;this.surface.openBatch();b=0;for(d=this.vectors.length;b<d;b++)(c=this.vectors[b])&&this.drawVector(c,a);this.surface.closeBatch()},drawVector:function(a,c){var b=a.extent,d=a.shape,e,
h,g,f=a.geometry,l=a.projectedGeometry;if(a.graphic.visible&&b&&(e=this._getScreenOffsets(this.view,b))&&(h=a.symbol)){if(a.resolution!==this.resolution||a.rotation!==this.rotation||!a.offsets||!this._compareOffsets(a.offsets,e)?a.offsets=e:g=!0,!d||c||!g)b=f.type,a.resolution=this.resolution,a.rotation=this.rotation,"point"===b?(this._isInvalidShape(h,d)&&this._removeShape(a),d=a.shape=this._drawPoint(this.surface,l||f,h,a,e),this._stylePoint(a,h)):"multipoint"===b?(d=a.shape=this._drawMarkers(this.surface,
l||f,h,a,e),this._styleMarkers(a,h)):h&&(this._isInvalidShape(h,d)&&this._removeShape(a,!1),d=a.shape=this._drawShape(this.surface,l||f,a,e),this._styleShape(a,h)),d.getNode().vector=a}else d&&this._removeShape(a)},_compareOffsets:function(a,c){var b=!1;return b=a.length===c.length?a.every(function(a,b){return a===c[b]}):!1},_getScreenOffsets:function(a,c){var b=c.spatialReference,b=this._viewGeoExtent&&4326===b.wkid?this._viewGeoExtent:this._viewExtent,d=b.spatialReference;if(d.isWrappable){var e=
[],h=d._getInfo(),g=a.state.worldScreenWidth,d=c._partwise,f,l;f=b._getParts(h);d&&d.length?(l=[],d.forEach(function(a){l=l.concat(a._getParts(h))})):l=c._getParts(h);l.forEach(function(a){f.forEach(function(b){b.extent.intersects(a.extent)&&a.frameIds.forEach(function(a){a=(b.frameIds[0]-a)*g;-1===e.indexOf(a)&&e.push(a)})}.bind(this))}.bind(this));return e.length?e.sort():null}return b.intersects(c)?[0]:null},_isInvalidShape:function(a,c){var b=c&&c.shape&&c.shape.type,d=a&&a.type,e=a&&a.style;
d&&(e=H[d]||e);I[e]&&(e="path");return!(!b||!(e&&b!==e))},_removeShape:function(a,c){var b=a.shape,d=b&&b.getNode();b&&(b.removeShape(),b.destroy());a.shape=a.offsets=null;!1!==c&&this._removeBgShape(a);d&&(d.e_graphic=null)},_removeBgShape:function(a){var c=a.bgShape,b=c&&c.getNode();c&&(c.removeShape(),c.destroy());a.bgShape=null;b&&(b.e_graphic=null)},_drawPoint:function(a,c,b,d,e,h){var g=b.type;c=this._projector.toScreenPoint(c,e[0]);var f=u.fromValues(c.x,c.y);c=f[0];e=f[1];var l=null!=h?d.shape&&
d.shape.children[h]:d.shape,m;h=[];var t=d.rotationAngle,k;if(d=d.size)d=isFinite(d[0])&&d[0],k=!!d;d=k?p.pt2px(d):null;f={x:f[0],y:f[1]};if(null==t){var n=z.toRadian(360-this.view.rotation);h.push(r.rotateAt(n,f))}t&&h.push(r.rotategAt(t,f));t=p.pt2px(b.xoffset);n=p.pt2px(b.yoffset);(0!==t||0!==n)&&h.push(r.translate(t,-n));0!==b.angle&&h.push(r.rotategAt(b.angle,f));if("simple-marker-symbol"===g)switch(m=b.style,g=Math.round,d=k?d:p.pt2px(b.size),m){case q.STYLE_SQUARE:case q.STYLE_CROSS:case q.STYLE_X:case q.STYLE_DIAMOND:b=
isNaN(d)?16:d/2;m=this._drawPath(a,l,this._smsToPath(q,m,c,e,g(c-b),g(c+b),g(e-b),g(e+b)));break;case q.STYLE_TARGET:k=p.pt2px(b._targetWidth)/2;f=p.pt2px(b._targetHeight)/2;m=this._drawPath(a,l,this._smsToPath(q,m,c,e,g(c-k),g(c+k),g(e-f),g(e+f),p.pt2px(b._spikeSize)));break;case q.STYLE_PATH:m=this._drawPath(a,l,b.path,!0);b=m.getBoundingBox();a=this._getScaleMatrix(b,d);(1!==a.xx||1!==a.yy)&&h.push(r.scaleAt(a.xx,a.yy,f));h.push(r.translate(-(b.x+b.width/2)+c,-(b.y+b.height/2)+e));break;default:b=
isNaN(d)?16:d/2,m=this._drawCircle(a,l,{cx:c,cy:e,r:b})}else if("shield-label-symbol"===g)f=p.pt2px(b.width),k=p.pt2px(b.height),m=a.createGroup(),l=a.createImage({x:c-f/2,y:e-k/2,width:f,height:k,src:b.url}),m.add(l),null!=b.font&&(e+=0.2*p.pt2px(b.getHeight()),a=a.createText({type:"text",text:b.text,x:c,y:e,align:"middle",decoration:b.decoration,rotated:b.rotated,kerning:b.kerning}),k=b.font.clone(),k.size=p.pt2px(k.size),a.setFont(k),a.setFill(b.color),m.add(a));else if("picture-marker-symbol"===
g)f=k?d:p.pt2px(b.width),k=k?d:p.pt2px(b.height),m=this._drawImage(a,l,{x:c-f/2,y:e-k/2,width:f,height:k,src:b.url});else if("text-symbol"===g){if(k=b.font)k=k.clone(),k.size=null!=d?d:p.pt2px(k.size);m=this._drawText(a,l,{type:"text",text:b.text,x:c,y:e,align:s.getSVGAlign(b),decoration:b.decoration||k&&k.decoration,rotated:b.rotated,kerning:b.kerning});k&&m.setFont(k);w&&(a=m.getNode(),c=s.getSVGBaseline(b),b=s.getSVGBaselineShift(b),a&&(a.setAttribute("dominant-baseline",c),b&&a.setAttribute("baseline-shift",
b)))}m.setTransform(r.multiply(h));return m},_getScaleMatrix:function(a,c){var b=a.width/a.height,d=1,e=1;isNaN(c)||(1<b?(d=c/a.width,e=c/b/a.height):(e=c/a.height,d=c*b/a.width));return{xx:d,yy:e}},_drawMarkers:function(a,c,b,d,e){var h=c.points;a=d.shape||a.createGroup();var g,f,l=h.length,m=[],p=0,k,n=e?e.length:0;a.children[0]&&this._isInvalidShape(b,a.children[0])&&a.clear();for(f=0;f<l;f++){g=h[f];for(k=0;k<n;k++)m[0]=e[k],a.add(this._drawPoint(a,{x:g[0],y:g[1],spatialReference:c.spatialReference},
b,d,m,p++))}c=a.children.length;if(l*e.length<c)for(f=c-1;f>=l*e.length;f--)a.children[f].removeShape();return a},_drawShape:function(a,c,b,d){var e=c.type;b=b.shape;var h=this._projector,g=[],f,l;"extent"===e&&(c=D.fromExtent(c),e=c.type);if("polyline"===e||"polygon"===e){f=0;for(l=d.length;f<l;f++)g=g.concat(h.toScreenPath(c,d[f]));b=this._drawPath(a,b,g);this._rendererLimits&&("polyline"===e?this._clipPolyline(b,c):this._clipPolygon(b,c))}return b},_drawRect:function(a,c,b){return c?c.setShape(b):
a.createRect(b)},_drawImage:function(a,c,b){return c?c.setShape(b):a.createImage(b)},_drawCircle:function(a,c,b){return c?c.setShape(b):a.createCircle(b)},_drawPath:function(a,c,b,d){b=d?b:b.join(" ");return c?c.setShape(b):a.createPath(b)},_drawText:function(a,c,b){return c?c.setShape(b):a.createText(b)},_smsToPath:function(a,c,b,d,e,h,g,f,l){switch(c){case a.STYLE_SQUARE:return["M",e+","+g,h+","+g,h+","+f,e+","+f,"Z"];case a.STYLE_CROSS:return["M",b+","+g,b+","+f,"M",e+","+d,h+","+d];case a.STYLE_X:return["M",
e+","+g,h+","+f,"M",e+","+f,h+","+g];case a.STYLE_DIAMOND:return["M",b+","+g,h+","+d,b+","+f,e+","+d,"Z"];case a.STYLE_TARGET:return["M",e+","+g,h+","+g,h+","+f,e+","+f,e+","+g,"M",e-l+","+d,e+","+d,"M",b+","+(g-l),b+","+g,"M",h+l+","+d,h+","+d,"M",b+","+(f+l),b+","+f]}},_stylePoint:function(a,c,b){var d=c.type,e=c.style;b=null!=b?a.shape&&a.shape.children[b]:a.shape;if(!("shield-label-symbol"===d||"picture-marker-symbol"===d)){var h=s.getStroke(c);c=s.getFill(c);var e=e===q.STYLE_X||e===q.STYLE_CROSS,
g=h&&h.color,f=a.color||(e?g:c);a=a.opacity;f&&null!=a&&(f=this._applyOpacity(f,a));f&&(e?f!==g&&(h=h?v.mixin({},h):{},h.color=f):f!==c&&(c=f));"text-symbol"===d?b.setFill(c):"simple-marker-symbol"===d&&b.setFill(c).setStroke(h)}},_styleMarkers:function(a,c){var b,d=a.shape.children.length;for(b=0;b<d;b++)this._stylePoint(a,c,b)},_styleShape:function(a,c){var b=s.getStroke(c),d=s.getFill(c),e=c.type,h=a.shape,g=a.outlineSize,f=-1!==e.indexOf("line-symbol"),l=f?"none"!==c.style:c.outline&&"none"!==
c.outline.style,m,n,k;g&&Array.isArray(g)&&(g=isFinite(g[0])&&g[0]);g=null!=g?p.pt2px(g):null;if((a.color||null!=a.opacity)&&"picture-fill-symbol"!==e)e=a.color,m=a.opacity,f?(n=e||b&&b.color)&&null!=m&&(n=this._applyOpacity(n,m)):d&&d.toCss&&(k=e||d)&&null!=m&&(k=this._applyOpacity(k,m));h.setStroke(!l||null==g&&!n?b:v.mixin({},b,null!=g?{width:g}:null,n&&{color:n})).setFill(k||d);w&&h.rawNode.setAttribute("vector-effect","non-scaling-stroke")},_applyOpacity:function(a,c){null!=c&&(a=a.clone(),a.a=
c);return a},_updateTransform:function(){var a=this.transform=this.transform||n.create(),c=this.resolution,b=u.fromValues(0.5*this.view.width,0.5*this.view.height),d=u.fromValues(1/c,-1/c),e=u.fromValues(-this.x,-this.y);n.identity(a);n.translate(a,a,b);n.scale(a,a,d);n.translate(a,a,e);a[4]=Math.round(a[4]);a[5]=Math.round(a[5]);this._projector.set({resolution:c,transform:a})}})});