// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("require exports dojo/promise/all dojo/Deferred ../../webgl-engine/lib/TextTextureAtlas ../../webgl-engine/lib/MaterialCollection ../../webgl-engine/materials/HUDMaterial ./Graphics3DWebStyleSymbol ../../../../layers/support/LabelClass ../../lib/glMatrix".split(" "),function(n,k,s,t,u,v,w,p,q,l){var x=l.vec3d;n=function(){function a(){this.hudMaterialCollection=this.textTextureAtlas=null;this.showLabelsChangeOnResume=!1;this.labelClasses=[];this.eventHandles=[];this.graphicsCore=this.layer=
this.layerView=null}a.prototype.initialize=function(g,e,c){var d=this;this.layerView=g;this.layer=e;this.graphicsCore=c;this.layerView.view.labelManager.addSceneServiceLayerView(this);this.eventHandles.push(this.layerView.watch("suspended",function(){return d.suspendedChange()}))};a.prototype.destroy=function(){this.layerView.view.labelManager.removeSceneServiceLayerView(this);this.textTextureAtlas&&(this.textTextureAtlas.dispose(),this.textTextureAtlas=null);this.hudMaterialCollection&&(this.hudMaterialCollection.dispose(),
this.hudMaterialCollection=null);this.labelClasses=null;this.eventHandles.forEach(function(g){return g.remove()});this.graphicsCore=this.layer=this.layerView=this.eventHandles=null};a.prototype.clear=function(){this.layerView.view.labelManager.setDirty();this.textTextureAtlas&&(this.textTextureAtlas.dispose(),this.textTextureAtlas=null);this.hudMaterialCollection&&(this.hudMaterialCollection.dispose(),this.hudMaterialCollection=null)};a.prototype.suspendedChange=function(){!1===this.layerView.suspended&&
this.showLabelsChangeOnResume&&this.showLabelsChange()};a.prototype.initLabelingInfo=function(){var g=this,e=new t;this.layer.then(function(){var c=g.layer.labelingInfo&&g.layer.labelingInfo.filter(function(b){return!!b.symbol});if(c&&0<c.length){g.labelClasses=Array(c.length);for(var d=[],b=function(b){var a=g.graphicsCore.getOrCreateGraphics3DSymbol(c[b].symbol);a.then(function(){var d=g.labelClasses,e=c[b],f;f=a instanceof p?a.graphics3DSymbol:a;d[b]={labelClass:e,graphics3DSymbolLayer:f,graphics3DGraphics:[]}});
d.push(a)},a=0;a<c.length;a++)b(a);s(d).then(function(){e.resolve()})}else e.resolve()});return e.promise};a.prototype.createLabelsForGraphic=function(a,e){if(this.labelClasses&&0<this.labelClasses.length&&e._graphics[0])for(var c=0;c<this.labelClasses.length;c++){var d=this.labelClasses[c];if(q.evaluateWhere(d.labelClass.where,a.attributes)){var b=d.labelClass.getLabelExpression();if(b&&(b=q.buildLabelText(b,a.attributes,this.layer.fields))){var c=d.graphics3DSymbolLayer.childGraphics3DSymbols[0],
f=this.evalLabelPlacementParams(a,e);null==this.textTextureAtlas&&(this.textTextureAtlas=new u(this.layer.id,this.layerView.view._stage),this.hudMaterialCollection=new v(this.layerView.view._stage));if(b=c.createGraphics3DGraphic(a,{text:b,centerOffset:f.centerOffset,translation:f.translation,screenOffset:f.screenOffset,anchor:f.anchor},this.hudMaterialCollection,this.textTextureAtlas))b._labelClass=d.labelClass,e.addLabelGraphic(b),d.graphics3DGraphics.push(e),b.setVisibilityFlag("VISIBILITY_LABEL_SHOW",
this.layerLabelsEnabled()),this.layerView.view.labelManager.setInitialLabelGraphicState(b);break}}}return e};a.prototype.evalLabelPlacementParams=function(a,e){var c=h[this.layer.labelingInfo[0].labelPlacement]||h["default"];if("polygon"===a.geometry.type||"polyline"===a.geometry.type||"extent"===a.geometry.type)return{anchor:"center"};if("point"!==a.geometry.type)return{anchor:c.anchor};var d=e.graphics3DSymbol,b=(d instanceof p?d.graphics3DSymbol:d).symbol.symbolLayers.getItemAt(0),d={screenOffset:[0,
0],centerOffset:[0,0,0,-1],translation:e.getCenterObjectSpace(),anchor:c.anchor};if("Icon"===b.type)if(b=e._graphics[0].getScreenSize(),e.isDraped())d.anchor="center";else{var f=e._graphics[0].stageObject.getGeometryRecords()[0].materials[0];f instanceof w?(f=f.getParams(),d.screenOffset=[b[0]/2*(c.normalizedOffset[0]-2*(f.anchorPos[0]-0.5)),b[1]/2*(c.normalizedOffset[1]-2*(f.anchorPos[1]-0.5))]):d.screenOffset=[b[0]/2*c.normalizedOffset[0],b[1]/2*c.normalizedOffset[1]]}else"Object"===b.type&&(b=
e._graphics[0].getBoundingBoxObjectSpace(),b=[b[3]-b[0],b[4]-b[1],b[5]-b[2]],f=Math.max(b[0],b[1]),d.centerOffset[0]=1.1*f/2*c.normalizedOffset[0],d.translation[2]+=1.1*b[2]/2*c.normalizedOffset[1],b=x.length(b),d.centerOffset[2]=1.1*b/2*c.normalizedOffset[2]);return d};a.prototype.layerLabelsEnabled=function(){return this.layer.labelsVisible};a.prototype.getGraphics3DGraphics=function(){return this.graphicsCore.getGraphics3DGraphics()};a.prototype.getGraphics3DGraphicsKeys=function(){return this.graphicsCore.getGraphics3DGraphicsKeys()};
a.prototype.showLabelsChange=function(){var a=this;if(this.layerView.suspended)this.showLabelsChangeOnResume=!0;else if(this.layerView.loadedGraphics){var e=this.layerLabelsEnabled();this.layerView.loadedGraphics.forEach(function(c){var d=a.graphicsCore.getGraphics3DGraphicById(c.uid);if(d){if(e&&0===d._labelGraphics.length){d=a.createLabelsForGraphic(c,d);for(c=0;c<d._labelGraphics.length;c++){var b=d._labelGraphics[c];b.initialize(a.graphicsCore.labelStageLayer,a.layerView.view._stage)}}for(c=0;c<
d._labelGraphics.length;c++)b=d._labelGraphics[c],b.setVisibilityFlag("VISIBILITY_LABEL_SHOW",e)}});this.layerView.view.labelManager.setDirty();this.showLabelsChangeOnResume=!1}};a.prototype.elevationInfoChange=function(){this.labelClasses&&this.labelClasses.forEach(function(a){a.graphics3DSymbolLayer.layerPropertyChanged("elevationInfo",{})})};return a}();var h={"above-center":{normalizedOffset:[0,1,0],anchor:"bottom"},"above-left":{normalizedOffset:[-1,1,0],anchor:"bottom-right"},"above-right":{normalizedOffset:[1,
1,0],anchor:"bottom-left"},"below-center":{normalizedOffset:[0,-1,2],anchor:"top"},"below-left":{normalizedOffset:[-1,-1,0],anchor:"top-right"},"below-right":{normalizedOffset:[1,-1,0],anchor:"top-left"},"center-center":{normalizedOffset:[0,0,1],anchor:"center"},"center-left":{normalizedOffset:[-1,0,0],anchor:"right"},"center-right":{normalizedOffset:[1,0,0],anchor:"left"}};k={"above-center":["default","esriServerPointLabelPlacementAboveCenter"],"above-left":["esriServerPointLabelPlacementAboveLeft"],
"above-right":["esriServerPointLabelPlacementAboveRight"],"below-center":["esriServerPointLabelPlacementBelowCenter"],"below-left":["esriServerPointLabelPlacementBelowLeft"],"below-right":["esriServerPointLabelPlacementBelowRight"],"center-center":["esriServerPointLabelPlacementCenterCenter"],"center-left":["esriServerPointLabelPlacementCenterLeft"],"center-right":["esriServerPointLabelPlacementCenterRight"]};var r,m;for(m in k)l=k[m],r=h[m],l.forEach(function(a){h[a]=r});Object.freeze&&(Object.freeze(h),
Object.keys(h).forEach(function(a){Object.freeze(h[a]);Object.freeze(h[a].normalizedOffset)}));return n});