// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("require exports ../../../../core/watchUtils ../../../../core/arrayUtils ../../../../core/Error ../../../../core/Logger ../../../../core/promiseUtils ../../support/projectionUtils ../../../../renderers/support/rendererConversion ../../../../geometry/Point ../../../../geometry/Extent ../../webgl-engine/Stage ../../webgl-engine/lib/Util ../../webgl-engine/lib/Layer ../../webgl-engine/lib/FloatingBoxLocalOriginFactory ../../../../symbols/WebStyleSymbol ../../../../symbols/support/symbolConversion ../../lib/glMatrix ./Graphics3DGraphic ./Graphics3DSymbol ./Graphics3DWebStyleSymbol ./graphicUtils ../../support/aaBoundingBox ../../support/mathUtils dojo/Deferred".split(" "),
function(u,Q,r,B,v,C,D,p,E,F,G,s,w,x,H,I,y,z,J,K,L,M,A,n,N){u=z.vec3d;var q=new F,t=u.create(),O=C.getLogger("esri.views.3d.LayerView3D"),P=function(){return function(){this.localOriginFactory=this.layer=this.overlaySR=this.renderCoordsHelper=this.renderSpatialReference=this.clippingExtent=this.layerOrder=this.stage=this.renderer=this.elevationProvider=this.streamDataSupplier=this.sharedResources=null}}();return function(){function c(){this.graphics={};this.graphicsDrapedIds={};this.graphicsBySymbol=
{};this.graphicsKeys=[];this.symbols={};this.computedExtent=null;this.symbolCreationContext=new P;this.hasDraped=!1;this.updatingGraphicIds={};this.graphicTransformFunc=this.onComputedExtentChange=this.stage=this.labelStageLayer=this.stageLayer=this.tilingSchemeHandle=null;this.eventHandles=[];this.labeling=this.spatialIndex=this.scaleVisibility=this.elevation=this.layer=this.layerView=this.viewSR=null;this.whenGraphics3DGraphicRequests={}}c.prototype.initialize=function(a,b,d,h,e,f,k,g,l){var m=
this;this.layerView=a;this.layer=b;this.viewSR=a.view.spatialReference;this.elevation=d;this.scaleVisibility=h;this.spatialIndex=e;this.labeling=f;this.onComputedExtentChange=k;this.graphicTransformFunc=g;this.initializeStage(this.layerView.view,this.layer.id);this.symbolCreationContext.sharedResources=this.layerView.view.sharedSymbolResources;this.symbolCreationContext.renderer=this.layer.renderer;this.symbolCreationContext.stage=this.stage;this.symbolCreationContext.streamDataSupplier=this.layerView.view.sharedSymbolResources.streamDataSupplier;
this.symbolCreationContext.renderSpatialReference=this.layerView.view.renderSpatialReference;this.symbolCreationContext.renderCoordsHelper=this.layerView.view.renderCoordsHelper;this.symbolCreationContext.layer=this.layer;this.symbolCreationContext.layerView=this.layerView;this.symbolCreationContext.layerOrder=0;this.symbolCreationContext.localOriginFactory=c.createLocalOriginFactory();this.symbolCreationContext.elevationProvider=l;this.tilingSchemeHandle=r.when(l,"tilingScheme",function(a){a.spatialReference.equals(m.symbolCreationContext.overlaySR)||
(m.symbolCreationContext.overlaySR=l.spatialReference,m.recreateAllGraphics())});this.eventHandles.push(this.layerView.watch("suspended",function(){return m.suspendedChange()}));this.eventHandles.push(r.on(a,"loadedGraphics","change",function(a){return m.graphicsCollectionChanged(a)},function(){m.clearSymbolsAndGraphics();m.graphicsCollectionChanged({added:m.layerView.loadedGraphics.toArray(),removed:[]})}));this.validateRenderer(this.layer.renderer)};c.prototype.destroy=function(){var a=this;this.clear();
if(this.stage){var b=[this.stageLayer.getId()];this.labelStageLayer&&b.push(this.labelStageLayer.getId());this.stage.removeFromViewContent(b);b.forEach(function(b){return a.stage.remove(s.ModelContentType.LAYER,b)});this.stage=this.labelStageLayer=this.stageLayer=null}this.tilingSchemeHandle&&(this.tilingSchemeHandle.remove(),this.tilingSchemeHandle=null);this.eventHandles.forEach(function(a){return a.remove()});this.layerView=this.labeling=this.scaleVisibility=this.viewSR=this.onComputedExtentChange=
this.eventHandles=null;for(var d in this.whenGraphics3DGraphicRequests)this.whenGraphics3DGraphicRequests[d].reject(new v("graphic:layer-destroyed","Layer has been destroyed"));this.whenGraphics3DGraphicRequests=null};c.prototype.clear=function(){var a=!1,b;for(b in this.graphics){var d=this.graphics[b];d&&(a=a||d.isDraped(),d.destroy())}this.graphics={};this.graphicsKeys=null;for(var h in this.symbols)(b=this.symbols[h])&&b.destroy();this.symbols={};this.graphicsBySymbol={};this.hasDraped=!1;a&&
this.layerView._notifyDrapedDataChange()};c.prototype.initializeStage=function(a,b){this.stage=a._stage;this.stageLayer=new x(b,{state:this.layerView.suspended?"HIDDEN":"VISIBLE"},b);this.stage.add(s.ModelContentType.LAYER,this.stageLayer);var d=[this.stageLayer.getId()];this.labeling&&(this.labelStageLayer=new x(b,{state:this.layerView.suspended?"HIDDEN":"IGNORED"},b+"_labels"),this.stage.add(s.ModelContentType.LAYER,this.labelStageLayer),d.push(this.labelStageLayer.getId()));this.stage.addToViewContent(d)};
c.prototype.setDrawingOrder=function(a){this.symbolCreationContext.layerOrder=a;var b={},d={},h;for(h in this.graphics)this.graphics[h].setDrawOrder(a,b,d);for(var e in d)this.symbols[e].setDrawOrder(a,b);w.objectEmpty(b)||(this.stage.getTextureGraphicsRenderer().updateRenderOrder(b),this.layerView._notifyDrapedDataChange())};c.prototype.suspendedChange=function(){!0===this.layerView.suspended?(this.stageLayer.setState("HIDDEN"),this.labelStageLayer&&this.labelStageLayer.setState("HIDDEN"),this.hideAllGraphics()):
!1===this.layerView.suspended&&(this.stageLayer.setState("VISIBLE"),this.labelStageLayer&&this.labelStageLayer.setState("IGNORED"),this.updateAllGraphicsVisibility())};c.prototype.getGraphics3DGraphics=function(){return this.graphics};c.prototype.getGraphics3DGraphicById=function(a){return this.graphics[a]};c.prototype.getGraphics3DGraphicsKeys=function(){null===this.graphicsKeys&&(this.graphicsKeys=Object.keys(this.graphics));return this.graphicsKeys};c.prototype.numNodesUpdating=function(){return Object.keys(this.updatingGraphicIds).length};
c.prototype.whenGraphics3DGraphic=function(a){var b=this.graphics[a.uid];if(b)return D.resolve(b);b=this.whenGraphics3DGraphicRequests[a.uid];b||(b=new N,this.whenGraphics3DGraphicRequests[a.uid]=b);return b.promise};c.prototype.boundsForGraphics3DGraphic=function(a,b){void 0===b&&(b=A.create());var d=this.layerView.view.spatialReference,h=this.layerView.view.renderSpatialReference,e=this.layerView.view.basemapTerrain.spatialReference,f=a.getProjectedBoundingBox(function(a,b,e){return p.bufferToBuffer(a,
h,b,a,d,b,e)},function(a,b,h){return p.bufferToBuffer(a,e,b,a,d,b,h)},b);if(!f)return null;var c=a.isDraped(),g=this.symbolCreationContext.elevationProvider;c&&g&&(A.center(f,t),q.x=t[0],q.y=t[1],q.z=void 0,q.spatialReference=d,c=g.getElevation(q)||0,f[2]=Math.min(f[2],c),f[5]=Math.max(f[5],c));return f};c.prototype.whenGraphicBounds=function(a){var b=this;return r.whenOnce(this.layerView,"loadedGraphics").then(function(){if(b.layerView.loadedGraphics.some(function(b){return b===a}))return b.whenGraphics3DGraphic(a);
throw new v("internal:graphic-not-part-of-view","Graphic is not part of this view");}).then(function(a){return b.boundsForGraphics3DGraphic(a)})};c.prototype.graphicsCollectionChanged=function(a){var b=this.graphicTransformFunc?this.graphicTransformFunc(a.added):a.added;this.add(b);this.remove(a.removed)};c.prototype.graphicUpdateHandler=function(a){var b=this.graphics[a.graphic.uid];if(b)switch(a.property){case "visible":b.setVisibilityFlag("VISIBILITY_GRAPHIC",a.newValue)&&(b.isDraped()&&this.layerView._notifyDrapedDataChange(),
this.labeling&&this.layerView.view.labelManager.setDirty())}};c.prototype.beginGraphicUpdate=function(a){this.updatingGraphicIds[a.uid]=!0;this.layerView.get("symbols-updating")||this.layerView.set("symbols-updating",!0);this.layerView._evaluateUpdatingState()};c.prototype.endGraphicUpdate=function(a){a&&delete this.updatingGraphicIds[a.uid];this.layerView.get("symbols-updating")&&w.objectEmpty(this.updatingGraphicIds)&&(this.layerView.view.flushDisplayModifications(),this.layerView.set("symbols-updating",
!1));this.layerView._evaluateUpdatingState()};c.prototype.expandComputedExtent=function(a){var b,d,h,e,f,k;if("point"===a.type)b=d=a.x,h=e=a.y,a.z&&(f=k=a.z);else if("polygon"===a.type||"polyline"===a.type||"multipoint"===a.type){k=a.extent;if(!k)return;b=k.xmin;d=k.xmax;h=k.ymin;e=k.ymax;f=k.zmin;k=k.zmax}var g=this.viewSR,l=c.tmpVec;!a.spatialReference.equals(g)&&p.xyzToVector(b,h,0,a.spatialReference,l,g)&&(b=l[0],h=l[1],p.xyzToVector(d,e,0,a.spatialReference,l,g),d=l[0],e=l[1]);n.isFinite(b)&&
(n.isFinite(d)&&n.isFinite(h)&&n.isFinite(e))&&((g=this.computedExtent)?(g.xmin=Math.min(b,g.xmin),g.xmax=Math.max(d,g.xmax),g.ymin=Math.min(h,g.ymin),g.ymax=Math.max(e,g.ymax)):this.computedExtent=g=new G(b,h,d,e,a.spatialReference),n.isFinite(f)&&!n.isFinite(k)&&(g.zmin=null!=g.zmin?Math.min(f,g.zmin):f,g.zmax=null!=g.zmax?Math.max(k,g.zmax):k),this.onComputedExtentChange&&this.onComputedExtentChange())};c.prototype.updateHasDraped=function(){this.hasDraped=!1;for(var a in this.graphicsDrapedIds)if(this.graphicsDrapedIds.hasOwnProperty(a)){this.hasDraped=
!0;break}};c.prototype.elevationInfoChange=function(){this.labeling&&this.labeling.elevationInfoChange();for(var a in this.graphicsBySymbol){var b=this.symbols[a],d=this.graphicsBySymbol[a];if(!b||!b.layerPropertyChanged("elevationInfo",d))this.recreateSymbol(a);else for(var h in d)for(var e=d[h],b=e.graphic,e=e._labelGraphics,c=0;c<e.length;c++){var k=e[c];k.graphics3DSymbolLayer.updateGraphicElevationInfo(b,k)}}};c.prototype.clearSymbolsAndGraphics=function(){this.clear();this.elevation&&this.elevation.clear();
this.labeling&&this.labeling.clear()};c.prototype.recreateAllGraphics=function(){this.clearSymbolsAndGraphics();this.computedExtent=null;this.onComputedExtentChange&&this.onComputedExtentChange();this.layerView.loadedGraphics&&this.layerView.view.basemapTerrain.tilingScheme&&this.add(this.layerView.loadedGraphics.toArray())};c.prototype.recreateSymbol=function(a){var b=this.graphicsBySymbol[a],d=[],h=!1,e;for(e in b){var c=b[e];c.isDraped()&&(delete this.graphicsDrapedIds[e],h=!0);d.push(c.graphic);
c.destroy();this.graphics[e]=null}this.graphicsBySymbol[a]={};(b=this.symbols[a])&&b.destroy();this.symbols[a]=void 0;this.updateHasDraped();h&&this.layerView._notifyDrapedDataChange();this.add(d)};c.prototype.add=function(a){if(this.layerView.view.basemapTerrain&&this.layerView.view.basemapTerrain.tilingScheme){for(var b=a.length,d=Array(b),h=Array(b),c=Array(b),f=0;f<b;f++){var k=a[f],g=k.geometry;if(g&&(this.expandComputedExtent(g),(g=this.layerView.getRenderingInfo?this.layerView.getRenderingInfo(k):
{symbol:k.symbol})&&g.symbol))if(h[f]=g.symbol,c[f]=g,g=this.getOrCreateGraphics3DSymbol(h[f],g.renderer))d[f]=g,this.beginGraphicUpdate(k)}for(f=0;f<b;f++)this.waitForSymbol(d[f],h[f],a[f],c[f])}};c.prototype.waitForSymbol=function(a,b,d,c){var e=this;a&&a.then(function(){e.graphicsBySymbol[b.id]||(e.graphicsBySymbol[b.id]={});e.createGraphics3DGraphic(a,d,c);e.endGraphicUpdate(d);e.labeling&&e.layerView.view.labelManager.setDirty()},function(){e.endGraphicUpdate(d)})};c.prototype.remove=function(a){for(var b=
!1,d=a.length,c=0;c<d;c++){var e=a[c].uid,f=this.graphics[e];if(f){f.isDraped()&&(delete this.graphicsDrapedIds[e],b=!0);var k=f.graphics3DSymbol.symbol.id;f.destroy();delete this.graphics[e];delete this.graphicsBySymbol[k][e];this.graphicsKeys=null}}this.updateHasDraped();b&&this.layerView._notifyDrapedDataChange();this.labeling&&this.layerView.view.labelManager.setDirty()};c.prototype.createGraphics3DSymbol=function(a,b){var d=y.to3D(a,!0,!1);if(d.symbol){var c=void 0;if(b&&b.backgroundFillSymbol){var e=
y.to3D(b.backgroundFillSymbol,!1,!0);e.symbol&&(c=e.symbol.symbolLayers)}return new K(d.symbol,this.symbolCreationContext,c)}return null};c.prototype.getOrCreateGraphics3DSymbol=function(a,b){var d=this,c=this.symbols[a.id];void 0===c&&(c=a instanceof I?new L(a,function(a){return d.createGraphics3DSymbol(a,b)}):this.createGraphics3DSymbol(a,b),this.symbols[a.id]=c);return c};c.prototype.createGraphics3DGraphic=function(a,b,d){if(!this.graphics[b.uid]&&(d=a.createGraphics3DGraphic(b,d),this.labeling&&
this.labeling.layerLabelsEnabled()&&(d=this.labeling.createLabelsForGraphic(b,d)),this.graphics[b.uid]=d,this.graphicsKeys=null,this.graphicsBySymbol[a.symbol.id][b.uid]=d,d.initialize(this.stageLayer,this.labelStageLayer,this.stage),d.isDraped()&&(this.hasDraped=this.graphicsDrapedIds[b.uid]=!0,this.layerView._notifyDrapedDataChange()),d.centroid=null,"point"!==b.geometry.type&&d instanceof J&&(d.centroid=M.computeCentroid(b.geometry,this.viewSR)),a=this.scaleVisibility&&this.scaleVisibility.scaleRangeActive(),
this.spatialIndex&&this.spatialIndex.shouldAddToSpatialIndex(b,d,a)&&this.spatialIndex.addGraphicToSpatialIndex(b,d),a&&this.scaleVisibility.updateGraphicScaleVisibility(b,d),d.setVisibilityFlag("VISIBILITY_GRAPHIC",b.visible&&!this.layerView.suspended),a=this.whenGraphics3DGraphicRequests[b.uid]))a.resolve(d),delete this.whenGraphics3DGraphicRequests[b.uid]};c.prototype.rendererChange=function(a){this.validateRenderer(a);this.symbolCreationContext.renderer=a;this.recreateAllGraphics()};c.prototype.opacityChange=
function(){var a=!1,b;for(b in this.graphicsBySymbol){var d=this.graphicsBySymbol[b];this.symbols[b].layerPropertyChanged("opacity");if(!a)for(var c in d)if(d[c].isDraped()){this.layerView._notifyDrapedDataChange();a=!0;break}}};c.prototype.setClippingExtent=function(a,b){var d=this.symbolCreationContext.clippingExtent,c=[];p.extentToBoundingRect(a,c,b)?this.symbolCreationContext.clippingExtent=[c[0],c[1],-Infinity,c[2],c[3],Infinity]:this.symbolCreationContext.clippingExtent=null;return!B.equals(this.symbolCreationContext.clippingExtent,
d)};c.prototype.updateAllGraphicsVisibility=function(){var a=this;if(this.layerView.loadedGraphics){var b=!1;this.layerView.loadedGraphics.forEach(function(d){var c=a.getGraphics3DGraphicById(d.uid);if(c){var e=c.setVisibilityFlag("VISIBILITY_GRAPHIC",d.visible);a.scaleVisibility&&(d=a.scaleVisibility.updateGraphicScaleVisibility(d,c),e=e||d);e&&c.isDraped()&&(b=!0)}});b&&this.layerView._notifyDrapedDataChange();this.layerView.view.labelManager.setDirty()}};c.prototype.hideAllGraphics=function(){var a=
this;if(this.layerView.loadedGraphics){var b=!1;this.layerView.loadedGraphics.forEach(function(c){(c=a.getGraphics3DGraphicById(c.uid))&&c.setVisibilityFlag("VISIBILITY_GRAPHIC",!1)&&c.isDraped()&&(b=!0)});b&&this.layerView._notifyDrapedDataChange();this.layerView.view.labelManager.setDirty()}};c.prototype.validateRenderer=function(a){(a=E.validateTo3D(a))&&O.warn("Renderer for layer '"+(this.layer.title?this.layer.title+", ":"")+", id:"+this.layer.id+"' is not supported in a SceneView",a.message)};
c.createLocalOriginFactory=function(){return new H(5E6,16)};c.tmpVec=z.vec3d.create();return c}()});