// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define(["require","exports"],function(r,s){return function(){function c(){this._scaleRangeActive=!1;this.layerScaleRangeVisibilityDirty=this.layerScaleRangeVisibility=!0;this.layerScaleRangeVisibilityQuery=!1;this.basemapTerrain=this.graphicsCore=this.extent=this.spatialIndex=this.layer=this.layerView=this.scaleChangeEventHandle=null}c.prototype.initialize=function(a,b,d,c,m){this.layerView=a;this.layer=b;this.spatialIndex=d;this.graphicsCore=c;this._scaleRangeActive=null!==b.minScale&&0<b.minScale&&
8E7>b.minScale||1E3<b.maxScale;this.basemapTerrain=m;this.layerMinMaxScaleChangeHandler(!1)};c.prototype.destroy=function(){this.scaleChangeEventHandle&&(this.scaleChangeEventHandle.remove(),this.scaleChangeEventHandle=null);this.graphicsCore=this.spatialIndex=this.extent=this.layerView=null};c.prototype.needsIdleUpdate=function(){return this.layerView.view.basemapTerrain&&this.layerScaleRangeVisibilityDirty};c.prototype.canResume=function(){return this.layerScaleRangeVisibility};c.prototype.setExtent=
function(a){this.extent=a;this.layerScaleRangeVisibilityDirty=!0};c.prototype.idleUpdate=function(a){this.layerView.view.basemapTerrain&&(!a.done()&&this.layerScaleRangeVisibilityDirty)&&(this.updateSuspendScaleVisible(),this.layerScaleRangeVisibilityDirty=!1)};c.prototype.scaleRangeActive=function(){return this._scaleRangeActive};c.prototype.updateSuspendScaleVisibleFinish=function(a){this.layerScaleRangeVisibilityQuery=!1;this.layerScaleRangeVisibility!==a&&(this.layerScaleRangeVisibility=a,this.layerView._notifySuspendedChange())};
c.prototype.updateSuspendScaleVisible=function(){var a=this,b=this.layerView.view.basemapTerrain;!this.extent||!b||!this._scaleRangeActive?this.updateSuspendScaleVisibleFinish(!0):this.layerScaleRangeVisibilityQuery||(this.layerScaleRangeVisibilityQuery=!0,b.queryVisibleScaleRange(this.extent,this.layer.minScale,this.layer.maxScale,function(b){return a.updateSuspendScaleVisibleFinish(b)}))};c.prototype.visibleAtScale=function(a){var b=this.layer.minScale;return a>this.layer.maxScale&&(!b||a<b)};c.prototype.visibleAtScaleLabel=
function(a,b){return a>b.maxScale&&(!b.minScale||a<b.minScale)};c.prototype.graphicVisible=function(a,b){var d;b.centroid?d=b.centroid:"point"===a.geometry.type&&(d=a.geometry);return d?(d=this.layerView.view.basemapTerrain?this.layerView.view.basemapTerrain.getScale(d):1,this.visibleAtScale(d)):!0};c.prototype.updateGraphicScaleVisibility=function(a,b){if(this._scaleRangeActive&&b.addedToSpatialIndex){var d=this.graphicVisible(a,b);return b.setVisibilityFlag("VISIBILITY_SCALERANGE",d)}return!1};
c.prototype.scaleUpdateHandler=function(a){var b=this;if(!this.layerView.suspended&&this.spatialIndex.hasGraphics()){var d=a.extent,c=a.scale;this.spatialIndex.intersects(d,a.spatialReference,function(a,n){for(var p=b.visibleAtScale(c),l=!1,h=0;h<n;h++){var f=b.graphicsCore.getGraphics3DGraphicById(a[h]);if(f){var e=f.centroid;if(!e||!(d[0]>e.x||d[1]>e.y||d[2]<e.x||d[3]<e.y)){for(var e=f.setVisibilityFlag("VISIBILITY_SCALERANGE",p),k=0;k<f._labelGraphics.length;k++){var g=f._labelGraphics[k];if(g._labelClass&&
null!=g._labelClass.minScale&&null!=g._labelClass.maxScale)var q=b.visibleAtScaleLabel(c,g._labelClass),e=e||g.setVisibilityFlag("VISIBILITY_SCALERANGE_LABEL",q)}e&&b.layerView.view.labelManager.setDirty();e&&f.isDraped()&&(l=!0)}}}l&&b.layerView._notifyDrapedDataChange()})}this.layerScaleRangeVisibilityDirty=!0};c.prototype.layerMinMaxScaleChangeHandler=function(a){var b=this;void 0===a&&(a=!0);var c=this.layer;(this._scaleRangeActive=null!==c.minScale&&0<c.minScale&&8E7>c.minScale||1E3<c.maxScale)&&
!this.scaleChangeEventHandle?(this.scaleChangeEventHandle=this.basemapTerrain.on("scale-change",function(a){return b.scaleUpdateHandler(a)}),this.layerView.suspended||this.spatialIndex.addGraphicsToSpatialIndex(this._scaleRangeActive)):!this._scaleRangeActive&&this.scaleChangeEventHandle&&(this.scaleChangeEventHandle.remove(),this.scaleChangeEventHandle=null);!this.layerView.suspended&&a&&this.graphicsCore.updateAllGraphicsVisibility();this.layerScaleRangeVisibilityDirty=!0};return c}()});