// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("../../../../core/declare ../../../../Color ./Graphics3DSymbolLayer ./Graphics3DGraphicLayer ./ElevationAligners ./Graphics3DSymbolCommonCode ./graphicUtils ../i3s/I3SSymbolLoader ../../lib/glMatrix ../../webgl-engine/Stage ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/GeometryUtil ../../webgl-engine/materials/Material ../../webgl-engine/lib/Util".split(" "),function(E,A,F,v,w,q,G,H,B,n,I,h,J,K){var L=K.assert,r=B.mat4d,C=B.vec3d,s=[1,1,1],M=[10,10,10],D=[n.ModelContentType.MATERIAL,
n.ModelContentType.TEXTURE,n.ModelContentType.GEOMETRY];return E([F],{_prepareResources:function(){var a=this.symbol,c=this._getStageIdHint();a.resource&&a.resource.href?this._prepareModelResources(a.resource.href,c):this._preparePrimitiveResources(a.resource?a.resource.primitive:"sphere",c)},_sizeToScale:function(a,c,b,d){for(var e=Array(3),f=2;0<=f;f--){var g=a[f];null!==g&&isFinite(g)?e[f]=g/(c[f+3]-c[f]):e[f]="symbolValue"===g?b?b[f]:1:null}a=d;c=0;for(f=2;0<=f;f--)g=e[f],null!==g&&(a=g,c=Math.max(c,
Math.abs(g)));for(f=2;0<=f;f--)null===e[f]?e[f]=a:0===e[f]&&(e[f]=0.0010*c);return e},_computeSymbolScale:function(a,c){var b=[a.width,a.depth,a.height];return b[0]||b[1]||b[2]?this._sizeToScale(b,c,null,1):null},_preparePrimitiveResources:function(a,c){var b=this.symbol;if("sphere"===a)this._geometryData=h.createPolySphereGeometry(0.5,2,!0),this._geometryOrigin="center";else if("cube"===a)this._geometryData=h.createBoxGeometry(1),this._geometryOrigin="center";else if("cylinder"===a)this._geometryData=
h.createCylinderGeometry(1,0.5,16,[0,0,1],[0,0,0.5]),this._geometryOrigin="bottom";else if("cone"===a)0>b.height?(this._geometryData=h.createConeGeometry(1,0.5,15,!0),b.height=-b.height):this._geometryData=h.createConeGeometry(1,0.5,15,!1),h.cgToGIS(this._geometryData),this._geometryOrigin="bottom";else if("tetrahedron"===a)this._geometryData=h.createTetrahedronGeometry(1),h.cgToGIS(this._geometryData),this._geometryOrigin="bottom";else if("diamond"===a)this._geometryData=h.createDiamondGeometry(1),
h.cgToGIS(this._geometryData),this._geometryOrigin="center";else{console.warn("Unknown object symbol primitive: "+a);this.reject();return}this._geometry=new I(this._geometryData,c);this._context.stage.add(n.ModelContentType.GEOMETRY,this._geometry);var d=[-0.5,-0.5,-0.5,0.5,0.5,0.5];this._symbolScale=this._computeSymbolScale(b,d);this._boundingBox=d;d=this._getMaterialOpacity();d={specular:[0,0,0],shininess:3,opacity:d,transparent:1>d||this._isPropertyDriven("opacity"),instanced:this._hasPerInstanceColor()?
["transformation","color"]:["transformation"]};this._isPropertyDriven("color")?(d.ambient=s,d.diffuse=s):(b=b.material?A.toUnitRGB(b.material.color):s,d.ambient=b,d.diffuse=b);this._material=new J(d,c+"_objectmat");this._context.stage.add(n.ModelContentType.MATERIAL,this._material);this.resolve()},_prepareModelResources:function(a,c){var b={materialParamsMixin:{instanced:this._hasPerInstanceColor()?["transformation","color"]:["transformation"]},idHint:c};(new H(this._context.streamDataSupplier)).fetchSymbol(a,
b).then(function(a){if(!this.isRejected()){var b=a.stageResources,c=this._context.stage,g=this.symbol.material,x;this._isPropertyDriven("color")?x={ambient:s,diffuse:s}:g&&g.color&&(g=A.toUnitRGB(g.color),x={ambient:g.map(function(a){return a/1.5}),diffuse:g});var l=this._computeModelOpacityOverride();a.originalMaterialOpacities=Array(b[n.ModelContentType.MATERIAL].length);b[n.ModelContentType.MATERIAL].forEach(function(b,c){var e=b.getParameterValues();a.originalMaterialOpacities[c]=e.opacity;x&&
b.setParameterValues(x);l.overwrite?b.setParameterValues({opacity:l.overwrite,transparent:l.blendingRequired}):null!=l.multiply&&(e.opacity*=l.multiply,e.transparent=1>e.opacity,b.setParameterValues({opacity:e.opacity,transparent:e.transparent}))});D.forEach(function(a){for(var d=b[a],g=0;d&&g<d.length;g++)c.add(a,d[g])});for(var k=b[n.ModelContentType.GEOMETRY],g=a.geometryTransformations,p=[Number.MAX_VALUE,Number.MAX_VALUE,Number.MAX_VALUE,-Number.MAX_VALUE,-Number.MAX_VALUE,-Number.MAX_VALUE],
h=[0,0,0],t=[0,0,0],u=0;u<k.length;u++)for(var q=k[u],z=0,v=q.getNumGroups();z<v;++z){var m=q.getBoundingInfo(z);r.multiplyVec3(g[u],m.getBBMin(),h);r.multiplyVec3(g[u],m.getBBMax(),t);for(m=0;3>m;++m){if(h[m]>t[m]){var w=h[m];h[m]=t[m];t[m]=w}p[m]=Math.min(p[m],h[m]);p[m+3]=Math.max(p[m+3],t[m])}}this._boundingBox=p;this._symbolScale=this._computeSymbolScale(this.symbol,p);C.scale(a.pivotOffset,-1);k=g.length;for(p=0;p<k;p++)r.translate(g[p],a.pivotOffset);C.scale(a.pivotOffset,-1);this._i3sModel=
a;this.resolve()}}.bind(this),function(){this.reject()}.bind(this))},_computeModelOpacityOverride:function(){var a={overwrite:null,blendingRequired:!1,multiply:null},c=this._getMaterialOpacity();this._isPropertyDriven("opacity")?(a.overwrite=c,a.blendingRequired=!0):this.symbol.material&&void 0!==this.symbol.material.transparency?(a.overwrite=c,a.blendingRequired=1>a.overwrite):1>c&&(a.multiply=c,a.blendingRequired=!0);return a},destroy:function(){this.isFulfilled()||this.reject();var a=this._context.stage;
if(this._i3sModel){var c=this._i3sModel.stageResources;D.forEach(function(b){for(var d=c[b],e=0;d&&e<d.length;e++)a.remove(b,d[e].getId())})}else this._material&&a.remove(n.ModelContentType.MATERIAL,this._material.getId()),this._geometry&&a.remove(n.ModelContentType.GEOMETRY,this._geometry.getId())},createGraphics3DGraphic:function(a,c){var b=a.geometry;if("polyline"===b.type)b=q.placePointOnPolyline(b);else if("polygon"===b.type)b=q.placePointOnPolygon(b);else if("extent"===b.type)b=b.get("center");
else if("point"!==b.type)return this._logWarning("unsupported geometry type for object symbol: "+b.type),null;var d="graphic"+a.uid,e=this._getGraphicElevationInfo(a);return this._createAs3DShape(a,b,c,e,d,a.uid)},layerPropertyChanged:function(a,c,b){if("opacity"===a){if(this._i3sModel){var d=this._computeModelOpacityOverride();this._i3sModel.stageResources[n.ModelContentType.MATERIAL].forEach(function(a,b){if(d.overwrite)a.setParameterValues({opacity:d.overwrite,transparent:d.blendingRequired});
else{var c=this._i3sModel.originalMaterialOpacities[b];null!=d.multiply&&(c*=d.multiply);a.setParameterValues({opacity:c,transparent:1>c})}}.bind(this))}else c=this._getMaterialOpacity(),this._material.setParameterValues({opacity:c,transparent:1>c||this._isPropertyDriven("opacity")});return!0}if("elevationInfo"===a){this._updateElevationInfo();a=this._context.elevationProvider;var e=this._context.renderCoordsHelper,f=w.perObjectElevationAligner,g=q.ELEV_MODES.ABSOLUTE_HEIGHT,h;for(h in c){var l=c[h],
k=l._graphics[b];k&&(l=this._getGraphicElevationInfo(l.graphic),k.elevationAligner=l.mode!==g?f:null,k.elevationInfo.set(l),f(k,a,e))}return!0}return!1},_createAs3DShape:function(a,c,b,d,e,f){a=this._hasPerInstanceColor()?{color:G.mixinColorAndOpacity(b.color,b.opacity)}:null;var g=this._computeObjectScale(b,!this._i3sModel),h=this._context.layer.id;if(this._i3sModel){var l=this._i3sModel.stageResources[n.ModelContentType.GEOMETRY],k=this._i3sModel.materialsByComponent,p=this._i3sModel.geometryTransformations;
e=q.createStageObjectForPoint.call(this,c,null,null,null,null,d,e,h,f);if(null===e)return null;for(f=0;f<l.length;f++){h=r.identity();this._applyObjectRotation(b,this.symbol,h);g&&r.scale(h,g);r.multiply(h,p[f]);for(var s=k[f],t=s.length,u=Array(t),y=0;y<t;y++)u[y]=a;e.addGeometry(l[f],s,h,u)}}else k=this.symbol,"bottom"===k.anchor&&"center"===this._geometryOrigin?l=[0,0,0.5]:"center"===k.anchor&&"bottom"===this._geometryOrigin&&(l=[0,0,-0.5]),k=r.identity(),this._applyObjectRotation(b,this.symbol,
k),g&&r.scale(k,g),l&&r.translate(k,l),e=q.createStageObjectForPoint.call(this,c,[this._geometry],[[this._material]],[k],[a],d,e,h,f);if(null===e)return null;e.setCastShadow(!0);b=null;d.mode!==q.ELEV_MODES.ABSOLUTE_HEIGHT&&(b=w.perObjectElevationAligner);d=new v(this,e,null,null,null,b,d,v.VisibilityModes.REMOVE_OBJECT);q.extendPointGraphicElevationInfo(d,c,this._context.elevationProvider);return d},_computeObjectScale:function(a,c){var b;a.size&&this._isPropertyDriven("size")?(b=this._sizeToScale(a.size,
this._boundingBox,this._symbolScale,null),L(null!=b[0],"sizeInfo has no values")):b=this._symbolScale?this._symbolScale.slice(0):c?M.slice(0):[1,1,1];for(var d=this._context.renderCoordsHelper.unitInMeters,e=2;0<=e;e--)b[e]/=d;return 1!==b[0]||1!==b[1]||1!==b[2]?b:null},_applyObjectRotation:function(a,c,b){a=(a.rotationAngle||0)+(c.heading||0);return 0!==a?r.rotateZ(b,-a/180*Math.PI,b):null},_hasPerInstanceColor:function(){return this._isPropertyDriven("color")||this._isPropertyDriven("opacity")}})});