// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("./terrainUtils ./TileUtils ./TerrainConst ./TileGeometryFactory ./UpsampleInfo ./ElevationData ../support/mathUtils ../lib/glMatrix ../../../core/arrayUtils".split(" "),function(e,x,g,D,E,F,y,u,z){function A(a){this.waitingAgents=[];this.init(a)}var l=u.vec3d,r=u.vec2d,v=u.vec4d,G=u.mat4d,B=e.weakAssert,w=l.create(),f=v.create(),s=v.create(),H=l.create(),p={},t=g.LayerClass.LAYER_CLASS_COUNT,I=g.LayerClass.MAP,n=g.LayerClass.ELEVATION,q=g.TileUpdateTypes;e=function(a,b,c){this.lij=[0,0,0];
this.extent=v.create();this.extentWGS84Rad=v.create();this.centerAtSeaLevel=l.create();this.center=l.create();this.tileUp=H;this.elevationBounds=r.create();this.children=[null,null,null,null];this.layerInfo=Array(t);this.intersectsClippingArea=this.isWithinClippingArea=!0;this.clippingArea=null;this._maxTesselation=0};e.prototype.init=function(a,b,c,d){this.lij[0]=a[0];this.lij[1]=a[1];this.lij[2]=a[2];d.getExtent(a[0],a[1],a[2],this.extent,this.extentWGS84Rad);this.intersectsClippingArea=this.isWithinClippingArea=
!0;this.clippingArea=null;this.radius=this.edgeLen=0;this.vlevel=a?a[0]:0;b&&b.elevationBounds?r.set(b.elevationBounds,this.elevationBounds):r.set2(0,0,this.elevationBounds);this.parent=b;for(a=0;4>a;a++)this.children[a]=null;this.pendingUpdates=0;this.renderData=null;this.renderOrder=this.screenDepth=0;this.visible=!1;this.parentSurface=c;for(a=0;a<t;a++)if(c){b=c.numLayers(a);var m;this.layerInfo[a]?(m=this.layerInfo[a],m.length=b):(m=Array(b),this.layerInfo[a]=m);for(var e=0;e<b;e++)m[e]=C(a,m[e]),
a==n&&this.findElevationBoundsForLayer(e,-1)}else this.layerInfo[a]=null;this.computeElevationBounds();this._maxTesselation=Math.min(d.pixelSize[0],g.MAX_TILE_TESSELATION)};e.prototype.dispose=function(){for(var a=0;a<t;a++)for(var b=this.layerInfo[a],c=0;c<b.length;c++){var d=b[c];d.upsampleFromTile&&(E.Pool.release(d.upsampleFromTile),d.upsampleFromTile=null)}};e.prototype.updateScreenDepth=function(a){l.set(this.center,s);s[3]=1;G.multiplyVec4(a,s,s);this.screenDepth=s[2]/s[3]};e.prototype.shouldSplit=
function(a,b){var c=this.lij[0];if(1>c)return q.SPLIT;l.subtract(this.center,b,w);var d=l.length(w),m=this.edgeLen/(2*a[0]*d),d=this.edgeLen/(2*a[2]*d),e=a[1],h=a[3],k=a[4],g=a[5];return m<e?this.vlevel!==this.lij[0]?(this.vlevel=this.lij[0],q.VSPLITMERGE):q.NONE:c>=k?(c+=Math.ceil(-y.log2(e/m)),c!==this.vlevel?(this.vlevel=c,q.VSPLITMERGE):q.NONE):6<c&&(l.scale(this.tileUp,l.dot(this.tileUp,w),f),l.subtract(f,w),l.length2(f)>this.radius*this.radius&&(l.scale(f,this.radius/l.length(f)),l.add(f,this.center),
l.subtract(b,f,f),c=this.elevationBounds[1]-this.elevationBounds[0],Math.min(1,(Math.abs(l.dot(f,this.tileUp))+0.5*c+this.curvatureHeight)/l.length(f))*d<0.1/g*h))?q.NONE:q.SPLIT};e.prototype.createElevationDataFromLERC=function(a){var b;try{b=F.createFromLERC(this.lij,this.extent,a,{noDataValue:g.ELEVATION_NODATA_VALUE})}catch(c){console.warn("Error decoding %s: %s",a.url,c.message)}return b};e.prototype.getWGS84Extent=function(){return this.extentWGS84Rad.map(y.rad2deg)};e.prototype.load=function(a){for(var b=
0;b<t;b++)this.layerInfo[b]&&this._createOrUpdateAgents(0,b);a.loadTile(this)};e.prototype.unload=function(a){this.renderData&&a.unloadTile(this);for(a=0;a<t;a++)for(var b=this.layerInfo[a],c=0;c<b.length;c++){var d=b[c];d.loadingAgent&&d.loadingAgent!==p&&(d.loadingAgent.dispose(),this.parentSurface.agentTypeByLayerIndex(c,a).Pool.release(d.loadingAgent),d.loadingAgent=null);d.pendingUpdates=0}this.pendingUpdates&=~g.TileUpdateTypes.UPDATE_GEOMETRY;this.pendingUpdates&=~g.TileUpdateTypes.UPDATE_TEXTURE};
e.prototype.updateClippingStatus=function(a){z.equals(a,this.clippingArea)||(a?(this.intersectsClippingArea=this.intersectsExtent(a),this.isWithinClippingArea=this.isWithinExtent(a)):this.isWithinClippingArea=this.intersectsClippingArea=!0,this.clippingArea=a,this.renderData&&this.updateGeometry())};e.prototype.updateVisibility=function(a,b,c){a=c||this.isVisible(a,b)&&this.intersectsClippingArea;if(a!==this.visible){this.visible=a;b=this.layerInfo[0];for(c=0;c<b.length;c++){var d=b[c];d.loadingAgent&&
d.loadingAgent!==p&&d.loadingAgent.setSuspension(!a)}}return a};e.prototype.getLayerInfo=function(a,b){return this.layerInfo[b][a]};e.prototype.hasLayerData=function(a,b){var c=this.layerInfo[b][a];return c&&c.data};e.prototype.tileDataAvailable=function(a,b,c){return(b=this.layerInfo[c][b].tilemapData)?null!=b.dataValue?b.dataValue:b.isTileAvailable(a.lij[1],a.lij[2]):!0};e.prototype.requestLayerData=function(a,b,c){g.TILE_LOADING_DEBUGLOG&&console.log("tile %s layer %d/%d requested by tile %s",
this.lij.toString(),b,a,c.tile.lij.toString());var d=this.layerInfo[b][a];if(-1<d.waitingAgents.indexOf(c))return console.warn("agent already requested this piece of map data (tile %s, agent tile %s, layer: %d/%d)",this.lij.toString(),c.tile.lij.toString(),b,a),!0;if(d.data)return console.warn("agent requested existing data (tile %s, agent tile %s, layer: %d/%d)",this.lij.toString(),c.tile.lij.toString(),b,a),d.waitingAgents.push(c),setTimeout(c.dataArrived.bind(c,this),0),!0;if(d.pendingUpdates&
q.DECODE_LERC)return d.waitingAgents.push(c),!0;d.waitingAgents.push(c);if(!d.requestPromise){var m=this.parentSurface.requestTileData(this,a,b);a=function(){d.requestPromise===m&&(d.requestPromise=null)};d.requestPromise=m;m.then(a,a)}return d.requestPromise?!0:!1};e.prototype.descendants=function(a){a||(a=[]);for(var b=0;4>b;b++){var c=this.children[b];c&&(c.descendants(a),a.unshift(this.children[b]))}return a};e.prototype.isLij=function(a){return this.lij[0]===a[0]&&this.lij[1]===a[1]&&this.lij[2]==
a[2]};e.prototype.findByLij=function(a){if(this.isLij(a))return this;for(var b=0;4>b;b++){var c=this.children[b];if(c&&(c=c.findByLij(a)))return c}return null};e.prototype.unrequestLayerData=function(a,b,c){g.TILE_LOADING_DEBUGLOG&&console.log("tile %s layer %d/%d canceled by tile %s",this.lij.toString(),b,a,c.tile.lij.toString());var d=this.layerInfo[b][a],m=d.waitingAgents;c=m.indexOf(c);B(-1<c,"agent has not requested this piece of map data");m[c]=m[m.length-1];m.length--;1>m.length&&(B(d.requestPromise||
d.rawData,"no pending operations on layerInfo that agents were waiting for"),d.requestPromise&&(this.parentSurface.cancelRequest(d.requestPromise),d.requestPromise=null),g.TILE_LOADING_DEBUGLOG&&console.log("tile %s layer %d/%d request/loading canceled",this.lij.toString(),b,a))};e.prototype.dataArrived=function(a,b,c){a=this.layerInfo[b][a];a.data=c;for(c=0;c<a.waitingAgents.length;c++)a.waitingAgents[c].dataArrived(this);a.waitingAgents.length=0};e.prototype.dataMissing=function(a,b,c){c.notInTilemap||
console.error("Tile %s layer %d/%d error",this.lij.toString(),b,a);a=this.layerInfo[b][a];for(b=0;b<a.waitingAgents.length;b++)a.waitingAgents[b].dataMissing(this);a.waitingAgents.length=0};e.prototype.updateTexture=function(a){this.renderData&&(a?this.parentSurface._renderer.updateTileTexture(this):(this.pendingUpdates|=g.TileUpdateTypes.UPDATE_TEXTURE,this.parentSurface._pendingUpdates=!0))};e.prototype.computeElevationBounds=function(){r.set2(Number.MAX_VALUE,-Number.MAX_VALUE,this.elevationBounds);
for(var a=this.layerInfo[n],b=!1,c=0;c<a.length;c++){var d=a[c];d.elevationBounds&&(this.elevationBounds[0]=Math.min(this.elevationBounds[0],d.elevationBounds[0]),this.elevationBounds[1]=Math.max(this.elevationBounds[1],d.elevationBounds[1]),b=!0)}b||r.set2(0,0,this.elevationBounds);this.updateRadiusAndCenter()};e.prototype.updateRadiusAndCenter=function(){l.scale(this.tileUp,0.5*(this.elevationBounds[0]+this.elevationBounds[1]),f);l.add(this.centerAtSeaLevel,f,this.center)};e.prototype.findElevationBoundsForLayer=
function(a,b){var c=this.layerInfo[n][a];if(!c.elevationBounds||c.elevationBounds[2]<b){var d=this.parentSurface.layerViewByIndex(a,n);if(x.fallsWithinLayer(this,d,!1)){d=!1;if(c.data)r.set(c.data.bounds,f),f[2]=this.lij[0],d=!0;else{for(var m=this.parent,e=0,h=null,k=c.data;m&&(!k||e<g.ELEVATION_DESIRED_RESOLUTION_LEVEL);){e=this.vlevel-m.lij[0];h=k||h;k=m.layerInfo[n][a].data;if(!k&&h&&e>=g.ELEVATION_DESIRED_RESOLUTION_LEVEL)break;m=m.parent}if(k=k||h)k.computeMinMaxValue(this.lij[0],this.lij[1],
this.lij[2],f),Infinity!==f[0]&&(f[2]=k.level,d=!0)}d&&(c.elevationBounds?l.set(f,c.elevationBounds):c.elevationBounds=[f[0],f[1],f[2]])}}};e.prototype.updateGeometry=function(){this.pendingUpdates|=g.TileUpdateTypes.UPDATE_GEOMETRY;this.parentSurface._pendingUpdates=!0};e.prototype.modifyLayers=function(a,b,c){for(var d=b.length,e=this.layerInfo[c],f=Array(d),h=0;h<e.length;h++){var k=e[h];k.loadingAgent&&k.loadingAgent!==p&&(k.loadingAgent.dispose(),this.parentSurface.agentTypeByLayerIndex(h,c).Pool.release(k.loadingAgent),
k.loadingAgent=null);k.waitingAgents.length=0}if(c===I)for(h=0;h<e.length;h++)void 0===a[h]&&(k=e[h],k.data instanceof WebGLTexture&&this.parentSurface._renderer.releaseTileTexture(k.data));for(h=0;h<d;h++)a=b[h],f[h]=-1<a?e[a]:C(c);this.layerInfo[c]=f};e.prototype.restartAgents=function(a){if(this.renderData)if(this._createOrUpdateAgents(0,a),a===n){this.updateGeometry();a=this.layerInfo[a];for(var b=0;b<a.length;b++)a[b].pendingUpdates|=g.TileUpdateTypes.UPDATE_GEOMETRY;this.parentSurface._pendingUpdates=
!0}else this.updateTexture(!0)};e.prototype.updateAgents=function(a){if(this.renderData){for(var b=this.layerInfo[a],c=0;c<b.length;c++){var d=b[c];d.loadingAgent===p&&(d.loadingAgent=null)}this._createOrUpdateAgents(0,a)}};e.prototype.agentDone=function(a,b){var c=this.layerInfo[b],d=c[a];d.loadingAgent=p;!d.data&&!d.upsampleFromTile&&a<c.length-1&&this._createOrUpdateAgents(a+1,b)};e.prototype._createOrUpdateAgents=function(a,b){var c;c=b===n?!1:!this.visible;for(var d=a,e=this.layerInfo[b];d<e.length;){var f=
e[d],h=!1,k=this.parentSurface.layerViewByIndex(d,b);if(null!==f.loadingAgent&&f.loadingAgent!==p)h=f.loadingAgent.update();else if(f.loadingAgent!==p&&x.fallsWithinLayer(this,k,!1)){var l=this.parentSurface.agentTypeByLayerIndex(d,b),g=l.Pool.acquire();(h=g.init(this,d,b,c))?f.loadingAgent=g:(l.Pool.release(g),f.loadingAgent=p)}if(h&&!k.isTransparent())break;d++}};e.prototype.geometryState=function(a){var b,c=this._getElevationInfo(a?a.samplerData:null),d=this.lij[0],e=!1;c.samplerData?(b=this.vlevel-
d,b=Math.max(d-c.maxTileLevel,g.ELEVATION_DESIRED_RESOLUTION_LEVEL-b),d=this._maxTesselation,b=y.clamp((d>>b)+1,2,d+1)):b=8>d?this._numSubdivisionsAtLevel[d]+1:2;b=D.supportedNumVertsPerRow(b);d=this.clippingArea;if(!this.intersectsClippingArea||this.isWithinClippingArea)d=null;a?(a.numVertsPerRow!==b&&(a.numVertsPerRow=b,e=!0),c.changed&&(a.samplerData=c.samplerData,e=!0),z.equals(a.clippingArea,d)||(a.clippingArea=d,e=!0),a.needsUpdate=e):a={numVertsPerRow:b,samplerData:c.samplerData,needsUpdate:!0,
clippingArea:d};return a};e.prototype._getElevationInfo=function(a){for(var b=this.layerInfo[n],c=b.length,d=Array(c),e=0,f=0,h=!1,k=0;k<c;k++){var g=b[k];if(g.upsampleFromTile){var g=g.upsampleFromTile.tile,l=g.layerInfo[n][k].data;if(!a||a[e]!==l.samplerData)h=!0;d[e++]=l.samplerData;f=Math.max(f,g.lij[0])}else if(g.data&&(l=this.parentSurface.layerViewByIndex(k,n),x.fallsWithinLayer(this,l,!1))){if(!a||a[e]!==g.data.samplerData)h=!0;d[e++]=g.data.samplerData;f=this.lij[0]}}a&&a.length!==e&&(h=
!0);0<e?d.length=e:d=null;return{changed:h,samplerData:d,maxTileLevel:f}};e.prototype.isWithinExtent=function(a){var b=this.extent;return b[0]>=a[0]&&a[2]>=b[2]&&b[1]>=a[1]&&a[3]>=b[3]};e.prototype.intersectsExtent=function(a){var b=this.extent;return b[2]>=a[0]&&a[2]>=b[0]&&b[3]>=a[1]&&a[3]>=b[1]};A.prototype.init=function(a){this.waitingAgents.length=0;this.rawData=this.requestPromise=this.loadingAgent=this.upsampleFromTile=this.tilemapRequest=this.tilemapData=this.data=null;this.pendingUpdates=
0;a===n&&(this.elevationBounds=null)};var C=function(a,b){return b?(b.init(a),b):new A(a)};return e});