// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("require exports ../../core/tsSupport/declareExtendsHelper ../../core/tsSupport/decorateHelper ../../core/tsSupport/paramHelper ../../core/accessorSupport/decorators dojo/io-query ../../core/Collection ../../core/JSONSupport ../../core/Logger ../../core/lang ../../core/accessorSupport/ensureType ../../renderers/support/jsonUtils ../../tasks/QueryTask ../../tasks/support/Query ../../PopupTemplate ./LabelClass ./layerSourceUtils".split(" "),function(B,C,n,e,p,d,q,r,s,t,k,u,v,w,l,x,y,g){function h(d){return function(a){var f=
this.layer,c=this._get(d);this._set(d,a);f&&c!==a&&f.emit("sublayer-update",{propertyName:d})}}var z=t.getLogger("esri.layers.support.Sublayer"),A=0;return function(m){function a(){m.apply(this,arguments);this._sublayersHandles=null}n(a,m);Object.defineProperty(a.prototype,"definitionExpression",{get:function(){return this._get("definitionExpression")},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"id",{get:function(){var f=this._get("id");return null==f?A++:f},enumerable:!0,configurable:!0});
Object.defineProperty(a.prototype,"labelingInfo",{get:function(){return this._get("labelingInfo")},enumerable:!0,configurable:!0});a.prototype.writeLabelingInfo=function(f,a,b){if((!b||b.writeAsDynamic)&&f&&f.length)a.layerDefinition={drawingInfo:{labelingInfo:f.map(function(f){return f.write({},b)})}}};Object.defineProperty(a.prototype,"labelsVisible",{get:function(){return this._get("labelsVisible")},enumerable:!0,configurable:!0});a.prototype.writeLabelsVisible=function(f,a,b){if(!b||b.writeAsDynamic)a.showLabels=
f};Object.defineProperty(a.prototype,"legendEnabled",{get:function(){return this._get("legendEnabled")},enumerable:!0,configurable:!0});a.prototype.writeLegendEnabled=function(f,a,b){f||(a.showLegend=!1)};Object.defineProperty(a.prototype,"layer",{set:function(a){this._set("layer",a);this.sublayers&&this.sublayers.forEach(function(c){return c.layer=a})},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"minScale",{get:function(){return this._get("minScale")},enumerable:!0,configurable:!0});
a.prototype.writeMinScale=function(a,c,b){if(b&&b.writeOverridesOnly&&(b=b&&b.serviceSublayer)&&b.minScale===a&&b.maxScale===this.maxScale)return;c.minScale=a};Object.defineProperty(a.prototype,"maxScale",{get:function(){return this._get("maxScale")},enumerable:!0,configurable:!0});a.prototype.writeMaxScale=function(a,c,b){if(b&&b.writeOverridesOnly&&(b=b&&b.serviceSublayer)&&b.maxScale===a&&b.minScale===this.minScale)return;c.maxScale=a};Object.defineProperty(a.prototype,"opacity",{get:function(){return this._get("opacity")},
enumerable:!0,configurable:!0});a.prototype.readOpacity=function(a,c){return 1-0.01*c.layerDefinition.drawingInfo.transparency};a.prototype.writeOpacity=function(a,c,b){if(!b||b.writeAsDynamic)c.layerDefinition={drawingInfo:{transparency:100-100*a}}};a.prototype.writeParent=function(a,c,b){if(!b||!b.writeOverridesOnly)c.parentLayerId=!this.parent||this.parent===this.layer?-1:this.parent.id};Object.defineProperty(a.prototype,"popupTemplate",{get:function(){return this._get("popupTemplate")},enumerable:!0,
configurable:!0});Object.defineProperty(a.prototype,"renderer",{get:function(){return this._get("renderer")},enumerable:!0,configurable:!0});a.prototype.readRenderer=function(a,c,b){if(a=c.layerDefinition.drawingInfo.renderer||void 0)(a=v.read(a,c,b)||void 0)||z.error("Failed to create renderer",{rendererDefinition:c.drawingInfo.renderer,layer:this,context:b});return a};a.prototype.writeRenderer=function(a,c,b){if(!b||b.writeAsDynamic)c.layerDefinition={drawingInfo:{renderer:a.toJSON()}}};Object.defineProperty(a.prototype,
"source",{get:function(){return this._get("source")||{mapLayerId:this.id,type:g.MAPLAYER}},enumerable:!0,configurable:!0});a.prototype.writeSource=function(a,c,b){if(!b||b.writeAsDynamic||!b.writeOverridesOnly)c.layerDefinition={source:g.sourceToJSON(a)}};Object.defineProperty(a.prototype,"sublayers",{set:function(a){var c=this,b=this._get("sublayers");b&&(b.forEach(function(a){a.parent=null;a.layer=null}),this._sublayersHandles.forEach(function(a){return a.remove()}),this._sublayersHandles=null);
a&&(a.forEach(function(a){a.parent=c;a.layer=c.layer}),this._sublayersHandles=[a.on("after-add",function(a){a=a.item;a.parent=c;a.layer=c.layer}),a.on("after-remove",function(a){a=a.item;a.parent=null;a.layer=null})]);this._set("sublayers",a)},enumerable:!0,configurable:!0});a.prototype.castSublayers=function(f){return u.default(r.ofType(a),f)};a.prototype.writeSublayers=function(a,c,b){if(!b||!b.writeOverridesOnly)c.subLayerIds=this.get("sublayers.length")?this.sublayers.map(function(a){return a.id}).toArray().reverse():
null};Object.defineProperty(a.prototype,"title",{get:function(){return this._get("title")},enumerable:!0,configurable:!0});a.prototype.writeTitle=function(a,c,b){if(b&&b.writeOverridesOnly&&(b=b&&b.serviceSublayer)&&b.title===a)return;c.name=a};Object.defineProperty(a.prototype,"url",{get:function(){var a=this.layer,c=this.source;if(!a)return null;if(g.isMapLayerSource(c))return a.parsedUrl.path+"/"+c.mapLayerId;c={layer:JSON.stringify({source:g.sourceToJSON(this.source)})};return a.parsedUrl.path+
"/dynamicLayer?"+q.objectToQuery(c)},enumerable:!0,configurable:!0});Object.defineProperty(a.prototype,"visible",{get:function(){return this._get("visible")},enumerable:!0,configurable:!0});a.prototype.writeVisible=function(a,c,b){if(b&&b.writeOverridesOnly&&(b=b&&b.serviceSublayer)&&b.visible===a)return;c.defaultVisibility=a};a.prototype.clone=function(){var f=new a;this.hasOwnProperty("definitionExpression")&&(f.definitionExpression=this.definitionExpression);this.hasOwnProperty("id")&&(f.id=this.id);
this.hasOwnProperty("labelingInfo")&&(f.labelingInfo=k.clone(this.labelingInfo));this.hasOwnProperty("labelsVisible")&&(f.labelsVisible=this.labelsVisible);this.hasOwnProperty("legendEnabled")&&(f.legendEnabled=this.legendEnabled);this.hasOwnProperty("layer")&&(f.layer=this.layer);this.hasOwnProperty("minScale")&&(f.minScale=this.minScale);this.hasOwnProperty("maxScale")&&(f.maxScale=this.maxScale);this.hasOwnProperty("opacity")&&(f.opacity=this.opacity);this.hasOwnProperty("parent")&&(f.parent=this.parent);
this.hasOwnProperty("popupTemplate")&&(f.popupTemplate=this.popupTemplate.clone());this.hasOwnProperty("renderer")&&(f.renderer=this.renderer.clone());this.hasOwnProperty("source")&&(f.source=k.clone(this.source));this.hasOwnProperty("sublayers")&&(f.sublayers=this.sublayers.clone());this.hasOwnProperty("title")&&(f.title=this.title);return f};a.prototype.createQuery=function(){return new l({returnGeometry:!0,where:this.definitionExpression||"1\x3d1"})};a.prototype.queryFeatures=function(a){var c=
this;void 0===a&&(a=this.createQuery());return(new w({url:this.url})).execute(a).then(function(a){a&&a.features&&a.features.forEach(function(a){a.popupTemplate=c.popupTemplate});return a})};a.prototype.toExportImageJSON=function(){var a={id:this.id,source:g.sourceToJSON(this.source)};this.definitionExpression&&(a.definitionExpression=this.definitionExpression);if(this.renderer||this.labelingInfo||null!=this.opacity||null!=this.labelsVisible){var c=a.drawingInfo={};this.renderer&&(c.renderer=this.renderer.toJSON());
null!=this.labelsVisible&&(c.showLabels=this.labelsVisible);!1!==this.labelsVisible&&this.labelingInfo&&(c.labelingInfo=this.labelingInfo);null!=this.opacity&&(c.transparency=100-100*this.opacity)}return a};e([d.property({value:null,set:h("definitionExpression"),json:{readFrom:"layerDefinition.definitionExpression",writeTo:"layerDefinition.definitionExpression"}})],a.prototype,"definitionExpression",null);e([d.property({json:{writeAlways:!0}})],a.prototype,"id",null);e([d.property({value:null,type:[y],
set:h("labelingInfo"),json:{readFrom:"layerDefinition.drawingInfo.labelingInfo"}})],a.prototype,"labelingInfo",null);e([d.write("labelingInfo")],a.prototype,"writeLabelingInfo",null);e([d.property({set:h("labelsVisible"),json:{readFrom:"showLabels"}})],a.prototype,"labelsVisible",null);e([d.write("labelsVisible")],a.prototype,"writeLabelsVisible",null);e([d.property({value:!0,type:Boolean,json:{readFrom:"showLegend"}})],a.prototype,"legendEnabled",null);e([d.write("showLegend")],a.prototype,"writeLegendEnabled",
null);e([d.property({value:null})],a.prototype,"layer",null);e([d.property({value:0,json:{writable:!0}})],a.prototype,"minScale",null);e([d.write("minScale")],a.prototype,"writeMinScale",null);e([d.property({value:0})],a.prototype,"maxScale",null);e([d.write("maxScale")],a.prototype,"writeMaxScale",null);e([d.property({set:h("opacity")})],a.prototype,"opacity",null);e([d.read("opacity",["layerDefinition.drawingInfo.transparency"])],a.prototype,"readOpacity",null);e([d.write("opacity")],a.prototype,
"writeOpacity",null);e([d.property({json:{writeNull:!0}})],a.prototype,"parent",void 0);e([d.write("parent")],a.prototype,"writeParent",null);e([d.property({value:null,type:x,json:{readFrom:"popupInfo",writeTo:"popupInfo"}})],a.prototype,"popupTemplate",null);e([d.property({value:null,set:h("renderer"),json:{writeTo:"layerDefinition.drawingInfo.renderer"}})],a.prototype,"renderer",null);e([d.read("renderer",["layerDefinition.drawingInfo.renderer"])],a.prototype,"readRenderer",null);e([d.write("renderer")],
a.prototype,"writeRenderer",null);e([d.property({cast:g.castSource,set:h("source"),json:{read:g.sourceFromJSON,readFrom:"layerDefinition.source"}})],a.prototype,"source",null);e([d.write("source")],a.prototype,"writeSource",null);e([d.property({value:null,json:{writeNull:!0}})],a.prototype,"sublayers",null);e([d.cast("sublayers")],a.prototype,"castSublayers",null);e([d.write("sublayers")],a.prototype,"writeSublayers",null);e([d.property({value:null,json:{readFrom:"name",writeAlways:!0,writeNull:!0}})],
a.prototype,"title",null);e([d.write("title")],a.prototype,"writeTitle",null);e([d.property({readOnly:!0,dependsOn:["layer","source"]})],a.prototype,"url",null);e([d.property({value:!0,set:h("visible"),json:{readFrom:"defaultVisibility"}})],a.prototype,"visible",null);e([d.write("visible")],a.prototype,"writeVisible",null);e([p(0,d.cast(l))],a.prototype,"queryFeatures",null);return a=e([d.subclass("esri.layers.support.Sublayer")],a)}(d.declared(s))});