// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("require exports ./tsSupport/declareExtendsHelper ./tsSupport/decorateHelper dojo/aspect ./accessorSupport/decorators ./accessorSupport/ensureType ./Accessor ./ArrayPool ./Evented ./ObjectPool ./Scheduler ./lang".split(" "),function(B,O,E,x,F,s,G,H,t,I,J,K,L){function y(f){return!f?!1:f.isInstanceOf&&f.isInstanceOf(C)?!0:!1}function z(f){return!f?[]:y(f)?f.toArray():f.length?Array.prototype.slice.apply(f):[]}function v(f){return!f||!f.length?void 0:f[0]}function D(f,b,a,c){b&&b.forEach(function(b,
e,d){f.push(b);D(f,a.call(c,b,e,d),a,c)})}(function(){return function(){}})();B=function(){function f(){this.target=null;this.defaultPrevented=this.cancellable=!1}f.prototype.preventDefault=function(){this.cancellable&&(this.defaultPrevented=!0)};f.prototype.reset=function(b){this.defaultPrevented=!1;this.item=b};return f}();var M=function(){},h=new J(B,function(){this.target=this.item=null}),k=new Set,q=new Set,r=new Set,A=new Map,N=0,C=function(f){function b(a){f.call(this,a);this._boundDispatch=
this._dispatchColChange.bind(this);this._chgListeners=[];this._timer=this._notification=null;this.length=0;this._items=[];Object.defineProperty(this,"uid",{value:N++})}E(b,f);b.ofType=function(a){if(!a)return b;if(A.has(a))return A.get(a);var c=b.createSubclass({declaredClass:"esri.core.Collection\x3c"+a.prototype.declaredClass+"\x3e"});Object.defineProperty(c.prototype,"itemType",{value:a});A.set(a,c);return c};b.prototype.normalizeCtorArgs=function(a){return!a?{}:Array.isArray(a)||y(a)?{items:a}:
a};Object.defineProperty(b.prototype,"items",{get:function(){return this._items},set:function(a){this._emitBeforeChanges()||(this._splice.apply(this,[0,this.length].concat(z(a))),this._emitAfterChanges())},enumerable:!0,configurable:!0});b.prototype.on=function(a,c){var b;Array.isArray(a)?b=a:-1<a.indexOf(",")&&(b=a.split(/\s*,\s*/));if(b){for(var e=[],d=0;d<b.length;d++)e.push(this.on(b[d],c));e.remove=function(){for(var a=0;a<e.length;a++)e[a].remove()};return e}if("change"===a){var g=this._chgListeners;
this._notification&&this._dispatchColChange();var f={removed:!1,callback:c};g.push(f);return{remove:function(){this.remove=M;f.removed=!0;g.splice(g.indexOf(f),1)}}}return F.after(this,"on"+a,c,!0)};b.prototype.hasEventListener=function(a){return"change"===a?0<this._chgListeners.length:this.inherited(arguments)};b.prototype.add=function(a,c){if(this._emitBeforeChanges())return this;var b=this.getNextIndex(c);this._splice(b,0,a);this._emitAfterChanges();return this};b.prototype.addMany=function(a,
c){void 0===c&&(c=this._items.length);if(this._emitBeforeChanges())return this;var b=this.getNextIndex(c);this._splice.apply(this,[b,0].concat(z(a)));this._emitAfterChanges();return this};b.prototype.removeAll=function(){if(!this.length||this._emitBeforeChanges())return[];var a=this._splice(0,this.length)||[];this._emitAfterChanges();return a};b.prototype.clone=function(){return this._createNewInstance({items:this._items.map(L.clone)})};b.prototype.concat=function(){for(var a=[],c=0;c<arguments.length;c++)a[c-
0]=arguments[c];a=a.map(z);return this._createNewInstance({items:(b=this._items).concat.apply(b,a)});var b};b.prototype.drain=function(a,c){if(this.length&&!this._emitBeforeChanges()){for(var b=this._splice(0,this.length),e=0,d=b.length;e<d;e++)a.call(c,b[e],e,b);this._emitAfterChanges()}};b.prototype.every=function(a,c){return this._items.every(a,c)};b.prototype.filter=function(a,c){var b;b=2===arguments.length?this._items.filter(a,c):this._items.filter(a);return this._createNewInstance({items:b})};
b.prototype.find=function(a,c){if("function"!==typeof a)throw new TypeError(a+" is not a function");for(var b=this._items,e=0,d=b.length;e<d;e++){var g=b[e];if(a.call(c,g,e,b))return g}};b.prototype.findIndex=function(a,c){if("function"!==typeof a)throw new TypeError(a+" is not a function");for(var b=this._items,e=0,d=b.length;e<d;e++)if(a.call(c,b[e],e,b))return e;return-1};b.prototype.flatten=function(a,c){var w=[];D(w,this,a,c);return new b(w)};b.prototype.forEach=function(a,c){return this._items.forEach(a,
c)};b.prototype.getItemAt=function(a){return this._items[a]};b.prototype.getNextIndex=function(a){var c=this.length;a=null==a?c:a;0>a?a=0:a>c&&(a=c);return a};b.prototype.includes=function(a,c){void 0===c&&(c=0);return!arguments.length?!1:-1!==this._items.indexOf(a,c)};b.prototype.indexOf=function(a,c){void 0===c&&(c=0);return this._items.indexOf(a,c)};b.prototype.join=function(a){void 0===a&&(a=",");return this._items.join(a)};b.prototype.lastIndexOf=function(a,c){void 0===c&&(c=this.length-1);return this._items.lastIndexOf(a,
c)};b.prototype.map=function(a,c){var w=this._items.map(a,c);return new b({items:w})};b.prototype.reorder=function(a,c){void 0===c&&(c=this.length-1);var b=this.indexOf(a);if(-1!==b){0>c?c=0:c>=this.length&&(c=this.length-1);if(b!==c){if(this._emitBeforeChanges())return a;this._splice(b,1);this._splice(c,0,a);this._emitAfterChanges()}return a}};b.prototype.pop=function(){if(this.length&&!this._emitBeforeChanges()){var a=v(this._splice(this.length-1,1));this._emitAfterChanges();return a}};b.prototype.push=
function(){for(var a=[],c=0;c<arguments.length;c++)a[c-0]=arguments[c];if(this._emitBeforeChanges())return this.length;this._splice.apply(this,[this.length,0].concat(a));this._emitAfterChanges();return this.length};b.prototype.reduce=function(a,c){var b=this._items;return 2===arguments.length?b.reduce(a,c):b.reduce(a)};b.prototype.reduceRight=function(a,c){var b=this._items;return 2===arguments.length?b.reduceRight(a,c):b.reduceRight(a)};b.prototype.remove=function(a){return this.removeAt(this.indexOf(a))};
b.prototype.removeAt=function(a){if(!(0>a||a>=this.length||this._emitBeforeChanges()))return a=v(this._splice(a,1)),this._emitAfterChanges(),a};b.prototype.removeMany=function(a){if(!a||!a.length||this._emitBeforeChanges())return[];a=y(a)?a.toArray():a;for(var c=this._items,b=[],e=0,d=a.length;e<d;e++){var g=c.indexOf(a[e]);-1<g&&(g=v(this._splice(g,1)))&&b.push(g)}this._emitAfterChanges();return b};b.prototype.reverse=function(){if(this._emitBeforeChanges())return this;var a=this._splice(0,this.length);
a&&(a.reverse(),this._splice.apply(this,[0,0].concat(a)));this._emitAfterChanges();return this};b.prototype.shift=function(){if(this.length&&!this._emitBeforeChanges()){var a=v(this._splice(0,1));this._emitAfterChanges();return a}};b.prototype.slice=function(a,b){void 0===a&&(a=0);void 0===b&&(b=this.length);return this._createNewInstance({items:this._items.slice(a,b)})};b.prototype.some=function(a,b){return this._items.some(a,b)};b.prototype.sort=function(a){if(!this.length||this._emitBeforeChanges())return this;
var b=this._splice(0,this.length);arguments.length?b.sort(a):b.sort();this._splice.apply(this,[0,0].concat(b));return this};b.prototype.splice=function(a,b){for(var f=[],e=2;e<arguments.length;e++)f[e-2]=arguments[e];if(this._emitBeforeChanges())return[];f=this._splice.apply(this,[a,b].concat(f))||[];this._emitAfterChanges();return f};b.prototype.toArray=function(){return this._items.slice()};b.prototype.toJSON=function(){return this.toArray()};b.prototype.toLocaleString=function(){return this._items.toLocaleString()};
b.prototype.toString=function(){return this._items.toString()};b.prototype.unshift=function(){for(var a=[],b=0;b<arguments.length;b++)a[b-0]=arguments[b];if(this._emitBeforeChanges())return this.length;this._splice.apply(this,[0,0].concat(a));this._emitAfterChanges();return this.length};b.prototype._createNewInstance=function(a){return new this.constructor(a)};b.prototype._splice=function(a,b){for(var f=this,e=[],d=2;d<arguments.length;d++)e[d-2]=arguments[d];var g=this._items,u=this.constructor.prototype.itemType,
p,l;!this._notification&&this.hasEventListener("change")&&(this._notification={listeners:this._chgListeners.slice(),items:this._items.slice(),changes:[]},this._timer&&this._timer.remove(),this._timer=K.schedule(this._boundDispatch));if(b){l=g.splice(a,b);if(this.hasEventListener("before-remove")){d=h.acquire();d.target=this;d.cancellable=!0;for(var m=0,k=l.length;m<k;m++)p=l[m],d.reset(p),this.emit("before-remove",d),d.defaultPrevented&&(l.splice(m,1),g.splice(a,0,p),a+=1,m-=1,k-=1);h.release(d)}this.length=
this._items.length;if(this.hasEventListener("after-remove")){d=h.acquire();d.target=this;d.cancellable=!1;m=0;for(k=l.length;m<k;m++)d.reset(l[m]),this.emit("after-remove",d);h.release(d)}this._notifyChangeEvent(null,l)}if(e&&e.length){u&&(e=e.map(G.ensureType.bind(null,u)));if(this.hasEventListener("before-add")){var n=h.acquire();n.target=this;n.cancellable=!0;e=e.filter(function(a){n.reset(a);f.emit("before-add",n);return!n.defaultPrevented});h.release(n)}g.splice.apply(g,[a,0].concat(e));this.length=
this._items.length;if(this.hasEventListener("after-add")){d=h.acquire();d.target=this;d.cancellable=!1;g=0;for(u=e;g<u.length;g++)p=u[g],d.reset(p),this.emit("after-add",d);h.release(d)}this._notifyChangeEvent(e,null)}return l};b.prototype._emitBeforeChanges=function(){var a=!1;if(this.hasEventListener("before-changes")){var b=h.acquire();b.target=this;b.cancellable=!0;this.emit("before-changes",b);a=b.defaultPrevented;h.release(b)}return a};b.prototype._emitAfterChanges=function(){if(this.hasEventListener("after-changes")){var a=
h.acquire();a.target=this;a.cancellable=!1;this.emit("after-changes",a);h.release(a)}};b.prototype._notifyChangeEvent=function(a,b){this.hasEventListener("change")&&this._notification.changes.push({added:a,removed:b})};b.prototype._dispatchColChange=function(){this._timer&&(this._timer.remove(),this._timer=null);if(this._notification){var a=this._notification;this._notification=null;var b=a.changes;k.clear();q.clear();r.clear();for(var f=0;f<b.length;f++){var e=b[f],d=e.added,e=e.removed;if(d)if(0===
r.size&&0===q.size)for(var g=0,h=d;g<h.length;g++)d=h[g],k.add(d);else{g=0;for(h=d;g<h.length;g++)d=h[g],q.has(d)?(r.add(d),q.delete(d)):r.has(d)||k.add(d)}if(e)if(0===r.size&&0===k.size)for(g=0;g<e.length;g++)d=e[g],q.add(d);else for(g=0;g<e.length;g++)d=e[g],k.has(d)?k.delete(d):(r.delete(d),q.add(d))}var p=t.acquire();k.forEach(function(a){p.push(a)});var l=t.acquire();q.forEach(function(a){l.push(a)});var m=this._items,s=a.items,n=t.acquire();r.forEach(function(a){s.indexOf(a)!==m.indexOf(a)&&
n.push(a)});if(a.listeners&&(p.length||l.length||n.length)){b={target:this,added:p,removed:l,moved:n};f=0;for(d=a.listeners.length;f<d;f++)e=a.listeners[f],e.removed||e.callback.call(this,b)}t.release(p);t.release(l);t.release(n)}};x([s.property()],b.prototype,"length",void 0);x([s.property()],b.prototype,"items",null);return b=x([s.subclass("esri.core.Collection")],b)}(s.declared(H,I));return C});