// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("require exports dojo/_base/window dojo/_base/lang dojo/_base/url dojo/io-query ../config ./lang ./sniff ./Logger ./Error".split(" "),function(x,e,O,P,g,s,y,z,A,Q,R){function t(a){var b={path:null,query:null},c=new g(a),d=a.indexOf("?");null===c.query?b.path=a:(b.path=a.substring(0,d),b.query=s.queryToObject(c.query));c.fragment&&(b.hash=c.fragment,null===c.query&&(b.path=b.path.substring(0,b.path.length-(c.fragment.length+1))));return b}function B(a,b){void 0===a&&(a=!1);void 0===b&&(b=!0);
var c,d=l.proxyUrl;if("string"===typeof a){c=/^\s*https:/i.test(a)||f(a)&&"https"===e.appUrl.scheme;var h=u(a);h&&(d=h.proxyUrl)}else c=!!a;if(!d)throw S.warn(C),new R("urlutils:proxy-not-set",C);var m;c&&(b&&"https"===e.appUrl.scheme)&&(c=D(d),E(c)&&(d=c,m=1));d=t(d);d._xo=m;return d}function F(a){var b=a.indexOf("?");-1!==b?(n.path=a.slice(0,b),n.query=a.slice(b+1)):(n.path=a,n.query=null);return n}function G(a){a=F(a).path;if(!a||"/"!==a[a.length-1])a+="/";a=v(a,!0);return a=a.toLowerCase()}function u(a){var b=
l.proxyRules;a=G(a);for(var c=0;c<b.length;c++)if(0===a.indexOf(b[c].urlPrefix))return b[c]}function H(a){a=p(a);var b=a.indexOf("/sharing");return 0<b?a.substring(0,b):a.replace(/\/+$/,"")}function I(a,b,c){void 0===c&&(c=!1);a=w(a);b=w(b);return!c&&a.scheme!==b.scheme?!1:a.host.toLowerCase()===b.host.toLowerCase()&&a.port===b.port}function E(a){if(A("esri-phonegap"))return!0;if(!A("esri-cors"))return!1;var b=l.corsEnabledServers||[];"string"===typeof a&&(a=q(a)?w(a):e.appUrl);for(var c=0;c<b.length;c++){var d;
d=b[c];e.corsServersUrlCache[d]||(!r.test(d)&&!f(d)?e.corsServersUrlCache[d]=[new g("http://"+d),new g("https://"+d)]:e.corsServersUrlCache[d]=[new g(k(d))]);d=e.corsServersUrlCache[d];for(var h=0;h<d.length;h++)if(I(a,d[h]))return!0}return!1}function k(a,b,c){void 0===b&&(b=e.appBaseUrl);if(f(a))return c&&c.preserveProtocolRelative?a:"file"===e.appUrl.scheme?"https:"+a:e.appUrl.scheme+":"+a;if(r.test(a))return a;c=J;if("/"===a[0]){var d=b.indexOf("//"),d=b.indexOf("/",d+2);b=-1===d?b:b.slice(0,d)}return c(b,
a)}function K(a,b){void 0===b&&(b=e.appBaseUrl);if(!q(a))return a;for(var c=p(a),d=c.toLowerCase(),h=p(b).toLowerCase().replace(/\/+$/,""),m=function(a,b,c){c=a.indexOf(b,c);return-1===c?a.length:c},f=m(d,"/",d.indexOf("//")+2),g=-1;d.slice(0,f+1)===h.slice(0,f)+"/";){g=f+1;if(f===d.length)break;f=m(d,"/",f+1)}if(-1===g)return a;a=c.slice(g);c=h.slice(g-1).replace(/[^/]+/g,"").length;if(0<c)for(d=0;d<c;d++)a="../"+a;else a="./"+a;return a}function p(a){a=k(a);a=T(a);return a=a.replace(/^(https?:\/\/)(arcgis\.com)/i,
"$1www.$2")}function J(){for(var a=[],b=0;b<arguments.length;b++)a[b-0]=arguments[b];if(a&&a.length){b=[];if(q(a[0])){var c=a[0],d=c.indexOf("//");b.push(c.slice(0,d+1));L.test(a[0])&&(b[0]+="/");a[0]=c.slice(d+2)}else"/"===a[0][0]&&b.push("");a=a.reduce(function(a,b){return a.concat(b.split("/"))},[]);for(c=0;c<a.length;c++)d=a[c],".."===d&&0<b.length?b.pop():d&&("."!==d||0===b.length)&&b.push(d);return b.join("/")}}function q(a){return f(a)||r.test(a)}function M(a){return"data:"===a.slice(0,5)}
function f(a){return a&&"/"===a[0]&&"/"===a[1]}function D(a){return f(a)?"https:"+a:a.replace(N,"https:")}function v(a,b){void 0===b&&(b=!1);if(f(a))return a.slice(2);a=a.replace(r,"");b&&(1<a.length&&"/"===a[0]&&"/"===a[1])&&(a=a.slice(2));return a}function T(a){var b=y.request.httpsDomains;if(!(N.test(a)||f(a)&&"http"===e.appUrl.scheme)||"https"!==e.appUrl.scheme&&!L.test(e.appBaseUrl))return a;var c=a.indexOf("/",7),d;d=-1===c?a:a.slice(0,c);if(z.endsWith(d,""+e.appUrl.host+(null!=e.appUrl.port?
":"+e.appUrl.port:""))||b&&b.some(function(a){return z.endsWith(d,a)}))a=D(a);return a}function w(a){if("string"===typeof a)return new g(k(a));a.scheme||(a.scheme=e.appUrl.scheme);return a}x=O.global;var S=Q.getLogger("esri.core.urlUtils"),l=y.request,C="esri/config: esriConfig.request.proxyUrl is not set. If making a request to a CORS-enabled\n server, please push the domain into esriConfig.request.corsEnabledServers.",r=/^\s*[a-z][a-z0-9-+.]*:(?![0-9])/i,N=/^\s*http:/i,L=/^\s*file:/i;e.appUrl=new g(x.location);
e.corsServersUrlCache={};e.appBaseUrl=function(){var a=e.appUrl.path,a=a.substring(0,a.lastIndexOf(a.split("/")[a.split("/").length-1]));return""+(e.appUrl.scheme+"://"+e.appUrl.host+(null!=e.appUrl.port?":"+e.appUrl.port:""))+a}();e.urlToObject=t;e.getProxyUrl=B;e.addProxy=function(a){var b=u(a),c,d;b?(d=F(b.proxyUrl),c=d.path,d=d.query?s.queryToObject(d.query):null):l.forceProxy&&(d=B(),c=d.path,d=d.query);c&&(b=t(a),a=c+"?"+b.path,(c=s.objectToQuery(P.mixin(d||{},b.query)))&&(a=a+"?"+c));return a};
var n={path:"",query:""};e.addProxyRule=function(a){for(var b=G(a.urlPrefix),c=l.proxyRules,d=c.length,e=0;e<c.length;e++){var f=c[e].urlPrefix;if(0===b.indexOf(f)){if(b.length===f.length)return-1;d=e;break}0===f.indexOf(b)&&(d=e+1)}c.splice(d,0,a);return d};e.getProxyRule=u;e.hasSamePortal=function(a,b){a=H(a);b=H(b);return v(a)===v(b)};e.hasSameOrigin=I;e.canUseXhr=E;e.makeAbsolute=k;e.makeRelative=K;e.normalize=p;e.join=J;e.getOrigin=function(a){if(M(a))return null;var b=a.indexOf("://");if(-1===
b&&f(a))b=2;else if(-1!==b)b+=3;else return null;b=a.indexOf("/",b);return-1===b?a:a.slice(0,b)};e.isAbsolute=q;e.isDataProtocol=M;e.read=function(a,b){var c=b&&b.url&&b.url.path;return!a||!c?a:k(a,c,{preserveProtocolRelative:!0})};e.write=function(a,b){if(!a)return a;a=k(a);var c=b&&b.url&&b.url.path;c&&(a=K(a,c));return a}});