// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/Deferred dojo/io-query ../request ../geometry/support/normalizeUtils ../geometry/SpatialReference ../layers/MapImageLayer ../layers/support/MapImage ./Task ./support/DataFile ./support/Date ./support/FeatureSet ./support/GPMessage ./support/JobInfo ./support/LinearUnit ./support/ParameterValue ./support/RasterData".split(" "),function(e,l,m,g,n,h,p,q,r,s,t,u,v,k,w,x,y){h=r.createSubclass({declaredClass:"esri.tasks.Geoprocessor",constructor:function(){this._updateTimers=
[];this._handleExecuteResponse=this._handleExecuteResponse.bind(this);this._handleGetResultImageResponse=this._handleGetResultImageResponse.bind(this);this._handleGetResultDataResponse=this._handleGetResultDataResponse.bind(this)},__msigns:[{n:"execute",c:1,a:[{i:0,p:["*"]}],e:2},{n:"submitJob",c:1,a:[{i:0,p:["*"]}],e:3}],properties:{outSpatialReference:{value:null,type:h},processSpatialReference:{value:null,type:h},updateDelay:{value:1E3,type:Number},url:{}},cancelJob:function(a){return g(this.parsedUrl.path+
"/jobs/"+a+"/cancel",{query:e.mixin({},this.parsedUrl.query,{f:"json"}),callbackParamName:"callback"}).then(function(a){return a.data})},cancelJobStatusUpdates:function(a){clearTimeout(this._updateTimers[a]);this._updateTimers[a]=null},checkJobStatus:function(a){return g(this.parsedUrl.path+"/jobs/"+a,{query:e.mixin({},this.parsedUrl.query,{f:"json"}),callbackParamName:"callback"}).then(this._handleCheckJobStatusResponse)},getResultImage:function(a,c,b){b=this._gpEncode(e.mixin({},this.parsedUrl.query,
{f:"json"},b.toJSON()));return g(this.parsedUrl.path+"/jobs/"+a+"/results/"+c,{query:b,callbackParamName:"callback"}).then(this._handleGetResultImageResponse)},getResultData:function(a,c){return g(this.parsedUrl.path+"/jobs/"+a+"/results/"+c,{query:e.mixin({},this.parsedUrl.query,{f:"json",returnType:"data"}),callbackParamName:"callback"}).then(this._handleGetResultDataResponse)},getResultMapImageLayer:function(a){var c=this.parsedUrl,b;b=c.path.indexOf("/GPServer/");a=c.path.substring(0,b)+"/MapServer/jobs/"+
a;c.query&&(a+="?"+m.objectToQuery(c.query));return new p(a)},execute:function(a,c){var b=this.outSpatialReference,d=c.assembly,b=this._gpEncode(e.mixin({},this.parsedUrl.query,{f:"json","env:outSR":b?b.wkid||JSON.stringify(b.toJSON()):null,"env:processSR":this.processSpatialReference?this.processSpatialReference.wkid||JSON.stringify(this.processSpatialReference.toJSON()):null},a),null,d&&d[0]);return g(this.parsedUrl.path+"/execute",{query:b,callbackParamName:"callback"}).then(this._handleExecuteResponse)},
submitJob:function(a,c){var b=this.outSpatialReference,d=c.assembly,b=this._gpEncode(e.mixin({},this.parsedUrl.query,{f:"json","env:outSR":b?b.wkid||JSON.stringify(b.toJSON()):null,"env:processSR":this.processSpatialReference?this.processSpatialReference.wkid||JSON.stringify(this.processSpatialReference.toJSON()):null},a),null,d&&d[0]),f=new l,z=this._jobUpdateHandler.bind(this);g(this.parsedUrl.path+"/submitJob",{query:b,callbackParamName:"callback"}).then(function(a){z(a.data,f)}).then(null,function(a){f.reject(a)});
return f.promise},_gpEncode:function(a,c,b){for(var d in a){var f=a[d];e.isArray(f)?a[d]=JSON.stringify(f.map(function(a){return this._gpEncode({item:a},!0).item},this)):f instanceof Date&&(a[d]=f.getTime())}return this._encode(a,c,b)},_decode:function(a){var c=a.dataType,b=x.fromJSON(a);if(-1!==["GPBoolean","GPDouble","GPLong","GPString"].indexOf(c))return b;if("GPLinearUnit"===c)b.value=w.fromJSON(b.value);else if("GPFeatureRecordSetLayer"===c||"GPRecordSet"===c)b.value=u.fromJSON(b.value);else if("GPDataFile"===
c)b.value=s.fromJSON(b.value);else if("GPDate"===c)a=b.value,e.isString(a)?b.value=t.fromJSON({date:a}):b.value=Date.fromJSON(a);else if("GPRasterData"===c||"GPRasterDataLayer"===c)a=a.value.mapImage,b.value=a?q.fromJSON(a):y.fromJSON(b.value);else if(-1!==c.indexOf("GPMultiValue:")){var d=c.split(":")[1];a=b.value;b.value=a.map(function(a){return this._decode({paramName:"_name",dataType:d,value:a}).value},this)}else console.log(this.declaredClass+" : GP Data type not handled. : "+b.dataType),b=null;
return b},_jobUpdateHandler:function(a,c){var b=a.jobId,d=k.fromJSON(a),f,e;clearTimeout(this._updateTimers[b]);this._updateTimers[b]=null;c.progress(d);switch(d.jobStatus){case "job-submitted":case "job-executing":case "job-waiting":case "job-new":f=this._getJobStatus.bind(this);e=this._jobUpdateHandler.bind(this);this._updateTimers[b]=setTimeout(function(){f(b).then(function(a){e(a,c)})},this.updateDelay);break;default:c.resolve(d)}},_getJobStatus:function(a){return g(this.parsedUrl.path+"/jobs/"+
a,{query:e.mixin({},this.parsedUrl.query,{f:"json"}),callbackParamName:"callback"}).then(function(a){return a.data})},_handleGetResultDataResponse:function(a){return this._decode(a.data)},_handleCheckJobStatusResponse:function(a){return k.fromJSON(a.data)},_handleExecuteResponse:function(a){a=a.data;var c=a.messages||[];return{results:(a.results||[]).map(this._decode,this),messages:c.map(v.fromJSON)}},_handleGetResultImageResponse:function(a){return this._decode(a.data)}});n._createWrappers(h);return h});