// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("../core/lang ../core/kebabDictionary ../core/urlUtils ../geometry/Polygon ../geometry/support/scaleUtils dojo/_base/lang dojo/dom-construct dojox/gfx/canvas ./Geoprocessor ./support/PrintTemplate ./support/printTaskUtils ./Task".split(" "),function(E,s,w,x,y,m,z,t,A,B,n,C){var u={Feet:"ft",Kilometers:"km",Meters:"m",Miles:"mi"},v=s({esriFeet:"Feet",esriKilometers:"Kilometers",esriMeters:"Meters",esriMiles:"Miles"}),D=s({MAP_ONLY:"map-only","A3 Landscape":"a3-landscape","A3 Portrait":"a3-portrait",
"A4 Landscape":"a4-landscape","A4 Portrait":"a4-portrait","Letter ANSI A Landscape":"letter-ansi-a-landscape","Letter ANSI A Portrait":"letter-ansi-a-portrait","Tabloid ANSI B Landscape":"tabloid-ansi-b-landscape","Tabloid ANSI B Portrait":"tabloid-ansi-b-portrait"});return C.createSubclass({declaredClass:"esri.tasks.PrintTask",constructor:function(){this._handleExecuteResponse=this._handleExecuteResponse.bind(this)},_legendLayers:[],_legendLayerNameMap:{},properties:{_geoprocessor:{dependsOn:["url",
"updateDelay"],get:function(){return new A(this.url,{updateDelay:this.updateDelay})}},mode:{value:"sync"},url:{value:null,type:String},updateDelay:{value:1E3,type:Number}},execute:function(a){a=this._setPrintParams(a);return this._geoprocessor["async"===this.mode?"submitJob":"execute"](a).then(this._handleExecuteResponse)},_createOperationalLayers:function(a,d){var b=[],h,c,f,g,k=a.map.allLayers.items,e=/^https?:\/\/basemaps(dev)?\.arcgis\.com(\/b2)?\/arcgis\/rest\/services\/World_Basemap\/VectorTileServer/i;
for(h=0;h<k.length;h++)if(c=k[h],c.loaded&&c.visible)switch(g={id:c.id,title:this._legendLayerNameMap[c.id]||c.title,opacity:c.opacity,minScale:c.minScale||0,maxScale:c.maxScale||0,url:c.url&&w.normalize(c.url),token:c.token},f=c.declaredClass,f){case "esri.layers.ImageryLayer":f={bandIds:c.bandIds,compressionQuality:c.compressionQuality,format:c.format,interpolation:c.interpolation};c.mosaicRule&&(f.mosaicRule=c.mosaicRule.toJSON());c.renderingRule&&(f.renderingRule=c.renderingRule.toJSON());b.push(m.mixin(g,
f));this._legendLayers&&this._legendLayers.push({id:c.id});break;case "esri.layers.OpenStreetMapLayer":m.mixin(g,{type:"OpenStreetMap"});b.push(g);break;case "esri.layers.GraphicsLayer":m.mixin(g,this._createFeatureCollectionJSON(c));b.push(g);this._legendLayers&&this._legendLayers.push({id:c.id});break;case "esri.layers.VectorTileLayer":e.test(c.serviceUrl)&&(g.url="http://services.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer",b.push(g));break;case "esri.layers.MapImageLayer":var n=
{id:c.id,subLayerIds:[]},l=[];c.allSublayers.forEach(function(a,b){a.visible&&(l.push(a.toJSON()),n.subLayerIds.push(a.id))});m.mixin(g,{layers:l});b.push(g);this._legendLayers.push(n);break;case "esri.layers.WebTileLayer":f=c.urlTemplate.replace(/\$\{/g,"{");m.mixin(g,{type:"WebTiledLayer",urlTemplate:f,credits:c.copyright});c.subDomains&&0<c.subDomains.length&&(g.subDomains=c.subDomains);b.push(g);break;case "esri.layers.FeatureLayer":case "esri.layers.StreamLayer":var p;a.whenLayerView(c).then(function(a){return a.queryGraphics()}).then(function(a){p=
a.map(function(a){a.geometry.hasZ=!1;return a})});m.mixin(g,this._createFeatureCollectionJSON(c,p));b.push(g);this._legendLayers&&this._legendLayers.push({id:c.id});break;default:b.push(g)}return b},_createFeatureCollectionJSON:function(a,d){var b=n.createPolygonLayer(),h=n.createPolylineLayer(),c=n.createPointLayer(),f=n.createMultipointLayer(),g=n.createPointLayer();g.layerDefinition.name="textLayer";delete g.layerDefinition.drawingInfo;"esri.layers.FeatureLayer"===a.declaredClass||"esri.layers.StreamLayer"===
a.declaredClass?b.layerDefinition.name=h.layerDefinition.name=c.layerDefinition.name=f.layerDefinition.name=this._legendLayerNameMap[a.id]||a.get("arcgisProps.title")||a.title:"esri.layers.GraphicsLayer"===a.declaredClass&&(d=a.graphics.items);if(a.renderer&&!m.isFunction(a.get("renderer.attributeField"))){var k=a.renderer.toJSON();b.layerDefinition.drawingInfo.renderer=k;h.layerDefinition.drawingInfo.renderer=k;c.layerDefinition.drawingInfo.renderer=k;f.layerDefinition.drawingInfo.renderer=k}else delete b.layerDefinition.drawingInfo,
delete h.layerDefinition.drawingInfo,delete c.layerDefinition.drawingInfo,delete f.layerDefinition.drawingInfo;k=a.fields;a.renderer&&(!k&&!m.isFunction(a.get("renderer.attributeField")))&&("esri.renderer.ClassBreaksRenderer"===a.renderer.declaredClass?(k=[{name:a.renderer.attributeField,type:"esriFieldTypeDouble"}],a.renderer.normalizationField&&k.push({name:a.renderer.normalizationField,type:"esriFieldTypeDouble"})):"esri.renderer.UniqueValueRenderer"===a.renderer.declaredClass&&(k=[{name:a.renderer.attributeField,
type:"esriFieldTypeString"}],a.renderer.attributeField2&&k.push({name:a.renderer.attributeField2,type:"esriFieldTypeString"}),a.renderer.attributeField3&&k.push({name:a.renderer.attributeField3,type:"esriFieldTypeString"})));k&&(b.layerDefinition.fields=k,h.layerDefinition.fields=k,c.layerDefinition.fields=k,f.layerDefinition.fields=k);for(var k=d&&d.length,e,q=0;q<k;q++){var l=d[q];if(!1!==l.visible&&l.geometry&&(e=l.toJSON(),!e.symbol||!(e.symbol.outline&&"esriCLS"===e.symbol.outline.type))){e.symbol&&
(e.symbol.outline&&e.symbol.outline.color&&e.symbol.outline.color[3])&&(e.symbol.outline.color[3]=255);if(a.renderer&&!e.symbol&&(m.isFunction(a.renderer.attributeField)||a.renderer.hasVisualVariables())){var p=a.renderer,r=p.getSymbol(l);if(!r)continue;e.symbol=r.toJSON();p.hasVisualVariables()&&n.applyVisualVariables(e.symbol,{renderer:p,graphic:l,symbol:r})}e.symbol&&(e.symbol.path?e.symbol=this._convertSvgToPictureMarkerSymbolJson(e.symbol):e.symbol.text&&delete e.attributes);"polygon"===l.geometry.type?
b.featureSet.features.push(e):"polyline"===l.geometry.type?h.featureSet.features.push(e):"point"===l.geometry.type?e.symbol&&e.symbol.text?g.featureSet.features.push(e):c.featureSet.features.push(e):"multipoint"===l.geometry.type?f.featureSet.features.push(e):"extent"===l.geometry.type&&(e.geometry=x.fromExtent(l.geometry).toJSON(),b.featureSet.features.push(e))}}b=[b,h,f,c,g].filter(function(a){return 0<a.featureSet.features.length});b.forEach(function(a){a.layerDefinition.drawingInfo&&a.layerDefinition.drawingInfo.renderer&&
this._convertSvgRenderer(a.layerDefinition.drawingInfo.renderer)},this);return{id:a.id,opacity:a.opacity,minScale:a.minScale||0,maxScale:a.maxScale||0,featureCollection:{layers:b}}},_convertSvgToPictureMarkerSymbolJson:function(a){this._canvasParent||(this._canvasParent=z.create("div"),this._canvasSurface=t.createSurface(this._canvasParent,200,200));var d=this._canvasSurface.createObject(t.Path,a.path).setFill(a.color).setStroke(a.outline);"pendingRender"in this._canvasSurface&&this._canvasSurface._render(!0);
var b=this._canvasSurface.rawNode.getContext("2d"),d=d.getBoundingBox(),h=Math.ceil(d.width+d.x),c=Math.ceil(d.height+d.y),f=b.getImageData(d.x,d.y,h,c);b.canvas.width=h;b.canvas.height=c;b.putImageData(f,0,0);return{type:"esriPMS",imageData:b.canvas.toDataURL("image/png").substr(22),angle:-a.angle,contentType:"image/png",height:a.size?a.size:c-d.y,width:a.size?a.size:h-d.x,xoffset:a.xoffset,yoffset:a.yoffset}},_convertSvgRenderer:function(a){var d=a.type;if("simple"===d&&a.symbol&&a.symbol.path)a.symbol=
this._convertSvgToPictureMarkerSymbolJson(a.symbol);else if("uniqueValue"===d||"classBreaks"===d)d=a["uniqueValue"===d?"uniqueValueInfos":"classBreakInfos"],a.defaultSymbol&&a.defaultSymbol.path&&(a.defaultSymbol=this._convertSvgToPictureMarkerSymbolJson(a.defaultSymbol)),d&&d.forEach(function(a){a&&a.path&&(a.symbol=this._convertSvgToPictureMarkerSymbolJson(a.symbol))},this)},_getPrintDefinition:function(a,d){var b=a.extent,h=a.map,c=a.spatialReference;c&&c.isWrappable&&(b=b.clone()._normalize(!0),
c=b.spatialReference);b={mapOptions:{showAttribution:d.attributionVisible,extent:b&&b.toJSON(),spatialReference:c&&c.toJSON()},operationalLayers:this._createOperationalLayers(a,d)};d.preserveScale&&(b.mapOptions.scale=d.outScale||y.getScale(h));h.timeExtent&&(b.mapOptions.time=[h.timeExtent.startTime.getTime(),h.timeExtent.endTime.getTime()]);return b},_handleExecuteResponse:function(a){return"sync"===this.mode?a.results[0].value:this._geoprocessor.getResultData(a.jobId,"Output_File").then(function(a){return a.value})},
_setPrintParams:function(a){var d=a.template||new B;null==d.showLabels&&(d.showLabels=!0);var b=d.exportOptions,h;b&&(h={outputSize:[b.width,b.height],dpi:b.dpi});var b=d.layoutOptions,c;if(b){var f,g;if("Miles"===b.scalebarUnit||"Kilometers"===b.scalebarUnit)f="Kilometers",g="Miles";else if("Meters"===b.scalebarUnit||"Feet"===b.scalebarUnit)f="Meters",g="Feet";c={titleText:b.titleText,authorText:b.authorText,copyrightText:b.copyrightText,customTextElements:b.customTextElements,scaleBarOptions:{metricUnit:v.toJSON(f),
metricLabel:u[f],nonMetricUnit:v.toJSON(g),nonMetricLabel:u[g]}}}f=null;b&&b.legendLayers&&(f=b.legendLayers.map(function(a){this._legendLayerNameMap[a.layerId]=a.title;var b={id:a.layerId};a.subLayerIds&&(b.subLayerIds=a.subLayerIds);return b},this));b=this._getPrintDefinition(a.view,d);a.outSpatialReference&&(b.mapOptions.spatialReference=a.outSpatialReference.toJSON());m.mixin(b,{exportOptions:h,layoutOptions:c});m.mixin(b.layoutOptions,{legendOptions:{operationalLayers:null!=f?f:this._legendLayers}});
d={Web_Map_as_JSON:JSON.stringify(b),Format:d.format,Layout_Template:D.toJSON(d.layout)};a.extraParameters&&m.mixin(d,a.extraParameters);return d}})});