// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("../core/declare ../core/lang ../core/kebabDictionary dojo/_base/array dojo/_base/lang ../symbols/support/jsonUtils ./Renderer".split(" "),function(n,e,g,p,h,f,q){var k=g({esriNormalizeByLog:"log",esriNormalizeByPercentOfTotal:"percent-of-total",esriNormalizeByField:"field"}),l=g({esriClassifyNaturalBreaks:"natural-breaks",esriClassifyEqualInterval:"equal-interval",esriClassifyQuantile:"quantile",esriClassifyStandardDeviation:"standard-deviation",esriClassifyGeometricalInterval:"geometrical-interval"}),
m=n(q,{declaredClass:"esri.renderer.ClassBreaksRenderer",properties:{backgroundFillSymbol:{value:null,json:{read:f.read,write:function(a,b,c){if(a=f.write(a,{},c))b.backgroundFillSymbol=a}}},classBreakInfos:{set:function(a){this._symbols={};a&&a.forEach(this._processCBInfo,this);this._set("classBreakInfos",a)},json:{readFrom:["classBreakInfos","minValue"],read:function(a,b,c){var d=b.minValue;if(a&&Array.isArray(a)){var r=a[0]&&null!=a[0].classMaxValue;return a.map(function(a){a=e.clone(a);if(r){var g=
a.classMaxValue;a.minValue=d;d=a.maxValue=g}a.symbol=f.read(a.symbol,b,c);return a})}return a},write:function(a,b,c){a=this.classBreakInfos||[];var d=a[0]&&a[0].minValue;b.minValue=-Infinity===d?-Number.MAX_VALUE:d;b.classBreakInfos=p.map(a,function(a){a=e.clone(a);a.symbol&&(a.symbol=f.write(a.symbol,{},c));a.classMaxValue=Infinity===a.maxValue?Number.MAX_VALUE:a.maxValue;delete a.minValue;delete a.maxValue;return e.fixJson(a)})}}},classificationMethod:{value:null,json:{read:l.fromJSON,write:function(a,
b){var c=l.toJSON(a);c&&(b.classificationMethod=c)}}},defaultLabel:{value:null,json:{writable:!0}},defaultSymbol:{value:null,json:{read:f.read,write:function(a,b,c){if(a=f.write(a,{},c))b.defaultSymbol=a}}},expression:{value:null,json:{writable:!0}},expressionTree:{dependsOn:["expression"],get:function(){return this.expression?this._parseExpr(this.expression,{vars:{$feature:"any"}}):null}},field:{value:null,json:{writable:!0}},isMaxInclusive:!0,normalizationField:{value:null,json:{writable:!0}},normalizationTotal:{value:null,
json:{writable:!0}},normalizationType:{value:null,dependsOn:["normalizationField","normalizationTotal"],get:function(){var a=this._get("normalizationType"),b=!!this.normalizationField,c=null!=this.normalizationTotal;if(b||c)a=b&&"field"||c&&"percent-of-total",b&&c&&console.warn("warning: both normalizationField and normalizationTotal are set!");else if("field"===a||"percent-of-total"===a)a=null;return a},json:{read:k.fromJSON,write:function(a,b){var c=k.toJSON(a);c&&(b.normalizationType=c)}}},requiredFields:{dependsOn:["field",
"normalizationField"]},type:"classBreaks"},constructor:function(){this._symbols={};this.classBreakInfos=[]},addClassBreakInfo:function(a,b,c){a=h.isObject(a)?a:{minValue:a,maxValue:b,symbol:c};this.classBreakInfos.push(a);this._processCBInfo(a)},removeClassBreakInfo:function(a,b){var c,d,f=this.classBreakInfos.length,e=this._symbols;for(d=0;d<f;d++)if(c=[this.classBreakInfos[d].minValue,this.classBreakInfos[d].maxValue],c[0]==a&&c[1]==b){delete e[a+"-"+b];this.classBreakInfos.splice(d,1);break}},
getBreakIndex:function(a){var b=this.field,c=a.attributes,d=this.classBreakInfos.length,f=this.isMaxInclusive;if(this.expression)a=this._executeExpr(this.expressionTree,this._createExprContext(a));else if(h.isFunction(b))a=b(a);else{a=parseFloat(c[b]);var b=this.normalizationType,e;b&&(e=parseFloat(this.normalizationTotal),c=parseFloat(c[this.normalizationField]),"log"===b?a=Math.log(a)*Math.LOG10E:"percent-of-total"===b&&!isNaN(e)?a=100*(a/e):"field"===b&&!isNaN(c)&&(a/=c))}for(c=0;c<d;c++)if(b=
[this.classBreakInfos[c].minValue,this.classBreakInfos[c].maxValue],b[0]<=a&&(f?a<=b[1]:a<b[1]))return c;return-1},getClassBreakInfo:function(a){a=this.getBreakIndex(a);return-1!==a?this.classBreakInfos[a]:null},getSymbol:function(a){a=this.getBreakIndex(a);return(a=-1<a&&[this.classBreakInfos[a].minValue,this.classBreakInfos[a].maxValue])?this._symbols[a[0]+"-"+a[1]]:this.defaultSymbol},clone:function(){return new m({field:this.field,backgroundFillSymbol:this.backgroundFillSymbol&&this.backgroundFillSymbol.clone(),
classificationMethod:this.classificationMethod,defaultLabel:this.defaultLabel,defaultSymbol:this.defaultSymbol&&this.defaultSymbol.clone(),expression:this.expression,classBreakInfos:e.clone(this.classBreakInfos),isMaxInclusive:this.isMaxInclusive,normalizationField:this.normalizationField,normalizationTotal:this.normalizationTotal,normalizationType:this.normalizationType,visualVariables:e.clone(this.visualVariables)})},collectRequiredFields:function(a){this.inherited(arguments);[this.field,this.normalizationField].forEach(function(b){b&&
(a[b]=!0)})},_processCBInfo:function(a){var b=a.minValue,c=a.maxValue,d=a.symbol;d&&!d.declaredClass&&(a.symbol=f.fromJSON(d));this._symbols[b+"-"+c]=a.symbol}});return m});