// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("../core/declare ../core/Accessor ../core/JSONSupport ../core/kebabDictionary ../core/screenUtils ../core/lang dojo/_base/lang ../Color ../arcade/arcade".split(" "),function(D,E,F,v,w,B,q,k,t){var r=v({sizeInfo:"size",colorInfo:"color",transparencyInfo:"opacity",rotationInfo:"rotation"}),C=v({widthAndDepth:"width-and-depth"}),y=Math.PI;return D([E,F],{declaredClass:"esri.renderer.Renderer",properties:{authoringInfo:{value:null,json:{write:function(a,b){a=B.clone(a);a.visualVariables&&a.visualVariables.forEach(function(a){"opacity"===
a.type&&(a.type=r.toJSON(a.type))});b.authoringInfo=a}}},requiredFields:{dependsOn:["visualVariables"],get:function(){var a=Object.create(null);this.collectRequiredFields(a);return Object.keys(a)}},type:{readOnly:!0,json:{readable:!1,writeAlways:!0}},visualVariables:{json:{readFrom:["visualVariables","rotationType","rotationExpression"],read:function(a,b){return this._readVariables(a,b)},write:function(a,b){var c=[];a.forEach(function(a){"size"===a.type?c.push(this._writeSizeInfo(a)):"color"===a.type?
c.push(this._writeColorInfo(a)):"opacity"===a.type?c.push(this._writeOpacityInfo(a)):"rotation"===a.type&&c.push(this._writeRotationInfo(a))},this);b.visualVariables=c}}}},constructor:function(){this._ipDataCache={}},_rotationRE:/^\[([^\]]+)\]$/i,_meterIn:{inches:39.3701,feet:3.28084,yards:1.09361,miles:6.21371E-4,"nautical-miles":5.39957E-4,millimeters:1E3,centimeters:100,decimeters:10,meters:1,kilometers:0.0010,"decimal-degrees":180/20015077},_scaleExpr:"view.scale",_visualVariablesSetter:function(a){var b=
this._ipDataCache;this.visualVariables&&this.visualVariables.forEach(function(a,d){b.hasOwnProperty(d)&&(b[d]=null)},this);a&&a.some(function(a){return!!a.target})&&a.sort(function(a,b){return a.target===b.target?0:a.target?1:-1});a&&a.forEach(function(a,d){"color"===a.type?b[d]=this._processColorInfo(a):"opacity"===a.type?b[d]=this._processOpacityInfo(a):"size"===a.type&&(b[d]=this._processSizeInfo(a))},this);this._set("visualVariables",a)},getSymbol:function(a){},getVisualVariableValues:function(a,
b){var c=this.visualVariables,d;c&&(d=c.map(function(c){var d,n=c.type,x=n+"Info";b=q.mixin({},b);b[x]=c;switch(n){case "size":d=this.getSize(a,b);break;case "color":d=this.getColor(a,b);break;case "opacity":d=this.getOpacity(a,b);break;case "rotation":d=this.getRotationAngle(a,b)}return{variable:c,value:d}},this).filter(function(a){return null!=a.value},this));return d},hasVisualVariables:function(a,b){return a?!!this.getVisualVariablesForType(a,b):!(!this.getVisualVariablesForType("size",b)&&!this.getVisualVariablesForType("color",
b)&&!this.getVisualVariablesForType("opacity",b)&&!this.getVisualVariablesForType("rotation",b))},getVisualVariablesForType:function(a,b){var c=this.visualVariables,d;c&&(d=c.filter(function(c){return c.type===a&&("string"===typeof b?c.target===b:!1===b?!c.target:!0)}))&&0===d.length&&(d=void 0);return d},getSize:function(a,b){var c=this._getVarInfo(b&&b.sizeInfo,"size"),d=c.variable,c=this._ipDataCache[c.cacheKey],e=null;if(d)var g=d.minSize,e=d.maxSize,g="object"===typeof g&&g?this._getSize(a,g,
c&&c.minSize,b):g,e="object"===typeof e&&e?this._getSize(a,e,c&&c.maxSize,b):e,e=this._getSize(a,d,c&&c.root,b,[g,e]);return e},getSizeRangeAtScale:function(a,b){var c,d=this._getVarInfo(a,"size"),e=this._ipDataCache[d.cacheKey],g={scale:b};if((a=d.variable)&&b){var n=a.minSize,d=a.maxSize,n="object"===typeof n&&n?this._getSize({},n,e&&e.minSize,g):n,e="object"===typeof d&&d?this._getSize({},d,e&&e.maxSize,g):d;if(null!=n||null!=e)c={minSize:n,maxSize:e}}return c},getColor:function(a,b){var c=this._getVarInfo(b&&
b.colorInfo,"color");return this._getColorComponent(a,c.variable,this._ipDataCache[c.cacheKey])},getOpacity:function(a,b){var c=this._getVarInfo(b&&b.opacityInfo,"opacity");return this._getColorComponent(a,c.variable,this._ipDataCache[c.cacheKey],!0)},getRotationAngle:function(a,b){var c=this._getVarInfo(b&&b.rotationInfo,"rotation").variable,d="arithmetic"===c.rotationType,c=c.field,e=a.attributes,g=0;c&&(q.isFunction(c)?g=c.apply(this,arguments):e&&(g=e[c]||0),g=(g+(d?-90:0))*(d?-1:1));return g},
collectRequiredFields:function(a){var b=[];this.visualVariables&&(b=b.concat(this.visualVariables));b.forEach(function(b){b&&b.field&&(a[b.field]=!0);b&&b.normalizationField&&(a[b.normalizationField]=!0)})},_getVarInfo:function(a,b){var c;a&&a.type===b&&this.visualVariables?(c=this.visualVariables.indexOf(a),a=this.visualVariables[c]):this.visualVariables&&(a=(c=this.getVisualVariablesForType(b))&&c[0],c=this.visualVariables.indexOf(a));return{variable:a,cacheKey:c}},_readSizeInfo:function(a){a.axis&&
(a.axis=C.fromJSON(a.axis));return a},_readColorInfo:function(a){a&&(a.colors&&a.colors.forEach(function(b,c){q.isArray(b)?a.colors[c]=k.fromJSON(b):a.colors[c]=new k(b)}),a.stops&&a.stops.forEach(function(b,c){b.color&&q.isArray(b.color)?a.stops[c].color=k.fromJSON(b.color):b.color&&(a.stops[c].color=new k(b.color))}));return a},_readOpacityInfo:function(a){var b;a&&(b=q.mixin({},a),b.transparencyValues&&(b.opacityValues=b.transparencyValues.map(function(a){return 1-a/100}),delete b.transparencyValues),
b.stops&&(b.stops=b.stops.map(function(a){a=q.mixin({},a);a.opacity=1-a.transparency/100;delete a.transparency;return a})));return b},_readVariables:function(a,b){a&&(a=a.map(function(a){a=B.clone(a);a.type=r.fromJSON(a.type);"size"===a.type?a=this._readSizeInfo(a):"color"===a.type?a=this._readColorInfo(a):"opacity"===a.type&&(a=this._readOpacityInfo(a));return a},this));var c=b.rotationType,d=b.rotationExpression;if(d&&(c={type:"rotation",rotationType:c},(d=d.match(this._rotationRE))&&d[1]))c.field=
d[1],a||(a=[]),a.push(c);return a},_processColorInfo:function(a){a&&(a.colors&&a.colors.forEach(function(b,c){b instanceof k||(a.colors[c]=new k(b))}),a.stops&&a.stops.forEach(function(b,c){b.color&&!(b.color instanceof k)&&(a.stops[c].color=new k(b.color))}),this._sortStops(a.stops));return this._interpolateData(a)},_processOpacityInfo:function(a){this._sortStops(a&&a.stops);return this._interpolateData(a)},_processSizeInfo:function(a){a.stops&&Array.isArray(a.stops)?a.stops=this._processSizeInfoStops(a.stops):
(a.minSize=a.minSize&&this._processSizeInfoSize(a.minSize),a.maxSize=a.maxSize&&this._processSizeInfoSize(a.maxSize));return{root:this._interpolateData(a),minSize:this._interpolateData(a.minSize),maxSize:this._interpolateData(a.maxSize)}},_processSizeInfoSize:function(a){"object"===typeof a?a.stops=this._processSizeInfoStops(a.stops):a=w.toPt(a);return a},_processSizeInfoStops:function(a){a&&Array.isArray(a)&&(a.forEach(function(a){a.size=w.toPt(a.size)}),this._sortStops(a));return a},_sortStops:function(a){a&&
Array.isArray(a)&&a.sort(function(a,c){return a.value-c.value})},_getSize:function(a,b,c,d,e){var g=a.attributes,n=b.field,x=b.expression,h=b.stops,f=0,k="number"===typeof a,l=k?a:null;if(n||x){var r=d&&d.scale,m=e?e[0]:b.minSize,p=e?e[1]:b.maxSize,s=b.minDataValue,t=b.maxDataValue,v=b.valueUnit||"unknown",A=b.valueRepresentation,f=b.scaleBy,w=b.normalizationField,z=g?parseFloat(g[w]):void 0,u=d&&d.shape;x&&(l=x.toLowerCase()===this._scaleExpr?null==r?this._getAverageValue(b):r:null);"number"!==typeof l&&
(q.isFunction(n)?l=n.apply(this,arguments):g&&(l=g[n]));if(null==l||w&&!k&&(isNaN(z)||0===z))return null;!isNaN(z)&&!k&&(l/=z);if(h)p=this._lookupData(l,c),l=p[0],m=p[1],l===m?f=h[l].size:(l=h[l].size,h=h[m].size,f=l+(h-l)*p[2]);else if(null!=m&&null!=p&&null!=s&&null!=t)l<=s?f=m:l>=t?f=p:(h=(l-s)/(t-s),"area"===f&&u?(m=(l="circle"===u)?y*Math.pow(m/2,2):m*m,p=l?y*Math.pow(p/2,2):p*p,h=m+h*(p-m),f=l?2*Math.sqrt(h/y):Math.sqrt(h)):f=m+h*(p-m));else if("unknown"===v)null!=m&&null!=s?(m&&s?(h=l/s,f=
"circle"===u?2*Math.sqrt(h*Math.pow(m/2,2)):"square"===u||"diamond"===u||"image"===u?Math.sqrt(h*Math.pow(m,2)):h*m):f=l+(m||s),f=f<m?m:f,null!=p&&f>p&&(f=p)):f=l;else{h=(d&&d.resolution?d.resolution:1)*this._meterIn[v];if("area"===A)f=Math.sqrt(l/y)/h,f*=2;else if(f=l/h,"radius"===A||"distance"===A)f*=2;null!=m&&f<m&&(f=m);null!=p&&f>p&&(f=p)}}else b&&(f=h&&h[0]&&h[0].size,null==f&&(f=b.minSize));return f=isNaN(f)?0:f},_getAverageValue:function(a){var b=a.stops,c;b?(c=b[0].value,a=b[b.length-1].value):
(c=a.minDataValue||0,a=a.maxDataValue||0);return(c+a)/2},_getColorComponent:function(a,b,c,d,e){var g=a.attributes,n=b&&b.field,k="number"===typeof a?a:null,h;if(n){var f=b.normalizationField,r=g?parseFloat(g[f]):void 0;"number"!==typeof k&&(q.isFunction(n)?k=n.apply(this,arguments):g&&(k=g[n]));null!=k&&(f&&(!isNaN(r)&&0!==r)&&(k/=r),h=d?this._getOpacity(k,b,c):this._getColor(k,b,c))}else b&&(g=b.stops,d?(h=g&&g[0]&&g[0].opacity,null==h&&(h=b.opacityValues&&b.opacityValues[0])):h=g&&g[0]&&g[0].color||
b.colors&&b.colors[0]);e&&(e.data=k,e.value=h);return e||h},_interpolateData:function(a){var b;if(a)if(a.colors||a.opacityValues){var c=(a.colors||a.opacityValues).length,d=a.minDataValue,e=(a.maxDataValue-d)/(c-1);b=[];for(a=0;a<c;a++)b[a]=d+a*e}else a.stops&&(b=a.stops.map(function(a){return a.value}));return b},_getOpacity:function(a,b,c){a=this._lookupData(a,c);var d;b=b||this.opacityInfo;a&&(c=a[0],d=a[1],c===d?d=this._getOpacValue(b,c):(c=this._getOpacValue(b,c),b=this._getOpacValue(b,d),d=
c+(b-c)*a[2]));return d},_getOpacValue:function(a,b){return a.opacityValues?a.opacityValues[b]:a.stops[b].opacity},_getColor:function(a,b,c){a=this._lookupData(a,c);var d;b=b||this.colorInfo;a&&(d=a[0],c=a[1],d=d===c?this._getColorObj(b,d):k.blendColors(this._getColorObj(b,d),this._getColorObj(b,c),a[2]),d=new k(d));return d},_getColorObj:function(a,b){return a.colors?a.colors[b]:a.stops[b].color},_lookupData:function(a,b){var c;if(b){var d=0,e=b.length-1;b.some(function(b,c){if(a<b)return e=c,!0;
d=c;return!1});c=[d,e,(a-b[d])/(b[e]-b[d])]}return c},_writeRotationInfo:function(a){a&&(a=q.mixin({},a),a.type=r.toJSON(a.type));return a},_writeSizeInfo:function(a){if(a){a=q.mixin({},a);var b=a.legendOptions,c=a.axis;a.type=r.toJSON(a.type);c&&(a.axis=C.toJSON(c));if(b&&(a.legendOptions=q.mixin({},b),b=b.customValues))a.legendOptions.customValues=b.slice(0)}return a},_writeColorInfo:function(a){a&&(a=q.mixin({},a),a.type=r.toJSON(a.type),a.colors&&(a.colors=a.colors.map(function(a){return k.toJSON(a)})),
a.stops&&(a.stops=a.stops.map(function(a){a=q.mixin({},a);a.color&&(a.color=k.toJSON(a.color));return a})));return a},_writeOpacityInfo:function(a){var b;a&&(b=q.mixin({},a),b.type=r.toJSON(b.type),b.opacityValues&&(b.transparencyValues=b.opacityValues.map(function(a){return 100*(1-a)}),delete b.opacityValues),b.stops&&(b.stops=b.stops.map(function(a){a=q.mixin({},a);a.transparency=100*(1-a.opacity);delete a.opacity;return a})));return b},_createExprContext:function(a){return{vars:{$feature:t.constructFeature(a)}}},
_parseExpr:function(a,b){return t.parseScript(a,b)},_executeExpr:function(a,b){return t.executeScript(a,b,-1)}})});