// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("../../layers/LayerView ../../../geometry/Extent ../../../core/urlUtils ../../../core/HandleRegistry ../../../layers/support/ExportImageParameters ./support/projectExtentUtils ../lib/glMatrix ../webgl-engine/Stage ../webgl-engine/lib/Texture ../webgl-engine/lib/RenderGeometry ../webgl-engine/lib/GeometryData ../webgl-engine/lib/GeometryUtil ../webgl-engine/materials/Material ../webgl-engine/lib/Util".split(" "),function(k,z,t,A,B,C,D,l,E,F,G,H,I,p){var q=p.assert,J=D.mat4d,m=p.VertexAttrConstants;
k=k.createSubclass({declaredClass:"esri.views.3d.layers.DynamicLayerView3D",supportsDraping:!0,hasDraped:!0,drawingOrder:0,_updatingOverlay:!1,_handles:null,_exportImageParameters:null,_imageVersion:null,constructor:function(){this._extents=[];this._images=[];this.fullExtentInViewSpatialReference=null;this._handles=new A},initialize:function(){this.drawingOrder=this.view.getDrawingOrder(this.layer.uid);this._handles.add(this.watch("suspended",function(a){if(a)this.clear(),this.emit("draped-data-change");
else{a=this._extents.length;for(var c=0;c<a;c++)this.fetch(c)}}.bind(this)));this._exportImageParameters=new B({layer:this.layer});var a=this.notifyChange.bind(this,"suspended");this._handles.add([this.watch("fullOpacity",this._opacityChangeHandler.bind(this)),this.layer.watch("minScale",a),this.layer.watch("maxScale",a),this._exportImageParameters.watch("version",function(a){this._imageVersion!==a&&(this._imageVersion=a,this._refetch())}.bind(this))],"layer");this.view.resourceController.registerIdleFrameWorker(this,
{idleBegin:function(){this._hasScaleRange()&&this.notifyChange("suspended")}});(a=C.toView(this).then(function(a){this.fullExtentInViewSpatialReference=a}.bind(this)))&&this.addResolvingPromise(a)},destroy:function(){this.clear();this._handles.destroy();this.view.resourceController.deregisterIdleFrameWorker(this);this._exportImageParameters&&(this._exportImageParameters.layer=null,this._exportImageParameters.destroy(),this._exportImageParameters=null)},getPopupData:function(a){var b=this.view.scale;
return this.layer.allSublayers.filter(function(a){var d=0===a.minScale||b<=a.minScale,e=0===a.maxScale||b>=a.maxScale;return a.popupTemplate&&a.visible&&d&&e}).map(function(c){var b=c.createQuery();b.geometry=a;b.outFields=this.getTemplateOutFields(c.popupTemplate);return c.queryFeatures(b).then(function(a){return a.features})},this)},getTemplateOutFields:function(a){if(!a||!a.fieldInfos)return["*"];var b=[];a.fieldInfos.forEach(function(a){var d=a.fieldName&&a.fieldName.toLowerCase();d&&("shape"!==
d&&0!==d.indexOf("relationships/"))&&b.push(a.fieldName)});return b},setDrapingExtent:function(a,b,c,d){var e=(b[2]-b[0])/(b[3]-b[1]);this._extents[a]={extent:b,spatialReference:c,imageSize:1.0001<e?[d,d/e]:0.9999>e?[d*e,d]:[d,d]};this.suspended||this.fetch(a)},fetch:function(a){var b=this._extents[a],c=b.extent,d=new z(c[0],c[1],c[2],c[3],b.spatialReference);this._exportImageParameters.scale!==this.view.scale&&(this._exportImageParameters.scale=this.view.scale);this._imageVersion=this._exportImageParameters.version;
this.layer.getImageUrl({extent:d,width:b.imageSize[0],height:b.imageSize[1],exportImageParameters:this._exportImageParameters},function(b){this._images[a]||(this._images[a]={texture:null,material:null,rendergeometry:null,domImage:null,worldExtent:c,loading:!1});var d=this._images[a],g=d.domImage||new Image;0!==b.indexOf("data:")&&t.canUseXhr(b)&&(g.crossOrigin="anonymous");g.src=t.normalize(b);d.loading=!0;g.onload=function(){q(d.domImage===g);d.worldExtent=c;this._createStageObjects(a,g);0===a&&
(this._images[1]&&this._images[1].rendergeometry)&&this._createStageObjects(1,null);d.loading=!1;this._evaluateUpdatingState();this.emit("draped-data-change")}.bind(this);g.onerror=function(){d.loading=!1;this._clearDomImage(d);this._evaluateUpdatingState()}.bind(this);d.domImage=g;this._evaluateUpdatingState()}.bind(this))},clear:function(){for(var a in this._images)this.clearImage(a)},clearImage:function(a){if(a=this._images[a])a.htmlImage&&(a.htmlImage.removeAttribute("src"),a.htmlImage.removeAttribute("onload"),
a.htmlImage.removeAttribute("onerror"),a.htmlImage=null),a.rendergeometry&&(this.view._stage.getTextureGraphicsRenderer().removeRenderGeometries([a.rendergeometry]),a.rendergeometry=null),a.texture&&(this.view._stage.remove(l.ModelContentType.TEXTURE,a.texture.getId()),a.texture=null),a.material&&(this.view._stage.remove(l.ModelContentType.MATERIAL,a.material.getId()),a.material=null),this._clearDomImage(a),a.loading=!1},canResume:function(){if(!this.inherited(arguments))return!1;var a=this.layer.minScale,
b=this.layer.maxScale;if(0<a||0<b){var c=this.view.scale;if(c<b||0<a&&c>a)return!1}return!0},_refetch:function(){for(var a=0;a<this._extents.length;a++)this._extents[a]&&this.fetch(a)},_drawingOrderSetter:function(a,b){if(a!==b){var c={};this._images.forEach(function(b){b&&b.material&&(b.material.setRenderPriority(a),c[b.material.getId()]=!0)});p.objectEmpty(c)||(this.view._stage.getTextureGraphicsRenderer().updateRenderOrder(c),this.emit("draped-data-change"))}return a},_hasScaleRange:function(){return 0<
this.get("layer.minScale")||0<this.get("layer.maxScale")},_opacityChangeHandler:function(a){this._images.forEach(function(b){b&&b.material&&b.material.setParameterValues({opacity:a})}.bind(this));this.emit("draped-data-change")},_clearDomImage:function(a){a.domImage&&(a.domImage.removeAttribute("src"),a.domImage.removeAttribute("onload"),a.domImage.removeAttribute("onerror"),a.domImage=null)},_evaluateUpdatingState:function(){this.notifyChange("updating")},isUpdating:function(){if(this._updatingOverlay)return!0;
var a=!1,b;for(b in this._images)if(this._images[b].loading){a=!0;break}return a},_createStageObjects:function(a,b){var c=this.view._stage,d=c.getTextureGraphicsRenderer(),e=this._images[a];b?(e.texture&&c.remove(l.ModelContentType.TEXTURE,e.texture.getId()),e.texture=new E(b,"dynamicMapLayer",{width:b.width,height:b.height}),c.add(l.ModelContentType.TEXTURE,e.texture)):q(e.texture);e.material?b&&e.material.setParameterValues({textureId:e.texture.getId()}):(e.material=new I({ambient:[1,1,1],diffuse:[0,
0,0],transparent:!0,opacity:this.fullOpacity,textureId:e.texture.getId()},"dynamicMapLayer"),e.material.setRenderPriority(this.drawingOrder),c.add(l.ModelContentType.MATERIAL,e.material));if(0===a)c=e.worldExtent,c=H.createSquareGeometry([[c[0],c[1],-1],[c[2],c[1],-1],[c[2],c[3],-1],[c[0],c[3],-1]],!0);else{q(1===a);c=this._images[0].worldExtent;if(!c)return;c=K(c,e.worldExtent,-1)}var f=new F(c);f.material=e.material;f.origin={vec3:[0,0,0],id:"0_0"};f.transformation=J.identity();f.name="dynamicMapLayer";
f.uniqueName="dynamicMapLayer#"+c.id;d.addRenderGeometries([f]);e.rendergeometry&&d.removeRenderGeometries([e.rendergeometry]);e.rendergeometry=f}});var K=function(){var a=new Float32Array([0,0,1]);return function(b,c,d){var e=[b[1]-c[1],b[3]-b[1],c[3]-b[3],123456],f=[b[0]-c[0],b[2]-b[0],c[2]-b[2],123456],g=c[2]-c[0],l=c[3]-c[1],u=0<f[0]&&0<f[2]?3:2;b=0<e[0]&&0<e[2]?3:2;var r=(b+1)*(u+1),h=new Float32Array(3*r),r=new Float32Array(2*r);b=new Uint32Array(6*(b*u-1));for(var x=0,k=0,p=0,n=0,s=0,v=0;4>
v;v++){var q=e[v];if(!(0>=q)){for(var y=0,w=0;4>w;w++){var t=f[w];0>=t||(h[k++]=c[0]+y,h[k++]=c[1]+x,h[k++]=d,r[p++]=y/g,r[p++]=x/l,3>w&&(3>v&&!(1===w&&1===v))&&(b[s++]=n,b[s++]=n+1,b[s++]=n+u+1,b[s++]=n+1,b[s++]=n+u+2,b[s++]=n+u+1),n++,y+=t)}x+=q}}c={};c[m.POSITION]={size:3,data:h};c[m.NORMAL]={size:3,data:a};c[m.UV0]={size:2,data:r};d={};e=new Uint32Array(b.length);for(h=0;h<e.length;h++)e[h]=0;d[m.POSITION]=b;d[m.NORMAL]=e;d[m.UV0]=b;return{faces:{type:"triangle",indices:d,positionKey:m.POSITION},
vertexAttr:c,id:G.getNewId().toString()}}}();return k});