// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/accessorSupport/decorators dojo/promise/all ./graphics/Graphics3DSpatialIndex ./graphics/Graphics3DLayerViewCore ./graphics/graphicUtils ./support/LayerViewUpdatingPercentage ../../layers/GraphicsLayerView ../../../layers/FeatureLayer ../../../layers/graphics/controllers/SnapshotController ../support/PromiseLightweight ../../../core/watchUtils ./support/projectExtentUtils ../../../core/Error ../../../core/promiseUtils ../../../layers/graphics/QueryEngine".split(" "),
function(B,C,n,g,f,p,q,r,s,t,u,v,w,x,y,z,h,k,A){return function(m){function a(){m.call(this);this.controller=null;this.supportsDraping=!0;this._overlayUpdating=null;this._progressMaxNumNodes=0;this._eventHandles=[];this._controllerClientSideFiltering=!1;this.fullExtentInViewSpatialReference=this._suspendResumeExtent=null;this._isUpdating=!1}n(a,m);Object.defineProperty(a.prototype,"drawingOrder",{set:function(c){this.layerViewCore.graphicsCore.setDrawingOrder(c);this._set("drawingOrder",c)},enumerable:!0,
configurable:!0});Object.defineProperty(a.prototype,"hasDraped",{get:function(){return this.layerViewCore.graphicsCore.hasDraped},enumerable:!0,configurable:!0});a.prototype.initialize=function(){var c=this;this.spatialIndex=new q;this.layerViewCore=new r({owner:this,layer:this.layer,spatialIndex:this.spatialIndex,frustumVisibilityEnabled:!0,scaleVisibilityEnabled:!0,labelingEnabled:this.layer.isInstanceOf(v),elevationAlignmentEnabled:!0,verticalScaleEnabled:!0,updateSuspendResumeExtent:function(){return c.updateSuspendResumeExtent()},
updateClippingExtent:function(a){return c.updateClippingExtent(a)}});this.layerViewCore.initialize();this.drawingOrder=this.view.getDrawingOrder(this.layer.uid);this.createController();this.layerViewCore.labeling&&this.addResolvingPromise(this.layerViewCore.labeling.initLabelingInfo());this.addResolvingPromise(this.validateMaximumFeatureCount());this.addResolvingPromise(this.validateGeometryType());var a=z.toView(this).then(function(a){c.fullExtentInViewSpatialReference=a});a&&this.addResolvingPromise(a);
this._evaluateUpdatingState()};a.prototype.destroy=function(){this._eventHandles.forEach(function(c){return c.remove()});this._eventHandles=null;this.controller&&(this.controller.destroy(),this.controller=null);this.layerViewCore&&(this.layerViewCore.destroy(),this.layerViewCore=null);this.spatialIndex&&(this.spatialIndex.destroy(),this.spatialIndex=null);this.loadedGraphics=null};a.prototype.getRenderingInfo=function(c){var a=this.inherited(arguments);if(a&&a.color){var b=a.color;a.color=[b.r/255,
b.g/255,b.b/255,b.a]}return a};a.prototype.getGraphicsFromStageObject=function(a,d){var b=a.getMetadata().graphicId,e=null;this.loadedGraphics&&this.loadedGraphics.some(function(a){return a.uid===b?(e=a,!0):!1});var l=new x.Promise;null!==e?l.done(e):l.reject();return l};a.prototype.getGraphics3DGraphics=function(){return this.layerViewCore.graphicsCore.getGraphics3DGraphics()};a.prototype.getGraphics3DGraphicsKeys=function(){return this.layerViewCore.graphicsCore.getGraphics3DGraphicsKeys()};a.prototype.queryGraphics=
function(){return this._queryEngine?this._queryEngine.queryFeatures():this._rejectQuery()};a.prototype.queryFeatures=function(a){return this._queryEngine?this._queryEngine.queryFeatures(a):this._rejectQuery()};a.prototype.queryObjectIds=function(a){return this._queryEngine?this._queryEngine.queryObjectIds(a):this._rejectQuery()};a.prototype.queryFeatureCount=function(a){return this._queryEngine?this._queryEngine.queryFeatureCount(a):this._rejectQuery()};a.prototype.queryExtent=function(a){return this._queryEngine?
this._queryEngine.queryExtent(a):this._rejectQuery()};a.prototype.whenGraphicBounds=function(a){return this.layerViewCore.graphicsCore.whenGraphicBounds(a)};a.prototype._rejectQuery=function(){return k.reject(new h("FeatureLayerView3D","Not ready to execute query"))};a.prototype._notifySuspendedChange=function(){this.notifyChange("suspended")};a.prototype._notifyDrapedDataChange=function(){this.notifyChange("hasDraped");this.emit("draped-data-change")};a.prototype.canResume=function(){return this.inherited(arguments)&&
this.layerViewCore&&this.layerViewCore.canResume()};a.prototype._evaluateUpdatingState=function(){if(this.layerViewCore.elevationAlignment){var a;a=0+this.layerViewCore.elevationAlignment.numNodesUpdating();a+=this.layerViewCore.graphicsCore.numNodesUpdating();var d;d=(d=(d=this.controller&&this.controller.isQueryInProgress)||this._overlayUpdating)||!(this.view.basemapTerrain&&this.view.basemapTerrain.ready);var b;b=(b=0<a||d)||this.spatialIndex.isUpdating();this._progressMaxNumNodes=Math.max(a,this._progressMaxNumNodes);
0===a&&(this._progressMaxNumNodes=1);this._isUpdating=b;this.notifyChange("updating");this._set("updatingPercentageValue",d?100:100*a/this._progressMaxNumNodes)}else this._isUpdating=!1,this.notifyChange("updating"),this._set("updatingPercentageValue",100)};a.prototype.isUpdating=function(){return this._isUpdating};a.prototype.createController=function(){var a=this,d=this.layer.createGraphicsController({layerView:this,options:{maxPageSize:300,extent:this.view.clippingArea}});y.whenTrueOnce(this.view,
"basemapTerrain.ready",function(){p([a,d]).then(function(b){b=b[1];b instanceof w&&(a.controller=b,a._eventHandles.push(a.controller.watch("isQueryInProgress",function(){return a._evaluateUpdatingState()})));a.loadedGraphics=b.graphics;a._queryEngine=new A({features:a.loadedGraphics,objectIdField:a.layer.objectIdField});a._evaluateUpdatingState()})})};a.prototype.updateClippingExtent=function(a){if(this.controller){if(this._controllerClientSideFiltering)return!1;this.controller.extent?(this.controller.extent=
null,this._controllerClientSideFiltering=!0):this.controller.extent=a;return!0}return!1};a.prototype.updateSuspendResumeExtent=function(){return this._suspendResumeExtent=s.enlargeExtent(this.layerViewCore.graphicsCore.computedExtent,this._suspendResumeExtent,1.2)};a.prototype.validateGeometryType=function(){var a=this.layer;switch(a.geometryType){case "multipatch":case "multipoint":return k.reject(new h("featurelayerview3d:unsupported-geometry-type","Unsupported geometry type ${geometryType}",{geometryType:a.geometryType}))}};
a.prototype.validateMaximumFeatureCount=function(){return 0>a.maximumFeatureCount||!this.layer.url?k.resolve():this.layer.queryFeatureCount().then(function(c){if(c>a.maximumFeatureCount)throw new h("featurelayerview3d:maximum-feature-count-exceeded","The maximum number of allowed features (${maximumFeatureCount}) has been exceeded (layer has ${numberOfFeatures} features)",{maximumFeatureCount:a.maximumFeatureCount,numberOfFeatures:c});})};a.prototype.getStats=function(){var a=this.layerViewCore.graphicsCore.getGraphics3DGraphics(),
d="null",b=this._suspendResumeExtent;b&&(d=[b[0],b[1],b[2],b[3]].map(function(a){return a.toPrecision(4)}).join(", "));var b="null",e=this.layerViewCore.graphicsCore.computedExtent;e&&(b=[e.xmin,e.ymin,e.xmax,e.ymax].map(function(a){return a.toPrecision(4)}).join(", "));return{numCollection:this.loadedGraphics.length,numGraphics:Object.keys(a).length,numElevationUpdating:this.layerViewCore.elevationAlignment.numNodesUpdating(),numSpatialIndexUpdating:this.spatialIndex.numNodesUpdating(),numGraphicsUpdating:this.layerViewCore.graphicsCore.numNodesUpdating(),
visibilityFrustum:this.layerViewCore.frustumVisibility.canResume(),visibilityScale:this.layerViewCore.scaleVisibility.canResume(),resumeExtent:d,computedExtent:b,updating:this.updating,suspended:this.suspended}};a.maximumFeatureCount=-1;g([f.property()],a.prototype,"drawingOrder",null);g([f.property()],a.prototype,"loadedGraphics",void 0);g([f.property()],a.prototype,"hasDraped",null);g([f.property()],a.prototype,"controller",void 0);return a=g([f.subclass("esri.views.3d.layers.FeatureLayerView3D")],
a)}(f.declared(u,t))});