// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/accessorSupport/decorators ../../../core/watchUtils ../../../core/promiseUtils ../../../core/Logger ../../../core/lang dojo/_base/lang dojox/color/_base dojo/has ../../layers/LayerView ../../../Graphic ../../../symbols/Symbol3D ./i3s/I3SUtil ./i3s/I3SBinaryReader ./i3s/I3SProjectionUtil ./graphics/graphicUtils ./support/LayerViewUpdatingPercentage ../support/projectionUtils ../support/aaBoundingBox ../webgl-engine/Stage ../webgl-engine/lib/Layer ../webgl-engine/lib/Geometry ../webgl-engine/lib/GeometryData ../webgl-engine/lib/Object3D ../webgl-engine/lib/Texture ../webgl-engine/materials/Material ../webgl-engine/lib/Util ../webgl-engine/lib/base64Binary ../lib/glMatrix ../../../layers/IntegratedMeshLayer".split(" "),
function(va,wa,ea,C,B,N,E,fa,ga,ha,ia,ja,ka,W,la,I,S,O,X,ma,T,Y,U,na,oa,pa,qa,M,ra,r,xa,H,V){function Z(k,e,a,b){var d=!1,c;e.encoding===I.DDS_ENCODING_STRING?c=M.DDS_ENCODING:d=!($(k.width)&&$(k.height));k=e.usedByEngineMats.some(function(a){return a.getParams().atlasRegions})||e.atlas;a=(a||!k)&&!d;return{mipmap:a,wrapClamp:k||!e.wrap,disableAnisotropy:k&&a&&b,encoding:c,noUnpackFlip:!0}}function aa(k,e){for(var a=e.toLowerCase(),b=0,d=Object.keys(k);b<d.length;b++){var c=d[b];if(c.toLowerCase()===
a)return k[c]}return null}var K=fa.getLogger("esri.layers.SceneService"),u=r.assert,sa=r.clamp,$=r.isPowerOfTwo,P=r.fallbackIfUndefined,Q=r.objectEmpty,q=r.VertexAttrConstants,ba=[1,1,1,1],k=U.ModelContentType,ta=[0.8,0.8,0.8],ua=[0.5,0.5,0.5],L=1,R=null;return function(r){function e(){r.apply(this,arguments)}ea(e,r);e.prototype.initialize=function(){var a=this;I.checkSpatialReference(this.layer,this.view.spatialReference,this.view.viewingMode);var b=this.layer.version,b=!ja("trident")||1<b.major||
1===b.major&&3<b.minor;this.useCompressedTextures=this.view.has("s3tc")&&b;this._disableAtlasAnisotropy=(this._enableAtlasMipMaps=this.view.has("standardDerivatives"))&&!this.view.has("shaderTextureLOD");this._initGraphicsController();this.dbg=!1;this.maxGpuMemory=1E3;this.geoMemoryEstimate=this.texMemoryEstimate=this.gpuMemoryEstimate=0;this._stage=this.view._stage;this._matId2Meta={};this._texId2Meta={};this._requestedTexImageIds={};this._nodeId2Meta={};this._colorOverride=null;for(var b=new Uint8Array(256),
d=0;d<b.length;d++)b[d]=255;this._whiteTexture=new M(b,"white",{width:8,height:8});this._stage.add(U.ModelContentType.TEXTURE,this._whiteTexture);this._layerEventHandles=[N.init(this.layer,"renderer",function(b){return a._rendererChange(b)}),N.watch(this,"fullOpacity",function(b){return a._opacityChange(b)}),N.init(this.layer,"objectIdFilter",function(){return a._objectIdFilterChange()}),N.init(this.view,"clippingArea",function(){return a._clippingAreaChanged()})];this._addThisLayerToStage();this.setVisibility(!this.suspended);
this.debugLODVis=this.debugNodeVis=!1};e.prototype.destroy=function(){this._stage.remove(U.ModelContentType.TEXTURE,this._whiteTexture.getId());this._removeThisLayerFromStage();this._layerEventHandles.forEach(function(a){a.remove()});this._stage=null;null!=this._controller&&(this._controller.destroy(),this._controller=null);this._nodeId2Meta=this._texId2Meta=this._matId2Meta=null};e.prototype.canResume=function(){return this.inherited(arguments)&&(!this._controller||this._controller.rootNodeVisible)};
e.prototype.isUpdating=function(){return this._controller&&this._controller.updating};e.prototype.memEstimateTextureAdded=function(a){a=a.getEstimatedTexMemRequiredMB();this.gpuMemoryEstimate+=a;this.texMemoryEstimate+=a};e.prototype.memEstimateTextureRemoved=function(a){a=a.getEstimatedTexMemRequiredMB();this.gpuMemoryEstimate-=a;this.texMemoryEstimate-=a};e.prototype.memEstimateGeometryAdded=function(a){a=a.estimateGpuMemoryUsage()/1E6;this.gpuMemoryEstimate+=a;this.geoMemoryEstimate+=a};e.prototype.memEstimateGeometryRemoved=
function(a){a=a.estimateGpuMemoryUsage()/1E6;this.gpuMemoryEstimate-=a;this.geoMemoryEstimate-=a};e.prototype.isBundleAlreadyAddedToStage=function(a,b){var d=!1,c=!1;if(null!=this._nodeId2Meta[a.id]&&this._nodeId2Meta[a.id].engineObjectsPerBundle&&this._nodeId2Meta[a.id].engineObjectsPerBundle[b])for(var c=!0,f=this._nodeId2Meta[a.id].engineObjectsPerBundle[b],n=0;n<f.length&&!(d=f[n].isPartiallyHidden());n++);return{wasPartiallyHidden:d,alreadyLoaded:c}};e.prototype._initGraphicsController=function(){var a=
this,b={addBundle:this._addBundle.bind(this),isBundleAlreadyAddedToStage:this.isBundleAlreadyAddedToStage.bind(this),isOverMemory:this.isOverMemory.bind(this),removeNodeData:this._removeNodeDataFromStage.bind(this),removeFeatures:this._removeFeatures.bind(this),getAddedFeatures:this._getAddedFeatures.bind(this),getAddedNodeIDs:this._getAddedNodeIDs.bind(this),areAllBundlesLoaded:this._areAllBundlesLoaded.bind(this),wholeNodeSwitchEnabled:!0},d={additionalStartNodeLoadingHandler:this._startNodeLoading.bind(this),
additionalCancelNodeLoadingHandler:this.cancelNodeLoading.bind(this),getTexturePrefetchFunctions:function(){return{_calcDesiredTextureLOD:a._calcDesiredTextureLOD.bind(a),_imageIsPartOfTextureBundle:a._imageIsPartOfTextureBundle.bind(a),_matId2Meta:a._matId2Meta,_texId2Meta:a._texId2Meta,useCompressedTextures:function(){return a.useCompressedTextures}}},_nodeDebugVisualizer:this._nodeDebugVisualizer,setPolygonOffset:this._setPolygonOffset.bind(this),traversalOptions:{initDepthFirst:!0,neighborhood:!0,
perLevelTraversal:!1,allowPartialOverlaps:!1},getLoadedAttributes:this.getLoadedAttributes.bind(this),setAttributeData:this.setAttributeData.bind(this)};this.layer.createGraphicsController({layerView:this,layerViewRequiredFunctions:b,layerViewOptionalFunctions:d}).then(function(b){b.watch("rootNodeVisible",function(){a.notifyChange("suspended")})})};e.prototype.setMaxGpuMemory=function(a){this.maxGpuMemory=a};e.prototype.setVisibility=function(a){if(this._stage&&this._engineLayer){var b=this._engineLayer.getId(),
d=0<=this._stage.getViewContent().indexOf(b);!!a!==d&&(b=[b],null!=this._nodeDebugVisualizer&&b.push(this._nodeDebugVisualizer.engineLayer.getId()),a?this._stage.addToViewContent(b):this._stage.removeFromViewContent(b))}};e.prototype.getEngineLayer=function(){return this._engineLayer};e.prototype.getStats=function(){var a={nodesInIndex:0,knownFeatures:0,displayedFeatures:0,displayedGeometries:0,displayedComponents:0,geometryDataSize:0,activeMaterials:0};if(!this._controller)return a;for(var b in this._controller.nodeIndex)if(this._controller.nodeIndex.hasOwnProperty(b)){a.nodesInIndex++;
var d=this._controller.nodeIndex[b];if(null!=d.features)for(var c=0;c<d.features.length;c++)a.knownFeatures++}a.activeMaterials=Object.keys(this._matId2Meta).length;return a};e.prototype._addThisLayerToStage=function(){var a=this._stage;this._initTexture=new M(null,"i3sInitTexture");a.add(k.TEXTURE,this._initTexture);var b=this.layer.id;this._engineLayer=b=new na(b,{},b);a.add(k.LAYER,b);null!=this._nodeDebugVisualizer&&this._nodeDebugVisualizer.dispose()};e.prototype._removeThisLayerFromStage=function(){this.cancelNodeLoading();
if(null!=this._engineLayer){var a=this._stage;a.remove(k.TEXTURE,this._initTexture.getId());if(null!=this._controller)for(var b in this._controller.nodeIndex)this._controller.nodeIndex.hasOwnProperty(b)&&(this._removeNodeDataFromStage(this._controller.nodeIndex[b]),delete this._controller.nodeIndex[b]);u(Q(this._nodeId2Meta));u(Q(this._matId2Meta));u(Q(this._texId2Meta));a.remove(k.LAYER,this._engineLayer.getId());null!=this._nodeDebugVisualizer&&this._nodeDebugVisualizer.dispose();this._nodeDebugVisualizer=
void 0;this._matId2Meta={};this._texId2Meta={};this._requestedTexImageIds={};this._nodeId2Meta={};this._engineLayer=void 0;this.gpuMemoryEstimate=0}};e.prototype._startNodeLoading=function(){this._updateAllTextureLOD()};e.prototype.cancelNodeLoading=function(){null!=this._nodeDebugVisualizer&&this._nodeDebugVisualizer.clear();this._requestedTexImageIds={}};e.prototype._isAllHidden=function(a){a=this._nodeId2Meta[a.id].engineObjects;for(var b=0;b<a.length;b++)if(!a[b].isAllHidden())return!1;return!0};
e.prototype.getLoadedAttributes=function(a){if((a=this._nodeId2Meta[a.id])&&1===a.engineObjects.length)return a.engineObjects[0].getMetadata().loadedAttributes};e.prototype.setAttributeData=function(a,b,d){if((a=this._nodeId2Meta[a.id])&&1===a.engineObjects.length){a=a.engineObjects[0];var c=a.getMetadata();c.loadedAttributes=b;c.attributeData=d;this._setObjectSymbology(a)}};e.prototype._createUnitTestData=function(a){var b=this.view.navigation.targetCamera,b={viewParams:{eye:b.eye,center:b.center,
up:b.up,viewMatrix:b.viewMatrix,projectionMatrix:b.projectionMatrix,fovX:b.fovX,viewport:b.viewport,perPixelRatio:b.perPixelRatio},visibleObjects:[]};a=a.getAll("objects");for(var d in a){var c=a[d];if(c.getParentLayer()===this._engineLayer){var f=c.getMetadata(),c=f.i3sNode,f=f.features.map(function(a){return a.id});f.sort();b.visibleObjects.push({featureIDs:f,nodeId:c})}}console.debug(""+b.visibleObjects.length);return JSON.stringify(b)};e.prototype.isOverMemory=function(){return this.gpuMemoryEstimate>
this.maxGpuMemory?(K.warn("over memory: "+this.gpuMemoryEstimate+" tex "+this.texMemoryEstimate+" geom "+this.geoMemoryEstimate),!0):!1};e.prototype._getAddedFeatures=function(a){if(null==this._nodeId2Meta[a])return null;var b=[];a=this._nodeId2Meta[a].engineObjects;for(var d=0;d<a.length;d++)b=b.concat(a[d].getMetadata().features);return b};e.prototype._getAddedNodeIDs=function(){return Object.keys(this._nodeId2Meta)};e.prototype._calcEngineMaterialTransparencyParams=function(a,b,d){var c=this.fullOpacity,
f=1-sa(P(b.transparency,0),0,1),c=c*f;a=1>c||a&&ga.endsWith(a.channels,"a")||!0===b.useVertexColorAlpha||d;return{opacity:c,transparent:a}};e.prototype._calcEngineMaterialDoubleSidedParams=function(a){return null!=a.doubleSided?a.doubleSided:!0};e.prototype._calcEngineMaterialCullFaceParams=function(a){return a.cullFace?a.cullFace:null!=a.doubleSided?a.doubleSided?"none":"back":"none"};e.prototype._createEngineMaterial=function(a,b,d,c,f,n){var m,h;null!=a&&(m=(h=this._texId2Meta[b])&&h.engineTex?
h.engineTex.getId():this._initTexture.getId());var g=d.params,e=P(g.diffuse,ta),p,v;null!=a&&(v=I.getAppropriateTextureEncoding(a.encoding,this.useCompressedTextures),p=-1<v?a.encoding[v]:a.encoding);"standard"!==d.type&&K.warn("Unknown material type '"+d.type+"', must be 'standard'");void 0===g.reflectivity&&K.warn("Material parameter 'reflectivity' is missing.");d=this.layer instanceof V;m={ambient:this._colorOverride||e,diffuse:this._colorOverride||e,specular:P(g.specular,ua),shininess:P(g.shininess,
64),atlasRegions:g.vertexRegions,textureId:m&&this._colorOverride?this._whiteTexture.getId():m,vertexColors:!0,flipV:!1,doubleSided:this._calcEngineMaterialDoubleSidedParams(g),cullFace:this._calcEngineMaterialCullFaceParams(g),writeStencil:d};d||(e=this._calcEngineMaterialTransparencyParams(a,g),ha.mixin(m,e));m=new ra(m,c);m.metadata={i3sMatId:c,i3sTexId:b,i3sTex:a,i3sMatParams:g};if(null!=a){h?h.usedByEngineMats.push(m):(h={id:b,featureMBS:{},usedByEngineMats:[m],images:a.images,encoding:p,encodingIdx:v,
atlas:!0===a.atlas,wrap:"none"!==a.wrap[0]||"none"!==a.wrap[1]},this._texId2Meta[b]=h);for(a=0;a<f.length;a++)g=f[a],h.featureMBS[g.id]=g.engineMBS;if(void 0!==n[b]){null==h.engineTex&&(f=n[b].data,a=Z(f,h,this._enableAtlasMipMaps,this._disableAtlasAnisotropy),h.engineTex=new M(f,h.id,a),this._stage.add(k.TEXTURE,h.engineTex),h.desiredLOD=n[b].desiredLOD,h.curLOD=h.desiredLOD,this.memEstimateTextureAdded(h.engineTex));f=h.engineTex.getId();for(a=0;a<h.usedByEngineMats.length;a++)g=h.usedByEngineMats[a],
null==this._colorOverride&&g.setParameterValues({textureId:f}),g.metadata.originalTextureId=f;n[b].createdTextureForDomImage();delete n[b]}else this._updateTextureLOD(h)}this._matId2Meta[c]||(this._matId2Meta[c]={});this._matId2Meta[c][b]={engineMat:m,refCount:1};return m};e.prototype._createVertexAndIndexArrays=function(a,b,d){var c,f=a.params.vertexAttributes,n={},e;for(e in f)if(f.hasOwnProperty(e)&&"classification"!==e){var h=f[e];c=S.valueType2TypedArrayClassMap[h.valueType];u(null!=c,"unsupported vertex attribute value type: "+
h.valueType);n[e]={data:new c(b,h.byteOffset,h.count*h.valuesPerElement),size:h.valuesPerElement}}if(null==n[q.COLOR]){c=S.valueType2TypedArrayClassMap.UInt8;n[q.COLOR]={data:new c(4*f.position.count),size:4};for(var g=0;g<n[q.COLOR].data.length;g++)n[q.COLOR].data[g]=0===g%3?255:0}e=!1;null==n[q.NORMAL]&&(e=!0,c=S.valueType2TypedArrayClassMap.Float32,n[q.NORMAL]={data:new c(3*f.position.count),size:3});var f=[],h=a.params.faces,l;if(null!=h&&"PerAttributeArray"!==a.params.topology){var p={};for(name in h)h.hasOwnProperty(name)&&
(c=h[name],u(0===c.count%3),u(c.count===h.position.count),u("UInt32"===c.valueType),p[name]=c.byteOffset);var v=a.params.components.length;l=Array(v);for(var k=h.position.componentIndices||[0],x=0;x<v;x++){var t=a.params.components[x],s=x<v-1?k[x+1]-k[x]:h.position.count-k[x];c={type:"triangle",positionKey:"position",indices:{},componentRange:[k[x],k[x]+s]};for(name in h)h.hasOwnProperty(name)&&(c.indices[name]=new Uint32Array(b,p[name],s),p[name]+=4*s);if(null==c.indices[q.COLOR]){c.indices[q.COLOR]=
new Uint32Array(s);for(g=0;g<s;g++)c.indices[q.COLOR][g]=g}if(e&&null==c.indices[q.NORMAL]){c.indices[q.NORMAL]=new Uint32Array(s);for(g=0;g<s;g++)c.indices[q.NORMAL][g]=g}l[x]=c;var g=t.textureID||"none",w=void 0;"none"!==g&&(w=d.textureDefinitions[g],u(void 0!==w,"geometry wants unknown texture "+g));if(w&&!0===w.atlas&&null!=w.regions){u(0<w.regions.length,"texture marked as atlas carries no region definition");g=w.regions[t.regionID].subimageRegion;f=f.concat([65536*g[0],65536*(g[2]-g[0]),65536*
(1-g[3]),65536*(g[3]-g[1])]);g=new Uint32Array(s);for(t=0;t<s;t++)g[t]=f.length/4-1;c.indices[q.REGION]=g}}}else{c={type:"triangle",positionKey:"position",indices:{}};a=n.position.data.length/n.position.size;if(a>L||null==R){for(;a>L;)L*=2;R=new Uint32Array(L);for(g=0;g<L;g++)R[g]=g}a=new Uint32Array(R.buffer,0,a);for(l in n)c.indices[l]=a;a=c.indices[c.positionKey];c.componentRange=[0,null!=a?a.length-1:0];l=[c]}0<f.length&&(a=new Uint16Array(f),n[q.REGION]={data:a,size:4});return{indexArrays:l,
vertexArrays:n}};e.prototype._createEngineMats=function(a,b,d,c,f){for(var n=a.params.components.length,e=Array(n),h=0;h<n;h++){var g=a.params.components[h],l=g.materialID,p=d.materialDefinitions[l];null!=p.href&&(p=c[p.hrefConcat].materialDefinitions[l]);u(void 0!==p,"geometry wants unknown material "+l);var v=g.textureID||"none",k=void 0;"none"!==v&&((null==d.textureDefinitions||null==d.textureDefinitions[v])&&K.warn("textureDefinitions missing in shared resource"),k=d.textureDefinitions[v]);g=
void 0;this._matId2Meta[l]&&this._matId2Meta[l][v]?(l=this._matId2Meta[l][v],g=l.engineMat,l.refCount++):g=this._createEngineMaterial(k,v,p,l,b,f);e[h]=g}return e};e.prototype._areAllBundlesLoaded=function(a,b){if(null==this._nodeId2Meta[a.id]||null==this._nodeId2Meta[a.id].engineObjectsPerBundle)return!1;for(var d=0;d<a.featureData.length;d++){if(null==this._nodeId2Meta[a.id].engineObjectsPerBundle[d])return!1;if(!b)for(var c=this._nodeId2Meta[a.id].engineObjectsPerBundle[d],f=0;f<c.length;f++)if(c[f].isPartiallyHidden())return!1}return!0};
e.prototype._getObjectIdField=function(){return this.layer.objectIdField||"OBJECTID"};e.prototype._findGraphic=function(a){a=aa(a.attributes,this._getObjectIdField());for(var b=0,d=Object.keys(this._nodeId2Meta);b<d.length;b++)for(var c=d[b],f=this._nodeId2Meta[c].engineObjects,n=0;n<f.length;n++){var e=f[n].getMetadata().featureIds.indexOf(a);if(-1!==e)return{node:this._controller.nodeIndex[c],nodeId:c,bundleNr:n,index:e}}return null};e.prototype.whenGraphicBounds=function(a){var b=this._findGraphic(a);
if(null!=b){a=this._nodeId2Meta[b.nodeId].engineObjects[b.bundleNr];for(var b=a.getMetadata().faceRanges[b.index],b=a.geometries[0].calculateBoundingInfo(0,b),d=b.bbMin,c=b.bbMax,b=[],f=0;8>f;++f){var n=[f&1?d[0]:c[0],f&2?d[1]:c[1],f&4?d[2]:c[2]];H.mat4d.multiplyVec3(a.objectTransformation,n);b[3*f]=n[0];b[3*f+1]=n[1];b[3*f+2]=n[2]}if(T.bufferToBuffer(b,this.view.renderSpatialReference,0,b,this.view.spatialReference,0,8)){a=Y.create(Y.NEGATIVE_INFINITY);for(d=0;d<b.length;d+=3)for(c=0;3>c;c++)a[c]=
Math.min(a[c],b[d+c]),a[c+3]=Math.max(a[c+3],b[d+c]);return E.resolve(a)}}return E.reject()};e.prototype.whenGraphicAttributes=function(a,b){var d=this,c=aa(a.attributes,this._getObjectIdField());return I.whenGraphicAttributes(this.layer,a,c,b,function(){return d._findGraphic(a)})};e.prototype.getGraphicsFromStageObject=function(a,b){if(this.layer instanceof V)return E.reject();var d=a.getMetadata(),c=a.getFaceRangeIndexFromTriangleNr(b);if(null!=c&&null!=d.graphics&&null!=d.graphics[0].attributes)return E.resolve(d.graphics[c]);
if(null!=c&&null!=d.featureIds&&null!=d.featureIds[c]){var f={};f[this._getObjectIdField()]=d.featureIds[c];for(var n=0,e=Object.keys(d.attributeData);n<e.length;n++){var h=e[n];f[h]=d.attributeData[h][c]}d=new W(null,null,f);d.layer=this.layer;return E.resolve(d)}return E.reject()};e.prototype._addBundle=function(a,b,d,c,f,n,e){if(!0===this.debugNodeVis&&null!=this._nodeDebugVisualizer){var h="grey";switch(a.level){case 1:h="red";break;case 2:h="green";break;case 3:h="blue";break;case 4:h="yellow";
break;case 5:h="magenta";break;case 6:h="brown"}this._nodeDebugVisualizer.show(a,this._controller.crsIndex,h)}var h=this._stage,g={};g[k.OBJECT]={};g[k.GEOMETRY]={};g[k.MATERIAL]={};g[k.TEXTURE]={};var l=this._engineLayer,p=l.getId(),v=c[a.sharedResource.hrefConcat];if(null!=this._nodeId2Meta[a.id]&&null!=this._nodeId2Meta[a.id].engineObjectsPerBundle&&this._nodeId2Meta[a.id].engineObjectsPerBundle[e])this._applyFilters(a),null!=f&&f.done();else if(!this.isOverMemory()){null==this._nodeId2Meta[a.id]&&
(this._nodeId2Meta[a.id]={engineObjects:[],engineObjectsPerBundle:[]});this._nodeId2Meta[a.id].engineObjectsPerBundle[e]=[];if(null!=b){for(var F=0;F<b.length;F++){var x=b[F].geometries,t=b[F].features,s=b[F].featureDataAttributes,w=c[a.geometryData[e].hrefConcat];u(w instanceof ArrayBuffer,"I3S: geometry data is not an ArrayBuffer");null==w._isReprojected&&(w._isReprojected={});for(var D=a.id+"|"+t[0].id.toString(),q=[],ca=[],da=[],G=void 0,z=function(b){var d=x[b],f=y._createVertexAndIndexArrays(d,
w,v);if(0===f.indexArrays.length)return"continue";var e=y._createEngineMats(d,t,v,c,n),h=y._controller.crsIndex,l=y.view.renderSpatialReference;G=O.reprojectPoints(y._controller.isMeshPyramid?O.ReprojectionTypes.PER_VERTEX:O.ReprojectionTypes.BOUNDINGBOX,f.vertexArrays.position.data,a.mbs,w._isReprojected[d.id],h,y._controller.crsVertex,l);w._isReprojected[d.id]=!0;y._controller.isMeshPyramid&&I.processNormals({normals:f.vertexArrays.normal.data,positions:f.vertexArrays.position.data,normalInd:f.indexArrays[0].indices.normal,
positionInd:f.indexArrays[0].indices.position},y.layer.normalReferenceFrame||"none",function(b,c){O.reprojectNormalsPerVertex(b,a.mbs,h,c,l)});var m=G.localTrafo;null!=d.transformation&&(m=H.mat4d.create(d.transformation),H.mat4d.multiply(G.localTrafo,m,m));for(d=0;d<e.length;d++){var p=e[d];g[k.MATERIAL][p.getId()]=p}f=new oa(new pa(f.indexArrays,f.vertexArrays),D+"_"+b);y.memEstimateGeometryAdded(f.getData());g[k.GEOMETRY][f.getId()]=f;q[b]=f;ca[b]=m;da[b]=e},y=this,r=0;r<x.length;++r)z(r);z=[];
for(r=0;r<t.length;r++){var B=new W(void 0,void 0,s[r]);B.set("layer",this.layer);z.push(B)}s=new qa({idHint:a.id,name:D,geometries:q,materials:da,transformations:ca,castShadow:!0,metadata:{graphics:z,i3sNode:a.id,ceLayer:p,features:t,faceRanges:b[F].faceRanges,featureIds:b[F].featureIds,attributeData:d?d.attributeData:null,loadedAttributes:d?d.loadedAttributes:null,layerId:this.layer.id}});z=H.mat4d.create();H.mat4d.identity(z);H.mat4d.multiply(z,G.globalTrafo,z);s.setObjectTransformation(z);this._nodeId2Meta[a.id].engineObjectsPerBundle[e].push(s);
this._nodeId2Meta[a.id].engineObjects.push(s);g[k.OBJECT][s.getId()]=s;this._setObjectSymbology(s);this._applyFilters(a)}h.beginMod();b=g[k.OBJECT];for(var A in b)b.hasOwnProperty(A)&&l.addObject(b[A]);for(var J in g)if(g.hasOwnProperty(J))for(name in A=g[J],A)A.hasOwnProperty(name)&&null==h.get(J,name)&&h.add(J,A[name]);h.endMod()}null!=f&&f.done()}};e.prototype._clippingAreaChanged=function(){var a=this,b=[];T.extentToBoundingBox(this.view.clippingArea,b,this.view.renderSpatialReference)?this._clippingArea=
b:this._clippingArea=null;this._updateFilters();if(this._controller){var d=this._controller.nodeIndex;d&&Object.keys(this._nodeId2Meta).forEach(function(b){return a._applyFilters(d[b])});this._controller.updateClippingArea(this.view.clippingArea)}};e.prototype._objectIdFilterChange=function(){var a=this;this._updateFilters();if(this._controller){var b=this._controller.nodeIndex;b&&Object.keys(this._nodeId2Meta).forEach(function(d){return a._applyFilters(b[d])})}};e.prototype._updateFilters=function(){var a=
this,b=[];if(this.layer.objectIdFilter){var d=new Float64Array(this.layer.objectIdFilter.ids),c="include"===this.layer.objectIdFilter.method;d.sort();b.push(function(b,e){return a._objectIdFilter(d,c,e)})}this._clippingArea&&b.push(function(b,c){return a._boundingboxFilter(b,a._clippingArea,c)});this._filters=b};e.prototype._objectIdFilter=function(a,b,d){for(var c=0;c<d.length;)0<=I.binaryIndexOf(a,d[c])===b?c++:d.splice(c,1)};e.prototype._boundingboxFilter=function(a,b,d){var c=[0,0,0,0];T.mbsToMbs(a.mbs,
this._controller.crsIndex,c,this.view.renderSpatialReference);c=null!=b?I.intersectBoundingBoxWithMbs(b,c):2;if(2!==c){var f=0;a=this._nodeId2Meta[a.id].engineObjects;for(var e=0;e<a.length;e++){var m=a[e],h=m.getMetadata().featureIds;if(0===c){for(var g=0,m=0;m<h.length&&f+g<d.length;m+=1)d[f+g]===h[m]&&g++;d.splice(f,g)}else{var l=m.getObjectTransformation(),g=m.getGeometryRecords()[0].transformation;H.mat4d.multiply(l,g);if(!(0!==l[1]||0!==l[2]||0!==l[3]||0!==l[4]||0!==l[6]||0!==l[7]||0!==l[8]||
0!==l[9]||0!==l[11]||1!==l[15]))for(var g=(b[0]-l[12])/l[0],p=(b[1]-l[13])/l[5],k=(b[2]-l[14])/l[10],F=(b[3]-l[12])/l[0],x=(b[4]-l[13])/l[5],l=(b[5]-l[14])/l[10],t=m.getGeometryRecords()[0].geometry.getData(),s=t.getFaces()[0].indices.position,t=t.getVertexAttr().position.data,w=m.getMetadata().faceRanges,D=void 0,r=void 0,q=void 0,u=void 0,G=void 0,z=void 0,m=0;m<w.length&&f<d.length;m+=1)if(d[f]===h[m]){for(var D=w[m],y=D[0],B=D[1],D=r=q=Number.MAX_VALUE,u=G=z=-Number.MAX_VALUE;y<=B;y+=1)for(var C=
0;3>C;C+=1)var A=3*s[3*y+C],J=t[A],E=t[A+1],A=t[A+2],D=Math.min(J,D),r=Math.min(E,r),q=Math.min(A,q),u=Math.max(J,u),G=Math.max(E,G),z=Math.max(A,z);D>F||u<g||r>x||G<p||q>l||z<k?d.splice(f,1):f++}}}}};e.prototype._applyFilters=function(a){if(this._nodeId2Meta[a.id]&&null!=this._nodeId2Meta[a.id].engineObjects){for(var b=this._nodeId2Meta[a.id].engineObjects,d=0;d<b.length;d++)b[d].unhideAllFaceRange();if(0!==this._filters.length){for(var c=[],d=0;d<b.length;d++)var f=b[d],c=c.concat(f.getMetadata().featureIds);
d=c.length;for(f=0;f<this._filters.length;f++)this._filters[f](a,c);if(c.length!==d)for(d=a=0;d<b.length;d++){for(var f=b[d],e=[],m=f.getMetadata().faceRanges,h=f.getMetadata().featureIds,g=0;g<h.length;g+=1){var l=h[g],p=m[g];a>=c.length||c[a]!==l?e.push(p):a++}0<e.length&&f.hideFaceRange(f.getGeometryRecords()[0],e)}}}};e.prototype._hideFeatures=function(a,b){for(var d=this._nodeId2Meta[a.id].engineObjects,c=0;c<d.length;c++){for(var f=d[c],e=[],m=f.getMetadata().features,h=f.getMetadata().faceRanges,
g=0;g<b.length;g++)for(var l=b[g],p=0;p<m.length;p++)l===m[p].id&&(null!=h&&1===f.getGeometryRecords().length?e.push(h[p]):f.hideAllFaceRanges());0<e.length&&f.hideFaceRange(f.getGeometryRecords()[0],e)}};e.prototype._removeFeatures=function(a,b){null!=this._nodeId2Meta[a.id]&&(this._hideFeatures(a,b),!0===this._isAllHidden(a)&&this._removeNodeDataFromStage(a))};e.prototype._removeNodeDataFromStage=function(a){if(!(null==this._nodeId2Meta[a.id]||null==this._nodeId2Meta[a.id].engineObjects)){for(var b=
this._stage,d=this._engineLayer,c=this._nodeId2Meta[a.id].engineObjects,f=0;f<c.length;++f){var e=c[f];d.removeObject(e);for(var m=e.getGeometryRecords(),h=0;h<m.length;h++){var g=m[h];this.memEstimateGeometryRemoved(g.geometry.getData());b.remove(k.GEOMETRY,g.geometry.getId());for(var l=0;l<g.materials.length;l++){var p=g.materials[l],v=p.getId(),r=p.metadata.i3sMatId,q=p.metadata.i3sTexId||"none",t=this._matId2Meta[r][q];u(0<t.refCount);t.refCount--;0===t.refCount&&this._removeMaterial(v,q,r,p,
b)}}b.remove(k.OBJECT,e.getId())}delete this._nodeId2Meta[a.id]}};e.prototype._removeMaterial=function(a,b,d,c,f){f.remove(k.MATERIAL,a);if("none"!==b){a=this._texId2Meta[b];var e=a.usedByEngineMats;c=e.indexOf(c);u(-1<c);e[c]=e[e.length-1];e.pop();if(1>e.length){if((c=a.engineTex)&&c!==this._initTexture)this.memEstimateTextureRemoved(c),f.remove(k.TEXTURE,a.engineTex.getId());a.engineTex=void 0;a.desiredLOD=-1;a.curLOD=-1;delete this._texId2Meta[b]}}delete this._matId2Meta[d][b];Q(this._matId2Meta[d])&&
delete this._matId2Meta[d]};e.prototype._updateAllTextureLOD=function(){for(var a in this._texId2Meta)this._texId2Meta.hasOwnProperty(a)&&this._updateTextureLOD(this._texId2Meta[a])};e.prototype._calcDesiredTextureLOD=function(a,b){var d,c=0;d=0;for(var f=Object.keys(a);d<f.length;d++){var e=a[f[d]],m=H.vec3.dist(e,this._controller.camPos),e=2*e[3]/m*this._controller.screenSizeFactor;e>c&&(c=e)}c/=9;for(d=b.length-1;0<d&&b[d].size<c;)d--;return d};e.prototype._updateTextureLOD=function(a){var b=this;
a.desiredLOD=this._calcDesiredTextureLOD(a.featureMBS,a.images);if(a.curLOD!==a.desiredLOD&&(0>a.curLOD||!a.curLOD||0===a.desiredLOD||a.desiredLOD>a.curLOD||a.desiredLOD<a.curLOD-1)){if(0===a.images.length)return;var d=a.images[a.desiredLOD],c=-1<a.encodingIdx?d.hrefConcat[a.encodingIdx]:d.hrefConcat;if(!this._requestedTexImageIds[d.id]){var f={metadata:{texMeta:a,image:d}};this._requestedTexImageIds[d.id]=!0;this._imageIsPartOfTextureBundle(d)?this._controller.streamDataSupplier.request(c,"binary",
f).then(this._extractTextureImageFromBlob.bind(this)):this._controller.streamDataSupplier.request(c,"image",f).then(function(a,c,d,f){b._textureImageLoaded(a,c,f.image,f.texMeta)})}}a.engineTex||(a.engineTex=this._initTexture,a.curLOD=-1);if(this.debugLODVis){d=ia.fromHsv(270*(a.desiredLOD/a.images.length),100,100).toRgb().map(function(a){return a/255});for(c=0;c<a.usedByEngineMats.length;c++)a.usedByEngineMats[c].setParameterValues({ambient:d,diffuse:d})}};e.prototype._extractTextureImageFromBlob=
function(a,b,d,c){var f=c.texMeta;if(0>f.desiredLOD||c.image.size>f.images[f.desiredLOD].size)delete this._requestedTexImageIds[c.image.id];else{var e=this;u("binary"===d);var m="";try{var h=d=0;-1<f.encodingIdx?(d=c.image.byteOffset[f.encodingIdx],h=c.image.length[f.encodingIdx]):(d=c.image.byteOffset,h=c.image.length);var g=new Uint8Array(b,d,h),l=new Blob([g],{type:f.encoding}),m=window.URL.createObjectURL(l)}catch(p){m="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAIElEQVQ4T2P8zyD6n4ECwDhqAMNoGDCMhgEwDw2DdAAAdzkhQdS8dl8AAAAASUVORK5CYII\x3d",
K.error("error loading texture "+a+" "+p)}var k=new Image;k.onerror=function(){window.URL.revokeObjectURL(m);k.src="";k.onerror=void 0;k.onload=void 0};k.onload=function(){e._controller.queueAnimationFrameFunctionCall(e._textureImageLoaded,e,[a,k,c.image,c.texMeta,m],void 0,1);window.URL.revokeObjectURL(m);k.src="";k.onerror=void 0;k.onload=void 0};k.src=m}};e.prototype._textureImageLoaded=function(a,b,d,c){delete this._requestedTexImageIds[d.id];if(!(0>c.desiredLOD)){a=c.images[c.desiredLOD];var f=
c.images[c.curLOD];if(!this.isOverMemory()||!(null==f||d.size>f.size))if(!f||d.size>f.size&&d.size<=a.size||d.size<f.size&&d.size>=a.size){if((f=c.engineTex)&&f!==this._initTexture)this.memEstimateTextureRemoved(f),this._stage.remove(k.TEXTURE,c.engineTex.getId());f=Z(b,c,this._enableAtlasMipMaps,this._disableAtlasAnisotropy);c.engineTex=new M(b,c.id,f);this._stage.add(k.TEXTURE,c.engineTex);c.curLOD=c.desiredLOD;this.memEstimateTextureAdded(c.engineTex);b=c.engineTex.getId();for(f=0;f<c.usedByEngineMats.length;f++){var e=
c.usedByEngineMats[f];null==this._colorOverride&&e.setParameterValues({textureId:b});e.metadata.originalTextureId=b}d!==a&&(c.curLOD=c.images.indexOf(d),u(-1<c.curLOD),this._requestedTexImageIds[a.id]||(d={metadata:{texMeta:c,image:a}},this._requestedTexImageIds[a.id]=!0,this._controller.streamDataSupplier.request(a.hrefConcat,"binary",d).then(this._extractTextureImageFromBlob.bind(this))))}}};e.prototype._imageIsPartOfTextureBundle=function(a){return!this._controller.isMeshPyramid};e.prototype._setPolygonOffset=
function(a,b){if(null!=this._nodeId2Meta[a.id]&&null!=this._nodeId2Meta[a.id].engineObjectsPerBundle)for(var d={polygonOffset:b},c=0;c<this._nodeId2Meta[a.id].engineObjectsPerBundle.length;c++)for(var f=this._nodeId2Meta[a.id].engineObjectsPerBundle[c],e=0;e<f.length;e++)for(var m=f[e].getGeometryRecords(),h=0;h<m.length;h++)for(var g=m[h].materials,l=0;l<g.length;l++)g[l].setParameterValues(d)};e.prototype._rendererChange=function(a){(this._currentRenderer=a)&&(a.colorInfo||a.sizeInfo)&&K.warn("renderer.colorInfo and renderer.sizeInfo are not supported for Scene Services. Use visualVariables instead.")};
e.prototype._getRenderer=function(a){return!a||a.symbol?null:this._rndForScale||this._currentRenderer};e.prototype._getSymbol=function(a){if(a.symbol)return a.symbol;var b=this._getRenderer(a);return b&&b.getSymbol(a)};e.prototype._getRenderingInfo=function(a){var b=this._getRenderer(a),d=this._getSymbol(a);if(!d||!(d instanceof la))return null;var d={symbol:d},c,e;if(b&&b.visualVariables){a=b.getVisualVariableValues(a);for(b=0;b<a.length;b++){var n=a[b],m=n.variable.type;"color"===m?c=n.value:"opacity"===
m&&(e=n.value)}}c&&(d.color=[c.r/255,c.g/255,c.b/255]);null!=e?d.opacity=e:c&&null!=c.a&&(d.opacity=c.a);return d};e.prototype._getSymbolFillColor=function(a){a=a.symbolLayers;for(var b=0;b<a.length;b++){var d=a.getItemAt(b);if("Fill"===d.type&&d.material&&d.material.color)return a=d.material.color,[a.r/255,a.g/255,a.b/255,a.a]}};e.prototype._setObjectSymbology=function(a){if(!(this.layer instanceof V)){for(var b=a.getMetadata(),d=[],c=b.graphics,e=!1,n=c.length,m=b.faceRanges?b.faceRanges.length:
n,h={attributes:{}},g=function(a){m===n&&null==b.attributeData?h=c[a]:Object.keys(b.attributeData).forEach(function(c){h.attributes[c]=b.attributeData[c][a]});var g=l._getRenderingInfo(h),k=null!=b.faceRanges?b.faceRanges[a]:null;if(g){var p=g.color,q=g.opacity;null==p||null==q?(g=l._getSymbolFillColor(g.symbol),p=X.overrideColor(p,q,g,g&&g[3],ba)):p=X.overrideColor(p,q,null,null,ba);1>p[3]&&(e=!0);d.push({faceRanges:k,color:p})}else d.push({faceRanges:k,color:void 0})},l=this,k=0;k<m;k++)g(k);this.layer.cachedDrawingInfo.color?
a.setFacerangeColors(d,"replace"):a.setFacerangeColors(d,"blend");a=a.getGeometryRecords();for(g=0;g<a.length;g++)for(var k=a[g],r=0;r<k.materials.length;r++){var q=k.materials[r],u=q.getParams().transparent,t=q.getParams().opacity;q.metadata.symbolIsTransparent=e;var s=this._calcEngineMaterialTransparencyParams(q.metadata.i3sTex,q.metadata.i3sMatParams,q.metadata.symbolIsTransparent);(u!==s.transparent||t!==s.opacity)&&q.setParameterValues({transparent:s.transparent,opacity:s.opacity})}}};e.prototype._opacityChange=
function(a){for(var b in this._matId2Meta)for(var d in this._matId2Meta[b]){a=this._matId2Meta[b][d].engineMat;var c=a.getParams().transparent,e=a.getParams().opacity,k=this._calcEngineMaterialTransparencyParams(a.metadata.i3sTex,a.metadata.i3sMatParams,a.metadata.symbolIsTransparent);(c!==k.transparent||e!==k.opacity)&&a.setParameterValues({transparent:k.transparent,opacity:k.opacity})}};C([B.property()],e.prototype,"layer",void 0);C([B.property()],e.prototype,"view",void 0);C([B.property()],e.prototype,
"_controller",void 0);C([B.property({dependsOn:["_controller.updating"]})],e.prototype,"updating",void 0);C([B.property({readOnly:!0,aliasOf:"_controller.updatingPercentage"})],e.prototype,"updatingPercentageValue",void 0);return e=C([B.subclass("esri.views.3d.layers.SceneLayerView3D")],e)}(B.declared(ka,ma))});