// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("require exports ../../../core/tsSupport/declareExtendsHelper ../../../core/tsSupport/decorateHelper ../../../core/accessorSupport/decorators ./graphics/Graphics3DLayerViewCore ./support/LayerViewUpdatingPercentage ../../layers/GraphicsLayerView ../../../Graphic ../../../geometry/Point ../../../geometry/Polygon ../../../geometry/Polyline ../../../core/Collection ../../../core/HandleRegistry ../../../core/promiseUtils ../lib/glMatrix ./i3s/I3SUtil ./i3s/I3SBinaryReader ../support/PreallocArray ../support/projectionUtils ../support/aaBoundingBox".split(" "),
function(w,Y,L,g,n,M,N,O,H,P,Q,R,S,T,x,U,E,V,K,W,s){w=function(w){function b(){w.call(this);this._nodesAddedToStage={};this.loadedGraphics=new S;this.supportsDraping=!0;this._overlayUpdating=null;this._handles=new T}L(b,w);b.prototype.initialize=function(){var a=this;E.checkSpatialReference(this.layer,this.view.spatialReference,this.view.viewingMode);this._handles.add([this.layer.watch("renderer",function(){return a._rendererChange()}),this.layer.watch("objectIdFilter",function(){return a._objectIdFilterChange()})]);
this._layerViewCore=new M({owner:this,layer:this.layer,spatialIndex:null,labelingEnabled:!0,frustumVisibilityEnabled:!1,elevationAlignmentEnabled:!0,verticalScaleEnabled:!0,updateSuspendResumeExtent:function(){return a._updateSuspendResumeExtent()},updateClippingExtent:function(d){return a._updateClippingExtent(d)},elevationChanged:function(d,c,e){return a._elevationChanged(d,c,e)}});this._layerViewCore.initialize();this.drawingOrder=this.view.getDrawingOrder(this.layer.uid);this._createController();
this.addResolvingPromise(this._layerViewCore.labeling.initLabelingInfo())};b.prototype.destroy=function(){this._layerViewCore&&(this._layerViewCore.destroy(),this._layerViewCore=null);this._controller&&(this._controller.destroy(),this._controller=null);this._nodesAddedToStage=this._intersectingGraphicIds=this._elevationUpdateNodes=null;this._nodeDebugVisualizer&&(this._nodeDebugVisualizer.dispose(),this._nodeDebugVisualizer=null);this._handles&&(this._handles.destroy(),this._handles=null)};Object.defineProperty(b.prototype,
"hasDraped",{get:function(){return this._layerViewCore.graphicsCore.hasDraped},enumerable:!0,configurable:!0});b.prototype.whenGraphicAttributes=function(a,d){var c=this,e=a.attributes[this._getObjectIdField()];return E.whenGraphicAttributes(this.layer,a,e,d,function(){return c._findGraphic(a.uid)})};b.prototype.getGraphicsFromStageObject=function(a,d){if(!this.loadedGraphics)return x.reject();var c=a.getMetadata().graphicId,e=this.loadedGraphics.find(function(a){return a.uid===c}),b=this._getObjectIdField();
return!e||!e.attributes||!e.attributes[b]?x.reject():x.resolve(e)};b.prototype.whenGraphicBounds=function(a){return this._layerViewCore.graphicsCore.whenGraphicBounds(a)};b.prototype.canResume=function(){return this.inherited(arguments)&&(!this._controller||this._controller.rootNodeVisible)};b.prototype.isUpdating=function(){return this._controller&&this._controller.updating};b.prototype.getRenderingInfo=function(a){var d=this.inherited(arguments);if(d&&d.color){var c=d.color;d.color=[c.r/255,c.g/
255,c.b/255,c.a]}return d};b.prototype._findGraphic=function(a){for(var d=0,c=Object.keys(this._nodesAddedToStage);d<c.length;d++)for(var e=c[d],b=this._nodesAddedToStage[e].bundles,f=0;f<b.length;f++)for(var k=b[f],l=0;l<k.length;l++)if(k[l].graphics.some(function(d){return d.uid===a}))return{node:this._controller.nodeIndex[e],nodeId:e,bundleNr:f,index:l};return null};b.prototype._elevationChanged=function(a,d,c){s[2]=-Infinity;s[3]=Infinity;var e=s.fromRect(X,a);null==this._elevationUpdateNodes&&
(this._elevationUpdateNodes=new K(10));a=this._elevationUpdateNodes;a.clear();this._controller&&this._controller.updateElevationChanged(e,d,a);d=a.length;this._intersectingGraphicIds||(this._intersectingGraphicIds=new K(10));e=this._intersectingGraphicIds;e.clear();for(var b=0;b<d;b++){var f=this._nodesAddedToStage[a.data[b].id];if(null!=f)for(var f=f.bundles,k=0;k<f.length;k++)for(var l=f[k],m=0;m<l.length;m++)for(var n=l[m].graphics,g=0;g<n.length;g++)e.push(n[g].uid)}c(this._intersectingGraphicIds.data,
this._intersectingGraphicIds.length)};b.prototype._evaluateUpdatingState=function(){};b.prototype._notifySuspendedChange=function(){};b.prototype._notifyDrapedDataChange=function(){this.notifyChange("hasDraped");this.emit("draped-data-change")};b.prototype._createController=function(){var a=this,d={addBundle:this._addBundle.bind(this),isBundleAlreadyAddedToStage:this._isBundleAlreadyAddedToStage.bind(this),isOverMemory:this._isOverMemory.bind(this),removeNodeData:this._removeNodeData.bind(this),removeFeatures:this._removeFeatures.bind(this),
getAddedFeatures:this._getAddedFeatures.bind(this),getAddedNodeIDs:this._getAddedNodeIDs.bind(this),areAllBundlesLoaded:this._areAllBundlesLoaded.bind(this),wholeNodeSwitchEnabled:!0},c={traversalOptions:{initDepthFirst:!1,neighborhood:!1,perLevelTraversal:!0,allowPartialOverlaps:!1,errorMetricToUse:"screenSpaceRelative",elevationInfo:this.layer.elevationInfo},getAllAddedFeatures:this._getAllAddedFeatures.bind(this),_nodeDebugVisualizer:this._nodeDebugVisualizer,getLoadedAttributes:this._getLoadedAttributes.bind(this),
setAttributeData:this._setAttributeData.bind(this)};this.layer.createGraphicsController({layerView:this,layerViewRequiredFunctions:d,layerViewOptionalFunctions:c}).then(function(d){a._controller=d;d.watch("rootNodeVisible",function(){a.notifyChange("suspended")})})};b.prototype._getAllAddedFeatures=function(){var a={};this.loadedGraphics.forEach(function(d){a[d._nodeId]=d._features});return a};b.prototype._addBundle=function(a,d,c,b,y,f,k){f=this._controller.crsIndex;var l=[],m=this._getObjectIdField();
null==this._nodesAddedToStage[a.id]&&(this._nodesAddedToStage[a.id]={bundles:[],attributeData:c?c.attributeData:null,loadedAttributes:c?c.loadedAttributes:null});this._nodesAddedToStage[a.id].bundles[k]=l;if(null==d)null!=y&&y.done();else{var g;if(this.layer.objectIdFilter){var n=this.layer.objectIdFilter.ids,w="include"===this.layer.objectIdFilter.method;g=function(a){return 0<=n.indexOf(a)===w}}for(c=0;c<d.length;c++)for(var C=d[c],s=C.featureDataPositions[0],F=0;F<C.geometries.length;F++){var z=
[],p=C.features[F<C.features.length?F:0],u=p?{}:null;if(p&&p.id){if(g&&!g(p.id))continue;u[m]=p.id}var r=C.geometries[F],t=r.params.type,q=p=void 0;if("ArrayBufferView"===r.type){q=r.params.vertexAttributes.position;if(null==q)continue;p=new V.valueType2TypedArrayClassMap[q.valueType](b[a.geometryData[k].hrefConcat],q.byteOffset,q.count*q.valuesPerElement);q=q.valuesPerElement}else"Embedded"===r.type&&(p=r.params.vertexAttributes.position,q=3);var A=void 0;if("lines"===t){for(var r=[],h=0;h<p.length;h+=
q)r.push([p[h]+a.mbs[0],p[h+1]+a.mbs[1]]);t=new R(f);t.addPath(r);A=t;z.push(new H(A,null,u))}else if("points"===t)for(h=0;h<p.length;h+=q)A=new P({x:p[h]+s[0],y:p[h+1]+s[1],z:2<q?p[h+2]+s[2]:void 0,spatialReference:f}),z.push(new H(A,null,u));else if("polygon"===t){A=t=new Q(f);t._outlineSegments=[];for(var x=0;x<r.params.rings.length;x++){for(var B=r.params.rings[x],D=B.start,E=[],I=[],v=[-1,-1],G=0;G<B.segments.length;G+=2){var h=B.segments[G+0],J=B.segments[G+1];0===h||1===h?(-1===v[0]&&(v[0]=
D-B.start),v[1]=D+J-B.start):-1!==v[0]&&(I.push(v),v=[-1,-1]);for(h=D*q;h<(D+J)*q;h+=q)E.push([p[h]+a.mbs[0],p[h+1]+a.mbs[1]]);D+=J}-1!==v[0]&&I.push(v);A._outlineSegments.push(I);t.addRing(E);null!=B.inner&&console.warn("inner rings not yet supported")}z.push(new H(A,null,u))}for(u=0;u<z.length;u++)z[u].layer=this.layer;this.loadedGraphics.addMany(z);l.push({features:C.features,graphics:z})}a=this._nodesAddedToStage[a.id];this._setBundleAttributes(a.bundles[k],a.loadedAttributes,a.attributeData);
y.done()}};b.prototype._areAllBundlesLoaded=function(a,d){var c=this._nodesAddedToStage[a.id];if(null==c)return!1;for(var b=0;b<a.featureData.length;b++){var y=c.bundles[b];if(null==y)return!1;if(!(d||null==a.features))for(var f=a.featureData[b].featureRange,k=a.features.length,l=f?f[1]:k-1,f=f?f[0]:0;f<=l;f++){var m;if(m=f<k){a:{for(m=y.length;m--;)for(var g=y[m].features,n=g.length;n--;)if(g[n].id===a.features[f].id){m=!0;break a}m=!1}m=!m}if(m)return!1}}return!0};b.prototype._isBundleAlreadyAddedToStage=
function(a,d){return null==this._nodesAddedToStage[a.id]?{alreadyLoaded:!1,wasPartiallyHidden:!1}:{alreadyLoaded:!!this._nodesAddedToStage[a.id].bundles[d],wasPartiallyHidden:!1}};b.prototype._isOverMemory=function(){return!1};b.prototype._removeFeatures=function(a,d){var b=this._nodesAddedToStage[a.id];if(null!=b){var b=b.bundles,e;for(e in b)for(var g=0;g<b[e].length;g++){var f=b[e][g],k=!1;if(null!=f){for(var l in f.features)if(-1!==d.indexOf(f.features[l].id)){k=!0;break}k&&(this.loadedGraphics.removeMany(f.graphics),
delete b[e][g])}}for(e=0;e<b.length;e++)for(g=0;g<b[e].length;g++)if(f=b[e][g],null!=f&&0<f.graphics.length)return;this._removeNodeData(a)}};b.prototype._removeNodeData=function(a){var b=this._nodesAddedToStage[a.id];if(null!=b){var b=b.bundles,c;for(c in b)for(var e in b[c])this.loadedGraphics.removeMany(b[c][e].graphics);delete this._nodesAddedToStage[a.id]}};b.prototype._getAddedFeatures=function(a){a=this._nodesAddedToStage[a];if(null==a)return null;a=a.bundles;var b=[],c;for(c in a)for(var e=
0;e<a[c].length;e++)b=b.concat(a[c][e].features);return b};b.prototype._getAddedNodeIDs=function(){return Object.keys(this._nodesAddedToStage)};b.prototype._getLoadedAttributes=function(a){if(a=this._nodesAddedToStage[a.id])return a.loadedAttributes};b.prototype._setAttributeData=function(a,b,c){if(a=this._nodesAddedToStage[a.id])a.loadedAttributes=b,a.attributeData=c,this._setNodeAttributes(a,b,c),this._layerViewCore.labeling.layerLabelsEnabled()&&this._layerViewCore.labeling.showLabelsChange()};
b.prototype._setNodeAttributes=function(a,b,c){a=a.bundles;for(var e in a)this._setBundleAttributes(a[e],b,c)};b.prototype._setBundleAttributes=function(a,b,c){for(var e=0;e<a.length;e++)for(var g=a[e],f=0;f<g.graphics.length;++f){var k=g.graphics[f];k.attributes||(k.attributes={});if(b)for(var l=0;l<b.length;++l){var m=b[l].name;k.attributes[m]=c[m][e]}}};b.prototype._updateSuspendResumeExtent=function(){this.layer.fullExtent?(this._suspendResumeExtent||(this._suspendResumeExtent=U.vec4d.create()),
W.extentToBoundingRect(this.layer.fullExtent,this._suspendResumeExtent,this.view.spatialReference)||(this._suspendResumeExtent=null)):this._suspendResumeExtent=null;return this._suspendResumeExtent};b.prototype._updateClippingExtent=function(a){this._controller&&this._controller.updateClippingArea(a);return!1};b.prototype._getObjectIdField=function(){return this.layer.objectIdField||"OBJECTID"};b.prototype._rendererChange=function(){var a=this;Object.keys(this._nodesAddedToStage).forEach(function(b){a._removeNodeData({id:b})})};
b.prototype._objectIdFilterChange=function(){var a=this;Object.keys(this._nodesAddedToStage).forEach(function(b){a._removeNodeData({id:b})});this._controller&&this._controller.restartNodeLoading()};g([n.property()],b.prototype,"loadedGraphics",void 0);g([n.property()],b.prototype,"layer",void 0);g([n.property()],b.prototype,"view",void 0);g([n.property()],b.prototype,"hasDraped",null);g([n.property()],b.prototype,"_controller",void 0);g([n.property({dependsOn:["_controller.updating"]})],b.prototype,
"updating",void 0);g([n.property({aliasOf:"_controller.updatingPercentage"})],b.prototype,"updatingPercentageValue",void 0);return b=g([n.subclass("esri.views.3d.layers.SceneLayerGraphicsView3D")],b)}(n.declared(O,N));var X=s.create(s.POSITIVE_INFINITY);return w});