// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.1/esri/copyright.txt for details.
//>>built
define("require ../core/declare ../core/promiseUtils dojo/_base/array dojo/on dojo/Deferred dojo/promise/all ../layers/support/layerUtils ../geometry/support/scaleUtils ../geometry/Extent ../tasks/support/Query ../layers/GroupLayer ../core/Accessoire".split(" "),function(G,H,I,k,D,y,J,E,x,K,L,F,M){var z;return H(M,{declaredClass:"esri.views.PopupManager",classMetadata:{properties:{map:{dependsOn:["view.map"],readOnly:!0}}},constructor:function(){this._featureLayersCache={}},destroy:function(){this._featureLayersCache=
{};this.view=null},_clickHandle:null,_featureLayersCache:null,enabled:!1,_enabledSetter:function(a){this._clickHandle&&(a?this._clickHandle.resume():this._clickHandle.pause());return a},_mapGetter:function(){return this.get("view.map")||null},view:null,_viewSetter:function(a){this._clickHandle&&(this._clickHandle.remove(),this._clickHandle=null);a&&(this._clickHandle=D.pausable(a,"click",this._clickHandler.bind(this)),this.enabled||this._clickHandle.pause());return a},getMapLayer:function(a){var c;
if(a&&(c=a.findLayerById()))if(a=c.id,this._featureLayersCache[a]){var g=a.lastIndexOf("_");-1<g&&(a=a.substring(0,g),c=this.map.findLayerById(a))}return c},_showPopup:function(a){function c(){r.clear();r.close()}function g(b){return h.allLayerViews.find(function(a){return a.layer===b})}function e(b){if(null==b)return!1;var a=g(b);return null==a?!1:b.loaded&&!a.suspended&&(b.popupEnabled&&b.popupTemplate||"esri.layers.GraphicsLayer"===b.declaredClass||a.getPopupData)}function A(b){return(b=g(b))&&
b.hasDraped}var h=this.view,r=h.popup,u=this,s=[],w="3d"===h.type;k.forEach(this.map.layers.toArray(),function(b){b.isInstanceOf(F)?k.forEach(b.layers.toArray(),function(b){e(b)&&(!w||A(b))&&s.push(b)}):e(b)&&(!w||A(b))&&s.push(b)});0<h.graphics.length&&s.push(h.graphics);var d=null;if(a.graphic&&(a.graphic.popupTemplate||e(a.graphic.layer)))d=a.graphic;if(!s.length&&!d)c();else{var f=[],p=!!d;if(d)if(d.layer&&"esri.layers.SceneLayer"===d.layer.declaredClass){var l=h.whenLayerView(d.layer).then(function(b){var a=
this._getOutFields(d.layer.popupTemplate);return b.whenGraphicAttributes(d,a)}.bind(this)).then(function(b){return[b]}).otherwise(function(){return[d]});f.unshift(l)}else d.getEffectivePopupTemplate()&&(l=new y,f.unshift(l.resolve([d])));else{var q=u._calculateClickTolerance(s),f=a.mapPoint;if(!f){c();return}var v=1;h.state&&(v=h.state.resolution);(l=h.basemapTerrain)&&l.overlayManager&&(v=l.overlayManager.overlayPixelSizeInMapUnits(f));q*=v;l&&!l.spatialReference.equals(h.spatialReference)&&(q*=
x.getUnitValueForSR(l.spatialReference)/x.getUnitValueForSR(h.spatialReference));var l=f.clone().offset(-q,-q),f=f.clone().offset(q,q),t=new K(Math.min(l.x,f.x),Math.min(l.y,f.y),Math.max(l.x,f.x),Math.max(l.y,f.y),h.spatialReference),f=k.map(s,function(b){var c;if("esri.layers.ImageryLayer"===b.declaredClass){c=new L;c.geometry=a.mapPoint;var d=g(b),e={rasterAttributeTableFieldPrefix:"Raster.",returnDomainValues:!0};e.layerView=d;c=b.queryVisibleRasters(c,e).then(function(b){p=p||0<b.length;return b})}else if("esri.layers.SceneLayer"!==
b.declaredClass)if(u._featureLayersCache[b.id]||"function"===typeof b.queryFeatures&&(0===b.mode||1===b.mode))d=b.createQuery(),d.geometry=t,c=b.queryFeatures(d).then(function(b){b=b.features;p=p||0<b.length;return b});else{if("esri.layers.MapImageLayer"===b.declaredClass)return d=g(b),d.getPopupData(t);var e=[],f;if("esri.core.Collection\x3cesri.Graphic\x3e"===b.declaredClass)f=b;else if("esri.layers.GraphicsLayer"===b.declaredClass)f=b.graphics;else if((d=g(b))&&(d.loadedGraphics||d._graphicsCollection))f=
d.loadedGraphics||d._graphicsCollection;f&&(e=f.filter(function(b){return b&&b.popupTemplate&&b.visible&&t.intersects(b.geometry)}).toArray());0<e.length&&(p=!0,c=I.resolve(e))}return c}),f=k.filter(f,function(b){return null!=b}),n=function(b){return b.reduce(function(b,a){return b.concat(a.items?n(a.items):a)},[])},f=n(f)}!k.some(f,function(b){return!b.isFulfilled()})&&!p?c():f.length&&r.open({promises:f,location:a.mapPoint})}},_getSubLayerFeatureLayers:function(a,c){var g=c||new y,e=[],A=a.length,
h=Math.floor(this.view.extent.width/this.view.width),r=this.view.scale,u=!1,s=this,w=0;a:for(;w<A;w++){var d=a[w],f=d.dynamicLayerInfos||d.layerInfos;if(f){var p=null;if(d._params&&(d._params.layers||d._params.dynamicLayers))p=d.visibleLayers;for(var p=E._getVisibleLayers(f,p),l=E._getLayersForScale(r,f),q=f.length,v=0;v<q;v++){var t=f[v],n=t.id,b=d.popupTemplates[n];if(!t.subLayerIds&&b&&b.popupTemplate&&-1<k.indexOf(p,n)&&-1<k.indexOf(l,n)){if(!z){u=!0;break a}var B=d.id+"_"+n,m=this._featureLayersCache[B];
if(!m||!m.loadError)m||((m=b.layerUrl)||(m=t.source?this._getLayerUrl(d.url,"/dynamicLayer"):this._getLayerUrl(d.url,n)),m=new z(m,{id:B,drawMode:!1,mode:z.MODE_SELECTION,outFields:this._getOutFields(b.popupTemplate),resourceInfo:b.resourceInfo,source:t.source}),this._featureLayersCache[B]=m),m.setDefinitionExpression(d.layerDefinitions&&d.layerDefinitions[n]),m.setGDBVersion(d.gdbVersion),m.popupTemplate=b.popupTemplate,m.setMaxAllowableOffset(h),m.setUseMapTime(!!d.useMapTime),d.layerDrawingOptions&&
(d.layerDrawingOptions[n]&&d.layerDrawingOptions[n].renderer)&&m.setRenderer(d.layerDrawingOptions[n].renderer),e.push(m)}}}}if(u){var x=new y;G(["../layers/FeatureLayer"],function(b){z=b;x.resolve()});x.then(function(){s._getSubLayerFeatureLayers(a,g)})}else{var C=[];k.forEach(e,function(b){if(!b.loaded){var a=new y;D.once(b,"load, error",function(){a.resolve()});C.push(a.promise)}});C.length?J(C).then(function(){e=k.filter(e,function(b){return!b.loadError&&b.isVisibleAtScale(r)});g.resolve(e)}):
(e=k.filter(e,function(b){return b.isVisibleAtScale(r)}),g.resolve(e))}return g.promise},_getLayerUrl:function(a,c){var g=a.indexOf("?");return-1===g?a+"/"+c:a.substring(0,g)+"/"+c+a.substring(g)},_getOutFields:function(a){var c;"esri.PopupTemplate"===a.declaredClass&&a.fieldInfos?(c=[],k.forEach(a.fieldInfos,function(a){var e=a.fieldName&&a.fieldName.toLowerCase();e&&("shape"!==e&&0!==e.indexOf("relationships/"))&&c.push(a.fieldName)})):c=["*"];return c},_calculateClickTolerance:function(a){var c=
6;k.forEach(a,function(a){if(a=a.renderer)"esri.renderer.SimpleRenderer"===a.declaredClass?((a=a.symbol)&&a.xoffset&&(c=Math.max(c,Math.abs(a.xoffset))),a&&a.yoffset&&(c=Math.max(c,Math.abs(a.yoffset)))):("esri.renderer.UniqueValueRenderer"===a.declaredClass||"esri.renderer.ClassBreaksRenderer"===a.declaredClass)&&k.forEach(a.infos,function(a){(a=a.symbol)&&a.xoffset&&(c=Math.max(c,Math.abs(a.xoffset)));a&&a.yoffset&&(c=Math.max(c,Math.abs(a.yoffset)))})});return c},_clickHandler:function(a){function c(a){return g.allLayerViews.find(function(c){return c.layer===
a})}var g=this.view,e=g.map,k=a.screenPoint,h=this;if(g.popup&&g.ready){var r="3d"===g.type,u=e.allLayers.some(function(a){if(a.isInstanceOf(F))return!1;var e;null==a?e=!1:(e=c(a),e=null==e?!1:a.loaded&&!e.suspended&&(a.popupEnabled&&a.popupTemplate||"esri.layers.GraphicsLayer"===a.declaredClass||e.getPopupData));if(e&&!(e=!r))e=(a=c(a))&&a.hasDraped;return e?!0:!1});null!=k?this.view.hitTest(k.x,k.y).then(function(c){0<c.results.length?h._showPopup(c.results[0]):u&&h._showPopup(a)}):h._showPopup(a)}}})});